import type { PhysicsIconName } from "./icons";

export interface StudioHome {
  id: string;
  name: string;
  eyebrow: string;
  tagline: string;
  icon: PhysicsIconName;
  accent: string;
  asset: string;
  startRoute: string;
  variant: "bench" | "track" | "field" | "space" | "matter";
  liveTitle: string;
  liveValue: string;
  concepts: Array<{ title: string; detail: string; icon: PhysicsIconName }>;
  activities: Array<{ title: string; detail: string; action: string }>;
}

const C = (title:string, detail:string, icon:PhysicsIconName) => ({title,detail,icon});
const A = (title:string, detail:string, action:string) => ({title,detail,action});

export const studioHomes: StudioHome[] = [
  {id:"measurement",name:"Measurement Studio",eyebrow:"PRECISION BEGINS WITH THE RIGHT INSTRUMENT",tagline:"Measure · Analyse · Reduce uncertainty · Discover",icon:"ruler",accent:"#38d8ff",asset:"/assets/concept-studio/measurement-hero.png",startRoute:"/experiments/measurement-errors",variant:"bench",liveTitle:"Instrument resolution",liveValue:"± 0.05 mm",concepts:[C("Length","Metre rule, Vernier caliper, micrometer and spherometer.","ruler"),C("Mass","Electronic balance and mass standards.","gauge"),C("Time","Stopwatch, oscillations and time measurement.","pendulum"),C("Uncertainty","Estimate, propagate and report uncertainty.","chart"),C("Significant Figures","Meaningful digits, rounding and calculations.","calculator"),C("Instrument Errors","Zero error, least count and calibration.","compass")],activities:[A("Featured Instruments","Explore tools used in real measurements.","Explore instruments"),A("Choose an Instrument","Select the best tool for a thin metal sheet.","Check answer"),A("Accuracy Progress","Continue focused measurement practice.","Continue learning")]},
  {id:"mechanics",name:"Mechanics Studio",eyebrow:"EXPLORE · BUILD · MEASURE · UNDERSTAND",tagline:"Build systems. Reveal the forces.",icon:"gauge",accent:"#ffb83e",asset:"/assets/concept-studio/mechanics-hero.png",startRoute:"/experiments/inclined-plane",variant:"bench",liveTitle:"Net force",liveValue:"12.4 N",concepts:[C("Force Systems","Vectors, components and resultants.","field"),C("Friction","Static, kinetic and real-world surfaces.","gauge"),C("Torque","Moments and rotational effects.","settings"),C("Equilibrium","Stable systems satisfy ΣF = 0 and Στ = 0.","check"),C("Momentum","Conservation, impulse and collisions.","rocket"),C("Machines","Levers, pulleys, gears and mechanical advantage.","settings")],activities:[A("Build Your System","Assemble components, set parameters and test ideas.","Start studio"),A("Free-Body Diagram Challenge","Draw the correct forces for a block on an incline.","Check answer"),A("Featured Machine","Explore a compound pulley hoist.","Explore machine")]},
  {id:"motion-kinematics",name:"Motion & Kinematics",eyebrow:"MOTION TRACK · CONSTANT ACCELERATION",tagline:"See motion frame by frame.",icon:"rocket",accent:"#30d7ff",asset:"/assets/concept-studio/motion-kinematics-hero.png",startRoute:"/experiments/uniform-motion",variant:"track",liveTitle:"Instant velocity",liveValue:"4.80 m/s",concepts:[C("Position","Position, displacement and origin.","compass"),C("Velocity","Average and instantaneous velocity.","rocket"),C("Acceleration","Constant and variable acceleration.","chart"),C("Projectiles","Range, height and flight time.","orbit"),C("Relative Motion","Motion depends on the reference frame.","eye"),C("Circular Motion","Constant speed with changing direction.","orbit")],activities:[A("Choose a Track Scenario","Compare level, inclined and friction tracks.","Choose track"),A("Graph Prediction Challenge","Predict the velocity graph before the run.","Check graph"),A("Motion Recorder","Capture motion, generate graphs and measure.","Open recorder")]},
  {id:"force-newton",name:"Force & Newton’s Laws",eyebrow:"AIR TRACK · REAL PHYSICS",tagline:"Change a force. Predict the motion.",icon:"gauge",accent:"#ff5d75",asset:"/assets/concept-studio/force-newton-hero.png",startRoute:"/experiments/newton-s-second-law",variant:"track",liveTitle:"Acceleration",liveValue:"2.40 m/s²",concepts:[C("Inertia","Resists changes in motion.","rocket"),C("F = ma","Net force, mass and acceleration.","calculator"),C("Action–Reaction","Equal and opposite forces on different objects.","field"),C("Friction","Opposes relative motion.","gauge"),C("Tension","Pulls along a string or cable.","settings"),C("Normal Force","Perpendicular to the surface.","field")],activities:[A("Select a Newton’s Law","Explore inertia, F = ma and action–reaction.","Select law"),A("Force Vector Sandbox","Set forces on both carts and predict motion.","Update vectors"),A("Misconception Challenge","Test whether a heavier cart pushes harder.","Check answer")]},
  {id:"work-energy-power",name:"Work, Energy & Power",eyebrow:"ENERGY IN MOTION",tagline:"Track where energy goes.",icon:"flame",accent:"#7cf173",asset:"/assets/experiments/conservation-of-energy/energy-track.png",startRoute:"/experiments/conservation-of-energy",variant:"field",liveTitle:"Total mechanical energy",liveValue:"48.2 J",concepts:[C("Work","Measure energy transferred by a force.","gauge"),C("Kinetic Energy","Connect speed and moving energy.","rocket"),C("Potential Energy","Store energy through position.","orbit"),C("Conservation","Account for every energy transfer.","check"),C("Power","Compare how quickly work is done.","spark"),C("Efficiency","Track useful output and dissipation.","chart")],activities:[A("Energy-System Builder","Shape a track and watch every energy reservoir.","Design system"),A("Conservation Challenge","Find the missing energy store in three systems.","Balance energy"),A("Continue Learning","Compare equal work completed over different times.","Continue")]},
  {id:"gravitation",name:"Gravitation Studio",eyebrow:"EARTH–MOON SYSTEM · ORBITAL LAB",tagline:"Shape an orbit with gravity.",icon:"orbit",accent:"#55a8ff",asset:"/assets/experiments/satellite-orbit/sprites/earth.png",startRoute:"/experiments/satellite-orbit",variant:"space",liveTitle:"Orbital speed",liveValue:"7.67 km/s",concepts:[C("Universal Gravitation","Every pair of masses attracts.","orbit"),C("Gravitational Field","Map force per unit mass.","field"),C("Orbits","Continuous free fall around a body.","moon"),C("Satellites","Use speed and altitude to shape a path.","rocket"),C("Escape Velocity","Find the speed needed to leave gravity.","rocket"),C("Kepler’s Laws","Connect orbital period, shape and radius.","chart")],activities:[A("Orbit Designer","Set altitude, inclination and eccentricity.","Update orbit"),A("Mission Presets","Try communications, observation and lunar transfer.","Choose mission"),A("Trajectory Prediction","Predict orbit, impact or escape.","Start studio")]},
  {id:"oscillations",name:"Oscillations Studio",eyebrow:"MOTION · PATTERN · UNDERSTANDING",tagline:"Tune rhythm, resonance and phase.",icon:"pendulum",accent:"#ba7cff",asset:"/assets/experiments/simple-pendulum/pendulum-stand.png",startRoute:"/experiments/simple-pendulum",variant:"bench",liveTitle:"Natural frequency",liveValue:"1.24 Hz",concepts:[C("Simple Harmonic Motion","Periodic motion with restoring force.","wave"),C("Pendulums","Gravitational oscillators.","pendulum"),C("Springs","Elastic restoring force.","spring"),C("Damping","Energy dissipation.","wave"),C("Resonance","Driven systems and large response.","spark"),C("Coupled Oscillators","Normal modes and energy transfer.","pendulum")],activities:[A("Oscillator Selector","Compare mass–spring, pendulum and coupled systems.","Select system"),A("Resonance Challenge","Find the driving frequency with largest amplitude.","Try a frequency"),A("Phase Portrait","Relate displacement and velocity in one view.","Tune frequency")]},
  {id:"waves-sound",name:"Waves & Sound Studio",eyebrow:"DIFFERENT SOURCES · SAME PHYSICS",tagline:"Watch energy travel without matter.",icon:"wave",accent:"#27e6cd",asset:"/assets/experiments/wave-lab/ripple-tank.png",startRoute:"/experiments/wave-lab",variant:"field",liveTitle:"Wave speed",liveValue:"2.40 m/s",concepts:[C("Wave Properties","Amplitude, wavelength, frequency and speed.","wave"),C("Superposition","Combine waves and add their effects.","field"),C("Interference","Constructive and destructive patterns.","spark"),C("Standing Waves","Nodes, antinodes and resonance.","wave"),C("Sound","From vibrations to what you hear.","volume"),C("Doppler Effect","Motion changes observed frequency.","rocket")],activities:[A("Wave Builder","Create a wave and change its properties.","Play wave"),A("Frequency Lab","Adjust frequency and explore wavelength.","Open lab"),A("Interference Challenge","Place sources to match a target pattern.","Start challenge")]},
  {id:"optics",name:"Optics Studio",eyebrow:"LASER · MIRROR · APERTURE · LENS · PRISM",tagline:"Build light paths you can see.",icon:"prism",accent:"#ffcf55",asset:"/assets/experiments/glass-slab-refraction/optical-bench.png",startRoute:"/experiments/glass-slab-refraction",variant:"bench",liveTitle:"Wavelength",liveValue:"450 nm",concepts:[C("Reflection","Trace reflected rays from mirrors.","eye"),C("Refraction","Bend light across boundaries.","prism"),C("Lenses","Construct real and virtual images.","eye"),C("Mirrors","Predict image position with rays.","eye"),C("Interference","Build bright and dark fringes.","wave"),C("Diffraction","Spread light through small openings.","wave")],activities:[A("Predict the Rays","Place components, predict the path, then check.","Try activity"),A("Build Your Own","Add optical components to the bench.","Open builder"),A("Spectrum Explorer","Investigate how different elements spread light.","Explore spectrum")]},
  {id:"electricity",name:"Electricity Studio",eyebrow:"CHARGE FLOW VISUALIZATION · REAL COMPONENTS",tagline:"Build circuits. See charge move.",icon:"battery",accent:"#ffe355",asset:"/assets/experiments/kirchhoff-circuit/breadboard.png",startRoute:"/experiments/kirchhoff-circuit",variant:"bench",liveTitle:"Circuit current",liveValue:"0.32 A",concepts:[C("Charge","Positive and negative charge in motion.","spark"),C("Electric Field","Forces distributed through space.","field"),C("Potential","Energy transferred per unit charge.","battery"),C("Current","Rate of charge flow.","gauge"),C("Resistance","Opposition to current.","settings"),C("Circuits","Complete electrical systems.","battery")],activities:[A("Circuit Builder","Drag components, connect them and explore.","Build circuit"),A("Live Meters","Measure voltage, current, resistance and power.","Take readings"),A("Find the Fault","Repair the circuit so the lamp turns on.","Check solution")]},
  {id:"magnetism",name:"Magnetism Studio",eyebrow:"MAGNETIC FIELD VISUALIZER",tagline:"Reveal invisible fields.",icon:"magnet",accent:"#ff668c",asset:"/assets/experiments/magnetic-field-current/field-mapping-bench.png",startRoute:"/experiments/magnetic-field-current",variant:"field",liveTitle:"Field strength",liveValue:"3.6 mT",concepts:[C("Magnetic Fields","Map direction with compass probes.","field"),C("Force on Charge","Predict charged-particle paths.","spark"),C("Current & Field","Connect current direction and field.","gauge"),C("Solenoids","Create a controlled field with a coil.","magnet"),C("Induction","Generate emf by changing flux.","spark"),C("Electromagnets","Tune turns, current and core.","magnet")],activities:[A("Trace the Particle Path","Predict a charged particle’s trajectory.","Start activity"),A("Induction Lab","Change magnetic flux and observe induced current.","Start activity"),A("Magnet Configuration","Compare bar magnets, loops and solenoids.","Choose setup")]},
  {id:"electronics",name:"Electronics Studio",eyebrow:"6 TOPICS · 28 PROJECTS · INTERACTIVE LAB",tagline:"Turn signals into working systems.",icon:"spark",accent:"#54e8ff",asset:"/assets/experiments/logic-gates/gate-modules.png",startRoute:"/experiments/logic-gates",variant:"bench",liveTitle:"Output signal",liveValue:"3.30 V",concepts:[C("Semiconductors","Materials engineered into devices.","atom"),C("Diodes","Control current direction.","spark"),C("Transistors","Switch and amplify signals.","settings"),C("Amplifiers","Make small signals useful.","volume"),C("Logic Gates","Build decisions with digital logic.","check"),C("Sensors","Connect circuits to the real world.","gauge")],activities:[A("Featured Project","Build an adjustable LED driver.","Open project"),A("Waveform Preview","Compare analog and digital signals.","Open scope"),A("Debug Challenge","Find why the LED does not turn on.","Start challenge")]},
  {id:"thermodynamics",name:"Thermodynamics Studio",eyebrow:"HEAT · WORK · MOLECULAR MOTION",tagline:"Follow heat, work and molecular motion.",icon:"thermometer",accent:"#ff8b57",asset:"/assets/experiments/gas-laws/gas-laws-apparatus.png",startRoute:"/experiments/gas-laws",variant:"matter",liveTitle:"Gas pressure",liveValue:"2.4 bar",concepts:[C("Temperature","Thermal equilibrium and measurement.","thermometer"),C("Heat Transfer","Conduction, convection and radiation.","flame"),C("Gas Laws","Pressure–volume–temperature relationships.","gauge"),C("First Law","Energy balance in thermal systems.","calculator"),C("Entropy","Disorder and spontaneity.","atom"),C("Heat Engines","Cycles and efficiency.","settings")],activities:[A("Build a Heat Engine","Set conditions, run a cycle and analyze efficiency.","Start studio"),A("Process Path Explorer","Compare isothermal and adiabatic changes.","Choose process"),A("Efficiency Challenge","Find the highest possible efficiency.","Check answer")]},
  {id:"fluid-mechanics",name:"Fluid Mechanics Studio",eyebrow:"FLOW IN ACTION · VENTURI · HYDRAULICS",tagline:"See pressure become motion.",icon:"drop",accent:"#42d9f5",asset:"/assets/experiments/bernoulli-fluid-flow/venturi-bench.png",startRoute:"/experiments/bernoulli-fluid-flow",variant:"field",liveTitle:"Throat pressure",liveValue:"18.2 kPa",concepts:[C("Density","Mass per unit volume.","drop"),C("Pressure","Force per unit area.","gauge"),C("Buoyancy","Upward force from displaced fluid.","drop"),C("Continuity","Conservation of flow.","wave"),C("Bernoulli","Exchange pressure and speed.","chart"),C("Viscosity","Internal resistance to flow.","drop")],activities:[A("Build a Flow System","Create and customize a pipe system.","Open builder"),A("Visualize Streamlines","Reveal velocity, pressure and flow patterns.","Open visualizer"),A("Predict Pressure","Estimate pressure at any point.","Predict")]},
  {id:"modern-physics",name:"Modern Physics Studio",eyebrow:"FROM QUANTA TO THE COSMOS",tagline:"Enter the quantum and nuclear world.",icon:"atom",accent:"#b981ff",asset:"/assets/experiments/photoelectric-equation/photoelectric-tube.png",startRoute:"/experiments/photoelectric-equation",variant:"matter",liveTitle:"Detector counts",liveValue:"4827 cpm",concepts:[C("Quantum Ideas","Light, matter and probability.","wave"),C("Photoelectric Effect","Light ejects electrons.","spark"),C("Matter Waves","Particles behave as waves.","wave"),C("Atomic Models","Quantized structure of the atom.","atom"),C("Nuclei","Protons, neutrons and nuclear forces.","flame"),C("Radioactivity","Unstable nuclei and decay.","chart")],activities:[A("Featured Experiments","Vary light frequency and measure stopping potential.","Run experiment"),A("Quantum Timeline","Connect six discoveries to new models.","Explore timeline"),A("Detector Panel","Separate signal, background and uncertainty.","Analyze counts")]},
  {id:"astronomy-astrophysics",name:"Astronomy & Astrophysics",eyebrow:"OBSERVATION TARGET · M31 ANDROMEDA",tagline:"Explore the universe through light and gravity.",icon:"orbit",accent:"#7ea4ff",asset:"/assets/concept-studio/astronomy-observatory-hero.png",startRoute:"/astrophysics",variant:"space",liveTitle:"Target distance",liveValue:"2.54 Mly",concepts:[C("Solar System","Planets, moons and small bodies.","sun"),C("Stars","Birth, life and death.","spark"),C("Spectra","Read light, composition and motion.","prism"),C("Galaxies","Structure, evolution and mergers.","orbit"),C("Cosmology","Origin, expansion and dark universe.","rocket"),C("Exoplanets","Worlds, detection and habitability.","moon")],activities:[A("Exoplanet Transit Explorer","Analyze real light curves and planet properties.","Launch"),A("Continue Learning","Resume stellar evolution and spectral classification.","Continue"),A("Cosmic-Scale Journey","Travel from Earth to the observable universe.","Begin journey")]}
];

const targetHeroAssets: Partial<Record<StudioHome["id"], string>> = {
  measurement: "/assets/concept-studio/measurement-hero.png",
  mechanics: "/assets/concept-studio/mechanics-hero.png",
  "motion-kinematics": "/assets/concept-studio/motion-kinematics-hero.png",
  "force-newton": "/assets/concept-studio/force-newton-hero.png",
  "work-energy-power": "/assets/concept-studio/work-energy-power-hero.png",
  gravitation: "/assets/concept-studio/gravitation-hero.png",
  oscillations: "/assets/concept-studio/oscillations-hero.png",
  "waves-sound": "/assets/concept-studio/waves-sound-hero.png",
  optics: "/assets/concept-studio/optics-hero.png",
  electricity: "/assets/concept-studio/electricity-hero.png",
  magnetism: "/assets/concept-studio/magnetism-hero.png",
  electronics: "/assets/concept-studio/electronics-hero.png",
  thermodynamics: "/assets/concept-studio/thermodynamics-hero.png",
  "fluid-mechanics": "/assets/concept-studio/fluid-mechanics-hero.png",
  "modern-physics": "/assets/concept-studio/modern-physics-hero.png",
  "astronomy-astrophysics": "/assets/concept-studio/astronomy-observatory-hero.png",
};

studioHomes.forEach((studio) => {
  studio.asset = targetHeroAssets[studio.id] ?? studio.asset;
});

export const studioHomeById = new Map(studioHomes.map((studio) => [studio.id, studio]));
