import { PhysicsObjectDefinition, PhysicsObjectInstance, PhysicsObjectKind, PropertyDefinition } from "../types";

const sharedRigidProperties = [
  { key: "mass", label: "Mass", unit: "kg", type: "number" as const, min: 0.01, step: 0.1 },
  { key: "x", label: "Position X", unit: "m", type: "number" as const, step: 0.1 },
  { key: "y", label: "Position Y", unit: "m", type: "number" as const, step: 0.1 },
  { key: "vx", label: "Velocity X", unit: "m/s", type: "number" as const, step: 0.1 },
  { key: "vy", label: "Velocity Y", unit: "m/s", type: "number" as const, step: 0.1 },
  { key: "friction", label: "Friction", type: "number" as const, min: 0, max: 1, step: 0.01 },
  { key: "restitution", label: "Restitution", type: "number" as const, min: 0, max: 1, step: 0.01 },
  { key: "airDrag", label: "Air drag", type: "number" as const, min: 0, max: 2, step: 0.01 },
  { key: "torque", label: "Torque", unit: "N m", type: "number" as const, step: 0.1 },
  { key: "locked", label: "Lock", type: "boolean" as const },
];

export const objectRegistry: PhysicsObjectDefinition[] = [
  {
    id: "ball",
    name: "Ball",
    category: "Mechanics",
    icon: "BALL",
    defaultProperties: { radius: 24, mass: 1, friction: 0.02, restitution: 0.82, color: "#38bdf8" },
    editableProperties: [{ key: "radius", label: "Radius", unit: "cm", type: "number", min: 8, step: 1 }, ...sharedRigidProperties],
    renderType: "canvas",
    simulationType: "rigid-body",
  },
  {
    id: "block",
    name: "Block",
    category: "Mechanics",
    icon: "BOX",
    defaultProperties: { width: 58, height: 42, mass: 2, friction: 0.18, restitution: 0.25, color: "#34d399" },
    editableProperties: [
      { key: "width", label: "Width", unit: "cm", type: "number", min: 10, step: 1 },
      { key: "height", label: "Height", unit: "cm", type: "number", min: 10, step: 1 },
      ...sharedRigidProperties,
    ],
    renderType: "canvas",
    simulationType: "rigid-body",
  },
  {
    id: "floor",
    name: "Floor",
    category: "Boundaries",
    icon: "FLR",
    defaultProperties: { width: 760, height: 28, mass: 0, friction: 0.35, restitution: 0.35, isStatic: true, color: "#64748b" },
    editableProperties: [
      { key: "width", label: "Width", unit: "cm", type: "number", min: 50, step: 10 },
      { key: "friction", label: "Friction", type: "number", min: 0, max: 1, step: 0.01 },
      { key: "restitution", label: "Restitution", type: "number", min: 0, max: 1, step: 0.01 },
    ],
    renderType: "canvas",
    simulationType: "rigid-body",
  },
  {
    id: "wall",
    name: "Wall",
    category: "Boundaries",
    icon: "WAL",
    defaultProperties: { width: 26, height: 420, mass: 0, friction: 0.3, restitution: 0.35, isStatic: true, color: "#94a3b8" },
    editableProperties: [
      { key: "height", label: "Height", unit: "cm", type: "number", min: 60, step: 10 },
      { key: "friction", label: "Friction", type: "number", min: 0, max: 1, step: 0.01 },
    ],
    renderType: "canvas",
    simulationType: "rigid-body",
  },
  {
    id: "ramp",
    name: "Ramp",
    category: "Mechanics",
    icon: "RMP",
    defaultProperties: { width: 220, height: 32, angle: -0.42, mass: 0, friction: 0.22, restitution: 0.28, isStatic: true, color: "#fbbf24" },
    editableProperties: [
      { key: "angle", label: "Angle", unit: "rad", type: "number", min: -1.2, max: 1.2, step: 0.01 },
      { key: "friction", label: "Friction", type: "number", min: 0, max: 1, step: 0.01 },
    ],
    renderType: "canvas",
    simulationType: "rigid-body",
  },
  {
    id: "spring",
    name: "Spring",
    category: "Constraints",
    icon: "SPR",
    defaultProperties: { width: 130, height: 22, mass: 0.2, springConstant: 24, friction: 0.04, restitution: 0.2, color: "#a78bfa" },
    editableProperties: [
      { key: "springConstant", label: "Spring Constant", unit: "N/m", type: "number", min: 0, step: 1 },
      { key: "damping", label: "Damping", type: "number", min: 0, max: 1, step: 0.01 },
      ...sharedRigidProperties,
    ],
    renderType: "canvas",
    simulationType: "rigid-body",
  },
  {
    id: "pendulum",
    name: "Pendulum",
    category: "Oscillations",
    icon: "PEN",
    defaultProperties: { radius: 18, mass: 1, length: 160, pivotX: 420, pivotY: 90, friction: 0.01, restitution: 0.2, color: "#fb923c" },
    editableProperties: [
      { key: "length", label: "Length", unit: "cm", type: "number", min: 40, step: 5 },
      { key: "damping", label: "Damping", type: "number", min: 0, max: 1, step: 0.01 },
      ...sharedRigidProperties,
    ],
    renderType: "canvas",
    simulationType: "rigid-body",
  },
  ...makePlaceholderObjects(),
];

function makePlaceholderObjects(): PhysicsObjectDefinition[] {
  const entries: Array<{
    id: PhysicsObjectKind;
    name: string;
    category: string;
    icon: string;
    simulationType: PhysicsObjectDefinition["simulationType"];
    defaults?: Record<string, number | string | boolean>;
    editable?: PropertyDefinition[];
  }> = [
    { id: "rope", name: "Rope", category: "Constraints", icon: "ROP", simulationType: "rigid-body", defaults: { width: 150, height: 8, mass: 0.2, color: "#cbd5e1" } },
    { id: "pulley", name: "Pulley", category: "Simple Machines", icon: "PUL", simulationType: "rigid-body", defaults: { radius: 28, mass: 1, isStatic: true, motorSpeed: 0, color: "#94a3b8" }, editable: [{ key: "motorSpeed", label: "Motor speed", unit: "rad/s", type: "number", step: 0.1 }, ...sharedRigidProperties] },
    { id: "cart", name: "Cart", category: "Mechanics", icon: "CAR", simulationType: "rigid-body", defaults: { width: 76, height: 36, mass: 2, color: "#60a5fa" } },
    { id: "wheel", name: "Wheel", category: "Rotational", icon: "WHL", simulationType: "rigid-body", defaults: { radius: 30, mass: 1.5, restitution: 0.5, color: "#f97316" } },
    { id: "disc", name: "Disc", category: "Rotational", icon: "DSC", simulationType: "rigid-body", defaults: { radius: 32, mass: 2, color: "#facc15" } },
    { id: "rod", name: "Rod", category: "Rotational", icon: "ROD", simulationType: "rigid-body", defaults: { width: 140, height: 14, mass: 1, color: "#a3e635" } },
    { id: "force-arrow", name: "Force Arrow", category: "Vectors", icon: "FRC", simulationType: "field", defaults: { width: 90, height: 12, isStatic: true, color: "#f43f5e" } },
    { id: "velocity-arrow", name: "Velocity Arrow", category: "Vectors", icon: "VEL", simulationType: "field", defaults: { width: 90, height: 12, isStatic: true, color: "#38bdf8" } },
    { id: "acceleration-arrow", name: "Acceleration Arrow", category: "Vectors", icon: "ACC", simulationType: "field", defaults: { width: 90, height: 12, isStatic: true, color: "#fb923c" } },
    { id: "stopwatch", name: "Stopwatch", category: "Instruments", icon: "TIM", simulationType: "field", defaults: { width: 54, height: 54, isStatic: true, color: "#e2e8f0" } },
    { id: "ruler", name: "Ruler", category: "Instruments", icon: "RUL", simulationType: "field", defaults: { width: 180, height: 18, isStatic: true, color: "#fde68a" } },
    { id: "protractor", name: "Protractor", category: "Instruments", icon: "ANG", simulationType: "field", defaults: { width: 92, height: 46, isStatic: true, color: "#f9a8d4" } },
    { id: "graph-plotter", name: "Graph Plotter", category: "Instruments", icon: "GRF", simulationType: "field", defaults: { width: 68, height: 52, isStatic: true, color: "#22d3ee" } },
    { id: "motion-sensor", name: "Motion Sensor", category: "Instruments", icon: "MOT", simulationType: "field", defaults: { width: 62, height: 34, isStatic: true, color: "#818cf8" } },
    { id: "force-sensor", name: "Force Sensor", category: "Instruments", icon: "SEN", simulationType: "field", defaults: { width: 62, height: 34, isStatic: true, color: "#fb7185" } },
    { id: "light-ray", name: "Light Ray", category: "Optics", icon: "RAY", simulationType: "optics", defaults: { width: 160, height: 6, wavelength: 540, intensity: 1, isStatic: true, color: "#fef08a" }, editable: [{ key: "wavelength", label: "Wavelength", unit: "nm", type: "number", min: 380, max: 700, step: 1 }, { key: "intensity", label: "Intensity", type: "number", min: 0, max: 1, step: 0.01 }, ...sharedRigidProperties] },
    { id: "plane-mirror", name: "Plane Mirror", category: "Optics", icon: "MIR", simulationType: "optics", defaults: { width: 18, height: 150, reflectivity: 0.9, isStatic: true, color: "#93c5fd" }, editable: [{ key: "reflectivity", label: "Reflectivity", type: "number", min: 0, max: 1, step: 0.01 }, { key: "angle", label: "Angle", unit: "rad", type: "number", step: 0.01 }, ...sharedRigidProperties] },
    { id: "convex-lens", name: "Convex Lens", category: "Optics", icon: "LEN", simulationType: "optics", defaults: { width: 36, height: 150, focalLength: 160, refractiveIndex: 1.5, material: "glass", isStatic: true, color: "#67e8f9" }, editable: [{ key: "focalLength", label: "Focal length", unit: "m", type: "number", step: 5 }, { key: "material", label: "Material", type: "select" }, { key: "angle", label: "Angle", unit: "rad", type: "number", step: 0.01 }, ...sharedRigidProperties] },
    { id: "concave-mirror", name: "Concave Mirror", category: "Optics", icon: "CMR", simulationType: "optics", defaults: { width: 22, height: 150, focalLength: 130, reflectivity: 0.92, isStatic: true, color: "#bfdbfe" }, editable: [{ key: "focalLength", label: "Focal length", unit: "m", type: "number", step: 5 }, { key: "reflectivity", label: "Reflectivity", type: "number", min: 0, max: 1, step: 0.01 }, { key: "angle", label: "Angle", unit: "rad", type: "number", step: 0.01 }, ...sharedRigidProperties] },
    { id: "prism", name: "Prism", category: "Optics", icon: "PRI", simulationType: "optics", defaults: { width: 86, height: 74, refractiveIndex: 1.5, isStatic: true, color: "#c4b5fd" }, editable: [{ key: "refractiveIndex", label: "Refractive index", type: "number", min: 1, step: 0.01 }, { key: "angle", label: "Angle", unit: "rad", type: "number", step: 0.01 }, ...sharedRigidProperties] },
    { id: "wave-source", name: "Wave Source", category: "Waves", icon: "SRC", simulationType: "wave", defaults: { radius: 18, frequency: 2, amplitude: 1, phase: 0, isStatic: true, color: "#38bdf8" }, editable: [{ key: "frequency", label: "Frequency", unit: "Hz", type: "number", min: 0.1, step: 0.1 }, { key: "amplitude", label: "Amplitude", type: "number", min: 0, step: 0.1 }, { key: "phase", label: "Phase", unit: "rad", type: "number", step: 0.1 }, ...sharedRigidProperties] },
    { id: "wave-barrier", name: "Wave Barrier", category: "Waves", icon: "BAR", simulationType: "wave", defaults: { width: 14, height: 220, gapWidth: 24, isStatic: true, color: "#94a3b8" }, editable: [{ key: "gapWidth", label: "Gap width", type: "number", min: 0, step: 1 }, ...sharedRigidProperties] },
    { id: "fluid-region", name: "Fluid Region", category: "Fluid Mechanics", icon: "FLD", simulationType: "fluid", defaults: { width: 360, height: 190, density: 1000, viscosity: 0.001, isStatic: true, color: "rgba(56,189,248,0.28)" }, editable: [{ key: "density", label: "Density", unit: "kg/m3", type: "number", min: 0, step: 10 }, { key: "viscosity", label: "Viscosity", unit: "Pa s", type: "number", min: 0, step: 0.001 }, ...sharedRigidProperties] },
    { id: "chladni-plate", name: "Chladni Plate", category: "Waves", icon: "CHL", simulationType: "wave", defaults: { width: 260, height: 180, frequency: 440, amplitude: 0.5, isStatic: true, color: "#334155" }, editable: [{ key: "frequency", label: "Frequency", unit: "Hz", type: "number", min: 80, max: 1600, step: 1 }, { key: "amplitude", label: "Amplitude", type: "number", min: 0, max: 1, step: 0.01 }, ...sharedRigidProperties] },
    { id: "charge", name: "Charge", category: "Electricity", icon: "Q", simulationType: "field", defaults: { radius: 22, mass: 0.1, charge: 1, isStatic: true, color: "#22d3ee" } },
    { id: "electric-field-region", name: "Electric Field Region", category: "Electricity", icon: "E", simulationType: "field", defaults: { width: 180, height: 110, isStatic: true, color: "#06b6d4" } },
    { id: "bar-magnet", name: "Bar Magnet", category: "Magnetism", icon: "MAG", simulationType: "field", defaults: { width: 130, height: 34, isStatic: true, color: "#d946ef" } },
    { id: "thermometer", name: "Thermometer", category: "Thermal", icon: "TMP", simulationType: "thermal", defaults: { width: 26, height: 120, temperature: 298, isStatic: true, color: "#ef4444" } },
    { id: "gas-container", name: "Gas Container", category: "Thermodynamics", icon: "GAS", simulationType: "thermal", defaults: { width: 150, height: 110, pressure: 101325, temperature: 300, isStatic: true, color: "#f97316" } },
    { id: "battery", name: "Battery", category: "Circuits", icon: "BAT", simulationType: "circuit", defaults: { width: 70, height: 38, emf: 9, internalResistance: 0.2, isStatic: true, color: "#22d3ee" }, editable: [{ key: "emf", label: "EMF", unit: "V", type: "number", min: 0, step: 0.1 }, { key: "internalResistance", label: "Internal R", unit: "ohm", type: "number", min: 0, step: 0.1 }, { key: "x", label: "Position X", unit: "m", type: "number", step: 0.1 }, { key: "y", label: "Position Y", unit: "m", type: "number", step: 0.1 }] },
    { id: "resistor", name: "Resistor", category: "Circuits", icon: "RES", simulationType: "circuit", defaults: { width: 74, height: 28, resistance: 10, isStatic: true, color: "#facc15" }, editable: [{ key: "resistance", label: "Resistance", unit: "ohm", type: "number", min: 0.01, step: 0.1 }, { key: "x", label: "Position X", unit: "m", type: "number", step: 0.1 }, { key: "y", label: "Position Y", unit: "m", type: "number", step: 0.1 }] },
    { id: "bulb", name: "Bulb", category: "Circuits", icon: "BLB", simulationType: "circuit", defaults: { radius: 24, resistance: 12, brightness: 0, isStatic: true, color: "#fde68a" }, editable: [{ key: "resistance", label: "Resistance", unit: "ohm", type: "number", min: 0.01, step: 0.1 }, { key: "x", label: "Position X", unit: "m", type: "number", step: 0.1 }, { key: "y", label: "Position Y", unit: "m", type: "number", step: 0.1 }] },
    { id: "switch", name: "Switch", category: "Circuits", icon: "SW", simulationType: "circuit", defaults: { width: 64, height: 30, closed: false, isStatic: true, color: "#94a3b8" }, editable: [{ key: "closed", label: "Closed", type: "boolean" }, { key: "x", label: "Position X", unit: "m", type: "number", step: 0.1 }, { key: "y", label: "Position Y", unit: "m", type: "number", step: 0.1 }] },
    { id: "ammeter", name: "Ammeter", category: "Circuits", icon: "A", simulationType: "circuit", defaults: { radius: 22, current: 0, isStatic: true, color: "#67e8f9" }, editable: [{ key: "x", label: "Position X", unit: "m", type: "number", step: 0.1 }, { key: "y", label: "Position Y", unit: "m", type: "number", step: 0.1 }] },
    { id: "voltmeter", name: "Voltmeter", category: "Circuits", icon: "V", simulationType: "circuit", defaults: { radius: 22, voltageDiff: 0, isStatic: true, color: "#a78bfa" }, editable: [{ key: "x", label: "Position X", unit: "m", type: "number", step: 0.1 }, { key: "y", label: "Position Y", unit: "m", type: "number", step: 0.1 }] },
    { id: "wire", name: "Wire", category: "Circuits", icon: "WR", simulationType: "circuit", defaults: { width: 1, height: 1, current: 0, isStatic: true, color: "#22c55e" }, editable: [] },
    { id: "double-pendulum", name: "Double Pendulum", category: "Oscillations", icon: "DP", simulationType: "numerical", defaults: { width: 1, height: 1, isStatic: true, pivotX: 420, pivotY: 110, length1: 120, length2: 120, mass1: 1, mass2: 1, angle1: 1.2, angle2: 1.95, omega1: 0, omega2: 0, damping: 0.002, color: "#fb923c" }, editable: [{ key: "pivotX", label: "Pivot X", type: "number", step: 1 }, { key: "pivotY", label: "Pivot Y", type: "number", step: 1 }, { key: "length1", label: "Length 1", unit: "m", type: "number", min: 20, step: 5 }, { key: "length2", label: "Length 2", unit: "m", type: "number", min: 20, step: 5 }, { key: "mass1", label: "Mass 1", unit: "kg", type: "number", min: 0.1, step: 0.1 }, { key: "mass2", label: "Mass 2", unit: "kg", type: "number", min: 0.1, step: 0.1 }, { key: "angle1", label: "Angle 1", unit: "rad", type: "number", step: 0.001 }, { key: "angle2", label: "Angle 2", unit: "rad", type: "number", step: 0.001 }, { key: "damping", label: "Damping", type: "number", min: 0, max: 0.1, step: 0.001 }] },
  ];

  return entries.map((entry) => ({
    id: entry.id,
    name: entry.name,
    category: entry.category,
    icon: entry.icon,
    defaultProperties: {
      width: 56,
      height: 36,
      mass: 1,
      friction: 0.08,
      restitution: 0.35,
      ...entry.defaults,
    },
    editableProperties: entry.editable ?? sharedRigidProperties,
    renderType: "canvas",
    simulationType: entry.simulationType,
  }));
}

export function createObject(kind: PhysicsObjectKind, x = 300, y = 160): PhysicsObjectInstance {
  const def = objectRegistry.find((item) => item.id === kind);
  if (!def) throw new Error(`Unknown physics object: ${kind}`);
  const defaults = def.defaultProperties;
  return {
    id: crypto.randomUUID(),
    kind,
    name: def.name,
    x,
    y,
    angle: Number(defaults.angle ?? 0),
    width: Number(defaults.width ?? 48),
    height: Number(defaults.height ?? 48),
    radius: Number(defaults.radius ?? 22),
    mass: Number(defaults.mass ?? 1),
    vx: 0,
    vy: 0,
    ax: 0,
    ay: 0,
    friction: Number(defaults.friction ?? 0.1),
    restitution: Number(defaults.restitution ?? 0.4),
    isStatic: Boolean(defaults.isStatic ?? false),
    locked: Boolean(defaults.locked ?? false),
    color: String(defaults.color ?? "#38bdf8"),
    charge: Number(defaults.charge ?? 0),
    temperature: Number(defaults.temperature ?? 293.15),
    density: Number(defaults.density ?? 1000),
    material: String(defaults.material ?? "default"),
    springConstant: Number(defaults.springConstant ?? 0),
    damping: Number(defaults.damping ?? 0.02),
    airDrag: Number(defaults.airDrag ?? 0.05),
    motorSpeed: Number(defaults.motorSpeed ?? 0),
    motorTorque: Number(defaults.motorTorque ?? 0),
    torque: Number(defaults.torque ?? 0),
    length: Number(defaults.length ?? 120),
    pivotX: Number(defaults.pivotX ?? x),
    pivotY: Number(defaults.pivotY ?? y - 120),
    focalLength: Number(defaults.focalLength ?? 120),
    refractiveIndex: Number(defaults.refractiveIndex ?? 1.5),
    reflectivity: Number(defaults.reflectivity ?? 0.9),
    wavelength: Number(defaults.wavelength ?? 540),
    intensity: Number(defaults.intensity ?? 1),
    viscosity: Number(defaults.viscosity ?? 0.001),
    frequency: Number(defaults.frequency ?? 1),
    amplitude: Number(defaults.amplitude ?? 1),
    phase: Number(defaults.phase ?? 0),
    gapWidth: Number(defaults.gapWidth ?? 20),
    length1: Number(defaults.length1 ?? 120),
    length2: Number(defaults.length2 ?? 120),
    mass1: Number(defaults.mass1 ?? 1),
    mass2: Number(defaults.mass2 ?? 1),
    angle1: Number(defaults.angle1 ?? 0),
    angle2: Number(defaults.angle2 ?? 0),
    omega1: Number(defaults.omega1 ?? 0),
    omega2: Number(defaults.omega2 ?? 0),
    emf: Number(defaults.emf ?? 0),
    internalResistance: Number(defaults.internalResistance ?? 0),
    resistance: Number(defaults.resistance ?? 1),
    brightness: Number(defaults.brightness ?? 0),
    closed: Boolean(defaults.closed ?? false),
    current: Number(defaults.current ?? 0),
    voltage: Number(defaults.voltage ?? 0),
    voltageDiff: Number(defaults.voltageDiff ?? 0),
    trail: [],
  };
}
