import { ExperimentDefinition } from "../types";
import { commonMistakesForExperiment } from "./commonMistakes";

export interface ExperimentReportInput {
  experiment: ExperimentDefinition;
  formula: string;
  variables: Array<{ label: string; value: number | string; unit?: string }>;
  observations: Array<{ label: string; value: string }>;
  graphSummary?: string;
  result: string;
  conclusion: string;
}

export function generateExperimentMarkdownReport(input: ExperimentReportInput) {
  const { experiment } = input;
  return [
    `# ${experiment.title} Lab Report`,
    "",
    "**Student Name:** ____________________",
    `**Generated By:** PhysicsLab Learning Platform`,
    `**Model Class:** ${experiment.modelClass ?? "Unclassified"}`,
    `**Trust Level:** ${experiment.trustLevel ?? 0}%`,
    `**Class Level:** ${experiment.classLevel}`,
    "",
    "## Aim",
    experiment.aim,
    "",
    "## Theory",
    experiment.theory,
    "",
    "## Formula Used",
    input.formula || experiment.formulae.map((formula) => formula.expression).join("; ") || "No formula recorded.",
    "",
    "## Assumptions",
    ...(experiment.assumptions ?? []).map((item) => `- ${item}`),
    "",
    "## Variables Used",
    ...input.variables.map((item) => `- ${item.label}: ${item.value}${item.unit ? ` ${item.unit}` : ""}`),
    "",
    "## Observation Table",
    "| Observation | Value |",
    "|---|---:|",
    ...input.observations.map((item) => `| ${item.label} | ${item.value} |`),
    "",
    "## Graph Summary",
    input.graphSummary ?? "Graph should be interpreted with registered measurement units and source confidence.",
    "",
    "## Result",
    input.result,
    "",
    "## Conclusion",
    input.conclusion,
    "",
    "## Common Mistakes Checked",
    ...commonMistakesForExperiment(experiment).slice(0, 5).map((item) => `- ${item}`),
    "",
    "## Viva Questions",
    ...experiment.vivaQuestions.slice(0, 5).map((item) => `- **${item.prompt}** ${item.answer}`),
    "",
    "## Units",
    ...experiment.formulae.flatMap((formula) => formula.variables.map((variable) => `- ${variable.symbol}: ${variable.unit || "unitless"}`)),
  ].join("\n");
}

export function downloadMarkdownReport(markdown: string, filename: string) {
  const blob = new Blob([markdown], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}
