import { ExperimentDefinition } from "../types";
import { commonMistakesForExperiment } from "./commonMistakes";
import { getExperimentValidationMetadata } from "./experimentValidationRegistry";

export interface ExperimentReportInput {
  experiment: ExperimentDefinition;
  formula: string;
  variables: Array<{ label: string; value: number | string; unit?: string }>;
  observations: Array<{ label: string; value: string }>;
  graphSummary?: string;
  whatChangedWhy?: string;
  misconceptionWarning?: string;
  validationStatus?: string;
  result: string;
  conclusion: string;
}

export function generateExperimentMarkdownReport(input: ExperimentReportInput) {
  const { experiment } = input;
  const validation = getExperimentValidationMetadata(experiment.id);
  const formulaText = input.formula || validation?.formula || experiment.formulae.map((formula) => formula.expression).join("; ") || "No formula recorded.";
  const assumptionRows = validation?.assumptions.length ? validation.assumptions : experiment.assumptions ?? [];
  const inputUnitRows = validation?.inputUnits.map((item) => `- ${item.label}: ${item.displayUnit}${item.displayUnit !== item.siUnit ? ` (converted internally to ${item.siUnit})` : " (SI)"}`) ?? [];
  const outputUnitRows = validation?.outputUnits.map((item) => `- ${item.label}: ${item.displayUnit}`) ?? [];
  const graphRows = validation?.graphExpectations.map((item) => `- ${item.label}: ${item.xLabel} vs ${item.yLabel}; expected ${item.shape ?? item.direction ?? "documented"} response.${item.notes ? ` ${item.notes}` : ""}`) ?? [];
  const benchmarkRows = validation?.benchmarkCases.map((item) => `- ${item.name}: expected ${item.expected} ${item.unit}, actual ${item.actual} ${item.unit}, tolerance ${item.tolerance}, ${item.pass ? "PASS" : "FAIL"}`) ?? [];
  const misconception = input.misconceptionWarning ?? commonMistakesForExperiment(experiment)[0] ?? "Check whether the model is a formula, approximation, or qualitative visual before making a numeric claim.";

  return [
    `# ${experiment.title} Lab Report`,
    "",
    "**Student Name:** ____________________",
    `**Generated By:** PhysicsLab Learning Platform`,
    `**Model Class:** ${experiment.modelClass ?? "Unclassified"}`,
    `**Validation Status:** ${input.validationStatus ?? validation?.status ?? "needs-benchmark"}`,
    `**Trust Level:** ${experiment.trustLevel ?? 0}%`,
    `**Class Level:** ${experiment.classLevel}`,
    "",
    "## Aim",
    experiment.aim,
    "",
    "## Theory",
    experiment.theory,
    "",
    "## Formula Used",
    formulaText,
    "",
    "## Symbols and Units",
    ...(inputUnitRows.length ? inputUnitRows : experiment.formulae.flatMap((formula) => formula.variables.map((variable) => `- ${variable.symbol}: ${variable.unit || "unitless"}`))),
    ...(outputUnitRows.length ? outputUnitRows : []),
    "",
    "## Assumptions",
    ...(assumptionRows.length ? assumptionRows.map((item) => `- ${item}`) : ["- Assumptions not yet registered. Treat output as formula-only or qualitative until reviewed."]),
    "",
    "## Input Values",
    ...input.variables.map((item) => `- ${item.label}: ${item.value}${item.unit ? ` ${item.unit}` : ""}`),
    "",
    "## Output Values",
    ...(input.observations.length ? input.observations.map((item) => `- ${item.label}: ${item.value}`) : ["- No output values recorded."]),
    "",
    "## Observation Table",
    "| Observation | Value |",
    "|---|---:|",
    ...input.observations.map((item) => `| ${item.label} | ${item.value} |`),
    "",
    "## Graph Summary",
    input.graphSummary ?? "Graph should be interpreted with registered measurement units and source confidence.",
    ...(graphRows.length ? ["", "## Graph Notes", ...graphRows] : []),
    ...(benchmarkRows.length ? ["", "## Benchmark and Validation Notes", ...benchmarkRows] : []),
    ...(validation?.validRanges.length ? ["", "## Valid Ranges and Edge Cases", ...validation.validRanges.map((item) => `- ${item.label}: ${item.min ?? "open"} to ${item.max ?? "open"} ${item.unit ?? ""}${item.warning ? `; ${item.warning}` : ""}`)] : []),
    "",
    "## Result",
    input.result,
    "",
    "## What Changed and Why",
    input.whatChangedWhy ?? "Change one input at a time, compare the output, and connect the trend to the formula.",
    "",
    "## Misconception Warning",
    misconception,
    "",
    "## Conclusion",
    input.conclusion,
    "",
    "## Conclusion Starter",
    `I observed that ${experiment.title.toLowerCase()} changes because ____________________________________.`,
    "",
    "## Common Mistakes Checked",
    ...commonMistakesForExperiment(experiment).slice(0, 5).map((item) => `- ${item}`),
    "",
    "## Viva Questions",
    ...vivaQuestionsForReport(experiment).map((item) => `- **${item.prompt}** ${item.answer}`),
    "",
    "## Units",
    ...experiment.formulae.flatMap((formula) => formula.variables.map((variable) => `- ${variable.symbol}: ${variable.unit || "unitless"}`)),
    ...(validation?.warnings.length ? ["", "## Model Warnings", ...validation.warnings.map((item) => `- ${item}`)] : []),
  ].join("\n");
}

function vivaQuestionsForReport(experiment: ExperimentDefinition) {
  return [
    ...experiment.vivaQuestions,
    { prompt: "Which input variable should be changed first in this lab?", answer: "Change one input at a time so the output trend and graph shape stay clear." },
    { prompt: "Which assumption must you mention before trusting the result?", answer: experiment.assumptions?.[0] ?? "Mention the stated ideal model and keep all units consistent." },
    { prompt: "How should you check whether the answer is reasonable?", answer: "Check the unit, sign or direction, graph trend, and expected result before writing the conclusion." },
  ].slice(0, 5);
}

export function downloadMarkdownReport(markdown: string, filename: string) {
  const blob = new Blob([markdown], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}
