export type StringVisualKind =
  | "scale" | "comparison" | "modes" | "topology" | "worldsheet" | "levels"
  | "spectrum" | "interaction" | "dimensions" | "partners" | "network" | "compact"
  | "calabi" | "tower" | "brane" | "duality" | "ads" | "graviton" | "emergent"
  | "holographic" | "landscape" | "blackhole" | "pagecurve" | "cosmos" | "cosmic-string";

export interface StringControl {
  label: string;
  min: number;
  max: number;
  step: number;
  value: number;
  unit: string;
}

export interface StringTheoryLesson {
  id: string;
  number: number;
  unit: string;
  title: string;
  eyebrow: string;
  subtitle: string;
  visual: StringVisualKind;
  formula: string;
  asset?: string;
  controls: [StringControl, StringControl];
  outline: string[];
  phases: string[];
  observations: string[];
}

const control = (label: string, min: number, max: number, step: number, value: number, unit = ""):
  StringControl => ({ label, min, max, step, value, unit });

const lesson = (
  number: number, id: string, unit: string, title: string, eyebrow: string, subtitle: string,
  visual: StringVisualKind, formula: string, controls: [StringControl, StringControl],
  outline: string[], phases: string[], observations: string[], asset?: string,
): StringTheoryLesson => ({ number, id, unit, title, eyebrow, subtitle, visual, formula, controls, outline, phases, observations, asset });

export const stringTheoryLessons: StringTheoryLesson[] = [
  lesson(1, "planck-scale", "Foundations", "The Planck Scale", "FROM THE COSMOS TO THE QUANTUM LIMIT", "Zoom beyond atoms to the Planck scale.", "scale", "ℓₚ = √(ℏG/c³)", [control("Scale", -35, -5, 1, -35, " m"), control("Resolution", 1, 100, 1, 72, "%")], ["The Big Picture", "From Atoms", "Subatomic World", "Quarks and Gluons", "The Planck Scale", "Strings at the Limit", "Implications"], ["Atoms", "Nucleus", "Quarks", "Planck Length", "Beyond"], ["Atomic structure gives way to nuclei and quark constituents.", "At the Planck length, quantum fluctuations of geometry cannot be ignored.", "The Planck length is about 1.616 × 10⁻³⁵ m."], "/assets/string-theory-studio/planck-scale-stack-v2.png"),
  lesson(2, "points-vs-strings", "Foundations", "Points vs. Strings", "TWO MODELS · ONE EXPERIMENT", "Compare a zero-dimensional particle with an extended one-dimensional string under the same probe.", "comparison", "S = −mc∫ds  ↔  S = −T∫dA", [control("Probe energy", 1, 100, 1, 44, "%"), control("String tension", 0.2, 2.5, 0.1, 1.2, " T")], ["Point particle", "Extended string", "Interaction vertex", "Ultraviolet behavior", "Shared observables", "Model limits"], ["Prepare", "Probe", "Scatter", "Compare", "Conclude"], ["A point has no internal spatial extent.", "A string interaction is spread across a worldsheet.", "Extended interactions can soften short-distance divergences."]),
  lesson(3, "vibration-modes", "Foundations", "Vibration Modes", "ONE STRING · MANY PARTICLES", "Excite standing waves and connect harmonic shape, energy and particle identity.", "modes", "fₙ = nv/2L", [control("Harmonic", 1, 6, 1, 2, " n"), control("Amplitude", 0.1, 1, 0.05, 0.65, "")], ["Fundamental mode", "Standing waves", "Nodes and antinodes", "Energy ladder", "Particle identity", "Mode superposition"], ["Pluck", "Fundamental", "Harmonics", "Measure", "Identify"], ["Allowed modes contain an integer number of half-wavelengths.", "Higher harmonics carry more excitation energy.", "The particle analogy concerns quantum string states, not audible sound."], "/assets/string-theory-studio/vibration-modes.png"),
  lesson(4, "open-closed-strings", "Foundations", "Open & Closed Strings", "TOPOLOGY CHANGES THE SPECTRUM", "Switch between strings with endpoints and loops, then inspect the states each topology supports.", "topology", "σ ∈ [0,π]  or  σ ≡ σ + 2π", [control("Loop closure", 0, 100, 1, 20, "%"), control("Excitation", 1, 5, 1, 2, "")], ["Open endpoints", "Closed loops", "Boundary conditions", "Gauge states", "Graviton state", "Topology change"], ["Open", "Bend", "Join", "Closed", "Compare"], ["Open strings may end on D-branes.", "Closed strings contain a massless spin-2 excitation.", "Joining endpoints changes the boundary condition continuously in this model."]),
  lesson(5, "worldsheet", "Quantum Strings", "Worldsheet", "A STRING WRITES A SURFACE THROUGH TIME", "Move from a worldline to the two-dimensional surface swept out by an evolving string.", "worldsheet", "Xᵘ = Xᵘ(τ,σ)", [control("Worldsheet time", 0, 10, 0.1, 4.2, " τ"), control("Wave amplitude", 0.1, 1.2, 0.05, 0.6, "")], ["Worldline review", "String coordinate σ", "Worldsheet time τ", "Embedding Xᵘ", "Causal propagation", "Action area"], ["Initial loop", "Sweep", "Ripple", "Inspect", "Measure"], ["A string needs one spatial parameter σ.", "Evolution adds τ, producing a two-dimensional worldsheet.", "The worldsheet is embedded in the higher-dimensional target spacetime."], "/assets/string-theory-studio/worldsheet.png"),
  lesson(6, "string-quantization", "Quantum Strings", "String Quantization", "CLASSICAL WAVES BECOME DISCRETE STATES", "Raise and lower oscillator occupation to build a quantized string state.", "levels", "M² ∝ (N − a)/α′", [control("Level number", 0, 8, 1, 3, " N"), control("String scale", 0.2, 2, 0.1, 1, " α′")], ["Classical modes", "Canonical variables", "Creation operators", "Number level N", "Mass formula", "Physical states"], ["Classical", "Promote", "Quantize", "Constrain", "Read spectrum"], ["Oscillator occupation is discrete.", "The intercept a depends on the theory and sector.", "Constraint conditions remove unphysical excitations."]),
  lesson(7, "particle-spectrum", "Quantum Strings", "Particle Spectrum", "FILTER THE STRING SPECTRUM", "Explore how oscillator level, mass and spin organize the states of a quantized string.", "spectrum", "α′M² = 4(N + Ñ − 2a)", [control("Mass level", 0, 8, 1, 2, ""), control("Spin filter", 0, 4, 1, 2, " ℏ")], ["Ground state", "Massless sector", "Excited tower", "Spin content", "Degeneracy", "Low-energy limit"], ["Vacuum", "Excite", "Filter", "Classify", "Compare"], ["Every oscillator level contains a family of states.", "Mass and spin are constrained by excitation number.", "The low-energy spectrum determines the effective field theory."]),
  lesson(8, "splitting-joining", "Quantum Strings", "Splitting & Joining", "INTERACTION WITHOUT A POINT VERTEX", "Run a continuous worldsheet interaction in which one string splits into two and rejoins.", "interaction", "gₛ ∼ e^Φ", [control("Interaction time", 0, 100, 1, 38, "%"), control("Coupling", 0.05, 1, 0.05, 0.35, " gₛ")], ["Incoming string", "Split channel", "Two-string state", "Join channel", "Coupling strength", "Conservation laws"], ["Approach", "Split", "Separate", "Rejoin", "Exit"], ["String interactions are changes in worldsheet topology.", "The coupling controls the probability amplitude, not classical force.", "Energy and momentum remain conserved at the interaction."]),
  lesson(9, "bosonic-string", "Supersymmetry", "Bosonic String", "THE FIRST CONSISTENT STRING MODEL", "Inspect why the bosonic string needs 26 dimensions and why its ground state is unstable.", "dimensions", "Dcritical = 26", [control("Dimension count", 2, 30, 1, 26, " D"), control("Ground mass²", -2, 2, 0.1, -1, " /α′")], ["Bosonic coordinates", "Conformal anomaly", "Critical dimension", "Open spectrum", "Closed spectrum", "Tachyon problem"], ["Choose D", "Check anomaly", "Inspect vacuum", "Find graviton", "Diagnose"], ["Quantum conformal symmetry selects D = 26.", "The ground state has negative mass squared in the simplest model.", "The closed-string spectrum still contains a graviton-like state."]),
  lesson(10, "superstrings", "Supersymmetry", "Superstrings", "ADD FERMIONS TO THE WORLDSHEET", "Balance bosonic and fermionic oscillations and observe how the critical dimension changes.", "partners", "Dcritical = 10", [control("Boson modes", 1, 10, 1, 6, ""), control("Fermion modes", 1, 10, 1, 6, "")], ["Worldsheet fermions", "R and NS sectors", "GSO projection", "Critical dimension", "Spacetime fermions", "Tachyon removal"], ["Bosons", "Add fermions", "Project", "Pair states", "Stabilize"], ["Worldsheet supersymmetry changes the anomaly balance.", "Consistent superstring theories live in ten spacetime dimensions.", "The GSO projection removes inconsistent states and enables spacetime supersymmetry."]),
  lesson(11, "supersymmetry", "Supersymmetry", "Supersymmetry", "MATCH BOSONS WITH FERMIONS", "Pair force and matter states while tracking the symmetry mismatch at observable energies.", "partners", "Q|boson⟩ = |fermion⟩", [control("SUSY breaking", 0, 100, 1, 28, "%"), control("Energy scale", 1, 100, 1, 62, "%")], ["Bosons and fermions", "Supercharge Q", "Supermultiplets", "Mass pairing", "Broken symmetry", "Experimental bounds"], ["Select state", "Apply Q", "Find partner", "Break symmetry", "Test"], ["Supersymmetry relates integer-spin and half-integer-spin states.", "Exact supersymmetry would give matched masses.", "No superpartner has yet been directly observed."]),
  lesson(12, "five-string-theories", "Supersymmetry", "Five String Theories", "FIVE CORNERS · ONE DEEPER FRAMEWORK", "Five theories became five windows.", "network", "Type I ↔ IIA ↔ IIB ↔ Heterotic", [control("Coupling", 0.05, 1.5, 0.05, 1, " gₛ"), control("Chirality", 0, 1, 1, 1, "")], ["The Big Picture", "From Atoms", "Subatomic World", "Quarks and Gluons", "Five String Theories", "Duality Web", "Implications"], ["Type I", "Type IIA", "Type IIB", "Heterotic SO(32)", "Heterotic E₈×E₈"], ["The five perturbative theories have different spectra.", "Dualities connect theories that once appeared separate.", "Their strong-coupling limits point toward M-theory."], "/assets/string-theory-studio/five-theories-v2.png"),
  lesson(13, "why-ten-dimensions", "Extra Dimensions", "Why 10 Dimensions?", "QUANTUM CONSISTENCY FIXES DIMENSION", "Change spacetime dimension and watch the conformal anomaly cancel only at the critical value.", "dimensions", "cₘ + cghost = 0  ⇒  D = 10", [control("Spacetime dimensions", 4, 14, 1, 10, " D"), control("Worldsheet energy", 0, 100, 1, 50, "%")], ["Classical symmetry", "Quantum anomaly", "Central charge", "Ghost fields", "Critical balance", "Physical meaning"], ["Set D", "Quantize", "Measure anomaly", "Balance", "Confirm"], ["Critical dimension follows from quantum consistency.", "For superstrings the matter and ghost central charges cancel at D = 10.", "Extra dimensions must be hidden or otherwise inaccessible at low energy."]),
  lesson(14, "compactification", "Extra Dimensions", "Compactification", "CURL A DIMENSION OUT OF SIGHT", "Shrink one spatial dimension into a circle and resolve it only when the probe wavelength becomes small enough.", "compact", "x ≡ x + 2πR", [control("Compact radius", 0.1, 2, 0.05, 0.65, " R"), control("Probe wavelength", 0.1, 3, 0.05, 1.4, " λ")], ["Extended dimensions", "Circular coordinate", "Compact radius", "Low-energy view", "High-energy probe", "Effective physics"], ["Flat line", "Curl", "Shrink", "Probe", "Resolve"], ["Points separated by 2πR are identified.", "Long-wavelength probes cannot resolve the circle.", "Compact geometry influences masses and couplings in the lower-dimensional theory."]),
  lesson(15, "calabi-yau-space", "Extra Dimensions", "Calabi–Yau Space", "GEOMETRY SHAPES PARTICLE PHYSICS", "Rotate a compact six-dimensional geometry and highlight cycles that determine low-energy fields.", "calabi", "Ric(g) = 0", [control("View rotation", 0, 360, 1, 42, "°"), control("Cycle emphasis", 0, 100, 1, 55, "%")], ["Complex geometry", "Ricci flatness", "Hidden cycles", "Moduli", "Field content", "Topology changes"], ["Unfold", "Rotate", "Select cycle", "Project", "Read spectrum"], ["Calabi–Yau spaces are compact Ricci-flat geometries.", "Different cycles support different wrapped-string states.", "Shape and size parameters appear as fields called moduli."], "/assets/string-theory-studio/calabi-yau.png"),
  lesson(16, "kaluza-klein-modes", "Extra Dimensions", "Kaluza–Klein Modes", "MOMENTUM AROUND A HIDDEN CIRCLE", "Quantize momentum in a compact dimension and build its visible tower of effective masses.", "tower", "mₙ² = m₀² + n²/R²", [control("Mode number", 0, 8, 1, 3, " n"), control("Compact radius", 0.25, 2, 0.05, 0.8, " R")], ["Periodic motion", "Momentum quantum n", "Mass shift", "KK tower", "Radius dependence", "Collider signatures"], ["Wrap", "Quantize", "Raise n", "Build tower", "Detect"], ["Periodic boundary conditions quantize compact momentum.", "Smaller radius produces wider mass spacing.", "No Kaluza–Klein tower has been experimentally confirmed."]),
  lesson(17, "d-branes", "Branes & M-Theory", "D-Branes", "STRING ENDPOINTS MEET DYNAMICAL SURFACES", "Move a brane and watch open-string endpoints remain constrained while closed strings travel through the bulk.", "brane", "X⊥|∂Σ = constant", [control("Brane separation", 0.2, 3, 0.05, 1.3, " ℓₛ"), control("String tension", 0.2, 2, 0.05, 1, " T")], ["Dirichlet boundary", "Neumann direction", "Open endpoints", "Brane motion", "Gauge fields", "Closed-string bulk"], ["Place branes", "Attach", "Separate", "Stretch", "Release"], ["A Dp-brane has p spatial dimensions.", "Open-string endpoints are fixed transversely to the brane.", "Massless open-string modes behave like gauge fields on the brane."], "/assets/string-theory-studio/d-branes.png"),
  lesson(18, "brane-worlds", "Branes & M-Theory", "Brane Worlds", "MATTER STAYS · GRAVITY ROAMS", "Compare fields confined to a three-brane with gravity propagating into an extra-dimensional bulk.", "brane", "S = Sbulk + Sbrane", [control("Bulk depth", 0.2, 3, 0.05, 1.2, ""), control("Gravity leakage", 0, 100, 1, 38, "%")], ["Our 3-brane", "Confined matter", "Bulk spacetime", "Gravity leakage", "Warped geometry", "Observable tests"], ["Place matter", "Emit light", "Launch graviton", "Enter bulk", "Compare"], ["Open-string matter can be localized on a brane.", "Closed-string gravitons are not tied to endpoints.", "Brane-world gravity models are constrained by precision experiments."]),
  lesson(19, "m-theory", "Branes & M-Theory", "M-Theory", "THE ELEVENTH DIMENSION EMERGES", "Increase Type IIA coupling until the hidden circle opens and strings reveal membrane ancestry.", "duality", "R₁₁ = gₛℓₛ", [control("IIA coupling", 0.05, 2, 0.05, 0.6, " gₛ"), control("11th radius", 0.05, 2, 0.05, 0.6, " R₁₁")], ["Strong IIA coupling", "Emergent circle", "Eleven dimensions", "M2-brane", "M5-brane", "Five-theory limit"], ["Weak coupling", "Increase gₛ", "Open circle", "Reveal branes", "Unify"], ["The eleventh radius grows with the Type IIA coupling.", "An M2-brane wrapped on the circle appears as a string.", "M-theory is a proposed nonperturbative framework, not a complete final formulation."]),
  lesson(20, "strings-to-membranes", "Branes & M-Theory", "Strings to Membranes", "EXTEND ONE DIMENSION INTO TWO", "Interpolate from a one-dimensional string to a two-dimensional membrane and compare their vibration patterns.", "brane", "Sₚ = −Tₚ∫dᵖ⁺¹ξ √−det(g)", [control("Surface width", 0, 2, 0.05, 0.8, ""), control("Mode energy", 0.2, 2, 0.05, 0.9, "")], ["String worldsheet", "Membrane volume", "p-brane action", "Surface modes", "Wrapped membrane", "Dimensional reduction"], ["String", "Widen", "Membrane", "Wrap", "Reduce"], ["A p-brane sweeps out a (p+1)-dimensional worldvolume.", "Membranes support richer surface vibration patterns.", "Wrapping a membrane dimension can yield an effective string."]),
  lesson(21, "t-duality", "Dualities", "T-Duality", "LARGE AND SMALL CIRCLES CAN MATCH", "Exchange momentum and winding while inverting the compactification radius.", "duality", "R ↔ α′/R ; n ↔ w", [control("Circle radius", 0.2, 3, 0.05, 1.6, " R"), control("Winding number", 0, 5, 1, 2, " w")], ["Momentum mode", "Winding mode", "Radius inversion", "Self-dual point", "IIA/IIB exchange", "Observable equivalence"], ["Choose R", "Wrap", "Invert", "Exchange", "Compare"], ["Momentum energy grows as 1/R.", "Winding energy grows as R/α′.", "At the self-dual radius, the descriptions coincide most directly."]),
  lesson(22, "s-duality", "Dualities", "S-Duality", "STRONG COUPLING BECOMES WEAK", "Invert the coupling and compare elementary states in one description with solitonic states in its dual.", "duality", "gₛ ↔ 1/gₛ", [control("Coupling", 0.1, 3, 0.05, 0.65, " gₛ"), control("Charge", 1, 5, 1, 2, "")], ["Weak coupling", "Strong coupling", "Coupling inversion", "Electric state", "Magnetic dual", "Nonperturbative test"], ["Start weak", "Increase", "Cross one", "Invert", "Match"], ["S-duality relates strong and weak coupling descriptions.", "Perturbation theory is useful only on the weakly coupled side.", "Dual states may exchange electric and magnetic roles."]),
  lesson(23, "mirror-symmetry", "Dualities", "Mirror Symmetry", "DIFFERENT GEOMETRIES · SAME PHYSICS", "Exchange complex-structure and Kähler deformations between a mirror pair of Calabi–Yau spaces.", "calabi", "h¹¹(X) = h²¹(Y)", [control("Complex deformation", 0, 100, 1, 35, "%"), control("Kähler deformation", 0, 100, 1, 65, "%")], ["Geometry X", "Mirror Y", "Complex moduli", "Kähler moduli", "Hodge exchange", "Quantum equivalence"], ["Select X", "Deform", "Mirror", "Exchange", "Match"], ["Mirror partners can have different topology.", "Their Hodge numbers are exchanged.", "The equivalence turns some hard quantum calculations into easier geometric ones."], "/assets/string-theory-studio/calabi-yau.png"),
  lesson(24, "ads-cft", "Dualities", "AdS/CFT", "GRAVITY IN THE BULK · QUANTUM THEORY ON THE EDGE", "Send an excitation through anti-de Sitter space and follow its encoded response on the boundary.", "ads", "Zgravity[φ₀] = ZCFT[φ₀]", [control("Bulk depth", 0, 100, 1, 58, "%"), control("Boundary energy", 1, 100, 1, 44, "%")], ["AdS geometry", "Conformal boundary", "Bulk field", "Boundary operator", "Radial scale", "Holographic dictionary"], ["Source", "Fall inward", "Propagate", "Reach boundary", "Decode"], ["A gravitational theory in AdS can correspond to a boundary CFT.", "Radial position maps roughly to energy scale.", "The duality is best established in special theoretical settings."]),
  lesson(25, "graviton", "Quantum Gravity", "Graviton", "A CLOSED-STRING SPIN-2 STATE", "Compose left- and right-moving oscillations to reveal the massless spin-2 state associated with gravity.", "graviton", "|g⟩ ∼ αⁱ₋₁ ãʲ₋₁|0⟩", [control("Helicity", -2, 2, 1, 2, ""), control("Wave amplitude", 0.1, 1, 0.05, 0.55, "")], ["Closed-string mode", "Tensor product", "Massless state", "Spin two", "Metric fluctuation", "Low-energy gravity"], ["Left mover", "Right mover", "Combine", "Polarize", "Curve"], ["A symmetric tensor state appears in every closed superstring theory.", "Its low-energy interactions match those expected for a graviton.", "This mathematical feature motivates string theory as quantum gravity."]),
  lesson(26, "emergent-geometry", "Quantum Gravity", "Emergent Geometry", "CONNECT ENTANGLEMENT · BUILD SPACE", "Add or remove quantum links and watch a continuous spatial geometry emerge from connectivity.", "emergent", "Area ∝ entanglement entropy", [control("Entanglement links", 0, 100, 1, 55, "%"), control("Coarse graining", 1, 10, 1, 4, "")], ["Quantum degrees", "Entanglement links", "Tensor networks", "Coarse graining", "Spatial distance", "Emergent continuum"], ["Separate", "Entangle", "Connect", "Coarse-grain", "Emerge"], ["More entanglement can correspond to stronger geometric connectivity.", "Tensor-network pictures illustrate this idea in simplified settings.", "Emergent spacetime remains an active research program."]),
  lesson(27, "holographic-principle", "Quantum Gravity", "Holographic Principle", "A VOLUME ENCODED BY ITS BOUNDARY", "Map interior information onto boundary cells and test how encoding capacity scales with area.", "holographic", "S ≤ A/4Gℏ", [control("Bulk information", 1, 100, 1, 48, "%"), control("Boundary cells", 8, 80, 1, 36, "")], ["Volume intuition", "Black-hole entropy", "Area scaling", "Boundary bits", "Bulk reconstruction", "Information bound"], ["Fill bulk", "Measure area", "Encode", "Scramble", "Reconstruct"], ["Black-hole entropy scales with horizon area.", "This motivates the idea that bulk information admits a boundary description.", "The principle is not a claim that ordinary space is literally a flat screen."]),
  lesson(28, "string-landscape", "Quantum Gravity", "String Landscape", "EXPLORE MANY EFFECTIVE VACUA", "Navigate flux and geometry choices that generate different low-energy constants and particle spectra.", "landscape", "Vvac = V(flux, moduli)", [control("Flux choice", 0, 12, 1, 4, ""), control("Vacuum energy", -1, 1, 0.05, 0.1, "")], ["Compact choices", "Fluxes", "Moduli potential", "Metastable vacua", "Low-energy constants", "Selection problem"], ["Choose geometry", "Add flux", "Stabilize", "Sample vacuum", "Compare"], ["Different compactifications can produce different effective laws.", "Vacuum stability depends on the moduli potential.", "The scale and interpretation of the landscape remain debated."]),
  lesson(29, "black-hole-microstates", "Black Holes & Cosmos", "Black-Hole Microstates", "COUNT STATES · RECOVER ENTROPY", "Increase brane charges and compare microscopic state counting with horizon entropy.", "blackhole", "S = kB ln Ω = A/4Gℏ", [control("D-brane charge", 1, 20, 1, 8, " Q"), control("Momentum charge", 1, 20, 1, 6, " P")], ["Macroscopic horizon", "Entropy formula", "D-brane system", "Bound states", "Microstate count", "Matching limit"], ["Build charges", "Bind", "Count", "Form horizon", "Compare"], ["Certain supersymmetric black holes allow controlled microstate counting.", "The microscopic entropy matches the Bekenstein–Hawking result in those cases.", "A complete description of generic astrophysical black holes is harder."], "/assets/string-theory-studio/black-hole-microstates.png"),
  lesson(30, "hawking-information", "Black Holes & Cosmos", "Hawking Information", "FOLLOW THE PAGE CURVE", "Track radiation entropy through formation, evaporation and the Page time.", "pagecurve", "Srad(t) = min(SHawking, Sisland)", [control("Evaporation time", 0, 100, 1, 34, "%"), control("Initial entropy", 10, 100, 1, 64, " S₀")], ["Pure initial state", "Hawking pairs", "Rising entropy", "Page time", "Island saddle", "Unitary endpoint"], ["Collapse", "Radiate", "Page time", "Turn over", "Evaporate"], ["A purely thermal calculation gives ever-rising radiation entropy.", "Unitary evolution requires entropy to fall after the Page time.", "Island calculations reproduce this curve in tractable gravity models."]),
  lesson(31, "early-universe", "Black Holes & Cosmos", "Early Universe", "BRANES, STRINGS AND RAPID EXPANSION", "Vary brane separation and watch potential energy drive a simplified inflationary expansion.", "cosmos", "H² = 8πGρ/3", [control("Brane separation", 0.2, 3, 0.05, 1.8, ""), control("Expansion rate", 0.1, 2, 0.05, 0.9, " H")], ["Hot early universe", "Brane potential", "Accelerated expansion", "Collision", "Reheating", "Observable imprints"], ["Separate", "Inflate", "Approach", "Collide", "Reheat"], ["Some models identify an inflaton with brane separation.", "Potential energy can drive accelerated expansion.", "These proposals must match precision cosmological data."]),
  lesson(32, "cosmic-superstrings", "Black Holes & Cosmos", "Cosmic Superstrings", "SEARCH THE SKY FOR STRING SIGNALS", "Stretch a cosmic string network and predict lensing and gravitational-wave signatures.", "cosmic-string", "μ ∼ 1/(2πα′)", [control("String tension Gμ", 1, 100, 1, 28, " ×10⁻¹¹"), control("Loop density", 1, 60, 1, 22, "")], ["Formation", "Network scaling", "Intercommutation", "String loops", "Lensing signature", "Wave background"], ["Create", "Stretch", "Reconnect", "Form loops", "Observe"], ["Cosmic superstrings are macroscopic descendants in some cosmologies.", "Their tension controls lensing and gravitational-wave strength.", "Current observations place upper limits rather than confirming detection."]),
];

export const stringTheoryUnits = Array.from(new Set(stringTheoryLessons.map((item) => item.unit)));

export function getStringTheoryLesson(id: string | null) {
  return stringTheoryLessons.find((item) => item.id === id) ?? stringTheoryLessons[0];
}
