export const scaleUniverseSpriteCatalog = {
  "needle-tip": { aspect: 1.9, scale: 2.2 },
  "dust-speck": { aspect: 1, scale: 1.8 },
  "flour-grain": { aspect: 1, scale: 1.8 },
  "sugar-crystal": { aspect: 1, scale: 1.9 },
  "mustard-seed": { aspect: 1, scale: 1.9 },
  "chia-seed": { aspect: 1, scale: 1.9 },
  lentil: { aspect: 1.25, scale: 1.9 },
  peppercorn: { aspect: 1, scale: 1.9 },
  eraser: { aspect: 1.7, scale: 2.2 },
  paperclip: { aspect: 1.85, scale: 2.3 },
  thumbtack: { aspect: 1, scale: 2 },
  staple: { aspect: 1.9, scale: 2.1 },
  button: { aspect: 1, scale: 1.95 },
  marble: { aspect: 1, scale: 1.95 },
  dice: { aspect: 1, scale: 1.95 },
  "battery-aa": { aspect: 0.45, scale: 2.35 },
  "chalk-stick": { aspect: 3.6, scale: 2.6 },
  "usb-drive": { aspect: 1.9, scale: 2.25 },
  key: { aspect: 2.3, scale: 2.35 },
  spoon: { aspect: 4.2, scale: 2.9 },
  fork: { aspect: 4.3, scale: 2.9 },
  toothbrush: { aspect: 4.4, scale: 2.9 },
  calculator: { aspect: 0.74, scale: 2.45 },
  notebook: { aspect: 0.72, scale: 2.45 },
  textbook: { aspect: 0.75, scale: 2.5 },
  "water-bottle": { aspect: 0.42, scale: 2.55 },
  "coffee-mug": { aspect: 1.15, scale: 2.15 },
  "desk-lamp": { aspect: 0.9, scale: 2.55 },
  "school-bag": { aspect: 0.78, scale: 2.85 },
  laptop: { aspect: 1.45, scale: 2.75 },
  tablet: { aspect: 0.72, scale: 2.4 },
  monitor: { aspect: 1.35, scale: 2.65 },
  chair: { aspect: 0.85, scale: 2.65 },
  desk: { aspect: 1.8, scale: 2.8 },
  door: { aspect: 0.46, scale: 2.9 },
  whiteboard: { aspect: 1.75, scale: 2.75 },
  "ceiling-fan": { aspect: 1.9, scale: 2.7 },
  "classroom-window": { aspect: 1.35, scale: 2.6 },
  "student-desk-row": { aspect: 2.9, scale: 3 },
  "laboratory-table": { aspect: 2.1, scale: 2.8 },
  microscope: { aspect: 0.78, scale: 2.6 },
  telescope: { aspect: 2.35, scale: 2.8 },
  football: { aspect: 1, scale: 2.25 },
  basketball: { aspect: 1, scale: 2.25 },
  "football-goal": { aspect: 2.4, scale: 3 },
  "basketball-hoop": { aspect: 0.65, scale: 2.85 },
  "cricket-bat": { aspect: 0.28, scale: 2.85 },
  "tennis-racket": { aspect: 0.45, scale: 2.75 },
  skateboard: { aspect: 2.7, scale: 2.7 },
  scooter: { aspect: 1.6, scale: 2.75 },
  motorbike: { aspect: 2.2, scale: 2.85 },
  "auto-rickshaw": { aspect: 1.55, scale: 2.8 },
  minivan: { aspect: 2.2, scale: 2.9 },
  car: { aspect: 2.35, scale: 2.85 },
  bicycle: { aspect: 2.15, scale: 2.75 },
  "school-bus": { aspect: 2.8, scale: 3 },
  "bus-stop-shelter": { aspect: 1.7, scale: 2.9 },
  "traffic-signal": { aspect: 0.38, scale: 3 },
  "street-light": { aspect: 0.32, scale: 3 },
  "utility-pole": { aspect: 0.28, scale: 3 },
  "small-tree": { aspect: 0.72, scale: 2.9 },
  "mango-tree": { aspect: 0.9, scale: 3 },
  "coconut-tree": { aspect: 0.55, scale: 3 },
  "garden-bench": { aspect: 2, scale: 2.75 },
  "playground-slide": { aspect: 1.5, scale: 2.85 },
  "water-tank": { aspect: 1.1, scale: 2.75 },
  "apartment-floor": { aspect: 2, scale: 2.65 },
  "two-storey-house": { aspect: 1.25, scale: 2.9 },
  "school-building": { aspect: 2.1, scale: 3 },
  "basketball-court": { aspect: 1.85, scale: 3 },
  "cricket-pitch": { aspect: 3.5, scale: 3 },
  "swimming-lane": { aspect: 3.2, scale: 3 },
  "metro-train-car": { aspect: 3.5, scale: 3 },
  "railway-platform": { aspect: 4, scale: 3 },
  "pedestrian-bridge": { aspect: 3, scale: 3 },
  "cell-tower": { aspect: 0.42, scale: 3 },
  "wind-turbine": { aspect: 0.7, scale: 3 },
  "solar-panel-row": { aspect: 3, scale: 3 },
  "water-tower": { aspect: 0.75, scale: 3 },
  "radio-telescope-dish": { aspect: 1.25, scale: 3 },
  "small-pond": { aspect: 1.8, scale: 2.8 },
  "city-block": { aspect: 2.5, scale: 3 },
  neighborhood: { aspect: 2.2, scale: 3 },
  village: { aspect: 2.2, scale: 3 },
  stadium: { aspect: 2.2, scale: 3 },
  "airport-terminal": { aspect: 2.5, scale: 3 },
  "harbor-ship": { aspect: 3.1, scale: 3 },
  "cargo-ship": { aspect: 3.4, scale: 3 },
  dam: { aspect: 3, scale: 3 },
  "bridge-span": { aspect: 4, scale: 3 },
  hill: { aspect: 1.8, scale: 2.8 },
  "river-width": { aspect: 3.5, scale: 3 },
  lake: { aspect: 2.2, scale: 3 },
  island: { aspect: 1.8, scale: 3 },
  cloud: { aspect: 1.8, scale: 2.8 },
  "rain-cell": { aspect: 1.5, scale: 2.8 },
  thunderstorm: { aspect: 1.45, scale: 2.9 },
  "hot-air-balloon": { aspect: 0.75, scale: 2.9 },
  drone: { aspect: 2.2, scale: 2.5 },
  "satellite-bus": { aspect: 1.4, scale: 2.6 },
  human: { aspect: 0.42, scale: 2.85 },
  giraffe: { aspect: 0.78, scale: 3 },
  elephant: { aspect: 1.75, scale: 3 },
  "blue-whale": { aspect: 3, scale: 3 },
  "tyrannosaurus-rex": { aspect: 1.9, scale: 3 },
};

export function scaleUniverseSpritePath(assetKey) {
  return `/assets/scale-universe/sprites/${assetKey}.png`;
}

export function scaleUniverseSpriteSpec(assetKey) {
  const metadata = scaleUniverseSpriteCatalog[assetKey];
  if (!metadata) return null;
  return {
    assetPath: scaleUniverseSpritePath(assetKey),
    assetAspect: metadata.aspect,
    assetScale: metadata.scale,
  };
}
