export const localScaleObjectSpecs = [
  ["needle-tip", "Needle Tip", "Everyday Object", 1e-4, "Human Scale", 7, "A sharp metal tip useful for comparing sub-millimeter sizes."],
  ["dust-speck", "Dust Speck", "Everyday Object", 5e-5, "Human Scale", 7, "A small visible speck near the limit of everyday sight."],
  ["flour-grain", "Flour Grain", "Everyday Object", 1.5e-4, "Human Scale", 7, "A tiny food particle only a fraction of a millimeter across."],
  ["sugar-crystal", "Sugar Crystal", "Everyday Object", 6e-4, "Human Scale", 7, "A small crystal made from many sugar molecules."],
  ["mustard-seed", "Mustard Seed", "Everyday Object", 1.5e-3, "Human Scale", 7, "A familiar seed measured in millimeters."],
  ["chia-seed", "Chia Seed", "Everyday Object", 2e-3, "Human Scale", 7, "A tiny seed that helps compare small visible objects."],
  ["lentil", "Lentil", "Everyday Object", 5e-3, "Human Scale", 7, "A small food item near half a centimeter wide."],
  ["peppercorn", "Peppercorn", "Everyday Object", 5e-3, "Human Scale", 7, "A small round spice at millimeter scale."],
  ["eraser", "Eraser", "Everyday Object", 4e-2, "Human Scale", 7, "A classroom object measured in centimeters."],
  ["paperclip", "Paper Clip", "Everyday Object", 3.3e-2, "Human Scale", 7, "A small bent wire object used to compare centimeters."],
  ["thumbtack", "Thumbtack", "Everyday Object", 1.2e-2, "Human Scale", 7, "A small pin-like object near centimeter scale."],
  ["staple", "Staple", "Everyday Object", 1.3e-2, "Human Scale", 7, "A small metal fastener a little over one centimeter wide."],
  ["button", "Button", "Everyday Object", 1.8e-2, "Human Scale", 7, "A small clothing fastener at centimeter scale."],
  ["marble", "Marble", "Everyday Object", 1.6e-2, "Human Scale", 7, "A small glass sphere useful for radius and diameter comparisons."],
  ["dice", "Dice", "Everyday Object", 1.6e-2, "Human Scale", 7, "A cube-shaped object with equal side lengths."],
  ["battery-aa", "AA Battery", "Everyday Object", 5e-2, "Human Scale", 7, "A common cylindrical battery roughly five centimeters long."],
  ["chalk-stick", "Chalk Stick", "Everyday Object", 8e-2, "Human Scale", 7, "A classroom object about the length of a hand."],
  ["usb-drive", "USB Drive", "Everyday Object", 6e-2, "Human Scale", 7, "A small storage device at centimeter scale."],
  ["key", "Key", "Everyday Object", 6e-2, "Human Scale", 7, "A metal object that fits easily in the hand."],
  ["spoon", "Spoon", "Everyday Object", 1.8e-1, "Human Scale", 7, "A utensil measured in tens of centimeters."],
  ["fork", "Fork", "Everyday Object", 1.9e-1, "Human Scale", 7, "A utensil slightly longer than many pencils."],
  ["toothbrush", "Toothbrush", "Everyday Object", 1.8e-1, "Human Scale", 7, "A personal object at decimeter scale."],
  ["calculator", "Calculator", "Everyday Object", 1.5e-1, "Human Scale", 7, "A classroom device that fits in one hand."],
  ["notebook", "Notebook", "Everyday Object", 2.4e-1, "Human Scale", 7, "A page-sized object useful for area comparisons."],
  ["textbook", "Textbook", "Everyday Object", 2.8e-1, "Human Scale", 7, "A book-sized classroom object at decimeter scale."],
  ["water-bottle", "Water Bottle", "Everyday Object", 2.5e-1, "Human Scale", 7, "A common bottle roughly a quarter meter tall."],
  ["coffee-mug", "Coffee Mug", "Everyday Object", 1.1e-1, "Human Scale", 7, "A cup-sized object that helps compare decimeter lengths."],
  ["desk-lamp", "Desk Lamp", "Everyday Object", 4e-1, "Human Scale", 7, "A tabletop lamp around half a meter tall."],
  ["school-bag", "School Bag", "Everyday Object", 4.5e-1, "Human Scale", 7, "A carried object close to torso scale."],
  ["laptop", "Laptop", "Everyday Object", 3.5e-1, "Human Scale", 8, "A familiar computer measured in tens of centimeters."],
  ["tablet", "Tablet", "Everyday Object", 2.5e-1, "Human Scale", 7, "A flat handheld device at decimeter scale."],
  ["monitor", "Computer Monitor", "Everyday Object", 6e-1, "Human Scale", 7, "A desktop display about half a meter across."],
  ["chair", "Chair", "Furniture", 9e-1, "Human Scale", 7, "A seat that connects furniture scale to human body scale."],
  ["desk", "Desk", "Furniture", 1.2, "Human Scale", 7, "A classroom table near meter scale."],
  ["door", "Door", "Building Part", 2.1, "Human Scale", 8, "A human-height opening useful for comparing body scale."],
  ["whiteboard", "Whiteboard", "Building Part", 2.4, "Human Scale", 7, "A classroom board a few meters across."],
  ["ceiling-fan", "Ceiling Fan", "Everyday Object", 1.2, "Human Scale", 7, "A rotating object near meter scale."],
  ["classroom-window", "Classroom Window", "Building Part", 1.5, "Human Scale", 7, "A window about the size of a person."],
  ["student-desk-row", "Student Desk Row", "Classroom Object", 5, "Human Scale", 7, "A row of desks spanning several meters."],
  ["laboratory-table", "Laboratory Table", "Classroom Object", 2.4, "Human Scale", 7, "A workbench-sized object used in science rooms."],
  ["microscope", "Microscope", "Scientific Instrument", 4e-1, "Human Scale", 8, "A classroom instrument used to observe microscopic objects."],
  ["telescope", "Small Telescope", "Scientific Instrument", 9e-1, "Human Scale", 8, "An optical instrument near meter scale."],
  ["football-goal", "Football Goal", "Sports Object", 7.3, "Human Scale", 7, "A sports structure several meters wide."],
  ["basketball-hoop", "Basketball Hoop", "Sports Object", 3.05, "Human Scale", 7, "A regulation hoop height just over three meters."],
  ["cricket-bat", "Cricket Bat", "Sports Object", 9.7e-1, "Human Scale", 7, "A handheld sports object close to one meter long."],
  ["tennis-racket", "Tennis Racket", "Sports Object", 6.9e-1, "Human Scale", 7, "A sports object around two-thirds of a meter long."],
  ["skateboard", "Skateboard", "Vehicle", 8e-1, "Human Scale", 7, "A small wheeled board below one meter long."],
  ["scooter", "Scooter", "Vehicle", 1.1, "Human Scale", 7, "A compact vehicle near meter scale."],
  ["motorbike", "Motorbike", "Vehicle", 2.1, "Human Scale", 7, "A two-wheeled vehicle a few meters long."],
  ["auto-rickshaw", "Auto Rickshaw", "Vehicle", 2.6, "Human Scale", 7, "A compact three-wheeled vehicle."],
  ["minivan", "Minivan", "Vehicle", 4.8, "Human Scale", 7, "A family vehicle slightly larger than a car."],
  ["bus-stop-shelter", "Bus Stop Shelter", "Building / Landmark", 5, "Earth and Geography", 7, "A small street structure at human scale."],
  ["traffic-signal", "Traffic Signal", "Building / Landmark", 4.5, "Earth and Geography", 7, "A roadside signal structure taller than a person."],
  ["street-light", "Street Light", "Building / Landmark", 8, "Earth and Geography", 7, "A pole-mounted light at small infrastructure scale."],
  ["utility-pole", "Utility Pole", "Building / Landmark", 1.2e1, "Earth and Geography", 7, "A tall pole that carries wires above streets."],
  ["small-tree", "Small Tree", "Plant", 4, "Earth and Geography", 7, "A young tree a few meters tall."],
  ["mango-tree", "Mango Tree", "Plant", 1.5e1, "Earth and Geography", 7, "A mature fruit tree at house scale."],
  ["coconut-tree", "Coconut Tree", "Plant", 2.5e1, "Earth and Geography", 7, "A tall palm tree at tens of meters scale."],
  ["garden-bench", "Garden Bench", "Everyday Object", 1.8, "Human Scale", 7, "A public seat close to human body scale."],
  ["playground-slide", "Playground Slide", "Building / Landmark", 4, "Earth and Geography", 7, "A small playground structure."],
  ["water-tank", "Water Tank", "Building / Landmark", 3, "Earth and Geography", 7, "A storage tank a few meters across."],
  ["apartment-floor", "Apartment Floor Height", "Building / Landmark", 3.2, "Earth and Geography", 7, "A single floor height in a building."],
  ["two-storey-house", "Two Storey House", "Building / Landmark", 7, "Earth and Geography", 8, "A small building measured in meters."],
  ["school-building", "School Building", "Building / Landmark", 3e1, "Earth and Geography", 8, "A familiar campus building at tens of meters scale."],
  ["basketball-court", "Basketball Court", "Sports Object", 2.8e1, "Earth and Geography", 7, "A court almost thirty meters long."],
  ["cricket-pitch", "Cricket Pitch", "Sports Object", 2.012e1, "Earth and Geography", 7, "A standard pitch about twenty meters long."],
  ["swimming-lane", "Swimming Lane", "Sports Object", 5e1, "Earth and Geography", 7, "A pool lane length at tens of meters scale."],
  ["metro-train-car", "Metro Train Car", "Vehicle", 2.2e1, "Human Scale", 7, "A rail car about twenty meters long."],
  ["railway-platform", "Railway Platform", "Building / Landmark", 2e2, "Earth and Geography", 7, "A long platform spanning hundreds of meters."],
  ["pedestrian-bridge", "Pedestrian Bridge", "Building / Landmark", 4e1, "Earth and Geography", 7, "A small bridge at street scale."],
  ["cell-tower", "Cell Tower", "Building / Landmark", 4e1, "Earth and Geography", 7, "A tower used for wireless communication."],
  ["wind-turbine", "Wind Turbine", "Building / Landmark", 1.2e2, "Earth and Geography", 8, "A large machine that converts wind energy into electricity."],
  ["solar-panel-row", "Solar Panel Row", "Building / Landmark", 2e1, "Earth and Geography", 7, "A row of solar panels at tens of meters scale."],
  ["water-tower", "Water Tower", "Building / Landmark", 5e1, "Earth and Geography", 7, "An elevated water storage structure."],
  ["radio-telescope-dish", "Radio Telescope Dish", "Scientific Instrument", 1e2, "Earth and Geography", 8, "A large dish that detects radio waves from space."],
  ["small-pond", "Small Pond", "Geography", 3e1, "Earth and Geography", 7, "A small body of water at local outdoor scale."],
  ["city-block", "City Block", "Geography", 1.2e2, "Earth and Geography", 7, "A city block is a useful urban distance."],
  ["neighborhood", "Neighborhood", "Geography", 1e3, "Earth and Geography", 7, "A local area about a kilometer across."],
  ["village", "Village", "Geography", 2e3, "Earth and Geography", 7, "A settlement measured in kilometers."],
  ["stadium", "Stadium", "Building / Landmark", 2e2, "Earth and Geography", 8, "A large sports venue at hundreds of meters scale."],
  ["airport-terminal", "Airport Terminal", "Building / Landmark", 5e2, "Earth and Geography", 7, "A large transportation building."],
  ["harbor-ship", "Harbor Ship", "Vehicle", 1.5e2, "Human Scale", 7, "A large ship seen at harbor scale."],
  ["cargo-ship", "Cargo Ship", "Vehicle", 3e2, "Human Scale", 8, "A very large ship hundreds of meters long."],
  ["dam", "Dam", "Building / Landmark", 2e2, "Earth and Geography", 8, "A major structure that holds back water."],
  ["bridge-span", "Bridge Span", "Building / Landmark", 1e3, "Earth and Geography", 8, "A large bridge span can reach kilometer scale."],
  ["hill", "Hill", "Geography", 3e2, "Earth and Geography", 7, "A local landform smaller than a mountain."],
  ["river-width", "River Width", "Geography", 5e2, "Earth and Geography", 7, "A wide river crossing measured in hundreds of meters."],
  ["lake", "Lake", "Geography", 1e4, "Earth and Geography", 8, "A lake can span many kilometers."],
  ["island", "Island", "Geography", 5e4, "Earth and Geography", 8, "An island can span city to regional scale."],
  ["cloud", "Cloud", "Atmosphere", 1e3, "Earth and Geography", 7, "A cloud can be around a kilometer wide."],
  ["rain-cell", "Rain Cell", "Atmosphere", 5e3, "Earth and Geography", 7, "A local rain cell spans several kilometers."],
  ["thunderstorm", "Thunderstorm Cell", "Atmosphere", 1e4, "Earth and Geography", 8, "A storm cell can cover a large local area."],
  ["hot-air-balloon", "Hot Air Balloon", "Vehicle", 2e1, "Human Scale", 7, "A balloon is a large human-made object that floats in air."],
  ["drone", "Drone", "Vehicle", 5e-1, "Human Scale", 7, "A small flying machine at hand scale."],
  ["satellite-bus", "Small Satellite Bus", "Vehicle", 1.5, "Human Scale", 8, "A compact spacecraft body about person scale."],
];
