import {
  buoyantForce,
  freeFallDistance,
  freeFallVelocity,
  hookeForce,
  idealGasPressure,
  lensImageDistance,
  mirrorImageDistance,
  newtonSecondLaw,
  ohmsLawVoltage,
  pendulumPeriod,
  photoelectricKineticEnergy,
  projectileRange,
  pressure,
  snellRefractionAngle,
  halfLifeRemaining,
} from "../../lib/labCalculators";

export const physicsValidationCases = [
  { name: "Free Fall distance", actual: freeFallDistance(0, 9.8, 2).value, expected: 19.6, tolerance: 1e-12 },
  { name: "Free Fall velocity", actual: freeFallVelocity(0, 9.8, 3).value, expected: 29.4, tolerance: 1e-12 },
  { name: "Projectile Motion range", actual: projectileRange(10, 45, 10).value, expected: 10, tolerance: 1e-12 },
  { name: "Newton Second Law", actual: newtonSecondLaw(10, 2).value, expected: 5, tolerance: 1e-12 },
  { name: "Hooke Law", actual: hookeForce(100, 0.2).value, expected: -20, tolerance: 1e-12 },
  { name: "Pendulum", actual: pendulumPeriod(1, 9.80665).value, expected: 2.006409, tolerance: 1e-5 },
  { name: "Ohm Law", actual: ohmsLawVoltage(2, 5).value, expected: 10, tolerance: 1e-12 },
  { name: "Pressure", actual: pressure(10, 2).value, expected: 5, tolerance: 1e-12 },
  { name: "Buoyancy", actual: buoyantForce(1000, 9.8, 0.01).value, expected: 98, tolerance: 1e-12 },
  { name: "Snell Law", actual: snellRefractionAngle(30, 1, 1.5).value, expected: 19.4712206, tolerance: 1e-6 },
  { name: "Lens Formula", actual: lensImageDistance(10, 30).value, expected: 7.5, tolerance: 1e-12 },
  { name: "Mirror Formula", actual: mirrorImageDistance(10, 30).value, expected: 15, tolerance: 1e-12 },
  { name: "Gas Laws", actual: idealGasPressure(1, 300, 0.024943).value, expected: 100000, tolerance: 5 },
  { name: "Photoelectric Effect", actual: photoelectricKineticEnergy(3, 2).value, expected: 1, tolerance: 1e-12 },
  { name: "Half-Life", actual: halfLifeRemaining(100, 20, 10).value, expected: 25, tolerance: 1e-12 },
] as const;
