import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { PhysicsAtlasIcon as Icon } from '../components/PhysicsAtlasIcon';
import type { PhysicsIconName } from '../lib/icons';
import { ConceptRelationshipGraph, type ConceptPositions } from '../components/ConceptRelationshipGraph';
import { ConceptRelationshipExample } from '../components/ConceptRelationshipExample';
import { relationshipConcepts, relationshipById, relationshipEdges, relationshipFormula, relationshipReadings, RELATIONSHIP_DEFAULTS, type RelationshipParameters } from '../lib/conceptRelationships';
import '../concept-relationships.css';

const challenges=[
 {question:'Keep the net force fixed and double the mass. What happens to the acceleration?',answers:['It doubles','It halves','It stays the same'],correct:'It halves',explanation:'a = F/m, so twice the mass gives half the acceleration at the same net force.'},
 {question:'Keep the mass fixed and double the speed. What happens to kinetic energy?',answers:['It doubles','It quadruples','It stays the same'],correct:'It quadruples',explanation:'K = ½mv², so doubling speed multiplies kinetic energy by four.'},
 {question:'Double the period of an oscillation. What happens to its frequency?',answers:['It doubles','It halves','It stays the same'],correct:'It halves',explanation:'f = 1/T, so doubling the period halves the frequency.'},
];
const observations={dynamics:'At the same mass, a larger net force produces a greater acceleration.',work:'Thrust can transfer energy by doing work as a rocket moves. Net work changes kinetic energy.',kinetic:'At the same mass, doubling a rocket’s speed quadruples its kinetic energy.',potential:'Near Earth’s surface, increasing altitude raises gravitational potential energy relative to the ground.',power:'Delivering the same work in less time requires greater average power.',oscillation:'Launch vibrations have a period and frequency: a shorter cycle means a higher frequency.',waves:'Sound from a launch travels through air; wave speed equals frequency times wavelength.',light:'Light from the exhaust travels at c in vacuum. Its frequency sets its wavelength.',fields:'Electric currents in spacecraft coils create magnetic fields; reversing current reverses the field.'};
type Dialog='Predict'|'Experiment'|'Explain'|'Notebook'|'Settings'|'Help'|null;
const initialPositions=()=>Object.fromEntries(relationshipConcepts.map(c=>[c.id,{x:c.x,y:c.y}]));
const controls:Record<keyof RelationshipParameters,[string,number,number,number,string]>={force:['Net force',-20,20,.5,'N'],mass:['Mass',.1,10,.1,'kg'],displacement:['Displacement',-5,5,.1,'m'],duration:['Elapsed time',.1,10,.1,'s'],speed:['Speed',0,20,.1,'m/s'],height:['Height',-10,10,.1,'m'],period:['Period',.1,5,.1,'s'],frequency:['Frequency',0,10,.1,'Hz'],wavelength:['Wavelength',.1,3,.1,'m'],opticalFrequency:['Light frequency',100,1000,10,'THz'],current:['Coil current',-5,5,.1,'A']};

export function ConceptRelationshipsPage(){
 const [selected,setSelected]=useState('force'),[strength,setStrength]=useState(.7),[layer,setLayer]=useState('all'),[mode,setMode]=useState('Observe'),[running,setRunning]=useState(true),[zoom,setZoom]=useState(1),[positions,setPositions]=useState<ConceptPositions>(initialPositions),[detail,setDetail]=useState('Connections'),[dialog,setDialog]=useState<Dialog>(null),[parameters,setParameters]=useState({...RELATIONSHIP_DEFAULTS}),[answer,setAnswer]=useState(''),[checked,setChecked]=useState(false),[version,setVersion]=useState(0);
 const [notes,setNotes]=useState(()=>{try{return localStorage.getItem('concept-relationship-notes')??'';}catch{return '';}}),[saved,setSaved]=useState(false);
 const [challengeIndex,setChallengeIndex]=useState(0),challenge=challenges[challengeIndex];
 const panel=useRef<HTMLDivElement>(null);
 const concept=relationshipById.get(selected)!,formula=relationshipFormula[concept.family],readings=relationshipReadings(concept.family,parameters);
 const direct=relationshipEdges.filter(e=>e.a===selected||e.b===selected).map(e=>({id:e.a===selected?e.b:e.a,strength:e.strength}));
 const related=(selected==='force'?['work','energy','motion'].map(id=>relationshipById.get(id)!):relationshipConcepts.filter(c=>c.id!==selected&&!direct.some(d=>d.id===c.id)&&c.main).slice(0,3));
 const parameterKeys:Record<string,Array<keyof RelationshipParameters>>={dynamics:['force','mass'],work:['force','displacement'],kinetic:['mass','speed'],potential:['mass','height'],power:['force','displacement','duration'],oscillation:['period'],waves:['frequency','wavelength'],light:['opticalFrequency'],fields:['current']};
 useEffect(()=>{if(!dialog)return;const previous=document.activeElement as HTMLElement;panel.current?.querySelector<HTMLElement>('button')?.focus();const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setDialog(null);if(e.key==='Tab'){const all=panel.current?.querySelectorAll<HTMLElement>('button,a[href],input,textarea,select');if(!all?.length)return;if(e.shiftKey&&document.activeElement===all[0]){e.preventDefault();all[all.length-1].focus();}else if(!e.shiftKey&&document.activeElement===all[all.length-1]){e.preventDefault();all[0].focus();}}};document.addEventListener('keydown',onKey);return()=>{document.removeEventListener('keydown',onKey);previous?.focus();};},[dialog]);
 function reset(){setSelected('force');setStrength(.7);setLayer('all');setMode('Observe');setRunning(true);setZoom(1);setPositions(initialPositions());setDetail('Connections');setDialog(null);setParameters({...RELATIONSHIP_DEFAULTS});setAnswer('');setChecked(false);setChallengeIndex(0);setVersion(v=>v+1);}
 function chooseMode(value:string){setMode(value);setDialog(value==='Observe'?null:value as Dialog);setAnswer('');setChecked(false);}
 return <div className="cr-page" data-ui-theme="dark">
  <aside className="cr-sidebar"><Link className="cr-brand" to="/concept-studio">CONCEPT<br/>STUDIO</Link><nav aria-label="Concept studio navigation">
   <Link aria-label="Home" to="/"><Icon name="home"/><span>Home</span></Link><Link aria-label="Concept Map" to="/concept-studio"><Icon name="atom"/><span>Concept Map</span></Link><Link aria-label="Concept Relationships" to="/graph" className="active" aria-current="page"><Icon name="atom"/><span>Concept<br/>Relationships</span></Link><Link aria-label="Simulations" to="/graph?view=experiments"><Icon name="chart"/><span>Simulations</span></Link>
   <button aria-label="Challenges" onClick={()=>chooseMode('Predict')}><Icon name="teacher"/><span>Challenges</span></button><Link aria-label="Resources" to="/formulas"><Icon name="book"/><span>Resources</span></Link><button aria-label="Notebook" onClick={()=>setDialog('Notebook')}><Icon name="clipboard"/><span>Notebook</span></button>
  </nav><div className="cr-sidebar-bottom"><button aria-label="Settings" onClick={()=>setDialog('Settings')}><Icon name="settings"/><span>Settings</span></button><button aria-label="Help" onClick={()=>setDialog('Help')}><span className="cr-help-icon">?</span><span>Help</span></button></div></aside>
  <main className="cr-main" id="content">
   <header className="cr-header"><p>CONCEPT STUDIO</p><h1>CONCEPT RELATIONSHIPS</h1><span>Explore how key physics concepts connect and influence each other.</span><small>IDEAS　→　CONNECTIONS　→　DEEPER UNDERSTANDING</small></header>
   <div className="cr-workspace"><section className="cr-map-panel" aria-label="Concept relationship map">
    <ConceptRelationshipGraph key={version} selected={selected} strength={strength} layer={layer} zoom={zoom} running={running} positions={positions} onSelect={setSelected} onMove={(id,x,y)=>setPositions(p=>({...p,[id]:{x,y}}))}/>
    <div className="cr-map-legend"><span><i className="cyan"/>Core concept</span><span><i className="blue"/>Related concept</span><span><i className="purple"/>Extended concept</span></div><span className="cr-map-badge">⌾　Interactive Map</span>
    <div className="cr-map-zoom"><button aria-label="Zoom out" disabled={zoom<=.6} onClick={()=>setZoom(z=>Math.max(.6,+(z-.1).toFixed(1)))}>−</button><output>{Math.round(zoom*100)}%</output><button aria-label="Zoom in" disabled={zoom>=1.6} onClick={()=>setZoom(z=>Math.min(1.6,+(z+.1).toFixed(1)))}>+</button><button onClick={()=>setZoom(1)}>Fit</button></div>
   </section><aside className="cr-inspector">
    <section className="cr-panel cr-controls"><h2>CONTROLS</h2><label><span>Focus Concept</span><select aria-label="Focus Concept" value={selected} onChange={e=>setSelected(e.target.value)}>{relationshipConcepts.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label><span>Link Strength</span><span className="cr-strength"><input type="range" aria-label="Link Strength" min=".1" max="1" step=".05" value={strength} onChange={e=>setStrength(+e.target.value)}/><output>{strength.toFixed(2)}</output></span></label><label><span>Prerequisite Layer</span><select aria-label="Prerequisite Layer" value={layer} onChange={e=>setLayer(e.target.value)}><option value="all">Show prerequisites</option><option value="hide">Hide prerequisites</option><option value="only">Prerequisites only</option></select></label></section>
    <section className="cr-panel cr-mode"><h2>MODE</h2><div>{([['Observe','eye'],['Predict','chart'],['Experiment','flask'],['Explain','spark']] as Array<[string,PhysicsIconName]>).map(([label,icon])=><button key={label} className={mode===label?'active':''} aria-pressed={mode===label} onClick={()=>chooseMode(label)}><Icon name={icon}/>{label}</button>)}</div></section>
    <section className="cr-panel cr-values"><h2>LIVE VALUES <span>({concept.family==='dynamics'?'Force → Acceleration':concept.label})</span></h2><dl>{readings.map(([label,symbol,value,unit],i)=><div key={label}><dt>{label}　<i>{symbol}</i></dt><dd className={i===2?'result':''}>{value.toFixed(concept.family==='light'&&i===2?0:1)} <small>{unit}</small></dd></div>)}</dl></section>
    <section className="cr-panel cr-navigation"><h2>NAVIGATION</h2><div><button aria-label="Reset" onClick={reset}><span aria-hidden="true">⟳</span>Reset</button><button onClick={()=>setRunning(v=>!v)} aria-label={running?'Pause':'Play'}><span aria-hidden="true">{running?'Ⅱ':'▷'}</span>{running?'Pause':'Play'}</button><button onClick={()=>setZoom(z=>z>=1.6?1:Math.min(1.6,z+.2))}><Icon name="search"/>Zoom</button><button aria-label="Next Challenge" onClick={()=>{setChallengeIndex(i=>(i+1)%challenges.length);chooseMode('Predict');}}><span aria-hidden="true">→</span>Next Challenge</button></div></section>
   </aside></div>
   <section className="cr-summary" aria-label="Selected concept details">
    <div className="cr-selected"><h2>SELECTED CONCEPT</h2><div className="cr-selected-title"><i/><span>{concept.label}</span><small>{concept.main?'Core':'Related'}</small></div>{(['Connections','Details','Examples'] as const).map((tab,i)=><button key={tab} className={detail===tab?'active':''} aria-pressed={detail===tab} onClick={()=>setDetail(tab)}><Icon name={(['atom','clipboard','spark'] as const)[i]}/>{tab}</button>)}</div>
    <div className="cr-links">{detail==='Connections'?<><h2>DIRECT LINKS</h2>{direct.slice(0,3).map(d=><button key={d.id} onClick={()=>setSelected(d.id)}><i/>{concept.label} → {relationshipById.get(d.id)!.label}<small>{d.strength>.8?'Strong':'Moderate'}</small></button>)}<h2>RELATED CONCEPTS</h2>{related.map(c=><button key={c.id} onClick={()=>setSelected(c.id)}><i/>{c.label}<small>Explore</small></button>)}</>:detail==='Details'?<><h2>CONCEPT DETAILS</h2><p>{concept.description}</p><p>Links describe conceptual connections, not physical trajectories.</p></>:<><h2>EXPERIMENTS</h2><p>Explore {concept.label.toLowerCase()} with its existing lesson and controls.</p><Link to={concept.route}>Open {concept.label} lab →</Link><Link aria-label="Simulations" to="/graph?view=experiments">Browse all experiments →</Link></>}</div>
    <div className="cr-key-relationship"><h2>KEY RELATIONSHIP</h2><div>{formula.equation}</div><dl>{formula.variables.map(([symbol,label])=><div key={symbol}><dt>{symbol}</dt><dd>{label}</dd></div>)}</dl></div>
    <div className="cr-visual-example"><h2>VISUAL EXAMPLE</h2><ConceptRelationshipExample parameters={parameters} family={concept.family}/></div>
    <div className="cr-observation"><h2>REAL-WORLD OBSERVATION</h2><img src="/assets/concept-relationships/rocket-launch.png" alt="Rocket accelerating upward under thrust"/><p>{observations[concept.family]}</p></div>
   </section>
  </main>
  {dialog&&<div className="cr-dialog-backdrop" onClick={e=>{if(e.target===e.currentTarget)setDialog(null);}}><div className="cr-dialog" ref={panel} role="dialog" aria-modal="true" aria-labelledby="cr-dialog-title"><header><h2 id="cr-dialog-title">{dialog==='Predict'?'Predict the relationship':dialog}</h2><button aria-label="Close panel" onClick={()=>setDialog(null)}>×</button></header>
   {dialog==='Predict'&&<><p>{challenge.question}</p><div className="cr-answers">{challenge.answers.map(value=><button key={value} className={answer===value?'active':''} aria-pressed={answer===value} onClick={()=>{setAnswer(value);setChecked(false);}}>{value}</button>)}</div><button className="cr-primary" disabled={!answer} onClick={()=>setChecked(true)}>Check prediction</button>{checked&&<p role="status">{answer===challenge.correct?'Correct.':'Try again.'} {challenge.explanation}</p>}<button className="cr-primary" onClick={()=>{setSelected(['force','kinetic','oscillation'][challengeIndex]);chooseMode('Experiment');}}>Test with the controls</button></>}
   {dialog==='Experiment'&&<><p>{concept.description}</p><div className="cr-lab-controls">{parameterKeys[concept.family].map(key=>{const [label,min,max,step,unit]=controls[key];return <label key={key}><span>{label}<output>{parameters[key]} {unit}</output></span><input aria-label={label} type="range" min={min} max={max} step={step} value={parameters[key]} onChange={e=>setParameters(p=>({...p,[key]:+e.target.value}))}/></label>;})}</div><div className="cr-lab-readings">{readings.map(([label,,value,unit])=><p key={label}>{label}: <strong>{value.toFixed(3)} {unit}</strong></p>)}</div><ConceptRelationshipExample parameters={parameters} family={concept.family}/><button className="cr-primary" onClick={()=>setParameters({...RELATIONSHIP_DEFAULTS})}>Reset values</button></>}
   {dialog==='Explain'&&<><p>{concept.description}</p><p className="cr-explain-equation">{formula.equation}</p><p>Net work changes kinetic energy: Wₙₑₜ = ΔK. Heat transfer can also change a system’s energy, so work is not every possible energy change.</p><p>Light’s c = λf applies in vacuum. Link Strength changes the map’s visual emphasis; it is not a measured coupling or force. Animated highlights show conceptual connections.</p></>}
   {dialog==='Notebook'&&<><label>Observations<textarea rows={7} value={notes} onChange={e=>{setNotes(e.target.value);setSaved(false);}}/></label><button className="cr-primary" onClick={()=>{try{localStorage.setItem('concept-relationship-notes',notes);setSaved(true);}catch{setSaved(false);}}}>Save notes</button>{saved&&<p role="status">Saved on this device.</p>}</>}
   {dialog==='Settings'&&<><label className="cr-setting"><input type="checkbox" checked={running} onChange={e=>setRunning(e.target.checked)}/> Animate conceptual connections</label><button className="cr-primary" onClick={reset}>Restore defaults</button></>}
   {dialog==='Help'&&<><p>Select a node or choose Focus Concept. Drag nodes to arrange the map; use arrow keys while a node is focused for keyboard movement.</p><p>Use Experiment to change physical quantities. Observe reads the map, Predict tests a relationship, and Explain gives its conditions.</p><p>Use −, +, or Fit to change the view. Reset restores the starting map and all example values. Escape closes this panel.</p></>}
  </div></div>}
 </div>;
}
