import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { createPortal } from 'react-dom';
import { GuidedPathIcon as Icon } from '../components/GuidedPathIcon';
import type { PhysicsIconName } from '../lib/icons';
import { LauncherScene } from '../components/LauncherScene';
import { LauncherGraph } from '../components/LauncherGraph';
import { LauncherRayDiagram } from '../components/LauncherRayDiagram';
import { LAUNCHER_DEFAULTS, launcherControls, launcherParameterKeys, launcherReadings, launcherStudios, type LauncherEquipment, type LauncherParameters, type LauncherStudio } from '../lib/experimentLauncher';
import '../experiment-launcher.css';
type Panel='Predict'|'Explain'|'Notebook'|'Analytics'|'Settings'|null;
const challenges:Record<LauncherStudio,{question:string;options:string[];answer:string;reason:string}>={
 optics:{question:'A 532 nm laser enters ordinary glass. Does it split into a rainbow?',options:['Yes, into every visible color','No, it remains monochromatic','It becomes white light'],answer:'No, it remains monochromatic',reason:'Refraction changes direction and wavelength inside the medium, not the source frequency. A spectrum requires multiple incident frequencies.'},
 mechanics:{question:'Double the pendulum length. How does its small-angle period change?',options:['It doubles','It grows by √2','It halves'],answer:'It grows by √2',reason:'T = 2π√(L/g), so the period grows with the square root of length.'},
 circuits:{question:'At fixed voltage, double the resistance. What happens to current?',options:['It doubles','It halves','It stays the same'],answer:'It halves',reason:'Ohm’s law gives I = V/R.'},
 thermal:{question:'At fixed heater power, double the water mass. What happens to its heating rate?',options:['It halves','It doubles','It stays the same'],answer:'It halves',reason:'dT/dt = P/(mc), assuming no heat loss and constant specific heat.'},
 waves:{question:'Double frequency at the same sound speed. What happens to wavelength?',options:['It doubles','It halves','It stays the same'],answer:'It halves',reason:'λ = v/f, so the wavelength halves.'},
};
const numerical:Record<LauncherStudio,{question:string;options:string[];answer:string;reason:string}>={
 optics:{question:'Light enters n = 1.52 glass from air at 30.0 degrees. What is its refracted angle?',options:['19.2 degrees','18.1 degrees','30.0 degrees'],answer:'19.2 degrees',reason:'Snell law gives arcsin(sin(30 degrees)/1.52) = 19.2049 degrees.'},
 mechanics:{question:'What is the small-angle period for L = 1.00 m and g = 9.81 m/s2?',options:['2.01 s','1.00 s','6.28 s'],answer:'2.01 s',reason:'T = 2 pi sqrt(1/9.81) = 2.0061 seconds.'},
 circuits:{question:'A 6.00 V source drives a 100 ohm resistor. What current flows?',options:['0.060 A','0.600 A','6.000 A'],answer:'0.060 A',reason:'I = V/R = 6/100 = 0.060 A.'},
 thermal:{question:'A 250 W heater warms 1 kg of water for 10 s with no losses. Approximately how much does temperature rise?',options:['0.60 degrees C','2.50 degrees C','25.0 degrees C'],answer:'0.60 degrees C',reason:'Delta T = Pt/(mc) = 2500/4184 = 0.598 K, also a 0.598 degree Celsius increase.'},
 waves:{question:'For f = 440 Hz and v = 343 m/s, what is the wavelength?',options:['0.780 m','1.283 m','343 m'],answer:'0.780 m',reason:'Wavelength = v/f = 343/440 = 0.779545 m.'},
};
const advanced:Record<LauncherStudio,{question:string;options:string[];answer:string;reason:string}>={
 optics:{question:'A ray inside n = 1.52 glass meets air at 50 degrees to the normal. What happens?',options:['Total internal reflection','It exits at 50 degrees','It exits along the normal'],answer:'Total internal reflection',reason:'The critical angle is arcsin(1/1.52), about 41.1 degrees. An internal 50-degree incidence exceeds it.'},
 mechanics:{question:'Quadruple the pendulum length. How does the small-angle period change?',options:['It doubles','It quadruples','It halves'],answer:'It doubles',reason:'The square-root dependence gives sqrt(4) = 2.'},
 circuits:{question:'Double voltage across a fixed resistor. How does dissipated power change?',options:['It quadruples','It doubles','It stays the same'],answer:'It quadruples',reason:'P = V squared / R, so doubling voltage multiplies power by four.'},
 thermal:{question:'Deliver the same heat to half the water mass. How does its temperature rise change?',options:['It doubles','It halves','It stays the same'],answer:'It doubles',reason:'Delta T = Q/(mc), so halving mass doubles the temperature rise.'},
 waves:{question:'Triple frequency at fixed sound speed. What happens to wavelength?',options:['It becomes one third','It triples','It stays the same'],answer:'It becomes one third',reason:'Wavelength is inversely proportional to frequency when wave speed is fixed.'},
};
export function ExperimentLauncherPage(){
 const [studio,setStudio]=useState<LauncherStudio>('optics'),[difficulty,setDifficulty]=useState('Intermediate'),[equipment,setEquipment]=useState<LauncherEquipment>('standard'),[p,setP]=useState({...LAUNCHER_DEFAULTS}),[tab,setTab]=useState('Live Values'),[mode,setMode]=useState('Observe'),[phase,setPhase]=useState('Setup'),[running,setRunning]=useState(true),[time,setTime]=useState(0),[zoom,setZoom]=useState(1),[light,setLight]=useState(false),[panel,setPanel]=useState<Panel>(null),[answer,setAnswer]=useState(''),[checked,setChecked]=useState(false),[attempts,setAttempts]=useState(0),[correct,setCorrect]=useState(0),[notes,setNotes]=useState(()=>{try{return localStorage.getItem('launcher-notes')??''}catch{return ''}}),[saved,setSaved]=useState(false),[notice,setNotice]=useState('');
 const root=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDivElement>(null),definition=launcherStudios.find(s=>s.id===studio)!,values=launcherReadings(studio,p,time),question=(difficulty==='Beginner'?challenges:difficulty==='Advanced'?advanced:numerical)[studio];
 const [overlayHost,setOverlayHost]=useState<HTMLElement>(()=>document.body);
 useEffect(()=>{const sync=()=>setOverlayHost(document.fullscreenElement===root.current?root.current!:document.body);document.addEventListener('fullscreenchange',sync);return()=>document.removeEventListener('fullscreenchange',sync)},[]);
 useEffect(()=>{if(!running)return;if(studio==='optics'||studio==='circuits'){let last=performance.now();const timer=setInterval(()=>{const now=performance.now();setTime(t=>t+(now-last)/1000);last=now},100);return()=>clearInterval(timer)}let frame=0,last=0;const tick=(now:number)=>{if(last)setTime(t=>Math.min(studio==='thermal'?60:Infinity,t+Math.min(.05,(now-last)/1000)*(studio==='waves'?.002:1)));last=now;frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[running,studio]);
 useEffect(()=>{if(studio==='thermal'&&time>=60)setRunning(false)},[studio,time]);
 useEffect(()=>{if(!panel)return;const previous=document.activeElement as HTMLElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.querySelector<HTMLElement>('button')?.focus({preventScroll:true});const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setPanel(null);if(e.key==='Tab'){const all=dialog.current?.querySelectorAll<HTMLElement>('button,input,select,textarea,a[href]');if(!all?.length)return;if(e.shiftKey&&document.activeElement===all[0]){e.preventDefault();all[all.length-1].focus()}else if(!e.shiftKey&&document.activeElement===all[all.length-1]){e.preventDefault();all[0].focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=overflow;previous?.focus({preventScroll:true})}},[panel]);
 function choose(next:LauncherStudio){setStudio(next);setTime(0);setRunning(true);setEquipment('standard');setAnswer('');setChecked(false)}
 function update(key:keyof LauncherParameters,value:number){setP(old=>({...old,[key]:value}));setTime(0)}
 function reset(){setP({...LAUNCHER_DEFAULTS});setTime(0);setRunning(true);setZoom(1);setTab('Live Values');setMode('Observe');setPhase('Setup');setEquipment('standard');setAnswer('');setChecked(false)}
 function predict(){setPanel('Predict');setMode('Predict');setAnswer('');setChecked(false)}
 function check(){setChecked(true);setAttempts(n=>n+1);if(answer===question.answer)setCorrect(n=>n+1)}
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await root.current?.requestFullscreen()}catch{setNotice('Fullscreen is unavailable in this browser window.')}}
 const setup=<div className="el-setup">{launcherParameterKeys[studio].filter(key=>equipment!=='white-light'||key!=='wavelength').map(key=>{const c=launcherControls[key];return <label key={key}><span>{c.label}<output>{p[key]} {c.unit}</output></span><input aria-label={c.label} type="range" min={c.min} max={c.max} step={equipment==='precision'?c.step/10:c.step} value={p[key]} onChange={e=>update(key,+e.target.value)}/></label>})}</div>;
 return <div className={`el-page${light?' el-light':''}`} ref={root} data-ui-theme={light?'light':'dark'}>
  <aside className="el-sidebar"><Link className="el-brand" to="/concept-studio"><span className="el-mark" aria-hidden="true"><svg viewBox="0 0 48 48"><path d="M22 3 4 35h12L28 14z" fill="#2489ff"/><path d="m26 3 18 32H32L20 14z" fill="#4ba3ff"/><path d="M4 37h16l6-10h18l-6 11H26l-5 8H10z" fill="#1460de"/><path d="m27 28-5 8h16l5-8z" fill="#6fbaff"/></svg></span><span>CONCEPT<strong>STUDIO</strong></span></Link><nav aria-label="Launcher navigation">{([['Home','home','/'],['Experiment Launcher','flask','/experiments'],['Library','book','/experiments?view=library'],['Lab Notebook','clipboard',null],['Challenges','teacher',null],['Analytics','chart',null],['Settings','settings',null]] as Array<[string,PhysicsIconName,string|null]>).map(([label,icon,url])=>url?<Link key={label} to={url} aria-label={label} className={label==='Experiment Launcher'?'active':''} aria-current={label==='Experiment Launcher'?'page':undefined}><Icon name={icon}/><span>{label}</span></Link>:<button key={label} aria-label={label} onClick={()=>label==='Challenges'?predict():setPanel(label==='Lab Notebook'?'Notebook':label as Panel)}><Icon name={icon}/><span>{label}</span></button>)}</nav><div className="el-motto">SCIENCE<br/>BUILDS<br/>BRIGHTER<br/>THINKERS<i/></div></aside>
  <main id="content" className="el-main"><header className="el-header"><div><h1>EXPERIMENT LAUNCHER</h1><p>Explore systems. Change variables. Discover what happens.</p></div><div className="el-appearance"><button aria-label="Toggle color theme" onClick={()=>setLight(v=>!v)}><Icon name="sun"/></button><div><button aria-pressed={!light} onClick={()=>setLight(false)}>Dark</button><button aria-pressed={light} onClick={()=>setLight(true)}>Light</button></div><button aria-label="Toggle fullscreen" onClick={fullscreen}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6"><path d="M8 3H3v5M16 3h5v5M3 16v5h5M21 16v5h-5"/></svg></button></div></header>
   <section className="el-filters" aria-label="Experiment configuration"><label><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg><span>Studio Type<select aria-label="Studio Type" value={studio} onChange={e=>choose(e.target.value as LauncherStudio)}>{launcherStudios.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></span></label><label><Icon name="chart" level/><span>Difficulty<select aria-label="Difficulty" value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{['Beginner','Intermediate','Advanced'].map(d=><option key={d}>{d}</option>)}</select></span></label><label><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V3h8v4M3 13h18M9 11v4M15 11v4"/></svg><span>Equipment Set<select aria-label="Equipment Set" value={equipment} onChange={e=>{setEquipment(e.target.value as LauncherEquipment);if(e.target.value==='white-light')setP(old=>({...old,wavelength:532}))}}><option value="standard">Standard</option><option value="precision">Precision</option>{studio==='optics'&&<option value="white-light">White-light source</option>}</select></span></label><button className="el-reset" onClick={reset}><span aria-hidden="true">⟲</span>Reset</button></section>
   <section className="el-workspace"><div className="el-lab"><LauncherScene studio={studio} p={p} time={studio==='optics'||studio==='circuits'?0:time} equipment={equipment} zoom={zoom}/><div className="el-gallery" aria-label="Choose experiment studio">{launcherStudios.map(s=><button key={s.id} className={studio===s.id?'active':''} aria-pressed={studio===s.id} onClick={()=>choose(s.id)}><div className="el-thumbnail"><LauncherScene thumbnail studio={s.id} p={LAUNCHER_DEFAULTS} time={0} equipment="standard" zoom={1}/></div><span>{s.label}</span></button>)}</div><span className="el-scene-status"><time>{time.toFixed(studio==='waves'?4:2)} s</time> · {studio==='optics'?'Ray diagram shows true angles; bench is a projected overview':studio==='waves'?'0.002× sound-wave playback':studio==='circuits'?'Ideal DC circuit':running?'Running':'Paused'}</span></div>
    <aside className="el-inspector"><section className="el-values"><div className="el-tabs">{['Live Values','Setup'].map(name=><button key={name} aria-pressed={tab===name} className={tab===name?'active':''} onClick={()=>setTab(name)}>{name}</button>)}</div>{tab==='Setup'?setup:<dl>{values.rows.map(([label,symbol,value,unit])=><div key={label}><dt>{equipment==='white-light'&&label==='Wavelength'?'Source band':label}　<i>{symbol}</i></dt><dd>{equipment==='white-light'&&label==='Wavelength'?'410–680':value===null?'—':value.toFixed(label==='Wavelength'&&studio==='optics'?0:label==='Refractive index'?2:studio==='circuits'?3:1)} <small>{unit}</small></dd></div>)}</dl>}</section><section className="el-equation"><h2>{studio==='optics'?"Snell’s Law":studio==='mechanics'?'Small-angle pendulum':studio==='circuits'?"Ohm’s Law":studio==='thermal'?'Heat Transfer':'Wave Relationship'}</h2><div>{definition.equation}</div></section><LauncherGraph studio={studio} p={p} time={time} equipment={equipment}/></aside>
   </section>
   <section className="el-actions"><div className="el-modes">{([['Observe','eye','Explore the setup'],['Predict','chart','Make a hypothesis'],['Experiment','flask','Run and adjust'],['Explain','clipboard','Connect results']] as Array<[string,PhysicsIconName,string]>).map(([label,icon,sub])=><button key={label} className={mode===label?'active':''} aria-pressed={mode===label} onClick={()=>{setMode(label);if(label==='Predict')predict();else if(label==='Explain')setPanel('Explain');else if(label==='Experiment'){setTab('Setup');setPhase('Investigate')}else setTab('Live Values')}}><Icon name={icon}/><span>{label}<small>{sub}</small></span></button>)}</div><div className="el-navigation"><button aria-label={running?'Pause':'Play'} onClick={()=>setRunning(v=>!v)}><span aria-hidden="true">{running?'Ⅱ':'▷'}</span>{running?'Pause':'Play'}</button><label><Icon name="search"/><select aria-label="Zoom" value={zoom} onChange={e=>setZoom(+e.target.value)}><option value="1">Zoom</option><option value="0.8">80%</option><option value="1.2">120%</option><option value="1.4">140%</option></select></label><button className="el-next" onClick={()=>{choose(launcherStudios[(launcherStudios.findIndex(s=>s.id===studio)+1)%launcherStudios.length].id);predict()}}>Next Challenge <span aria-hidden="true">→</span></button></div></section>
   <footer className="el-footer"><div>{['Setup','Investigate','Analyze','Conclude'].map(step=><button key={step} className={phase===step?'active':''} aria-current={phase===step?'step':undefined} onClick={()=>{setPhase(step);if(step==='Setup')setTab('Setup');if(step==='Investigate'){setTab('Setup');setMode('Experiment')}if(step==='Analyze')setPanel('Analytics');if(step==='Conclude')setPanel('Notebook')}}><i/>{step}</button>)}</div><span>SAME IDEAS. A BRIGHTER TOMORROW. <i/></span></footer>
  </main>{notice&&createPortal(<div role="status" className="el-notice" data-ui-theme="dark">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss notice">×</button></div>,overlayHost)}
  {panel&&createPortal(<div className="el-backdrop" data-ui-theme="dark" onClick={e=>{if(e.target===e.currentTarget)setPanel(null)}}><div ref={dialog} className="el-dialog" role="dialog" aria-modal="true" aria-labelledby="el-dialog-title"><header><h2 id="el-dialog-title">{panel==='Predict'?`${difficulty} challenge`:panel}</h2><button aria-label="Close panel" onClick={()=>setPanel(null)}>×</button></header>
   {panel==='Predict'&&<><p>{question.question}</p><div className="el-answers">{question.options.map(a=><button key={a} aria-pressed={answer===a} className={answer===a?'active':''} onClick={()=>{setAnswer(a);setChecked(false)}}>{a}</button>)}</div><button className="el-primary" disabled={!answer||checked} onClick={check}>Check answer</button>{checked&&<p role="status">{answer===question.answer?'Correct.':'Try again.'} {question.reason}</p>}<button className="el-primary" onClick={()=>{setPanel(null);setTab('Setup');setMode('Experiment')}}>Test the prediction</button></>}
   {panel==='Explain'&&<><p>{definition.description}</p><p className="el-formula-text">{definition.equation}</p>{studio==='optics'?<><div className="el-explain-ray"><LauncherRayDiagram p={p}/></div><p>At 30° incidence from air into n = 1.52 glass, θ₂ = 19.20°. The second surface can cause total internal reflection. No direct transmitted beam then reaches the detector.</p><p>The graph uses an ideal Gaussian profile and a 100 mm angular sensor referenced to the default beam direction. The Cauchy dispersion and Fresnel transmission are model predictions; secondary reflections and absorption are omitted.</p></>:<p>{studio==='mechanics'?'Angles stay at or below 10°. This is the linear small-angle approximation with g = 9.81 m/s².':studio==='thermal'?'Water begins at 20 °C, with c = 4,184 J/(kg·K). Heating stops at 60 s and ignores losses.':studio==='waves'?'Pressure is sinusoidal, with sound speed fixed at 343 m/s. The slow playback is explicitly labeled.':'An ideal source drives one fixed resistor. Positive and negative current follow the voltage sign; dissipated power is V²/R.'}</p>}{difficulty==='Advanced'&&<p>Check dimensions and boundary conditions, then compare the limiting case with the graph.</p>}<Link to={`/experiments/${definition.route}`}>Open the full {definition.label} lab →</Link></>}
   {panel==='Notebook'&&<><label>Lab observations<textarea rows={7} value={notes} onChange={e=>{setNotes(e.target.value);setSaved(false)}}/></label><button className="el-primary" onClick={()=>{try{localStorage.setItem('launcher-notes',notes);setSaved(true)}catch{setSaved(false);setNotice('Notes could not be saved on this device. Copy your observations before closing.')}}}>Save notes</button>{saved&&<p role="status">Saved on this device.</p>}</>}
   {panel==='Analytics'&&<><p>Current {definition.label.toLowerCase()} readings</p><dl>{values.rows.map(([label,,value,unit])=><div key={label}>{label}: <strong>{value?.toFixed(3)} {unit}</strong></div>)}</dl><p>Challenge answers this session: {correct} correct from {attempts} attempts.</p><LauncherGraph studio={studio} p={p} time={time} equipment={equipment}/></>}
   {panel==='Settings'&&<><p>Theme applies to this launcher workspace.</p><button className="el-primary" onClick={()=>setLight(v=>!v)}>Use {light?'dark':'light'} theme</button><button className="el-primary" onClick={()=>{reset();setPanel(null)}}>Restore experiment defaults</button><Link to="/experiments?view=library">Browse the complete experiment library →</Link></>}
  </div></div>,overlayHost)}
 </div>;
}
