import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { GuidedPathIcon as Icon } from '../components/GuidedPathIcon';
import type { PhysicsIconName } from '../lib/icons';
import { GuidedPathMap, GuidedWorkspaceScene } from '../components/GuidedPathVisuals';
import { GUIDED_DEFAULTS, guidedConditions, guidedControls, guidedEquations, guidedParameterKeys, guidedPathOrder, guidedReadings, guidedTopics, type GuidedParameters, type GuidedTopic } from '../lib/guidedPath';
import '../guided-path.css';

type Panel='Predict'|'Experiment'|'Explain'|'Notes'|'Settings'|null;
const questions:Record<GuidedTopic,{prompt:string;choices:string[];correct:string;reason:string}>={
 measurement:{prompt:'A ruler has 1 mm divisions. What is its estimated reading uncertainty?',choices:['±0.5 mm','±1 cm','Zero'],correct:'±0.5 mm',reason:'Half a division is 0.5 mm. This excludes calibration and systematic errors.'},
 mechanics:{prompt:'Two balls of different masses fall from the same height without air resistance. Which arrives first?',choices:['The heavier ball','The lighter ball','They arrive together'],correct:'They arrive together',reason:'Both have acceleration g. Fall time √(2h/g) does not depend on mass.'},
 waves:{prompt:'Keep the wavelength fixed and double the frequency. What happens to wave speed?',choices:['It doubles','It halves','It stays the same'],correct:'It doubles',reason:'v = λf. This comparison assumes the medium can support the changed wave speed.'},
 thermo:{prompt:'With the same heater power, which warms more slowly?',choices:['Twice the water mass','Half the water mass','Both warm equally'],correct:'Twice the water mass',reason:'dT/dt = P/(mc), so doubling mass halves the heating rate.'},
 em:{prompt:'What happens to the field when a solenoid’s current reverses?',choices:['Its direction reverses','It vanishes permanently','It keeps the same direction'],correct:'Its direction reverses',reason:'The signed axial field B = μ₀nI reverses with the current.'},
 quantum:{prompt:'Double an electron’s nonrelativistic speed. What happens to its wavelength?',choices:['It doubles','It halves','It stays the same'],correct:'It halves',reason:'λ = h/(mv). At fixed mass, twice the speed gives half the wavelength.'},
 astronomy:{prompt:'How does circular orbital speed change at a larger radius?',choices:['It decreases','It increases','It stays the same'],correct:'It decreases',reason:'v = √(GM/r). Larger orbital radius gives a lower circular speed.'},
};
const readStored=(key:string,fallback:string)=>{try{return localStorage.getItem(key)??fallback}catch{return fallback}};
export function GuidedPathPage(){
 const [selected,setSelected]=useState<GuidedTopic>('mechanics'),[level,setLevel]=useState('Beginner'),[length,setLength]=useState(8),[goal,setGoal]=useState('overview'),[search,setSearch]=useState(''),[mode,setMode]=useState('Observe'),[panel,setPanel]=useState<Panel>(null),[p,setP]=useState({...GUIDED_DEFAULTS}),[time,setTime]=useState(0),[running,setRunning]=useState(true),[zoom,setZoom]=useState(1),[rate,setRate]=useState(.25),[answer,setAnswer]=useState(''),[checked,setChecked]=useState(false),[notes,setNotes]=useState(()=>readStored('guided-path-notes','')),[saved,setSaved]=useState(false);
 const [completed,setCompleted]=useState<GuidedTopic[]>(()=>{try{const ids=JSON.parse(readStored('guided-path-completed','[]'));return Array.isArray(ids)?ids.filter(id=>guidedTopics.some(t=>t.id===id)):[]}catch{return []}});
 const dialog=useRef<HTMLDivElement>(null),topic=guidedTopics.find(t=>t.id===selected)!,state=guidedReadings(selected,p,time),order=useMemo(()=>guidedPathOrder(length,goal),[length,goal]),animated=['mechanics','waves','thermo','astronomy'].includes(selected),limit=selected==='mechanics'?state.fallTime:selected==='thermo'?60:Infinity;
 const question=level==='Advanced'&&selected==='mechanics'?{prompt:'A 2.00 kg ball falls 5.00 m without drag. At g = 9.81 m/s², what kinetic energy does it gain?',choices:['98.10 J','49.05 J','9.90 J'],correct:'98.10 J',reason:'The lost potential energy mgh becomes kinetic energy: 2 × 9.81 × 5 = 98.10 J.'}:level==='Beginner'?questions[selected]:selected==='mechanics'?{prompt:'A ball falls 5.00 m from rest at g = 9.81 m/s². What is its impact speed?',choices:['9.90 m/s','49.05 m/s','5.00 m/s'],correct:'9.90 m/s',reason:'v² = 2gh = 98.1 m²/s², so v = 9.9045… m/s. Mass cancels from mgh = ½mv².'}:questions[selected];
 useEffect(()=>{if(!running||!animated)return;let frame=0,last=0;const tick=(now:number)=>{if(last){const dt=Math.min((now-last)/1000,.05)*(selected==='astronomy'?120:rate);setTime(t=>Math.min(limit,t+dt));}last=now;frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[running,animated,selected,rate,limit]);
 useEffect(()=>{if(time>=limit&&running)setRunning(false)},[time,limit,running]);
 useEffect(()=>{if(!panel)return;const previous=document.activeElement as HTMLElement;dialog.current?.querySelector<HTMLElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setPanel(null);if(e.key==='Tab'){const nodes=dialog.current?.querySelectorAll<HTMLElement>('button,a[href],input,textarea,select');if(!nodes?.length)return;if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes[nodes.length-1].focus()}else if(!e.shiftKey&&document.activeElement===nodes[nodes.length-1]){e.preventDefault();nodes[0].focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus()}},[panel]);
 const choose=useCallback((id:GuidedTopic)=>{setSelected(id);setTime(0);setRunning(true);setSearch('');setAnswer('');setChecked(false)},[]);
 function open(value:Panel){setPanel(value);if(value==='Predict'||value==='Experiment'||value==='Explain'){setMode(value);setRunning(false)}setAnswer('');setChecked(false)}
 function reset(){setMode('Observe');setP({...GUIDED_DEFAULTS});setTime(0);setRunning(true);setZoom(1);setAnswer('');setChecked(false)}
 function update(key:keyof GuidedParameters,value:number){setP(old=>({...old,[key]:value}));setTime(0);setRunning(false)}
 function checkAnswer(){setChecked(true);if(answer===question.correct){const next=Array.from(new Set([...completed,selected]));setCompleted(next);try{localStorage.setItem('guided-path-completed',JSON.stringify(next))}catch{/* Current session progress remains available. */}}}
 function nextChallenge(){const next=order.find(id=>!completed.includes(id))??order[0];choose(next);open('Predict')}
 function configure(nextLength:number,nextGoal:string){setLength(nextLength);setGoal(nextGoal);const next=guidedPathOrder(nextLength,nextGoal);if(!next.includes(selected))choose(next[0])}
 const impact=state.impactSpeed.toFixed(2),equationExtra=selected==='mechanics'?`g = 9.81 m/s²\nh₀ = ${p.height.toFixed(2)} m\nImpact v = ${impact} m/s`:selected==='waves'?`λ = ${p.wavelength.toFixed(2)} m\nf = ${p.frequency.toFixed(2)} Hz\nv = ${(p.frequency*p.wavelength).toFixed(2)} m/s`:selected==='thermo'?`c = 4,184 J/(kg·K)\nT₀ = 20 °C\nΔT = ${(p.power*time/(p.mass*4184)).toFixed(2)} K`:selected==='em'?`n = 1,000 m⁻¹\nI = ${p.current.toFixed(2)} A\nB = ${state.rows[3][1].toFixed(2)} mT`:selected==='quantum'?`Nonrelativistic electron\nv = ${p.electronSpeed.toFixed(1)} × 10⁶ m/s\nλ = ${state.rows[3][1].toFixed(3)} nm`:selected==='astronomy'?`r = ${(state.r/1000).toFixed(0)} km\nT = ${(state.period/60).toFixed(2)} min\nv = ${(state.orbitalSpeed/1000).toFixed(2)} km/s`:`1 cm = 10 mm\nDivision = ${p.resolution} mm\nδL ≈ ±${(p.resolution/2).toFixed(1)} mm`;
 return <div className="gp-page" data-ui-theme="dark">
  <aside className="gp-sidebar"><Link className="gp-brand" to="/concept-studio">CONCEPT<br/>STUDIO</Link><nav aria-label="Guided learning navigation">{([['Home','home','/'],['Learn','folder','/roadmap'],['Explore','compass','/graph'],['Simulations','flask','/experiments'],['Challenges','teacher',null],['Library','book','/roadmap?view=curriculum'],['Notes','clipboard',null]] as Array<[string,PhysicsIconName,string|null]>).map(([label,icon,url])=>url?<Link key={label} aria-label={label} to={url} className={label==='Learn'?'active':''} aria-current={label==='Learn'?'page':undefined}><Icon name={icon}/><span>{label}</span></Link>:<button key={label} aria-label={label} onClick={()=>label==='Notes'?open('Notes'):open('Predict')}><Icon name={icon}/><span>{label}</span></button>)}</nav><button className="gp-settings" aria-label="Settings" onClick={()=>open('Settings')}><Icon name="settings"/><span>Settings</span></button></aside>
  <main id="content" className="gp-main"><header className="gp-header"><h1>GUIDED LEARNING PATH</h1><p>From measurement to the universe. Build concepts. Make connections.</p><div className="gp-search"><Icon name="search"/><input aria-label="Search topics" placeholder="Search topics..." value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')setSearch('')}}/>{search&&<div className="gp-search-results">{guidedTopics.filter(t=>`${t.name} ${t.lab}`.toLowerCase().includes(search.toLowerCase())).map(t=><button key={t.id} onClick={()=>choose(t.id)}>{t.name}</button>)}{!guidedTopics.some(t=>`${t.name} ${t.lab}`.toLowerCase().includes(search.toLowerCase()))&&<p>No matching topics.</p>}</div>}</div></header>
   <section className="gp-path-controls" aria-label="Learning path configuration"><label><Icon name="chart" level/><span>Starting Level<select aria-label="Starting Level" value={level} onChange={e=>setLevel(e.target.value)}>{['Beginner','Intermediate','Advanced'].map(l=><option key={l}>{l}</option>)}</select></span></label><label><Icon name="atom"/><span>Path Length<select aria-label="Path Length" value={length} onChange={e=>configure(+e.target.value,goal)}>{[4,6,8].map(n=><option key={n} value={n}>{n} Milestones</option>)}</select></span></label><label><Icon name="compass"/><span>Learning Goal<select aria-label="Learning Goal" value={goal} onChange={e=>configure(length,e.target.value)}><option value="overview">Understand the big picture</option><option value="motion">Understand motion</option><option value="energy">Follow energy transfers</option></select></span></label><button className="gp-next" onClick={nextChallenge}>Next Challenge <span aria-hidden="true">→</span></button></section>
   <GuidedPathMap selected={selected} order={order} onSelect={choose}/>
   <section className="gp-workbench" aria-label="Interactive learning workspace"><div className="gp-modes gp-card"><h2>Exploration Mode</h2>{([['Observe','eye'],['Predict','chart'],['Experiment','flask'],['Explain','clipboard']] as Array<[string,PhysicsIconName]>).map(([label,icon])=><button key={label} className={mode===label?'active':''} aria-pressed={mode===label} onClick={()=>{if(label==='Observe'){setMode(label);setPanel(null)}else open(label as Panel)}}><Icon name={icon}/>{label}</button>)}</div>
    <div className="gp-readings gp-card"><h2>Live Values</h2><dl>{state.rows.map(([label,value,unit],i)=><div key={i}><dt>{label}</dt><dd>{unit.startsWith('±')?'±':''}{value.toFixed(2)} <small>{unit.replace('± ','')}</small></dd></div>)}</dl></div>
    <div className="gp-workspace gp-card"><header><h2>Interactive Workspace</h2><select aria-label="Interactive Workspace" value={selected} onChange={e=>choose(e.target.value as GuidedTopic)}>{guidedTopics.map(t=><option key={t.id} value={t.id}>{t.lab}</option>)}</select></header><div className="gp-workspace-body"><div className="gp-scene"><GuidedWorkspaceScene topic={selected} p={p} time={time} zoom={zoom}/><span className="gp-playback-label">{animated?(selected==='astronomy'?'120 simulated s / s':`${rate}× playback`):'Static measurement'}</span></div><div className="gp-equation"><h2>Key Relationship</h2><div className={selected==='measurement'?'gp-long-equation':undefined}>{selected==='mechanics'?<svg viewBox="0 0 200 70" role="img" aria-label="v equals square root of 2 g h"><text x="0" y="51" fill="currentColor" fontFamily="Georgia,serif" fontSize="38" fontStyle="italic">v =</text><path d="M62 41l9 13 13-45h100" fill="none" stroke="currentColor" strokeWidth="2"/><text x="90" y="51" fill="currentColor" fontFamily="Georgia,serif" fontSize="38" fontStyle="italic">2gh</text></svg>:guidedEquations[selected]}</div><p>{equationExtra}</p></div></div></div>
    <div className="gp-playback gp-card"><button disabled={!animated} aria-label={!animated?'Static workspace':running?'Pause':time>=limit?'Replay':'Play'} onClick={()=>{if(time>=limit)setTime(0);setRunning(v=>!v)}}><span aria-hidden="true">{running?'Ⅱ':'▷'}</span>{!animated?'Static':running?'Pause':time>=limit?'Replay':'Play'}</button><button onClick={reset}><span aria-hidden="true">⟳</span>Reset</button><button disabled={zoom>=1.4} onClick={()=>setZoom(z=>Math.min(1.4,+(z+.1).toFixed(1)))}><span aria-hidden="true">+</span>Zoom In</button><button disabled={zoom<=.7} onClick={()=>setZoom(z=>Math.max(.7,+(z-.1).toFixed(1)))}><span aria-hidden="true">−</span>Zoom Out</button></div>
   </section>
   <section className="gp-progress" aria-label="Learning Path Progress"><h2>Learning Path Progress</h2><div>{order.map((id,i)=><button key={id} aria-label={`Milestone ${i+1}: ${guidedTopics.find(t=>t.id===id)!.name}${completed.includes(id)?', completed':''}`} aria-current={selected===id?'step':undefined} className={selected===id?'current':completed.includes(id)?'complete':''} onClick={()=>choose(id)}><span>{completed.includes(id)?'✓':i+1}</span><small>{guidedTopics.find(t=>t.id===id)!.short}</small></button>)}<button onClick={()=>open('Predict')} aria-label="Final challenge"><span>{length}</span><small>Challenge</small></button></div></section>
  </main>
  {panel&&<div className="gp-backdrop" onClick={e=>{if(e.target===e.currentTarget)setPanel(null)}}><div className="gp-dialog" ref={dialog} role="dialog" aria-modal="true" aria-labelledby="gp-panel-title"><header><h2 id="gp-panel-title">{panel==='Predict'?`${level} challenge`:panel==='Experiment'?topic.lab:panel}</h2><button aria-label="Close panel" onClick={()=>setPanel(null)}>×</button></header>
   {panel==='Predict'&&<><p>{question.prompt}</p><div className="gp-answers">{question.choices.map(a=><button key={a} aria-pressed={answer===a} className={answer===a?'active':''} onClick={()=>{setAnswer(a);setChecked(false)}}>{a}</button>)}</div><button className="gp-action" disabled={!answer} onClick={checkAnswer}>Check answer</button>{checked&&<p role="status">{answer===question.correct?'Correct. Milestone completed.':'Try again.'} {question.reason}</p>}<button className="gp-action" onClick={()=>open('Experiment')}>Test in workspace</button></>}
   {panel==='Experiment'&&<><p>{topic.description}</p><div className="gp-lab-controls">{guidedParameterKeys[selected].map(key=>{const c=guidedControls[key];return <label key={key}><span>{c.label}<output>{p[key]} {c.unit}</output></span><input type="range" aria-label={c.label} min={c.min} max={c.max} step={c.step} value={p[key]} onChange={e=>update(key,+e.target.value)}/></label>})}</div><p className="gp-condition">{guidedConditions[selected]}</p><button className="gp-action" onClick={()=>{setPanel(null);setTime(0);setRunning(true)}}>{animated?'Run experiment':'View measurement'}</button><button className="gp-action" onClick={reset}>Reset values</button><Link to={`/experiments/${topic.route}`}>Open full {topic.short} lab →</Link></>}
   {panel==='Explain'&&<><p>{topic.description}</p><div className="gp-explain-equation">{guidedEquations[selected]}</div><p>{guidedConditions[selected]}</p>{level!=='Beginner'&&<p>{selected==='mechanics'?'Energy conservation gives mgh = ½mv²; cancelling m yields v² = 2gh. Instantaneous displacement is ½gt² and velocity is gt.':level==='Advanced'?'Check dimensions on both sides and identify which variables are fixed before predicting a change.':'Change one quantity at a time and compare the measured ratio with the equation.'}</p>}<p>{selected==='mechanics'?'Live readings follow the falling ball. The relationship card predicts impact speed from its release height.':selected==='quantum'?'The path icon represents atomic physics symbolically; electrons do not follow classical elliptical orbits.':'Use Experiment to change quantities and compare the live readings.'}</p></>}
   {panel==='Notes'&&<><label>Your observations<textarea rows={7} value={notes} onChange={e=>{setNotes(e.target.value);setSaved(false)}}/></label><button className="gp-action" onClick={()=>{try{localStorage.setItem('guided-path-notes',notes);setSaved(true)}catch{setSaved(false)}}}>Save notes</button>{saved&&<p role="status">Saved on this device.</p>}</>}
   {panel==='Settings'&&<><label className="gp-setting">Playback speed<select aria-label="Playback speed" value={rate} onChange={e=>setRate(+e.target.value)}><option value="0.25">0.25× — slow motion</option><option value="1">1× — real time</option></select></label><p>Earth orbits use 120 simulated seconds per real second. Progress is earned by correct challenge answers and stored on this device.</p><button className="gp-action" onClick={()=>{setCompleted([]);try{localStorage.removeItem('guided-path-completed')}catch{} }}>Clear saved progress</button><Link to="/roadmap?view=curriculum">Open the full curriculum roadmap →</Link></>}
  </div></div>}
 </div>;
}
