import { useEffect,useRef,useState,type CSSProperties } from 'react';
import { Link } from 'react-router-dom';
import { PhysicsIcon,type PhysicsIconName } from '../lib/icons';
import { MASS_TIME_DEFAULTS,balanceReading,massTimeSettings,massTimeTrial,massTimeStatistics,type MassTimeInput } from '../lib/massTime';
import { MassTimeScene,MassTimeTimeline } from '../components/MassTimeScene';
import { MasteryChallengeDialog } from '../components/MasteryChallengeDialog';
import '../mastery-challenge.css';import '../mass-time.css';
const series=(input:MassTimeInput)=>Array.from({length:input.trialCount},(_,i)=>massTimeTrial(input,i));
function NumericControl({value,min,max,step,label,change}:{value:number;min:number;max:number;step:number;label:string;change:(value:number)=>void}) {
 const [draft,setDraft]=useState(String(value)),focused=useRef(false);
 useEffect(()=>{if(!focused.current)setDraft(String(value));},[value]);
 const commit=()=>{const n=Number(draft),next=draft.trim()!==''&&Number.isFinite(n)?Math.max(min,Math.min(max,n)):value;change(next);setDraft(String(next));};
 return <input type="number" aria-label={label} min={min} max={max} step={step} value={draft} onFocus={()=>{focused.current=true;}} onChange={e=>{setDraft(e.target.value);const n=e.target.valueAsNumber;if(Number.isFinite(n)&&n>=min&&n<=max)change(n);}} onBlur={()=>{focused.current=false;commit();}} onKeyDown={e=>{if(e.key==='Enter'){commit();e.currentTarget.blur();}}}/>;
}
function StopwatchIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><circle cx="12" cy="14" r="8"/><path d="M12 6V2m-3 0h6m3 5l2-2M12 9v6"/></svg>;}
export default function MassTimePage(){
 const [input,setInput]=useState(MASS_TIME_DEFAULTS),[records,setRecords]=useState(()=>series(MASS_TIME_DEFAULTS)),[index,setIndex]=useState(4),[time,setTime]=useState(.4),[running,setRunning]=useState(false),[complete,setComplete]=useState(true),[zoom,setZoom]=useState(1),[panel,setPanel]=useState<string|null>(null),[mode,setMode]=useState('Observe'),[powered,setPowered]=useState(true),[tare,setTare]=useState(0),[unit,setUnit]=useState<'g'|'kg'>('g'),[light,setLight]=useState(false),[notes,setNotes]=useState(''),[feedback,setFeedback]=useState(''),[answer,setAnswer]=useState(''),[challenge,setChallenge]=useState(0);
 const clock=useRef(time),s=massTimeSettings(input),stats=massTimeStatistics(records),trial=massTimeTrial(input,index),mass=balanceReading(s.massG,tare,powered),f=(n:number|null,d=4)=>n===null?'—':n.toFixed(d);
 const configure=(change:Partial<MassTimeInput>)=>{const next=massTimeSettings({...input,...change});setRunning(false);setInput(next);setRecords(series(next));setIndex(next.trialCount-1);setTime(.4);clock.current=.4;setComplete(true);setFeedback('');};
 const reset=()=>{setRunning(false);setInput(MASS_TIME_DEFAULTS);setRecords(series(MASS_TIME_DEFAULTS));setIndex(4);clock.current=.4;setTime(.4);setComplete(true);setZoom(1);setPowered(true);setTare(0);setUnit('g');setMode('Observe');setPanel(null);setFeedback('');setAnswer('');setChallenge(0);};
 const play=()=>{if(running){setRunning(false);return;}if(complete){setInput(old=>({...old,seed:old.seed+1}));setRecords([]);setIndex(0);clock.current=0;setTime(0);setComplete(false);}setRunning(true);};
 useEffect(()=>{if(!running)return;let id:number,prior=0,logged=records.some(r=>r.trial===index+1);const event=massTimeTrial(input,index),end=event.trueGate2+.16;const frame=(now:number)=>{if(prior)clock.current+=Math.min(.05,(now-prior)/1000);prior=now;setTime(clock.current);if(!logged&&clock.current>=event.gate2){logged=true;setRecords(old=>[...old,event]);}if(clock.current>=end){if(index+1>=s.trialCount){setComplete(true);setRunning(false);}else{clock.current=0;setTime(0);setIndex(i=>i+1);}return;}id=requestAnimationFrame(frame);};id=requestAnimationFrame(frame);return()=>cancelAnimationFrame(id);},[running,index,input]);
 const open=(name:string)=>{setRunning(false);setFeedback('');setPanel(name==='Observe'?null:name);if(['Observe','Predict','Experiment','Explain'].includes(name))setMode(name);};
 const balance=(action:string)=>{if(action==='Power')setPowered(v=>!v);if(action==='Tare'&&powered)setTare(s.massG);if(action==='Mode')setUnit(v=>v==='g'?'kg':'g');if(action==='Calibrate'){setTare(0);setPowered(true);setPanel('Calibration');}};
 const next=()=>{const n=(challenge+1)%3;setChallenge(n);configure(n===1?{spacingCm:100,setup:'A'}:n===2?{spacingCm:50,setup:'B'}:{spacingCm:50,setup:'A'});setAnswer('');setPanel('Challenge');};
 return <div className={`mst-page ${light?'mst-light':''}`} data-ui-theme="dark"><header className="mst-top"><Link to="/concept-studio"><PhysicsIcon name="wave"/>PHYSICS STUDIO</Link><nav><Link to="/topics/mechanics">Mechanics</Link> › <Link to="/concept-studio/measurement">Measurement</Link> › <span>Mass & Time</span></nav><button aria-label="Toggle laboratory lighting" onClick={()=>setLight(v=>!v)}><PhysicsIcon name="sun"/></button><button aria-label="Timing information" onClick={()=>open('Timing')}><StopwatchIcon/></button><select aria-label="Lab setup" value={input.setup} onChange={e=>configure({setup:e.target.value as 'A'|'B'})}><option value="A">Lab Setup A</option><option value="B">Lab Setup B</option></select></header><aside className="mst-sidebar">{([['Home','home','/concept-studio'],['Mechanics','compass','/topics/mechanics'],['Electricity','spark','/topics/electricity'],['Waves','wave','/topics/waves'],['Thermodynamics','thermometer','/topics/thermodynamics'],['Optics','eye','/topics/optics'],['Modern Physics','atom','/topics/modern-physics']] as Array<[string,PhysicsIconName,string]>).map(([name,icon,to],i)=><Link to={to} className={i===1?'active':''} key={name}><PhysicsIcon name={icon}/><span>{name}</span></Link>)}<hr/>{([['Apparatus','flask'],['Data','chart'],['Challenges','teacher'],['Notebook','clipboard'],['Settings','settings']] as Array<[string,PhysicsIconName]>).map(([name,icon])=><button key={name} onClick={()=>open(name)}><PhysicsIcon name={icon}/><span>{name}</span></button>)}</aside>
 <main id="content" className="mst-main"><header className="mst-modes"><div>{['Observe','Predict','Experiment','Explain'].map(name=><button key={name} aria-pressed={mode===name} onClick={()=>open(name)}>{name}</button>)}</div><h1>MEASUREMENT — MASS & TIME<small>From motion to measurement</small></h1></header><div className="mst-workspace"><section className="mst-scene"><img src="/assets/mass-time/measurement-bench.png" alt=""/><svg className="mst-wall-posters" viewBox="0 0 980 580" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><g fill="#26323b" textAnchor="middle" opacity=".72" fontFamily="Arial"><text x="99" y="65" fontSize="19" fontWeight="bold"><tspan x="99">SAME</tspan><tspan x="99" dy="29">IDEAS</tspan><tspan x="99" dy="29">REAL</tspan><tspan x="99" dy="29">PHYSICS</tspan></text><text x="867" y="79" fontSize="31" fontFamily="Georgia" fontStyle="italic">v = d / t</text><text x="810" y="125" fontSize="12">G1</text><text x="923" y="125" fontSize="12">G2</text><path d="M810 138v52m113-52v52M810 161h113m-108-4l-5 4 5 4m103-8l5 4-5 4" fill="none" stroke="#26323b" strokeWidth="1.5"/><text x="866" y="154" fontSize="14">d</text><text x="866" y="213" fontSize="12">{(s.spacingCm/100).toFixed(2)} m between gates</text></g></svg><MassTimeScene input={input} time={time} zoom={zoom} powered={powered} tare={tare} unit={unit} onBalance={balance}/><span className="mst-scene-caption">Simulated trial {index+1} · {s.velocity.toFixed(2)} m/s · balance independent of cart</span></section><aside className="mst-side"><section className="mst-controls"><h2>CONTROLS</h2>{([['Test Mass (g)','massG',50,500,1],['Gate Spacing (cm)','spacingCm',10,100,.1],['Trial Count','trialCount',1,20,1]] as Array<[string,'massG'|'spacingCm'|'trialCount',number,number,number]>).map(([label,key,min,max,step])=><label key={key}><span>{label}<NumericControl value={s[key]} min={min} max={max} step={step} label={`${label} value`} change={n=>configure({[key]:n})}/></span><input type="range" aria-label={label} min={min} max={max} step={step} value={s[key]} style={{'--fill':`${(s[key]-min)/(max-min)*100}%`} as CSSProperties} onChange={e=>configure({[key]:Number(e.target.value)})}/><small><span>{min}</span><span>{max}</span></small></label>)}</section><section className="mst-readings"><h2>LIVE MEASUREMENTS</h2>{[['gauge','Mass',mass===null?'OFF':`${f(unit==='kg'?mass/1000:mass,unit==='kg'?5:2)} ${unit}`],['pendulum','Last Elapsed Time',`${f(stats.last)} s`],['chart',`Mean Time (n = ${stats.n})`,`${f(stats.mean)} s`],['calculator','Repeatability (Std Dev)',stats.std===null?'— (need 2 trials)':`${f(stats.std)} s`]].map(([icon,label,value])=><div key={label}>{icon==='pendulum'?<StopwatchIcon/>:<PhysicsIcon name={icon as PhysicsIconName}/>}<p>{label}<strong>{value}</strong></p></div>)}</section></aside></div>
 <div className="mst-lower"><section className="mst-sensor"><h2>SENSOR TIMELINE</h2><MassTimeTimeline trial={trial} time={time} complete={complete}/></section><section className="mst-trials"><h2>TRIALS</h2><div><table><thead><tr><th>#</th><th>Time (s)</th><th>Δ from mean (s)</th></tr></thead><tbody>{records.map(r=><tr key={r.trial}><td>{r.trial}</td><td>{f(r.elapsed)}</td><td>{stats.mean===null?'—':`${r.elapsed>=stats.mean?'+':''}${f(r.elapsed-stats.mean)}`}</td></tr>)}</tbody><tfoot><tr><td>Mean</td><td>{f(stats.mean)}</td><td>—</td></tr><tr><td>Std Dev</td><td>{f(stats.std)}</td><td>—</td></tr></tfoot></table>{!records.length&&<p>Waiting for Gate 2…</p>}</div></section><section className="mst-equation"><h2>EQUATION</h2><p>v = <span><span>d</span><span>t</span></span></p><dl><div><dt>v</dt><dd>average speed (m/s)</dd></div><div><dt>d</dt><dd>gate spacing (m)</dd></div><div><dt>t</dt><dd>elapsed time (s)</dd></div></dl></section></div><footer className="mst-actions"><button aria-label="Reset" onClick={reset}>↶　Reset</button><button aria-label={running?'Pause':complete?'Run trials':'Resume trials'} onClick={play}>{running?'Ⅱ　Pause':complete?'▷　Run trials':'▷　Resume'}</button><label><PhysicsIcon name="search"/>Zoom<select aria-label="Zoom" value={zoom} onChange={e=>setZoom(Number(e.target.value))}>{[.75,1,1.25,1.5].map(v=><option key={v} value={v}>{v*100}%</option>)}</select></label><button className="mst-next" onClick={next}>Next Challenge →</button></footer></main>
 {panel&&<MasteryChallengeDialog title={panel} close={()=>setPanel(null)}>{panel==='Explain'&&<><p>For uniform motion, v = d / Δt. The cart crosses Gate 1 at 0.2 s and Gate 2 after another d/v seconds. The pulse width represents a 3 cm flag passing each gate.</p><p>The simulation adds independent uniform ±2 ms timestamp jitter and rounds each timestamp to 0.1 ms. Table values, mean, sample standard deviation and timeline use those same events. The mass standard is on a separate balance and does not set cart speed.</p><p>Sample standard deviation uses n−1; one trial cannot estimate repeatability.</p><Link to="/experiments/measurement-errors">Original uncertainty lesson</Link></>}
 {panel==='Predict'&&<><p>At fixed cart speed, doubling gate spacing will…</p>{['Double elapsed time','Halve elapsed time','Leave elapsed time unchanged'].map((a,i)=><button className="mc-primary" key={a} onClick={()=>setFeedback(i===0?'Correct. Δt = d/v.':'Use Δt = d/v while holding v fixed.')}>{a}</button>)}<p role="status">{feedback}</p></>}
 {panel==='Experiment'&&<><p>Run repeated trials to see sensor timing variation. Change the balance mass independently and compare the timing.</p><button className="mc-primary" onClick={()=>{setPanel(null);if(!complete){clock.current=0;setTime(0);setRecords([]);setIndex(0);}play();}}>Start trial series</button></>}
 {(panel==='Challenge'||panel==='Challenges')&&<><p>For d = {(s.spacingCm/100).toFixed(2)} m and speed {s.velocity.toFixed(2)} m/s, calculate the ideal elapsed time in seconds, to four decimals.</p><input aria-label="Elapsed time answer" className="mc-search" value={answer} onChange={e=>setAnswer(e.target.value)}/><button className="mc-primary" onClick={()=>setFeedback(answer.trim()!==''&&Math.abs(Number(answer)-s.spacingCm/100/s.velocity)<.000051?'Correct. The ideal transit time excludes sensor jitter.':'Use distance in meters divided by speed in meters per second.')}>Check time</button><p role="status">{feedback}</p></>}
 {panel==='Notebook'&&<textarea aria-label="Mass and time notes" rows={6} value={notes} onChange={e=>setNotes(e.target.value)}/>}
 {panel==='Data'&&<><p>{stats.n} simulated observations. Mean {f(stats.mean)} s; sample standard deviation {f(stats.std)} s.</p><p>Estimated speed from mean time: {stats.mean===null?'—':((s.spacingCm/100)/stats.mean).toFixed(4)} m/s.</p></>}
 {panel==='Apparatus'&&<><p>A balance measures the standard independently. TARE subtracts the current mass; MODE switches g/kg; CAL clears tare for the ideal calibrated model. Two gates time a 3 cm flag on a constant-speed cart.</p><Link to="/experiments/uniform-motion">Explore the original uniform-motion lesson</Link></>}
 {(panel==='Timing'||panel==='Settings')&&<><p>Lab A: 1.54 m/s. Lab B: 0.80 m/s. Gate clock: 0.0001 s resolution with independent ±0.002 s timestamp jitter. Every series is simulated and repeatable from its seed ({input.seed}).</p><p>Reset restores the default apparatus and preview series. Notes and lighting are session preferences.</p></>}
 {panel==='Calibration'&&<p>The ideal balance is calibrated with zero offset. Tare has been cleared. The {s.massG.toFixed(2)} g standard should read its full mass.</p>}
 </MasteryChallengeDialog>}
 </div>;
}
