import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { MasteryChallengeIcon as Icon } from '../components/MasteryChallengeIcon';
import { MasteryChallengeScene } from '../components/MasteryChallengeScene';
import { MasteryChallengeGraph } from '../components/MasteryChallengeGraph';
import { MasteryChallengeDialog } from '../components/MasteryChallengeDialog';
import { MASTERY_CONSTANTS, MASTERY_CONTROLS, MASTERY_DEFAULTS, masteryPeak, masteryState, type MasteryGraph, type MasteryParameters } from '../lib/masteryChallenge';
import '../mastery-challenge.css';
const missions=[{title:'Deliver target energy',hold:false,preset:MASTERY_DEFAULTS},{title:'Recover the focus',hold:false,preset:{...MASTERY_DEFAULTS,speed:2.4,focalLength:.15}},{title:'Keep the sample warm',hold:true,preset:{...MASTERY_DEFAULTS,speed:2.4,heatLeak:1}}];
const stages=['Move Cart','Power Circuit','Focus with Lens','Heat Sample'];
const modes=['Observe','Predict','Experiment','Explain'];
export default function MasteryChallengePage(){
 const [p,setP]=useState<MasteryParameters>({...MASTERY_DEFAULTS}),[time,setTime]=useState(0),[running,setRunning]=useState(true),[zoom,setZoom]=useState(1),[playback,setPlayback]=useState(.25);
 const [level,setLevel]=useState('Advanced'),[variables,setVariables]=useState('Essential'),[hints,setHints]=useState('Minimal'),[mission,setMission]=useState(0),[stage,setStage]=useState(0),[mode,setMode]=useState('Observe'),[panel,setPanel]=useState<string|null>(null),[graph,setGraph]=useState<MasteryGraph>('temperature'),[code,setCode]=useState(false),[search,setSearch]=useState('');
 const [answer,setAnswer]=useState<string|null>(null),[checked,setChecked]=useState(false),[attempts,setAttempts]=useState(0),[correct,setCorrect]=useState(0),[completed,setCompleted]=useState<string[]>([]);
 const s=masteryState(p,time),peak=masteryPeak(p),target=(level==='Advanced'?70:level==='Intermediate'?60:50)-(missions[mission].hold?10:0),historical=masteryState(p,Math.min(time,peak.time)).temperature;
 const reached=missions[mission].hold?time>=12&&masteryState(p,12).temperature>=target:historical>=target,canReach=missions[mission].hold?masteryState(p,12).temperature>=target:(Number.isFinite(peak.time)?peak.temperature>=target:peak.temperature>target);
 useEffect(()=>{if(!running||time>=60)return;let id=0,last=performance.now();const tick=(now:number)=>{const dt=Math.min(.05,(now-last)/1000)*playback;last=now;setTime(t=>Math.min(60,t+dt));id=requestAnimationFrame(tick)};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id)},[running,playback,time>=60]);
 useEffect(()=>{if(!reached)return;const key=`${missions[mission].title} · ${level}`;setCompleted(previous=>previous.includes(key)?previous:[...previous,key])},[reached,mission,level]);
 const start=(index:number)=>{setMission(index);setP({...missions[index].preset});setTime(0);setRunning(true);setZoom(1);setStage(0);setMode('Observe');setPanel(null);setAnswer(null);setChecked(false);setGraph('temperature')};
 const change=(key:keyof MasteryParameters,value:number)=>{setP(old=>({...old,[key]:value}));setTime(0);setAnswer(null);setChecked(false)};
 const open=(name:string)=>{if(modes.includes(name))setMode(name);setPanel(name==='Observe'?null:name)};
 const rows=[['Cart mass','m',`${p.mass.toFixed(2)} kg`],['Cart speed','v',`${s.velocity.toFixed(2)} m/s`],['Generated voltage','V',`${s.voltage.toFixed(1)} V`],['Current','I',`${s.current.toFixed(2)} A`],['Lens focal length','f',`${p.focalLength.toFixed(2)} m`],['Spot radius','r',`${(s.waist*1000).toFixed(2)} mm`],['Sample temperature','T',`${s.temperature.toFixed(1)} °C`],['Absorbed power','P',`${s.absorbedPower.toFixed(3)} W`],['Initial energy','E₀',`${s.initialEnergy.toFixed(3)} J`],['Stored heat','Q',`${s.storedHeat.toFixed(3)} J`],['Sample mass','mₛ',`${p.sampleMassMg} mg`],['Elapsed time','t',`${time.toFixed(2)} s`]];
 const explanation=<><p>The cart has a finite energy budget: <strong>½mv₀² = {s.initialEnergy.toFixed(3)} J</strong>. Regenerative braking produces V = kv and I = V/R while slowing the cart. Mechanical friction consumes part of that energy.</p><p>The idealized light emitter converts 70% of electrical power to light. Lens transmission, defocus and sample absorption reduce delivered heat. The warm spot is illumination, not thermal incandescence.</p><p>The magnified sample has a constant heat capacity of {s.heatCapacity.toFixed(4)} J/K. Its temperature follows C dT/dt = Pₐᵦₛ − H(T−20). This ideal model uses constant material properties and a linear heat leak; the generator rotor has negligible inertia.</p><dl className="mc-ledger">{[['Remaining kinetic',s.remainingEnergy],['Mechanical loss',s.mechanicalLoss],['Optical / conversion loss',s.opticalLoss],['Stored sample heat',s.storedHeat],['Heat lost to room',s.heatLoss]].map(([label,v])=><div key={String(label)}><dt>{label}</dt><dd>{Number(v).toFixed(4)} J</dd></div>)}</dl><p>Predicted peak: <strong>{peak.temperature.toFixed(1)} °C</strong>{Number.isFinite(peak.time)?` at ${peak.time.toFixed(2)} s`:' approached asymptotically without heat loss'}.</p></>;
 return <div className="mc-page" data-ui-theme="dark"><header className="mc-top"><Link to="/concept-studio">CONCEPT STUDIO</Link><span>Learn <b>•</b> Simulate <b>•</b> Reason <b>•</b> Master</span><p>Real Concepts. Deeper Understanding.</p><button aria-label="Search challenges" onClick={()=>{setSearch('');open('Search')}}><Icon name="search"/></button><button aria-label="Mastery settings" onClick={()=>open('Settings')}><Icon name="settings"/></button></header>
 <aside className="mc-sidebar"><nav aria-label="Mastery navigation"><button className="active" onClick={()=>open('Observe')}><Icon name="atom"/>Physics</button><button onClick={()=>open('Chemistry')}><Icon name="flask"/>Chemistry</button><button onClick={()=>open('Mathematics')}><Icon name="calculator"/>Mathematics</button><button onClick={()=>open('Earth Science')}><Icon name="orbit"/>Earth Science</button><button onClick={()=>open('Tools')}><Icon name="tools"/>Tools</button><hr/><button onClick={()=>open('Challenges')}><Icon name="trophy"/>Challenges</button><button onClick={()=>open('Progress')}><Icon name="levels"/>Progress</button><Link to="/quiz?view=practice"><Icon name="book"/>Library</Link></nav><button onClick={()=>open('Settings')}><Icon name="settings"/>Settings</button></aside>
 <main id="content" className="mc-main"><section className="mc-heading"><div><h1><Icon name="flag"/>PHYSICS MASTERY CHALLENGE</h1><p>Multiple systems. One real-world problem. Think across concepts.</p></div><div className="mc-filters"><label><Icon name="levels"/><span>Challenge Level<select aria-label="Challenge level" value={level} onChange={e=>{setLevel(e.target.value);setTime(0);setChecked(false);setAnswer(null)}}>{['Beginner','Intermediate','Advanced'].map(v=><option key={v}>{v}</option>)}</select></span></label><label><Icon name="eye"/><span>Variables Shown<select aria-label="Variables shown" value={variables} onChange={e=>setVariables(e.target.value)}><option>Essential</option><option>All</option></select></span></label><label><Icon name="lightbulb"/><span>Hint Depth<select aria-label="Hint depth" value={hints} onChange={e=>setHints(e.target.value)}><option>Minimal</option><option>Guided</option><option>Full</option></select></span></label></div></section>
 <section className="mc-mission"><div className="mc-lab"><MasteryChallengeScene p={p} time={time} zoom={zoom}/><div className="mc-mission-title">MISSION: {missions[mission].title.toUpperCase()}</div><div className="mc-stages">{stages.map((name,i)=><button key={name} className={stage===i?'active':''} onClick={()=>{setStage(i);open('Experiment')}}><i>{i+1}</i><span>{name}</span></button>)}</div><aside className="mc-goal"><h2>◎ &nbsp; GOAL</h2><p><span className="mc-goal-target">{missions[mission].hold?`Keep the sample at or above ${target} °C at 12 s.`:`Heat the sample to ${target} °C.`}</span><span className="mc-goal-detail"> Use the moving cart to generate electrical power, route it through the light source, focus light on the sample, and control heat loss.</span></p><strong role="status">{reached?'Target achieved':time>=60?'Run complete — adjust and retry':'Target not yet reached'}</strong></aside><span className="mc-clock">{time.toFixed(2)} s · {playback}× playback · schematic apparatus</span></div>
 <div className="mc-panels"><section className="mc-values"><h2>LIVE VALUES</h2><dl>{rows.slice(0,variables==='All'?rows.length:7).map(([label,symbol,value])=><div key={label}><dt>{label} <i>{symbol}</i></dt><dd>{value}</dd></div>)}</dl></section><section className="mc-relationship"><header><h2>DERIVED RELATIONSHIP</h2><div><button aria-pressed={code} onClick={()=>setCode(true)}>Code</button><button aria-pressed={!code} onClick={()=>setCode(false)}>Formula</button></div></header>{code?<pre>{`V = k * v\nI = V / R\nPabs = opticalEfficiency * V * I\ndTdt = (Pabs - H * (T - 20)) / C`}</pre>:<div className="mc-formula">P<sub>abs</sub> = η<sub>opt</sub> V I</div>}<dl><div><dt>P<sub>abs</sub></dt><dd>absorbed power at sample (W)</dd></div><div><dt>η<sub>opt</sub></dt><dd>light, lens and absorption fraction</dd></div><div><dt>V, I</dt><dd>instantaneous voltage and current</dd></div><div><dt>E₀</dt><dd>½ m v₀² = {s.initialEnergy.toFixed(3)} J</dd></div></dl></section><section className="mc-graphs"><h2>GRAPHS</h2><div className="mc-graph-tabs">{([['cart','Cart v(t)'],['circuit','Circuit V(t)'],['lens','Lens I(x)'],['temperature','Temp T(t)']] as const).map(([key,label])=><button key={key} aria-pressed={graph===key} onClick={()=>setGraph(key)}>{label}</button>)}</div><MasteryChallengeGraph p={p} time={time} kind={graph} target={target}/></section><section className="mc-controls"><h2>SCENE CONTROLS</h2><button aria-label="Reset" onClick={()=>start(mission)}><span>↻</span>Reset</button><button aria-label={running&&time<60?'Pause':'Play'} onClick={()=>{if(time>=60)setTime(0);setRunning(time>=60?true:!running)}}><span>{running&&time<60?'Ⅱ':'▷'}</span>{running&&time<60?'Pause':'Play'}</button><button aria-label="Zoom" onClick={()=>setZoom(v=>v>=1.2?.8:Number((v+.2).toFixed(1)))}><Icon name="search"/>Zoom {Math.round(zoom*100)}%</button><button className="mc-next" aria-label="Next Challenge" onClick={()=>start((mission+1)%missions.length)}>Next Challenge <span>›</span></button></section></div></section>
 <footer className="mc-modes">{modes.map((name,i)=><button key={name} className={mode===name?'active':''} aria-pressed={mode===name} onClick={()=>open(name)}><Icon name={(['eye','chart','flask','clipboard'] as const)[i]}/><span>{name}<small>{['See what’s happening','Make a hypothesis','Run and adjust','Justify the outcome'][i]}</small></span></button>)}</footer></main>
 {panel&&<MasteryChallengeDialog title={panel} close={()=>setPanel(null)}>
 {panel==='Experiment'&&<><div className="mc-dialog-tabs">{stages.map((name,i)=><button key={name} aria-pressed={stage===i} onClick={()=>setStage(i)}>{name}</button>)}</div><div className="mc-parameters">{(Object.keys(MASTERY_CONTROLS) as Array<keyof MasteryParameters>).filter(key=>MASTERY_CONTROLS[key].stage===stage).map(key=>{const control=MASTERY_CONTROLS[key];return <label key={key}><span>{control.label}<output>{p[key]} {control.unit}</output></span><input type="range" aria-label={control.label} min={control.min} max={control.max} step={control.step} value={p[key]} onChange={e=>change(key,Number(e.target.value))}/></label>})}</div><p>Changing a parameter prepares a new launch at t = 0. The apparatus and graphs update together.</p>{hints!=='Minimal'&&<p>{stage===0?'Initial energy grows with mass and with the square of launch speed.':stage===1?'A lower resistance increases electrical braking. It changes both the conversion fraction and the delivery time.':stage===2?'The sample plane is 0.10 m from the lens. Defocus spreads light beyond the sample.':'A smaller heat capacity warms faster. Lower conductance retains more of the absorbed energy.'}</p>}{hints==='Full'&&<p>Predicted peak: {peak.temperature.toFixed(1)} °C. Temperature at 12 s: {masteryState(p,12).temperature.toFixed(1)} °C.</p>}<button className="mc-primary" onClick={()=>{setRunning(true);setPanel(null)}}>Run this setup</button></>}
 {panel==='Predict'&&<><p>With this setup, will the sample {missions[mission].hold?`stay at or above ${target} °C at 12 s`:`reach ${target} °C during the launch` }?</p><div className="mc-answers">{['Yes','No'].map(v=><button key={v} disabled={checked} aria-pressed={answer===v} onClick={()=>setAnswer(v)}>{v}</button>)}</div><button className="mc-primary" disabled={!answer||checked} onClick={()=>{setChecked(true);setAttempts(v=>v+1);if((answer==='Yes')===canReach)setCorrect(v=>v+1)}}>Check prediction</button>{checked&&<p role="status">{(answer==='Yes')===canReach?'Correct.':'Review the energy budget.'} {missions[mission].hold?`At 12 s, the model gives ${masteryState(p,12).temperature.toFixed(1)} °C.`:`The predicted peak is ${peak.temperature.toFixed(1)} °C.`}</p>}<p>{correct} correct / {attempts} checked</p><button className="mc-primary" onClick={()=>open('Experiment')}>Test a change</button></>}
 {panel==='Explain'&&explanation}
 {(panel==='Challenges'||panel==='Search')&&<>{panel==='Search'&&<label>Find a mission<input className="mc-search" aria-label="Find a mission" value={search} onChange={e=>setSearch(e.target.value)} autoComplete="off"/></label>}<div className="mc-challenge-list">{missions.map((item,i)=>({item,i})).filter(({item})=>panel!=='Search'||item.title.toLowerCase().includes(search.toLowerCase())).map(({item,i})=><button key={item.title} onClick={()=>start(i)}>{i+1}. {item.title}<span>→</span></button>)}</div>{panel==='Search'&&!missions.some(item=>item.title.toLowerCase().includes(search.toLowerCase()))&&<p>No matching mission.</p>}<Link to="/quiz?view=practice">Open the original MCQ practice bank</Link></>}
 {panel==='Progress'&&<><p>{completed.length} mission/level combinations completed this session. {correct} of {attempts} predictions were correct.</p>{completed.length?<ul>{completed.map(item=><li key={item}>{item}</li>)}</ul>:<p>Reach a mission target to record your first completion.</p>}{explanation}</>}
 {panel==='Settings'&&<><label className="mc-setting">Playback speed<select aria-label="Playback speed" value={playback} onChange={e=>setPlayback(Number(e.target.value))}><option value="0.1">0.1×</option><option value="0.25">0.25×</option><option value="0.5">0.5×</option><option value="1">1×</option></select></label><p>Each run follows a single finite-energy launch for up to 60 simulated seconds. The graph shows the latest 12 seconds once that window is exceeded.</p><button className="mc-primary" onClick={()=>start(mission)}>Restart current mission</button></>}
 {panel==='Chemistry'&&<><p>The sample stores energy according to Q = mcΔT. Here c is a specified constant {MASTERY_CONSTANTS.specificHeat} J/(kg K); no phase change or chemical reaction is modeled.</p><p>The {p.sampleMassMg} mg sample has heat capacity {s.heatCapacity.toFixed(4)} J/K.</p><Link to="/topics/thermodynamics">Explore thermal concepts</Link></>}
 {panel==='Mathematics'&&<><p>Linear braking gives v(t) = v₀ exp(−bt/m), where b includes electrical and mechanical drag. Electrical power therefore decays twice as fast as velocity.</p><p>The temperature curve is the exact convolution of that decaying input and linear cooling. It is not a fitted decorative curve.</p><Link to="/solver">Open the physics solver</Link></>}
 {panel==='Earth Science'&&<><p>The launch energy is equivalent to lowering this cart through a height v₀²/(2g) = {(p.speed**2/(2*9.81)).toFixed(3)} m in Earth gravity, assuming no losses before launch.</p><p>Energy conversion and heat loss also govern natural systems; the same conservation principle applies at different scales.</p><Link to="/topics/energy">Explore energy</Link></>}
 {panel==='Tools'&&<><h3>Unit and energy checks</h3><p>{p.sampleMassMg} mg = {(p.sampleMassMg*1e-6).toExponential(2)} kg. {p.heatLeak} mW/K = {(p.heatLeak*.001).toFixed(5)} W/K.</p><p>Ignoring losses, heating this sample from 20 to {target} °C requires {(s.heatCapacity*(target-20)).toFixed(3)} J. The cart starts with {s.initialEnergy.toFixed(3)} J.</p><p>Actual delivered heat is lower because of the measured model losses.</p></>}
 </MasteryChallengeDialog>}
 </div>;
}
