import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { Link } from 'react-router-dom';
import { PhysicsIcon, type PhysicsIconName } from '../lib/icons';
import { MeterScaleScene } from '../components/MeterScaleScene';
import { MasteryChallengeDialog } from '../components/MasteryChallengeDialog';
import { METER_DEFAULTS, METER_MISSIONS, meterScaleState, type MeterScaleInput } from '../lib/meterScale';
import '../mastery-challenge.css';
import '../meter-scale.css';

const navigation: Array<[string, PhysicsIconName, string]> = [['Home','home','/concept-studio'],['Mechanics','atom','/topics/mechanics'],['Electricity','spark','/topics/electricity'],['Waves','wave','/topics/waves'],['Optics','prism','/topics/optics'],['Thermodynamics','thermometer','/topics/thermodynamics'],['Modern Physics','orbit','/topics/modern-physics'],['Experiments','flask','/experiments?view=library'],['Challenges','teacher','/quiz']];
export default function MeterScalePage() {
  const [input,setInput] = useState<MeterScaleInput>(METER_DEFAULTS), [camera,setCamera] = useState(40), [zoom,setZoom] = useState(1), [mode,setMode] = useState('Observe'), [panel,setPanel] = useState<string|null>(null), [mission,setMission] = useState(0), [answer,setAnswer] = useState(''), [feedback,setFeedback] = useState(''), [scanning,setScanning] = useState(false), [bright,setBright] = useState(false), [notes,setNotes] = useState('');
  const root = useRef<HTMLDivElement>(null), state = meterScaleState(input);
  const update = (change: Partial<MeterScaleInput>) => { setInput(old=>{const next={...old,...change};return {...next,position:Math.max(0,Math.min(100-next.length,next.position))};});setFeedback(''); };
  const reset = () => {setInput(METER_DEFAULTS);setCamera(40);setZoom(1);setMode('Observe');setPanel(null);setMission(0);setAnswer('');setFeedback('');setScanning(false);};
  useEffect(()=>{if(!scanning)return;let id:number,previous=0;let phase=Math.asin(input.angle/30);const tick=(now:number)=>{if(previous)phase+=Math.min(.05,(now-previous)/1000)*.7;previous=now;setInput(old=>({...old,angle:30*Math.sin(phase)}));id=requestAnimationFrame(tick);};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id);},[scanning]);
  const chooseMode = (name: string) => {setMode(name);if(name==='Observe'){setPanel(null);return;}setScanning(false);setPanel(name);};
  const nextMission = () => {const next=(mission+1)%METER_MISSIONS.length;setMission(next);setInput({...METER_DEFAULTS,...METER_MISSIONS[next]});setScanning(false);setAnswer('');setFeedback('');setMode('Experiment');setPanel('Experiment');};
  const check = () => {const reading=Number(answer);const correct=answer.trim()!==''&&Number.isFinite(reading)&&state.onScale&&Math.abs(reading-state.measured)<1e-7&&(mission!==1||Math.abs(input.angle)<.01)&&(mission!==2||input.division===.05);setFeedback(correct?`Correct: ${state.right.toFixed(state.decimals)} − ${state.left.toFixed(state.decimals)} = ${state.measured.toFixed(state.decimals)} cm.`:'Check the two readings, viewing angle and required scale division.');};
  const fullscreen = async () => {try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{setPanel('View');}};
  return <div className={`msr-page${bright?' msr-bright':''}`} ref={root} data-ui-theme="dark">
    <aside className="msr-sidebar"><Link className="msr-brand" to="/concept-studio">PHYSICS<br/>STUDIO</Link><nav>{navigation.map(([label,icon,href],index)=><Link key={label} to={href} className={`${index===1?'active ':''}${index===7?'msr-nav-divider':''}`}><PhysicsIcon name={icon}/><span>{label}</span></Link>)}<button onClick={()=>setPanel('Notes')}><PhysicsIcon name="clipboard"/><span>Notes</span></button></nav><button className="msr-settings" onClick={()=>setPanel('Settings')}><PhysicsIcon name="settings"/><span>Settings</span></button></aside>
    <header className="msr-top"><Link to="/topics/mechanics">Mechanics</Link><span>›</span><Link to="/concept-studio/measurement">Measurement</Link><span>›</span><span>Meter Scale</span><div><button aria-label="Bright scene" aria-pressed={bright} onClick={()=>setBright(true)}><PhysicsIcon name="sun"/></button><button aria-label="Dim scene" aria-pressed={!bright} onClick={()=>setBright(false)}><PhysicsIcon name="moon"/></button><button aria-label="Full screen" onClick={fullscreen}>⛶</button></div></header>
    <main id="content" className="msr-main"><header className="msr-heading"><h1>Measurement — Meter Scale</h1><p>Measure the length of a block using a meter rule. Adjust your viewing angle to explore parallax error.</p></header>
      <div className="msr-workspace"><div className="msr-left"><nav className="msr-modes" aria-label="Learning modes">{(['Observe','Predict','Experiment','Explain'] as const).map((name,index)=><button key={name} aria-pressed={mode===name} onClick={()=>chooseMode(name)}><PhysicsIcon name={(['eye','chart','flask','compass'] as const)[index]}/>{name}</button>)}</nav>
        <section className="msr-stage" aria-label="Interactive meter rule"><img className="msr-room" src="/assets/meter-scale/empty-bench.png" alt=""/><MeterScaleScene input={input} camera={camera} zoom={zoom} onMove={position=>update({position})}/><label className="msr-camera"><span><PhysicsIcon name="eye"/>Adjustable Camera View</span><input aria-label="Camera elevation" type="range" min="10" max="70" value={camera} style={{'--fill':`${(camera-10)/60*100}%`} as CSSProperties} onChange={e=>setCamera(Number(e.target.value))}/></label><p className="msr-scene-caption">1 cm raised edge · {input.bothEnds?'Both ends viewed at θ':'Left read normally; right viewed at θ'}</p></section>
        <section className="msr-equation"><div><h2><PhysicsIcon name="calculator"/>Measurement Equation</h2><p>L = x<sub>R</sub> − x<sub>L</sub></p></div><dl><div><dt>L</dt><dd>length of object</dd></div><div><dt>x<sub>R</sub></dt><dd>reading at right end</dd></div><div><dt>x<sub>L</sub></dt><dd>reading at left end</dd></div></dl></section>
      </div><aside className="msr-right"><section className="msr-controls"><h2>Controls</h2><label><span>Object Position (cm)<input aria-label="Object position value" type="number" min="0" max={100-input.length} step=".1" value={Number(input.position.toFixed(2))} onChange={e=>{if(e.target.value!==''&&Number.isFinite(e.target.valueAsNumber))update({position:e.target.valueAsNumber});}}/></span><input aria-label="Object position" type="range" min="0" max={100-input.length} step=".1" value={input.position} style={{'--fill':`${input.position/(100-input.length)*100}%`} as CSSProperties} onChange={e=>update({position:Number(e.target.value)})}/></label><label><span>Eye Angle (°)<input aria-label="Eye angle value" type="number" min="-30" max="30" step="1" value={Number(input.angle.toFixed(1))} onChange={e=>{setScanning(false);if(e.target.value!==''&&Number.isFinite(e.target.valueAsNumber))update({angle:Math.max(-30,Math.min(30,e.target.valueAsNumber))});}}/></span><input aria-label="Eye angle" type="range" min="-30" max="30" step="1" value={input.angle} style={{'--fill':`${(input.angle+30)/60*100}%`} as CSSProperties} onChange={e=>{setScanning(false);update({angle:Number(e.target.value)});}}/></label><label className="msr-select">Scale Division<select aria-label="Scale division" value={input.division} onChange={e=>update({division:Number(e.target.value)})}>{[[.05,'0.5 mm'],[.1,'1 mm'],[.2,'2 mm'],[.5,'5 mm'],[1,'1 cm']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></section>
      <section className="msr-readings"><h2>Live Measurements</h2>{([['ruler','Measured Length',state.onScale?state.measured.toFixed(state.decimals):'Off scale'],['ruler','Least Count',String(state.division)],['eye','Parallax (right endpoint)',`${state.shift<0?'−':state.shift>0?'+':''}${Math.abs(state.shift).toFixed(2)}`]] as const).map(([icon,label,value])=><div key={label}><PhysicsIcon name={icon}/><span>{label}<strong>{value}<small>{value==='Off scale'?'':' cm'}</small></strong></span></div>)}</section>
      <section className="msr-preview"><h2>View from Eye Angle</h2><div><img src="/assets/meter-scale/empty-bench.png" alt=""/><MeterScaleScene input={input} camera={65} preview/><span>{input.angle.toFixed(0)}°</span></div></section></aside></div>
      <footer className="msr-actions"><button aria-label="Reset" onClick={reset}><span>↶</span>Reset</button><button aria-label={scanning?'Pause':'Scan angle'} onClick={()=>setScanning(v=>!v)}><span>{scanning?'Ⅱ':'▷'}</span>{scanning?'Pause':'Scan angle'}</button><label><PhysicsIcon name="search"/><select aria-label="Zoom" value={zoom} onChange={e=>setZoom(Number(e.target.value))}><option value="1">Zoom 100%</option><option value="1.2">Zoom 120%</option><option value="1.5">Zoom 150%</option></select></label><button aria-label="Next Challenge" className="msr-next" onClick={nextMission}><span>→</span>Next Challenge</button></footer>
    </main>
    {panel&&<MasteryChallengeDialog title={panel} close={()=>setPanel(null)}>
      {panel==='Explain'&&<><p>Read x<sub>L</sub> = {state.left.toFixed(state.decimals)} cm and x<sub>R</sub> = {state.right.toFixed(state.decimals)} cm. Their difference is {state.onScale?`${state.measured.toFixed(state.decimals)} cm`:'outside this rule'}.</p><p>The reference edge is 1 cm above the graduations. Oblique sight gives displacement δ = h tan θ = {state.shift.toFixed(3)} cm. Positive θ means viewing from the left.</p><p>{input.bothEnds?'Both endpoints shift equally, so their geometric shifts cancel in the length.':'The left datum is read perpendicularly. Moving the eye for the right reading introduces a length bias.'} Each endpoint is rounded to the nearest graduation. The worst-case rounding error in their difference is one division ({state.division} cm).</p><p>The block is {input.length} cm long. Camera elevation changes the illustration; Eye Angle changes the reading geometry.</p><Link to="/experiments/measurement-errors">Open the existing uncertainty lesson</Link></>}
      {panel==='Predict'&&<><p>With the left datum read normally, what happens to the apparent right reading when the observer moves left (positive θ)?</p>{['It increases','It decreases','It stays fixed'].map((choice,index)=><button className="mc-primary" key={choice} onClick={()=>setFeedback(index===0?'Correct. δ = h tan θ is positive; the right reading shifts upward.':'Trace the sight line from the raised edge to the scale. Positive θ produces a positive displacement.')}>{choice}</button>)}<p role="status">{feedback}</p></>}
      {panel==='Experiment'&&<><h3>{METER_MISSIONS[mission].title}</h3><p>{METER_MISSIONS[mission].prompt}</p><p>Close this panel to adjust the controls or drag the block. Return here to check your answer.</p><label className="msr-answer">Measured length (cm)<input aria-label="Challenge length" type="number" step=".01" value={answer} onChange={e=>setAnswer(e.target.value)}/></label><button className="mc-primary" onClick={check}>Check measurement</button><p role="status">{feedback}</p></>}
      {panel==='Notes'&&<><p>Notes for this session</p><textarea aria-label="Measurement notes" value={notes} onChange={e=>setNotes(e.target.value)} rows={7}/></>}
      {panel==='Settings'&&<><label className="msr-checkbox"><input type="checkbox" checked={input.bothEnds} onChange={e=>update({bothEnds:e.target.checked})}/>Read both endpoints at the same eye angle</label><p>Equal raised heights and parallel sight lines give equal endpoint shifts, which cancel before rounding.</p><button className="mc-primary" onClick={()=>{setCamera(40);setZoom(1);setPanel(null);}}>Restore camera</button></>}
      {panel==='View'&&<p>Full screen is unavailable in this browser. Use the Zoom control to inspect the graduations.</p>}
    </MasteryChallengeDialog>}
  </div>;
}
