import { useEffect, useState, type CSSProperties } from 'react';
import { Link } from 'react-router-dom';
import { PhysicsIcon, type PhysicsIconName } from '../lib/icons';
import { MICROMETER_DEFAULTS, MICROMETER_WIRES, MICROMETER_CHALLENGES, micrometerState, type MicrometerInput } from '../lib/micrometer';
import { MicrometerScene } from '../components/MicrometerScene';
import { MasteryChallengeDialog } from '../components/MasteryChallengeDialog';
import '../mastery-challenge.css';
import '../micrometer.css';
export default function MicrometerPage() {
  const [input,setInput]=useState<MicrometerInput>(MICROMETER_DEFAULTS),[zoom,setZoom]=useState(1),[mode,setMode]=useState('Observe'),[panel,setPanel]=useState<string|null>(null),[running,setRunning]=useState(false),[bright,setBright]=useState(false),[challenge,setChallenge]=useState(0),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState(''),[notes,setNotes]=useState(''),[bookmarked,setBookmarked]=useState(false),[search,setSearch]=useState('');
  const s=micrometerState(input);
  const update=(change:Partial<MicrometerInput>)=>{setRunning(false);setInput(old=>{const next={...old,...change},state=micrometerState(next);return {...next,turns:state.turns,wire:state.wire,correction:state.correction};});setFeedback('');};
  const reset=()=>{setInput(MICROMETER_DEFAULTS);setZoom(1);setMode('Observe');setPanel(null);setRunning(false);setChallenge(0);setAnswer('');setFeedback('');};
  useEffect(()=>{if(!running)return;let turns=s.turns,prior=0,id:number;const frame=(now:number)=>{if(prior)turns=Math.max(input.wirePresent?s.wire/.5:0,turns-Math.min(.05,(now-prior)/1000)*.4);prior=now;setInput(old=>({...old,turns}));if(turns<=(input.wirePresent?s.wire/.5:0))setRunning(false);else id=requestAnimationFrame(frame);};id=requestAnimationFrame(frame);return()=>cancelAnimationFrame(id);},[running]);
  const open=(name:string)=>{setPanel(name==='Observe'?null:name);if(['Observe','Predict','Experiment','Explain'].includes(name))setMode(name);if(name!=='Observe')setRunning(false);};
  const next=()=>{const n=(challenge+1)%MICROMETER_CHALLENGES.length,c=MICROMETER_CHALLENGES[n];setChallenge(n);setInput({wire:c.wire,correction:c.correction,turns:(c.wire+.4)/.5,wirePresent:true});setAnswer('');setFeedback('');setRunning(false);setPanel('Challenge');};
  const fullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{setPanel('View');}};
  const readouts=[['settings','Pitch (P)','0.500 mm','Axial advance per rotation'],['compass','Least Count (LC)','0.01 mm','P / 50 (50 divisions)'],['ruler','Sleeve Reading (MSR)',`${s.sleeve.toFixed(2)} mm`,'Main scale (0.5 mm/div)'],['gauge','Thimble Reading (TSR)',`${s.divisions} divisions`,`${s.divisions} × 0.01 = ${s.thimble.toFixed(2)} mm`]] as Array<[PhysicsIconName,string,string,string]>;
  return <div className={`mcr-page${bright?' mcr-bright':''}`} data-ui-theme="dark"><header className="mcr-top"><Link to="/concept-studio"><PhysicsIcon name="atom"/>PHYSICS <span>STUDIO</span></Link><button className="mcr-search" onClick={()=>{setSearch('');open('Search');}}><PhysicsIcon name="search"/>Search experiments, concepts…</button><button aria-label="Toggle lighting" onClick={()=>setBright(v=>!v)}><PhysicsIcon name="sun"/></button><button aria-label="Full screen" onClick={fullscreen}>⛶</button></header>
    <aside className="mcr-sidebar"><nav>{([['Home','home','/concept-studio'],['Mechanics','wave','/topics/mechanics'],['Electricity','spark','/topics/electricity'],['Waves','wave','/topics/waves'],['Optics','prism','/topics/optics'],['Thermodynamics','thermometer','/topics/thermodynamics'],['Modern Physics','atom','/topics/modern-physics']] as Array<[string,PhysicsIconName,string]>).map(([label,icon,href],i)=><Link key={label} className={i===1?'active':''} to={href}><PhysicsIcon name={icon}/><span>{label}</span></Link>)}</nav><div><button onClick={()=>open('Tools')}><PhysicsIcon name="settings"/><span>Tools</span></button><button onClick={()=>open('Bookmarks')}><PhysicsIcon name="book"/><span>Bookmarks</span></button><button onClick={()=>open('Notes')}><PhysicsIcon name="clipboard"/><span>Notes</span></button></div></aside>
    <main id="content" className="mcr-main"><header className="mcr-heading"><div><h1>Micrometer Screw Gauge</h1><p>Measure the diameter of a thin wire using a micrometer screw gauge.</p></div><nav aria-label="Learning modes">{(['Observe','Predict','Experiment','Explain'] as const).map((name,i)=><button key={name} aria-pressed={mode===name} onClick={()=>open(name)}><PhysicsIcon name={(['eye','chart','flask','clipboard'] as const)[i]}/>{name}</button>)}</nav></header>
      <div className="mcr-workspace"><section className="mcr-scene" aria-label="Interactive micrometer"><img src="/assets/meter-scale/empty-bench.png" alt=""/><MicrometerScene input={input} zoom={zoom} onTurns={turns=>update({turns})}/><p className="mcr-scale-note">Travel 0–2 mm · drag thimble downward to close</p></section><aside className="mcr-side"><section className="mcr-controls"><h2>Controls</h2><label><PhysicsIcon name="ruler"/><span>Wire Gauge <small>(nominal diameter)</small></span><select aria-label="Wire gauge" value={input.wire} onChange={e=>update({wire:Number(e.target.value)})}>{MICROMETER_WIRES.map(w=><option key={w} value={w}>{w.toFixed(3)} mm</option>)}</select></label><label><PhysicsIcon name="gauge"/><span>Thimble Rotation (fine)<input aria-label="Thimble rotation" type="range" min={input.wirePresent?s.wire/.5:0} max="4" step=".02" value={s.turns} style={{'--fill':`${(s.turns-(input.wirePresent?s.wire/.5:0))/(4-(input.wirePresent?s.wire/.5:0))*100}%`} as CSSProperties} onChange={e=>update({turns:Number(e.target.value)})}/></span><output>{s.turns.toFixed(2)} turns</output></label><label><PhysicsIcon name="compass"/><span>Zero Correction<input aria-label="Zero correction" type="range" min="-.05" max=".05" step=".01" value={s.correction} style={{'--fill':`${(s.correction+.05)/.1*100}%`} as CSSProperties} onChange={e=>update({correction:Number(e.target.value)})}/></span><output>{s.correction.toFixed(2)} mm</output></label></section><section className="mcr-readings"><h2>Live Measurements</h2><div>{readouts.map(([icon,label,value,detail])=><article key={label}><PhysicsIcon name={icon}/><span>{label}<strong>{value}</strong><small>{detail}</small></span></article>)}</div></section></aside></div>
      <div className="mcr-lower"><section className="mcr-equation"><h2>Equation</h2><p>d = MSR + (TSR × LC) + ZC</p><dl>{[['d','diameter at contact'],['MSR','sleeve reading (mm)'],['TSR','thimble divisions (count)'],['LC','least count (0.01 mm)'],['ZC','signed zero correction (mm)']].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl></section><section className="mcr-result"><h2>{s.contact?'Measured Diameter':'Corrected Opening'}</h2><div><PhysicsIcon name="ruler"/><strong>{s.corrected.toFixed(2)} mm</strong></div><p>{s.contact?'Gentle contact — valid diameter':input.wirePresent?`Gap ${s.gap.toFixed(2)} mm — close onto the wire`:'Wire removed — close to check zero'}</p></section><section className="mcr-view"><h2>View</h2><div><button aria-label="Zoom in" onClick={()=>setZoom(v=>Math.min(1.6,Number((v+.2).toFixed(1))))}><PhysicsIcon name="search"/>Zoom In</button><button aria-label="Zoom out" onClick={()=>setZoom(v=>Math.max(.8,Number((v-.2).toFixed(1))))}><PhysicsIcon name="search"/>Zoom Out</button><button onClick={()=>setZoom(1)}>⛶<span>Fit View</span></button><div className="mcr-preview"><MicrometerScene input={input}/><i className="mcr-viewbox" style={{width:`${Math.min(100,100/zoom)}%`,height:`${Math.min(100,100/zoom)}%`}}/><span>{Math.round(zoom*100)}%</span></div></div></section></div>
      <footer className="mcr-actions"><button aria-label="Reset" onClick={reset}>↶　Reset</button><button aria-label={running?'Pause':'Close gently'} onClick={()=>setRunning(v=>!v)}>{running?'Ⅱ　Pause':'▷　Close gently'}</button><button className="mcr-next" onClick={next}>Next Challenge →</button></footer>
    </main>
    {panel&&<MasteryChallengeDialog title={panel} close={()=>setPanel(null)}>{panel==='Explain'&&<><p>Pitch / divisions = 0.500 / 50 = 0.01 mm per division. Physical opening = turns × pitch = {s.turns.toFixed(2)} × 0.500 = {s.opening.toFixed(2)} mm.</p><p>Raw reading = {s.sleeve.toFixed(2)} + {s.divisions} × 0.01 = {s.raw.toFixed(2)} mm. Add the signed zero correction ({s.correction.toFixed(2)} mm) to obtain {s.corrected.toFixed(2)} mm.</p><p>TSR is a division count, not a distance. A diameter is valid only when the anvil and spindle gently contact the wire. This rigid-contact model excludes wire compression.</p><Link to="/experiments/measurement-errors">Open original uncertainty lesson</Link></>}
      {panel==='Predict'&&<><p>A thimble turns through one complete revolution. How far does its spindle advance?</p>{['0.500 mm','0.010 mm','50 mm'].map((choice,i)=><button className="mc-primary" key={choice} onClick={()=>setFeedback(i===0?'Correct. One revolution advances one pitch.':'Distinguish a full revolution from one of its 50 divisions.')}>{choice}</button>)}<p role="status">{feedback}</p></>}
      {(panel==='Experiment'||panel==='Tools')&&<><label className="mcr-checkbox"><input type="checkbox" checked={input.wirePresent} onChange={e=>update({wirePresent:e.target.checked})}/>Wire present</label><button className="mc-primary" onClick={()=>{update({wirePresent:false,turns:0});setPanel(null);}}>Close without wire</button><button className="mc-primary" onClick={()=>{update({wirePresent:true,turns:s.wire/.5});setPanel(null);}}>Fit spindle to wire</button><button className="mc-primary" onClick={()=>setPanel('Challenge')}>Check current challenge</button><p>The lesson uses 0–2 mm of a 0–25 mm instrument's travel for thin wires. Dragging downward rotates the thimble toward closure.</p></>}
      {panel==='Challenge'&&<><h3>{MICROMETER_CHALLENGES[challenge].title}</h3><p>Bring the spindle into contact and report the corrected diameter. Close this dialog to adjust the instrument, then return through Experiment.</p><label>Diameter (mm)<input className="mcr-answer" aria-label="Challenge diameter" type="number" step=".01" value={answer} onChange={e=>setAnswer(e.target.value)}/></label><button className="mc-primary" onClick={()=>setFeedback(s.contact&&answer.trim()!==''&&Math.abs(Number(answer)-s.wire)<.001?'Correct. The calibrated diameter agrees with the wire.':'Check contact and apply the signed correction.')}>Check diameter</button><p role="status">{feedback}</p></>}
      {panel==='Notes'&&<><p>Notes for this session</p><textarea aria-label="Micrometer notes" rows={6} value={notes} onChange={e=>setNotes(e.target.value)}/></>}
      {panel==='Bookmarks'&&<><p>{bookmarked?'Micrometer is saved for this session.':'Save this instrument for this session.'}</p><button className="mc-primary" onClick={()=>setBookmarked(v=>!v)}>{bookmarked?'Remove bookmark':'Bookmark Micrometer'}</button>{bookmarked&&<Link to="/measurement/micrometer" onClick={()=>setPanel(null)}>Micrometer Screw Gauge</Link>}</>}
      {panel==='Search'&&<><label>Find a measurement lesson<input className="mc-search" aria-label="Find a measurement lesson" value={search} onChange={e=>setSearch(e.target.value)}/></label>{[['Meter Scale','/measurement/meter-scale'],['Vernier Caliper','/measurement/vernier-caliper'],['Micrometer','/measurement/micrometer'],['Uncertainty','/experiments/measurement-errors']].filter(([label])=>label.toLowerCase().includes(search.toLowerCase())).map(([label,href])=><Link key={label} to={href} onClick={()=>setPanel(null)}>{label}</Link>)}{!['meter scale','vernier caliper','micrometer','uncertainty'].some(v=>v.includes(search.toLowerCase()))&&<p>No matching lesson.</p>}</>}
      {panel==='View'&&<p>Full screen is unavailable. Use the page's zoom controls to inspect the instrument.</p>}
    </MasteryChallengeDialog>}
  </div>;
}
