import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {PhysicsIcon,type PhysicsIconName} from '../lib/icons';
import {MasteryChallengeDialog} from '../components/MasteryChallengeDialog';
import {MomentumScene} from '../components/MomentumScene';
import {MomentumForcePlot} from '../components/MomentumForcePlot';
import {MOMENTUM_DEFAULTS,momentumSettings,collisionTrial,collisionState,type MomentumInput} from '../lib/momentumCollision';
import '../mastery-challenge.css';import '../momentum-collisions.css';
const signed=(n:number,d=2)=>(Math.abs(n)<.5*10**-d?'':n>=0?'+':'')+(Math.abs(n)<.5*10**-d?0:n).toFixed(d);
function Control({label,value,min,max,step,digits=2,unit='',onChange}:{label:string;value:number;min:number;max:number;step:number;digits?:number;unit?:string;onChange:(v:number)=>void}){const[draft,setDraft]=useState(value.toFixed(digits));useEffect(()=>setDraft(value.toFixed(digits)),[value,digits]);const commit=()=>{const n=Number(draft);if(draft.trim()&&Number.isFinite(n)){const v=Math.max(min,Math.min(max,n));onChange(v);setDraft(v.toFixed(digits))}else setDraft(value.toFixed(digits))};return <label className="mcl-control"><span>{label}</span><div><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/><span className="mcl-number"><input aria-label={`${label} value`} type="number" min={min} max={max} step={step} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur()}}/>{unit&&<small>{unit}</small>}</span></div><small><span>{min}{label.includes('Restitution')?' (inelastic)':''}</span><span>{max}{label.includes('Restitution')?' (elastic)':''}</span></small></label>}
const challenges=[{title:'Transfer all the velocity',text:'Keep cart 1 at +0.60 m/s and cart 2 stationary. Make cart 1 stop after an elastic collision.',input:{ratio:2,u1:.6,u2:0,e:1}},{title:'Stick together',text:'Keep equal masses, cart 1 at +0.60 m/s and cart 2 stationary. Make their final velocities equal.',input:{ratio:1,u1:.6,u2:0,e:.8}},{title:'Reverse cart 1',text:'Keep initial velocities +0.60 and 0 m/s, with restitution 0.80. Make cart 1 leave at less than −0.10 m/s.',input:{ratio:1,u1:.6,u2:0,e:.8}}];
export default function MomentumCollisionsPage(){const[input,setInput]=useState(MOMENTUM_DEFAULTS),[time,setTime]=useState(.5),[running,setRunning]=useState(false),[zoom,setZoom]=useState(1),[mode,setMode]=useState('Observe'),[panel,setPanel]=useState<string|null>(null),[challenge,setChallenge]=useState(-1),[feedback,setFeedback]=useState(''),[expanded,setExpanded]=useState(true);const trial=collisionTrial(input),state=collisionState(trial,time);
 useEffect(()=>{if(!running)return;let id:number,previous=0;const tick=(now:number)=>{if(previous){const dt=Math.min(.04,(now-previous)/1000);setTime(t=>{const next=Math.min(1,t+dt);if(next>=1)setRunning(false);return next})};previous=now;id=requestAnimationFrame(tick)};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id)},[running]);
 const update=(p:Partial<MomentumInput>)=>{setInput(i=>momentumSettings({...i,...p}));setRunning(false);setFeedback('')};const reset=()=>{setInput(MOMENTUM_DEFAULTS);setTime(.5);setRunning(false);setZoom(1);setMode('Observe');setPanel(null);setChallenge(-1);setFeedback('');setExpanded(true)};
 const nextChallenge=()=>{const k=(challenge+1)%3;setChallenge(k);setInput(challenges[k].input);setTime(.5);setRunning(false);setFeedback('');setPanel('Challenge')};
 const check=()=>{const r=trial.result,fixed=Math.abs(input.u1-.6)<1e-9&&Math.abs(input.u2)<1e-9,pass=fixed&&(challenge===0?input.e===1&&Math.abs(r.v1)<.005:challenge===1?input.ratio===1&&Math.abs(r.v2-r.v1)<.005:input.e===.8&&r.v1<-.1);setFeedback(pass?'Correct. Your settings meet the collision target.':`Not yet. Final velocities are ${signed(r.v1)} and ${signed(r.v2)} m/s. Keep the specified settings and adjust the remaining control.`)};
 const nav=(label:string,to:string,icon:PhysicsIconName)=><Link to={to}><PhysicsIcon name={icon}/>{label}</Link>;
 return <div className="mcl-page" data-ui-theme="dark"><aside className="mcl-sidebar"><Link className="mcl-brand" to="/concept-studio">Physics Studio</Link><nav aria-label="Physics navigation">{nav('Home','/concept-studio','home')}<button aria-label="Mechanics" className="mcl-mechanics" aria-expanded={expanded} onClick={()=>setExpanded(v=>!v)}><PhysicsIcon name="settings"/>Mechanics <span>{expanded?'⌄':'›'}</span></button>{expanded&&<div className="mcl-subnav"><Link to="/concept-studio/motion-kinematics">Kinematics</Link><Link to="/mechanics/free-body-diagrams">Forces &amp; Newton’s Laws</Link><Link to="/mechanics/momentum-collisions" aria-current="page">Momentum &amp; Collisions</Link><Link to="/concept-studio/work-energy-power">Work &amp; Energy</Link><Link to="/mechanics/torque-levers">Rotational Motion</Link><Link to="/concept-studio/gravitation">Gravitation</Link></div>}{nav('Electricity & Magnetism','/concept-studio/electricity','spark')}{nav('Waves & Optics','/concept-studio/waves-sound','wave')}{nav('Thermodynamics','/concept-studio/thermodynamics','thermometer')}{nav('Modern Physics','/concept-studio/modern-physics','atom')}<hr/>{nav('Tools','/measurement/meter-scale','ruler')}<button onClick={()=>setPanel('Settings')}><PhysicsIcon name="settings"/>Settings</button>{challenge>=0&&<button onClick={()=>setPanel('Challenge')}><PhysicsIcon name="check"/>Current challenge</button>}</nav></aside>
 <main id="content" className="mcl-main"><header className="mcl-header"><div><h1>MECHANICS — MOMENTUM &amp; COLLISIONS</h1><p>Explore how momentum is conserved in collisions, and how the restitution coefficient controls the outcome.</p><div className="mcl-modes">{['Observe','Predict','Experiment','Explain'].map(v=><button key={v} aria-pressed={mode===v} onClick={()=>{setMode(v);setFeedback('');setPanel(v==='Observe'?null:v)}}>{v}</button>)}</div></div><section className="mcl-formula"><b>p = mv</b><p>Total momentum (isolated system) is conserved:</p><em>m₁u₁ + m₂u₂ = m₁v₁ + m₂v₂</em><p>Coefficient of restitution: <em>e = (v₂ − v₁) / (u₁ − u₂)</em></p></section></header>
 <MomentumScene trial={trial} time={time} zoom={zoom}/>
 <div className="mcl-workspace"><section className="mcl-panel mcl-controls"><h2>CONTROLS</h2><Control label="Cart Mass Ratio (m₂ / m₁)" value={input.ratio} min={.5} max={5} step={.05} digits={2} onChange={ratio=>update({ratio})}/><p className="mcl-mass-note">m₁ = 1.00 kg · m₂ = {input.ratio.toFixed(2)} kg</p><Control label="Initial Velocity (cart 1)" value={input.u1} min={-1} max={1} step={.01} unit="m/s" onChange={u1=>update({u1})}/><Control label="Initial Velocity (cart 2)" value={input.u2} min={-1} max={1} step={.01} unit="m/s" onChange={u2=>update({u2})}/><Control label="Coefficient of Restitution (e)" value={input.e} min={0} max={1} step={.01} onChange={e=>update({e})}/></section>
 <MomentumForcePlot trial={trial} time={time}/>
 <section className="mcl-panel mcl-readings"><h2>NUMERICAL READOUTS</h2><dl>{[['Total Momentum (before)',signed(trial.result.momentumBefore)+' kg·m/s'],['Total Momentum (current)',signed(state.momentum)+' kg·m/s'],['Kinetic Energy Change',signed(state.kineticChange,3)+' J'],['Impulse on Cart 1',signed(state.impulse1)+' N·s'],['Impulse on Cart 2',signed(state.impulse2)+' N·s']].map(([a,b])=><div key={a}><dt>{a}</dt><dd className={a==='Kinetic Energy Change'&&state.kineticChange<-.0005?'mcl-loss':''}>{b}</dd></div>)}</dl><div className="mcl-conserved"><PhysicsIcon name="check"/><span><b>Momentum conserved</b><small>{trial.closing<=0?'No collision: carts are not closing':time<trial.contactTime?'Approaching · contact has not started':'within numerical precision'}</small></span></div></section>
 <div className="mcl-playback"><div><button aria-label="Reset" onClick={reset}><span>⟲</span>Reset</button><button className="mcl-play" aria-label={running?'Pause':'Play'} onClick={()=>{if(time>=1)setTime(0);setRunning(v=>!v)}}><span>{running?'Ⅱ':'▷'}</span>{running?'Pause':'Play'}</button><button disabled={zoom<=.75} onClick={()=>setZoom(z=>Math.max(.75,z-.25))}><PhysicsIcon name="search"/>Zoom −</button><button disabled={zoom>=1.5} onClick={()=>setZoom(z=>Math.min(1.5,z+.25))}><PhysicsIcon name="search"/>Zoom +</button></div><input aria-label="Collision timeline" type="range" min="0" max="1" step=".001" value={time} onChange={e=>{setRunning(false);setTime(Number(e.target.value))}}/><div className="mcl-timeline-label"><span>t = {time.toFixed(2)} s</span><span>1.00 s</span></div></div><button aria-label="Next Challenge" className="mcl-next" onClick={nextChallenge}>Next Challenge <span>→</span></button></div>
 </main>{panel&&<MasteryChallengeDialog title={panel==='Challenge'&&challenge>=0?challenges[challenge].title:panel} close={()=>setPanel(null)}>
 {panel==='Predict'&&<><p>For equal masses, one initially stationary cart and a perfectly elastic collision, what happens?</p>{['Cart 1 stops; cart 2 takes its velocity','Both carts stop','Cart 1 keeps its initial velocity'].map((v,k)=><button key={v} className="mc-primary" onClick={()=>setFeedback(k===0?'Correct. Equal masses exchange their velocities when e = 1.':'Momentum and relative separation speed must both satisfy the collision equations.')}>{v}</button>)}<p role="status">{feedback}</p></>}
 {panel==='Experiment'&&<><p>Compare these cases, then scrub the timeline through contact.</p>{[['Elastic exchange',{ratio:1,u1:.6,u2:0,e:1}],['Stick together',{ratio:1,u1:.6,u2:0,e:0}],['Heavy target',{ratio:5,u1:.6,u2:0,e:.8}],['Separating carts',{ratio:1,u1:-.6,u2:.6,e:.8}]].map(([label,p])=><button className="mc-primary" key={String(label)} onClick={()=>update(p as MomentumInput)}>{String(label)}</button>)}</>}
 {panel==='Explain'&&<><p>Positive momentum points right. Cart 1 has mass 1 kg; the ratio changes cart 2’s internal ballast. Both snapshots show the same two carts at different times, with independent position rulers.</p><p>The horizontal track has no external force. Equal and opposite contact forces conserve total momentum at every instant. Their areas give the two impulses. Restitution sets the relative separation speed: v₂ − v₁ = e(u₁ − u₂).</p><p>The smooth half-sine force pulse is a chosen compliant-bumper model. Duration is {trial.duration.toFixed(2)} s for these approach speeds; restitution alone does not determine force shape. Bumpers compress and may retain deformation. At e = 0 the carts stick together.</p><p>During contact, lost kinetic energy includes stored deformation energy. After contact, ΔK = −½[m₁m₂/(m₁+m₂)](1−e²)(u₁−u₂)². Here the final change is {trial.closing>0?signed(-trial.result.dissipatedEnergy,3):'0.000'} J. No collision occurs when the carts are separating or moving together.</p><p>The dashed graph cursor and all numerical readouts use the current timeline. The full force curve shows the model prediction. Play stops at 1 s; scrub to 0 s to inspect the initial state.</p></>}
 {panel==='Settings'&&<><p>Apparatus magnification: {Math.round(zoom*100)}%. The rulers always show the physical position; the scene fits both carts automatically.</p><button className="mc-primary" onClick={()=>setZoom(1)}>Restore 100% zoom</button><p>Playback uses real elapsed time and stops at 1 s. It starts paused; use the timeline to inspect any instant without animation.</p><button className="mc-primary" onClick={()=>setRunning(false)}>Pause playback</button></>}
 {panel==='Challenge'&&challenge>=0&&<><p>{challenges[challenge].text}</p><p>Close this dialog to adjust the controls. Reopen Current challenge in the sidebar to check your settings.</p><button className="mc-primary" onClick={check}>Check solution</button><p role="status">{feedback}</p><button className="mc-primary" onClick={()=>setPanel(null)}>Adjust controls</button></>}
 </MasteryChallengeDialog>}</div>
}
