import { useEffect, useState, useRef, type CSSProperties } from 'react';
import { Link } from 'react-router-dom';
import { PhysicsIcon, type PhysicsIconName } from '../lib/icons';
import { SPHEROMETER_DEFAULTS, SPHEROMETER_CHALLENGES, spherometerState, type SpherometerInput, type SphericalSurface } from '../lib/spherometer';
import { SpherometerScene, SpherometerGeometry } from '../components/SpherometerScene';
import { MasteryChallengeDialog } from '../components/MasteryChallengeDialog';
import '../mastery-challenge.css';
import '../spherometer.css';
export default function SpherometerPage() {
  const [input,setInput]=useState<SpherometerInput>(SPHEROMETER_DEFAULTS),[zoom,setZoom]=useState(1),[running,setRunning]=useState(false),[mode,setMode]=useState('Observe'),[panel,setPanel]=useState<string|null>(null),[notes,setNotes]=useState(''),[uncertainty,setUncertainty]=useState(true),[challenge,setChallenge]=useState(0),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState('');
  const scanPhase=useRef<number|null>(null);
  const s=spherometerState(input),radius=s.flat?'∞':s.radius.toFixed(1),nearFlat=s.h<=.015;
  const update=(change:Partial<SpherometerInput>)=>{scanPhase.current=null;setRunning(false);setInput(old=>{const next={...old,...change},v=spherometerState(next);return {...next,height:v.h,legRadius:v.r};});setFeedback('');};
  const reset=()=>{scanPhase.current=null;setInput(SPHEROMETER_DEFAULTS);setZoom(1);setRunning(false);setMode('Observe');setPanel(null);setChallenge(0);setAnswer('');setFeedback('');};
  useEffect(()=>{if(!running)return;let phase=scanPhase.current??Math.asin(s.h-1),prior=0,id:number;const frame=(now:number)=>{if(prior)phase+=Math.min(.05,(now-prior)/1000)*.45;prior=now;scanPhase.current=phase;setInput(old=>({...old,height:1+Math.sin(phase)}));id=requestAnimationFrame(frame);};id=requestAnimationFrame(frame);return()=>cancelAnimationFrame(id);},[running]);
  const open=(name:string)=>{setPanel(name==='Observe'?null:name);if(['Observe','Predict','Experiment','Explain'].includes(name))setMode(name);if(name!=='Observe')setRunning(false);};
  const next=()=>{scanPhase.current=null;const n=(challenge+1)%SPHEROMETER_CHALLENGES.length,c=SPHEROMETER_CHALLENGES[n];setChallenge(n);setInput({height:c.height,legRadius:c.legRadius,surface:c.surface});setRunning(false);setAnswer('');setFeedback('');setPanel('Challenge');};
  return <div className="sph-page" data-ui-theme="dark"><header className="sph-top"><Link to="/concept-studio"><PhysicsIcon name="compass"/>PHYSICS <span>STUDIO</span></Link><nav><Link to="/concept-studio/measurement">Measurements</Link><span>›</span><span>Spherometer</span></nav><div>{(['Observe','Predict','Experiment','Explain'] as const).map((name,i)=><button key={name} aria-pressed={mode===name} onClick={()=>open(name)}><PhysicsIcon name={(['eye','chart','flask','clipboard'] as const)[i]}/>{name}</button>)}</div></header>
    <aside className="sph-sidebar">{([['Home','home','/concept-studio'],['Mechanics','book','/topics/mechanics'],['Measurements','flask','/concept-studio/measurement'],['Waves','wave','/topics/waves'],['Electricity','spark','/topics/electricity'],['Magnetism','magnet','/topics/magnetism'],['Optics','eye','/topics/optics'],['Modern Physics','atom','/topics/modern-physics']] as Array<[string,PhysicsIconName,string]>).map(([label,icon,href],i)=><Link key={label} className={i===2?'active':''} to={href}><PhysicsIcon name={icon}/><span>{label}</span></Link>)}<hr/><button onClick={()=>open('Tools')}><PhysicsIcon name="folder"/><span>Tools</span></button><Link to="/quiz"><PhysicsIcon name="teacher"/><span>Challenges</span></Link><button onClick={()=>open('Notebook')}><PhysicsIcon name="clipboard"/><span>Notebook</span></button><button onClick={()=>open('Settings')}><PhysicsIcon name="settings"/><span>Settings</span></button></aside>
    <main id="content" className="sph-main"><div className="sph-workspace"><div className="sph-left"><header><h1>SPHEROMETER</h1><p>Measure the radius of curvature of a spherical surface using a three-legged spherometer.</p></header><section className="sph-scene" aria-label="Spherometer apparatus"><img src="/assets/spherometer/optical-bench.png" alt=""/><SpherometerScene input={input} zoom={zoom}/></section></div><aside className="sph-controls-side"><section className="sph-controls"><h2>CONTROLS</h2><label><span>Screw Height, <i>h</i> (mm)<input type="number" aria-label="Screw height value" min="0" max="2" step=".001" value={Number(s.h.toFixed(3))} onChange={e=>{if(e.target.value!==''&&Number.isFinite(e.target.valueAsNumber))update({height:e.target.valueAsNumber});}}/></span><input style={{'--fill':`${s.h/2*100}%`} as CSSProperties} aria-label="Screw height" type="range" min="0" max="2" step=".001" value={s.h} onChange={e=>update({height:Number(e.target.value)})}/><small><span>0.000</span><span>2.000</span></small></label><label><span>Leg Radius, <i>r</i> (mm)<input aria-label="Leg radius value" type="number" min="10" max="100" step=".01" value={Number(s.r.toFixed(2))} onChange={e=>{if(e.target.value!==''&&Number.isFinite(e.target.valueAsNumber))update({legRadius:e.target.valueAsNumber});}}/></span><input style={{'--fill':`${(s.r-10)/90*100}%`} as CSSProperties} aria-label="Leg radius" type="range" min="10" max="100" step=".01" value={s.r} onChange={e=>update({legRadius:Number(e.target.value)})}/><small><span>10.00</span><span>100.00</span></small></label><label className="sph-surface">Surface Curvature<select aria-label="Surface curvature" value={input.surface} onChange={e=>update({surface:e.target.value as SphericalSurface})}><option value="convex">Convex (lens)</option><option value="concave">Concave (bowl)</option></select></label><div className="sph-surface-buttons">{(['convex','concave'] as const).map(surface=><button key={surface} aria-label={surface==='convex'?'Convex surface':'Concave surface'} aria-pressed={input.surface===surface} onClick={()=>update({surface})}><svg viewBox="0 0 100 28"><path d={surface==='convex'?'M10 24Q50-13 90 24Z':'M10 3Q50 38 90 3Q50 25 10 3Z'} fill="none" stroke="currentColor"/></svg></button>)}</div></section>
      <section className="sph-readings"><h2>LIVE MEASUREMENTS</h2><div><article><span>Sagitta, <i>h</i></span><strong>{s.h.toFixed(3)} <small>mm</small></strong>{uncertainty&&<p>σ = 0.005 mm</p>}</article><article><span>Radius of curvature, R</span><strong>{radius} <small>{s.flat?'':'mm'}</small></strong>{uncertainty&&<p>{nearFlat?'Near flat: poorly constrained':`σ ≈ ${s.radiusUncertainty.toFixed(1)} mm`}</p>}</article><article><span>Leg radius, <i>r</i></span><strong>{s.r.toFixed(2)} <small>mm</small></strong>{uncertainty&&<p>σ = 0.02 mm</p>}</article></div></section><section className="sph-equation"><h2>EQUATION</h2><div><p>R = <span><span>r² + h²</span><span>2h</span></span></p><dl><div><dt>R</dt><dd>radius magnitude (mm)</dd></div><div><dt>r</dt><dd>leg-circle radius (mm)</dd></div><div><dt>h</dt><dd>sagitta magnitude (mm)</dd></div></dl></div></section></aside></div>
      <div className="sph-views"><section><h2>SIDE VIEW (GEOMETRY)</h2><SpherometerGeometry input={input}/></section><section><h2>TOP VIEW</h2><SpherometerGeometry input={input} top/></section><section className="sph-sample"><h2>SAMPLE SURFACE</h2><div><img src="/assets/spherometer/optical-bench.png" alt=""/><SpherometerScene input={input} sample/></div><p>{s.flat?'Flat surface':input.surface==='convex'?'Convex spherical surface':'Concave spherical surface'}<small>R {s.flat?'→ ∞':`≈ ${radius} mm`}</small></p></section></div>
      <footer className="sph-actions"><button aria-label="Reset" onClick={reset}>↶　Reset</button><button aria-label={running?'Pause':'Scan curvature'} onClick={()=>setRunning(v=>!v)}>{running?'Ⅱ　Pause':'▷　Scan curvature'}</button><div><PhysicsIcon name="search"/><span>Zoom</span><button aria-label="Zoom out" onClick={()=>setZoom(v=>Math.max(.75,Number((v-.25).toFixed(2))))}>−</button><output>{Math.round(zoom*100)}%</output><button aria-label="Zoom in" onClick={()=>setZoom(v=>Math.min(1.5,Number((v+.25).toFixed(2))))}>+</button></div><button className="sph-next" onClick={next}>Next Challenge →</button></footer>
    </main>
    {panel&&<MasteryChallengeDialog title={panel} close={()=>setPanel(null)}>{panel==='Explain'&&<><p>The screw uses a 1 mm pitch and 100 drum divisions (0.01 mm per division). The live values retain interpolated model precision. A cross-section through the sphere gives r² + (R−h)² = R². Therefore R = (r²+h²)/(2h). Here r is the distance from the screw axis to a foot, not the separation between two feet.</p><p>The three feet are 120° apart. Their separation is √3 r = {s.legSeparation.toFixed(2)} mm. The signed curvature is {s.curvature.toExponential(3)} mm⁻¹; concave and convex surfaces have opposite signs but share the radius-magnitude equation.</p><p>{s.flat?'At zero sagitta the surface is flat, curvature is zero and the radius tends to infinity.':`R = (${s.r.toFixed(2)}² + ${s.h.toFixed(3)}²)/(2 × ${s.h.toFixed(3)}) = ${radius} mm.`}</p><p>Uncertainty uses independent standard uncertainties σh = 0.005 mm and σr = 0.02 mm with first-order propagation. Near zero sagitta this linear approximation becomes unreliable; the page flags that regime.</p><Link to="/experiments/measurement-errors">Original uncertainty lesson</Link></>}
      {panel==='Predict'&&<><p>Keeping leg radius fixed, what happens to R when sagitta increases within this range?</p>{['R decreases','R increases','R is unchanged'].map((choice,i)=><button className="mc-primary" key={choice} onClick={()=>setFeedback(i===0?'Correct. Larger sagitta indicates stronger curvature and a smaller radius.':'Compare r²/(2h) + h/2 for these shallow surfaces.')}>{choice}</button>)}<p role="status">{feedback}</p></>}
      {panel==='Experiment'&&<><p>Adjust sagitta and leg radius, then compare convex and concave surfaces. The three contacts lie on the same support circle.</p><button className="mc-primary" onClick={()=>{update({height:0});setPanel(null);}}>Set flat surface</button><button className="mc-primary" onClick={()=>setPanel('Challenge')}>Check current challenge</button></>}
      {panel==='Challenge'&&<><h3>{SPHEROMETER_CHALLENGES[challenge].title}</h3><p>{s.flat?'What is the radius of a perfectly flat surface? Enter infinity.':'Calculate the radius magnitude in millimeters. Round to one decimal place.'}</p><input className="mc-search" aria-label="Radius answer" value={answer} onChange={e=>setAnswer(e.target.value)}/><button className="mc-primary" onClick={()=>setFeedback((s.flat?['infinity','∞','inf'].includes(answer.trim().toLowerCase()):answer.trim()!==''&&Math.abs(Number(answer)-s.radius)<=.051)?'Correct. Your answer matches the spherical geometry.':'Recheck the leg-circle radius, sagitta and units.')}>Check radius</button><p role="status">{feedback}</p></>}
      {panel==='Notebook'&&<><p>Notes for this session</p><textarea rows={6} aria-label="Spherometer notes" value={notes} onChange={e=>setNotes(e.target.value)}/></>}
      {panel==='Tools'&&<><p>r = {(s.r/1000).toFixed(4)} m; h = {(s.h/1000).toFixed(6)} m.</p><p>R = {s.flat?'∞':(s.radius/1000).toFixed(4)} m. Curvature κ = {s.curvature.toExponential(4)} mm⁻¹.</p><p>For a nearly flat surface, curvature is more stable to report than radius. Propagated σκ ≈ {s.curvatureUncertainty.toExponential(2)} mm⁻¹.</p></>}
      {panel==='Settings'&&<><label className="sph-setting"><input type="checkbox" checked={uncertainty} onChange={e=>setUncertainty(e.target.checked)}/>Show uncertainty estimates</label><p>Inputs use millimeters. Height is a magnitude; surface selection sets the sign of curvature.</p></>}
    </MasteryChallengeDialog>}
  </div>;
}
