import { useEffect,useRef,useState } from 'react';import { Link } from 'react-router-dom';
import { PhysicsIcon,type PhysicsIconName } from '../lib/icons';
import { UNCERTAINTY_DEFAULTS,UNCERTAINTY_REFERENCE,uncertaintySettings,uncertaintyReading,uncertaintyStatistics,formatUncertainty,type UncertaintyInput,type UncertaintyErrorModel } from '../lib/uncertaintyAnalysis';
import { UncertaintyCylinder,UncertaintyPlot } from '../components/UncertaintyScene';import { MasteryChallengeDialog } from '../components/MasteryChallengeDialog';import '../mastery-challenge.css';import '../uncertainty-analysis.css';
const series=(s:UncertaintyInput)=>Array.from({length:s.count},(_,i)=>uncertaintyReading(s,i));
export default function UncertaintyPage(){
 const [input,setInput]=useState(UNCERTAINTY_DEFAULTS),[readings,setReadings]=useState(()=>series(UNCERTAINTY_DEFAULTS)),[selected,setSelected]=useState(9),[running,setRunning]=useState(false),[complete,setComplete]=useState(true),[zoom,setZoom]=useState(1),[mode,setMode]=useState('Observe'),[panel,setPanel]=useState<string|null>(null),[level,setLevel]=useState('Intermediate'),[notes,setNotes]=useState(''),[customValue,setCustomValue]=useState<string|null>(null),[customUncertainty,setCustomUncertainty]=useState<string|null>(null),[feedback,setFeedback]=useState(''),[challenge,setChallenge]=useState(0),[answer,setAnswer]=useState('');
 const elapsed=useRef(0),index=useRef(10),s=uncertaintySettings(input),stats=uncertaintyStatistics(readings,s.precision),f=(v:number|null,d=2)=>v===null?'—':v.toFixed(d),calcValue=customValue??f(stats.mean,3),calcUncertainty=customUncertainty??f(stats.combined,4),formatted=calcValue.trim()&&calcUncertainty.trim()?formatUncertainty(Number(calcValue),Number(calcUncertainty)):null;
 const configure=(change:Partial<UncertaintyInput>)=>{const next=uncertaintySettings({...input,...change});setInput(next);setReadings(series(next));setSelected(next.count-1);setRunning(false);setComplete(true);index.current=next.count;elapsed.current=0;setFeedback('');};
 const reset=()=>{configure(UNCERTAINTY_DEFAULTS);setZoom(1);setMode('Observe');setPanel(null);setCustomValue(null);setCustomUncertainty(null);setChallenge(0);setAnswer('');};
 const play=()=>{if(running){setRunning(false);return;}if(complete){setInput(old=>({...old,seed:old.seed+1}));setReadings([]);setSelected(0);index.current=0;elapsed.current=0;setComplete(false);}setRunning(true);};
 useEffect(()=>{if(!running)return;let id:number,prior=0;const frame=(now:number)=>{if(prior)elapsed.current+=Math.min(.05,(now-prior)/1000);prior=now;if(elapsed.current>=.65){elapsed.current-=.65;const point=uncertaintyReading(input,index.current);setReadings(old=>[...old,point]);setSelected(index.current);index.current++;if(index.current>=input.count){setRunning(false);setComplete(true);return;}}id=requestAnimationFrame(frame);};id=requestAnimationFrame(frame);return()=>cancelAnimationFrame(id);},[running,input]);
 const open=(name:string)=>{setRunning(false);setPanel(name==='Observe'?null:name);setFeedback('');if(['Observe','Predict','Experiment','Explain'].includes(name))setMode(name);};
 const next=()=>{const n=(challenge+1)%3;setChallenge(n);setAnswer('');setFeedback('');setRunning(false);setPanel('Challenge');};
 return <div className="unc-page" data-ui-theme="dark"><header className="unc-top"><Link to="/concept-studio"><PhysicsIcon name="ruler"/>PHYSICS STUDIO</Link></header><aside className="unc-sidebar">{([['Home','home','/concept-studio'],['Mechanics','compass','/topics/mechanics'],['Waves','wave','/topics/waves'],['Thermodynamics','thermometer','/topics/thermodynamics'],['Electricity','spark','/topics/electricity'],['Magnetism','magnet','/topics/magnetism'],['Optics','eye','/topics/optics'],['Modern Physics','atom','/topics/modern-physics'],['Measurement','ruler','/concept-studio/measurement'],['Simulations','flask','/experiments?view=library']] as Array<[string,PhysicsIconName,string]>).map(([name,icon,to],i)=><Link key={name} to={to} className={i===8?'active':''}><PhysicsIcon name={icon}/><span>{name}</span></Link>)}{([['Challenges','teacher'],['Notebook','clipboard'],['Settings','settings']] as Array<[string,PhysicsIconName]>).map(([name,icon])=><button key={name} onClick={()=>open(name)}><PhysicsIcon name={icon}/><span>{name}</span></button>)}</aside>
 <main id="content" className="unc-main"><header className="unc-header"><div><nav><Link to="/concept-studio/measurement">Measurement</Link>　›　Uncertainty &amp; Error Analysis</nav><h1>MEASUREMENT — UNCERTAINTY &amp; ERROR ANALYSIS</h1><p>Repeat measurements, analyze uncertainty, and quantify error.</p></div><div><select aria-label="Learning level" value={level} onChange={e=>setLevel(e.target.value)}>{['Beginner','Intermediate','Advanced'].map(l=><option key={l} value={l}>Level: {l}</option>)}</select><nav>{['Observe','Predict','Experiment','Explain'].map((name,i)=><button key={name} aria-pressed={mode===name} onClick={()=>open(name)}><PhysicsIcon name={(['eye','chart','flask','teacher'] as const)[i]}/>{name}</button>)}</nav></div></header>
 <div className="unc-workspace"><section className="unc-scene"><img src="/assets/uncertainty/volume-bench.png" alt=""/><UncertaintyCylinder reading={readings[selected]} zoom={zoom} corrected={input.correctBias}/></section><section className="unc-controls"><h2>Controls</h2><label>Sample Count (<i>n</i>)<select aria-label="Sample count" value={s.count} onChange={e=>configure({count:Number(e.target.value)})}>{[1,5,10,20,50].map(n=><option key={n}>{n}</option>)}</select></label><label>Instrument Precision<select aria-label="Instrument precision" value={s.precision} onChange={e=>configure({precision:Number(e.target.value)})}><option value="0.5">± 0.5 mL (cylinder)</option><option value="0.1">± 0.1 mL (calibrated)</option><option value="1">± 1.0 mL (coarse)</option></select></label><label>Error Model<select aria-label="Error model" value={input.model} onChange={e=>configure({model:e.target.value as UncertaintyErrorModel})}><option value="normal">Random (normal)</option><option value="systematic">Systematic (+0.8 mL)</option><option value="mixed">Random + systematic</option></select></label></section><section className="unc-live"><h2>Live Measurements</h2><div><table><thead><tr><th>#</th><th>Reading (mL)</th></tr></thead><tbody>{readings.map((r,i)=><tr key={r.trial} className={selected===i?'selected':''}><td>{r.trial}</td><td><button aria-label={`Inspect trial ${r.trial}`} onClick={()=>{setRunning(false);setSelected(i);}}>{r.value.toFixed(1)}</button></td></tr>)}</tbody></table>{!readings.length&&<p>Waiting for a reading…</p>}</div></section><section className="unc-results"><h2>Results</h2><dl>{[['Mean, x̄',`${f(stats.mean)} mL`],['Standard Deviation, s',`${f(stats.std)} mL`],['Percent Error',stats.percent===null?'—':`${stats.percent>=0?'+':''}${stats.percent.toFixed(2)} %`],['Combined Uncertainty',stats.combined===null?'—':`± ${f(stats.combined)} mL`]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><small>Reference: 66.4 mL · standard uncertainty, k = 1</small>{input.model!=='normal'&&!input.correctBias&&<p className="unc-bias">Injected +0.8 mL bias is uncorrected.</p>}<section className="unc-calculator"><h3>Significant Figures Calculator</h3><label>Value<input aria-label="Calculator value" value={calcValue} onChange={e=>setCustomValue(e.target.value)}/></label><label>Uncertainty<input aria-label="Calculator uncertainty" value={calcUncertainty} onChange={e=>setCustomUncertainty(e.target.value)}/></label><p>Result (proper format)</p><div><output>{formatted??'Enter valid value and positive uncertainty'}</output><button aria-label="Copy formatted result" disabled={!formatted} onClick={async()=>{try{await navigator.clipboard.writeText(formatted!);setFeedback('Copied formatted result.');}catch{setFeedback('Clipboard unavailable. Select the result to copy it.');}}}><PhysicsIcon name="clipboard"/></button></div><span role="status">{feedback}</span></section></section></div>
 <div className="unc-lower"><section><h2>Repeated Measurements</h2><UncertaintyPlot readings={readings} kind="scatter"/></section><section><h2>Distribution of Readings</h2><UncertaintyPlot readings={readings} kind="histogram"/></section><section className="unc-relation"><h2>Uncertainty Relation</h2><p><span className="unc-sigma">σ<sub>x̄</sub></span> = <span><span>s</span><span>√n</span></span></p><dl><div><dt>σ<sub>x̄</sub></dt><dd>standard uncertainty of the mean</dd></div><div><dt>s</dt><dd>sample standard deviation</dd></div><div><dt>n</dt><dd>number of measurements</dd></div></dl><small>{level==='Beginner'?'More repeats reduce random uncertainty.':level==='Advanced'?'Independent components: u꜀² = s²/n + a²/3.':'Combine SEM with calibration bound a/√3.'}</small></section></div><footer className="unc-actions"><button aria-label="Reset" onClick={reset}>↶　Reset</button><button aria-label={running?'Pause':complete?'Run measurements':'Resume measurements'} onClick={play}>{running?'Ⅱ　Pause':complete?'▷　Run measurements':'▷　Resume'}</button><div><button aria-label="Zoom out" onClick={()=>setZoom(v=>Math.max(.75,v-.25))}><PhysicsIcon name="search"/>−</button><input aria-label="Cylinder zoom" type="range" min=".75" max="1.5" step=".25" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/><output>{zoom*100}%</output><button aria-label="Zoom in" onClick={()=>setZoom(v=>Math.min(1.5,v+.25))}>+</button></div><button className="unc-next" onClick={next}>Next Challenge →</button></footer></main>
 {panel&&<MasteryChallengeDialog title={panel} close={()=>setPanel(null)}>{panel==='Explain'&&<><p>Read the bottom of the meniscus at eye level. The cylinder illustrates the selected observed reading; simulated random reading error has standard deviation 0.45 mL. Readings are interpolated to 0.1 mL.</p><p>The calibration half-width a is treated as a rectangular distribution: uB = a/√3. It is common to the series, so it is not divided by √n. The independent random component is s/√n, and u꜀ = √(s²/n + a²/3).</p><p>Percent error compares the mean with the 66.4 mL reference. Injected systematic bias is separate from the calibration specification; correct it before interpreting the uncertainty as describing an unbiased result.</p><a href="https://www.nist.gov/pml/nist-technical-note-1297/nist-tn-1297-appendix-law-propagation-uncertainty" target="_blank" rel="noreferrer">NIST uncertainty propagation guidance</a><p><Link to="/experiments/measurement-errors">Original uncertainty lesson</Link></p></>}
 {panel==='Predict'&&<><p>If sample count increases from 10 to 40 while s stays fixed, the standard uncertainty of the mean…</p>{['Halves','Doubles','Stays unchanged'].map((a,i)=><button className="mc-primary" key={a} onClick={()=>setFeedback(i===0?'Correct. The denominator √n doubles.':'Compare √10 with √40.')}>{a}</button>)}<p role="status">{feedback}</p></>}
 {(panel==='Experiment'||panel==='Settings')&&<><label className="unc-check"><input type="checkbox" checked={input.correctBias} onChange={e=>configure({correctBias:e.target.checked})}/>Correct the injected systematic bias</label><p>Correction subtracts 0.8 mL in systematic and mixed modes. It does not remove random scatter. More samples do not eliminate a common calibration component.</p><p>Current SEM: {f(stats.sem,4)} mL. Calibration component: {f(stats.uB,4)} mL.</p></>}
 {(panel==='Challenge'||panel==='Challenges')&&<><p>{['For s = 0.4 mL and n = 16, calculate the standard uncertainty of the mean (mL).','For a rectangular calibration bound ±0.5 mL, calculate uB (mL), to three decimals.','If s = 0.3 mL and n = 9, calculate the standard uncertainty of the mean (mL).'][challenge]}</p><input aria-label="Uncertainty answer" className="mc-search" value={answer} onChange={e=>setAnswer(e.target.value)}/><button className="mc-primary" onClick={()=>setFeedback(answer.trim()!==''&&Math.abs(Number(answer)-[.1,.5/Math.sqrt(3),.1][challenge])<.0006?'Correct. You used the appropriate uncertainty component.':'Check whether this asks for s/√n or a/√3.')}>Check uncertainty</button><p role="status">{feedback}</p></>}
 {panel==='Notebook'&&<textarea aria-label="Uncertainty notes" rows={6} value={notes} onChange={e=>setNotes(e.target.value)}/>}
 </MasteryChallengeDialog>}
 </div>;
}
