import { useEffect, useState, type CSSProperties } from 'react';
import { Link } from 'react-router-dom';
import { PhysicsIcon, type PhysicsIconName } from '../lib/icons';
import { VERNIER_DEFAULTS, VERNIER_CHALLENGES, vernierState, type VernierInput } from '../lib/vernierCaliper';
import { VernierCaliperScene, VernierMagnifier } from '../components/VernierCaliperScene';
import { MasteryChallengeDialog } from '../components/MasteryChallengeDialog';
import '../mastery-challenge.css';
import '../vernier-caliper.css';
export default function VernierCaliperPage() {
  const [input,setInput]=useState<VernierInput>(VERNIER_DEFAULTS),[mode,setMode]=useState('Observe'),[panel,setPanel]=useState<string|null>(null),[zoom,setZoom]=useState(1),[running,setRunning]=useState(false),[canResume,setCanResume]=useState(false),[bright,setBright]=useState(false),[expanded,setExpanded]=useState(true),[challenge,setChallenge]=useState(0),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState('');
  const s=vernierState(input);
  const update=(change:Partial<VernierInput>)=>{setRunning(false);setCanResume(false);setInput(old=>{const next={...old,...change},result=vernierState(next);return {...next,jaw:result.jaw,diameter:result.diameter,zeroError:result.zeroError};});setFeedback('');};
  const reset=()=>{setInput(VERNIER_DEFAULTS);setZoom(1);setRunning(false);setCanResume(false);setMode('Observe');setPanel(null);setChallenge(0);setAnswer('');setFeedback('');};
  useEffect(()=>{if(!running)return;let jaw=s.jaw,time=0,id:number;const frame=(now:number)=>{if(time)jaw=Math.max(input.objectPresent?s.diameter:0,jaw-Math.min(.05,(now-time)/1000)*5);time=now;setInput(old=>({...old,jaw}));if(jaw<=(input.objectPresent?s.diameter:0)){setRunning(false);setCanResume(false);}else id=requestAnimationFrame(frame);};id=requestAnimationFrame(frame);return()=>cancelAnimationFrame(id);},[running]);
  const demonstrate=()=>{if(running){setRunning(false);return;}if(!canResume)setInput(old=>({...old,jaw:Math.min(50,s.jaw+10)}));setCanResume(true);setRunning(true);};
  const open=(name:string)=>{setMode(['Observe','Predict','Experiment','Explain'].includes(name)?name:mode);setPanel(name==='Observe'?null:name);if(name!=='Observe')setRunning(false);};
  const next=()=>{const n=(challenge+1)%VERNIER_CHALLENGES.length,c=VERNIER_CHALLENGES[n];setChallenge(n);setInput({jaw:c.diameter+5,diameter:c.diameter,zeroError:c.zeroError,objectPresent:true});setRunning(false);setCanResume(false);setAnswer('');setFeedback('');setPanel('Challenge');};
  const controls:Array<[keyof Pick<VernierInput,'jaw'|'diameter'|'zeroError'>,string,number,number,PhysicsIconName]>=[['jaw','Jaw Position',input.objectPresent?s.diameter:0,50,'ruler'],['diameter','Object Diameter',5,40,'ruler'],['zeroError','Zero Error',-.2,.2,'chart']];
  return <div className={`vnc-page${bright?' vnc-bright':''}`} data-ui-theme="dark"><header className="vnc-top"><Link to="/concept-studio">PHYSICS <span>STUDIO</span></Link><nav><Link to="/concept-studio/measurement">Measurements</Link><b>›</b><Link to="/measurement/meter-scale">Length</Link><b>›</b><span>Vernier Caliper</span></nav><button aria-label="Toggle scene lighting" aria-pressed={bright} onClick={()=>setBright(v=>!v)}><PhysicsIcon name="sun"/></button><p>Precision Builds Understanding</p></header>
    <aside className="vnc-sidebar"><Link to="/concept-studio"><PhysicsIcon name="home"/>Home</Link><button aria-expanded={expanded} onClick={()=>setExpanded(v=>!v)}><PhysicsIcon name="compass"/>Mechanics<span>⌄</span></button>{expanded&&<nav className="vnc-mechanics">{[['Kinematics','/concept-studio/motion-kinematics'],['Dynamics','/concept-studio/force-newton'],['Work & Energy','/concept-studio/work-energy-power'],['Rotational Motion','/experiments/rotational-dynamics'],['Gravitation','/concept-studio/gravitation']].map(([label,href])=><Link key={label} to={href}>{label}</Link>)}</nav>}<Link className="active" to="/concept-studio/measurement"><PhysicsIcon name="ruler"/>Measurements</Link><Link to="/topics/fluid-mechanics"><PhysicsIcon name="drop"/>Properties of Matter</Link>{([['Waves','wave','/topics/waves'],['Electricity','spark','/topics/electricity'],['Magnetism','magnet','/topics/magnetism'],['Modern Physics','flask','/topics/modern-physics']] as Array<[string,PhysicsIconName,string]>).map(([label,icon,href])=><Link key={label} to={href}><PhysicsIcon name={icon}/>{label}<span>›</span></Link>)}<Link to="/quiz"><PhysicsIcon name="chart"/>Challenges</Link><button onClick={()=>open('Settings')}><PhysicsIcon name="settings"/>Settings</button></aside>
    <main id="content" className="vnc-main"><header className="vnc-learning"><nav aria-label="Learning modes">{(['Observe','Predict','Experiment','Explain'] as const).map((name,i)=><button key={name} aria-pressed={mode===name} onClick={()=>open(name)}><PhysicsIcon name={(['eye','chart','flask','compass'] as const)[i]}/>{name}</button>)}</nav><button className="vnc-challenge-link" onClick={next}><span>⚑</span><span><b>Next Challenge</b><small>Measure an unknown object</small></span><strong>›</strong></button></header>
      <div className="vnc-workspace"><section className="vnc-scene" aria-label="Interactive vernier caliper"><img src="/assets/meter-scale/empty-bench.png" alt=""/><VernierCaliperScene input={input} zoom={zoom} onJaw={jaw=>update({jaw})}/><span className="vnc-scale-note">50 vernier divisions = 49 mm · LC 0.02 mm</span><p>{s.contact?'Jaws in contact':input.objectPresent?`Gap ${(s.jaw-s.diameter).toFixed(2)} mm — close gently`:'Object removed — check zero with closed jaws'}</p></section>
        <aside className="vnc-analysis"><section className="vnc-detail"><h2>Vernier Scale (Magnified)</h2><VernierMagnifier input={input}/></section><section className="vnc-readings"><h2>Live Measurements</h2><div className="vnc-values"><div><span>Main Scale Reading</span><strong>{s.main.toFixed(2)} <small>mm</small></strong></div><div><span>Vernier Coincidence</span><strong>{s.coincidence}<small> / 50</small></strong></div><div><span>{input.objectPresent?'Final Diameter':'Corrected Opening'}</span><strong>{!input.objectPresent||s.contact?s.corrected.toFixed(2):'—'} <small>mm</small></strong></div></div><div className="vnc-equation"><p>D = M + (n × LC){s.zeroError!==0?' − z':''}</p><div>M = main scale reading<br/>n = vernier coincidence<br/>LC = least count (0.02 mm){s.zeroError!==0&&<><br/>z = {s.zeroError.toFixed(2)} mm</>}</div></div></section><section className="vnc-controls"><h2>Controls</h2><div>{controls.map(([key,label,min,max,icon])=><label key={key}><span><PhysicsIcon name={icon}/>{label}</span><input aria-label={label} type="range" min={min} max={max} step=".02" value={s[key]} style={{'--fill':`${(s[key]-min)/(max-min)*100}%`} as CSSProperties} onChange={e=>update({[key]:Number(e.target.value)})}/><output>{s[key].toFixed(2)} mm</output></label>)}</div></section></aside></div>
      <footer className="vnc-actions"><button aria-label="Reset" onClick={reset}><span>↶</span>Reset</button><button aria-label={running?'Pause':canResume?'Resume':'Demonstrate'} onClick={demonstrate}><span>{running?'Ⅱ':'▷'}</span>{running?'Pause':canResume?'Resume':'Demonstrate'}</button><label><PhysicsIcon name="search"/><select aria-label="Zoom" value={zoom} onChange={e=>setZoom(Number(e.target.value))}><option value="1">Zoom 100%</option><option value="1.2">Zoom 120%</option><option value="1.5">Zoom 150%</option></select></label><button className="vnc-next" aria-label="Next Challenge" onClick={next}>Next Challenge →</button></footer>
    </main><footer className="vnc-bottom"><span>EXPLORE　 ›　 MEASURE　 ›　 THINK　 ›　 GO FURTHER</span><span>SMALL MEASUREMENTS. BIGGER QUESTIONS.</span></footer>
    {panel&&<MasteryChallengeDialog title={panel} close={()=>setPanel(null)}>{panel==='Explain'&&<><p>50 vernier divisions occupy 49 mm. One vernier division is 0.98 mm, so LC = 1 − 0.98 = 0.02 mm.</p><p>Raw reading = {s.main.toFixed(2)} + {s.coincidence} × 0.02 = {s.raw.toFixed(2)} mm. Corrected opening = {s.raw.toFixed(2)} − ({s.zeroError.toFixed(2)}) = {s.corrected.toFixed(2)} mm.</p><p>{s.contact?'Both outside jaws contact the cylinder, so its diameter equals the corrected opening.':'A gap is not a diameter measurement. Close the jaws until they touch the object.'} The blue mark identifies the coincident vernier line in the magnified detail.</p><p>Negative raw readings near zero use the preceding main-scale millimeter and a positive vernier fraction. Zero error is always subtracted algebraically.</p><Link to="/experiments/measurement-errors">Original uncertainty lesson</Link></>}
      {panel==='Predict'&&<><p>A closed caliper reads +0.12 mm. How should you correct a later raw reading?</p>{['Subtract 0.12 mm','Add 0.12 mm','Leave it unchanged'].map((choice,i)=><button className="mc-primary" key={choice} onClick={()=>setFeedback(i===0?'Correct. Corrected reading = raw reading − zero error.':'The positive offset is present in every reading; subtract it.')}>{choice}</button>)}<p role="status">{feedback}</p></>}
      {(panel==='Experiment'||panel==='Settings')&&<><p>Drag the movable jaw or use its slider. The jaws cannot pass through a rigid specimen.</p><label className="vnc-checkbox"><input type="checkbox" checked={input.objectPresent} onChange={e=>update({objectPresent:e.target.checked})}/>Object present</label><button className="mc-primary" onClick={()=>{update({objectPresent:false,jaw:0});setPanel(null);}}>Close jaws to check zero</button><button className="mc-primary" onClick={()=>{update({objectPresent:true,jaw:s.diameter});setPanel(null);}}>Fit jaws to object</button><button className="mc-primary" onClick={()=>setPanel('Challenge')}>Check current challenge</button><p>Controls move in 0.02 mm steps. The zero-error adjustment shifts the vernier registration without changing the physical jaw opening.</p></>}
      {panel==='Challenge'&&<><h3>{VERNIER_CHALLENGES[challenge].title}</h3><p>Close the jaws onto the specimen. Read the scales and correct for zero error.</p><label className="vnc-answer">Diameter (mm)<input aria-label="Challenge diameter" type="number" step=".02" value={answer} onChange={e=>setAnswer(e.target.value)}/></label><button className="mc-primary" onClick={()=>setFeedback(s.contact&&answer.trim()!==''&&Math.abs(Number(answer)-s.diameter)<.001?'Correct. Your calibrated diameter matches the specimen.':'Check contact, the coincident division and the sign of zero error.')}>Check diameter</button><p role="status">{feedback}</p><p>Close this panel to adjust the jaws. Use Experiment to fit the jaws, then choose Check current challenge.</p></>}
    </MasteryChallengeDialog>}
  </div>;
}
