import { useEffect, useMemo, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { conceptExperiences, type ConceptExperience as Experience, type ConceptVisual } from "../lib/conceptExperiences";
import { PhysicsIcon } from "../lib/icons";

type Direction="increase"|"decrease"|"same";
type GraphPoint={time:number;value:number};
type LabTrial={id:string;conceptId:string;createdAt:string;values:Record<string,number>;metrics:[string,string][];prediction:Direction;expected:Direction;explanation:string};
const notebookKey="physicslab-concept-notebook-v1";

function readNotebook():LabTrial[]{try{return JSON.parse(localStorage.getItem(notebookKey)??"[]") as LabTrial[]}catch{return[]}}
function numericMetric(type:ConceptVisual,values:Record<string,number>){const entry=calculate(type,values)[0];return{label:entry[0],value:Number.parseFloat(entry[1].replace(/,/g,""))||0,formatted:entry[1]}}
function expectedDirection(experience:Experience,values:Record<string,number>):Direction{const control=experience.controls[0];const next={...values,[control.key]:Math.min(control.max,values[control.key]+Math.max(control.step,(control.max-control.min)*.08))};const before=numericMetric(experience.visual,values).value;const after=numericMetric(experience.visual,next).value;const tolerance=Math.max(.0001,Math.abs(before)*.002);return after-before>tolerance?"increase":before-after>tolerance?"decrease":"same"}
function liveValue(type:ConceptVisual,values:Record<string,number>,time:number){const base=numericMetric(type,values).value;switch(type){case"oscillation":return values.amplitude*Math.exp(-values.damping/100*time*.2)*Math.sin(time*values.frequency*Math.PI*2);case"wave":return values.amplitude*Math.sin(time*values.frequency*Math.PI*2);case"motion":return Math.max(0,values.speed*Math.sin(values.angle*Math.PI/180)*(time%5)-4.905*(time%5)**2);case"energy":return base*(.5+.5*Math.cos(time));case"electricity":case"electronics":return base*(.98+.02*Math.sin(time*7));case"thermal":return base*(.99+.01*Math.sin(time*3));default:return base*(.985+.015*Math.sin(time*1.8))}}

function RealtimeGraph({points,label,running}:{points:GraphPoint[];label:string;running:boolean}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current;if(!canvas)return;const rect=canvas.getBoundingClientRect();const dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));const ctx=canvas.getContext("2d");if(!ctx)return;ctx.setTransform(dpr,0,0,dpr,0,0);const w=rect.width,h=rect.height;const styles=getComputedStyle(canvas);const line=styles.getPropertyValue("--cx-cyan").trim()||"#58dcff";const grid=styles.getPropertyValue("--cx-line").trim()||"#1b3a49";const text=styles.getPropertyValue("--cx-muted").trim()||"#91aab5";ctx.clearRect(0,0,w,h);ctx.strokeStyle=grid;ctx.lineWidth=1;for(let i=0;i<5;i++){const y=20+i*(h-42)/4;ctx.beginPath();ctx.moveTo(48,y);ctx.lineTo(w-12,y);ctx.stroke()}if(points.length<2)return;const values=points.map(point=>point.value);let min=Math.min(...values),max=Math.max(...values);if(Math.abs(max-min)<.0001){min-=Math.max(1,Math.abs(min)*.05);max+=Math.max(1,Math.abs(max)*.05)}ctx.strokeStyle=line;ctx.lineWidth=2;ctx.beginPath();points.forEach((point,index)=>{const x=48+index/(points.length-1)*(w-62);const y=20+(max-point.value)/(max-min)*(h-42);index?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle=text;ctx.font="700 9px ui-monospace";ctx.textAlign="right";ctx.fillText(max.toPrecision(3),43,24);ctx.fillText(min.toPrecision(3),43,h-18);ctx.textAlign="left";ctx.fillText("TIME",48,h-5)},[points]);return <div className="concept-graph"><header><span>LIVE DATA STREAM</span><b>{label}</b><i className={running?"running":""}>{running?"SAMPLING":"PAUSED"}</i></header><canvas ref={ref} role="img" aria-label={`Live time-series graph of ${label}. ${points.length} samples recorded.`}/></div>}

function ConceptMissionPanel({experience,values,setValues}:{experience:Experience;values:Record<string,number>;setValues:(values:Record<string,number>)=>void}){
  const [scenario,setScenario]=useState("reference");
  const target=useMemo(()=>Object.fromEntries(experience.controls.map((control,index)=>{const fraction=index===0 ? .76 : .42;const raw=control.min+(control.max-control.min)*fraction;const rounded=Math.round(raw/control.step)*control.step;return[control.key,Number(rounded.toFixed(control.step<.1?2:control.step<1?1:0))]})),[experience]);
  const complete=experience.controls.every(control=>Math.abs(values[control.key]-target[control.key])<=Math.max(control.step*1.5,(control.max-control.min)*.015));
  const loadScenario=(kind:string,fractions:number[]|null)=>{
    setScenario(kind);
    const next=Object.fromEntries(experience.controls.map((control,index)=>{
      if(!fractions)return[control.key,control.value];
      const raw=control.min+(control.max-control.min)*fractions[index];
      return[control.key,Number((Math.round(raw/control.step)*control.step).toFixed(control.step<.1?2:control.step<1?1:0))];
    }));
    setValues(next);
  };
  return <section className="concept-missions" aria-labelledby={`missions-${experience.id}`}><header><div><span>MISSION MODES</span><h3 id={`missions-${experience.id}`}>Apply the concept under operating constraints</h3><p>Purpose: move from an isolated equation to realistic field and engineering configurations.</p></div><div className="concept-instruments"><b>60 Hz MODEL</b><b>SI UNITS</b><b>SENSORS NOMINAL</b></div></header><div className="concept-scenario-grid"><button className={scenario==="reference"?"active":""} onClick={()=>loadScenario("reference",null)}><span>REFERENCE</span><b>Laboratory baseline</b><small>Controlled starting values</small></button><button className={scenario==="field"?"active":""} onClick={()=>loadScenario("field",[.63,.57])}><span>FIELD EXAMPLE</span><b>{experience.examples[0].title}</b><small>Observe the concept in use</small></button><button className={scenario==="engineering"?"active":""} onClick={()=>loadScenario("engineering",[.84,.34])}><span>ENGINEERING</span><b>{experience.applications[0].title}</b><small>Test an applied configuration</small></button></div><div className="concept-calibration"><div><span>CALIBRATION CHALLENGE</span><h4>Commission the model to its assigned setpoint</h4><p>Adjust the live controls above until both instruments enter tolerance.</p></div><div className="concept-targets">{experience.controls.map(control=>{const error=Math.abs(values[control.key]-target[control.key])/(control.max-control.min);const progress=Math.max(0,100-error*400);return <div key={control.key}><span>{control.label}</span><b>{target[control.key]} {control.unit}</b><i><em style={{width:`${progress}%`}}/></i></div>})}</div><button className="concept-primary-action" onClick={()=>setValues({...target})}>Load setpoint</button><strong className={complete?"complete":""}>{complete?"COMMISSIONED":"CALIBRATION OPEN"}</strong></div></section>
}

export function ConceptExperience({ experience, compact=false }: { experience:Experience; compact?:boolean }) {
  const canvasRef=useRef<HTMLCanvasElement>(null); const elapsedRef=useRef(0); const [running,setRunning]=useState(true); const [values,setValues]=useState<Record<string,number>>(()=>Object.fromEntries(experience.controls.map((item)=>[item.key,item.value])));
  const [history,setHistory]=useState<GraphPoint[]>([]);const [prediction,setPrediction]=useState<Direction|"">("");const [predictionLocked,setPredictionLocked]=useState(false);const [baseline,setBaseline]=useState<Record<string,number>|null>(null);const [explanation,setExplanation]=useState("");const [trials,setTrials]=useState<LabTrial[]>(()=>readNotebook());const [noteMessage,setNoteMessage]=useState("");
  useEffect(()=>{setValues(Object.fromEntries(experience.controls.map((item)=>[item.key,item.value])));elapsedRef.current=0;setRunning(true);setHistory([]);setPrediction("");setPredictionLocked(false);setBaseline(null);setExplanation("");setNoteMessage("")},[experience.id]);
  const metrics=useMemo(()=>calculate(experience.visual,values),[experience.visual,values]);
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;let frame=0;const start=performance.now()-elapsedRef.current*1000;const reduce=matchMedia("(prefers-reduced-motion: reduce)").matches;const draw=(now:number)=>{const rect=canvas.getBoundingClientRect();const dpr=Math.min(2,devicePixelRatio||1);if(canvas.width!==Math.round(rect.width*dpr)||canvas.height!==Math.round(rect.height*dpr)){canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr)}const ctx=canvas.getContext("2d");if(!ctx)return;ctx.setTransform(dpr,0,0,dpr,0,0);const time=running&&!reduce?(now-start)/1000:elapsedRef.current;elapsedRef.current=time;drawExperience(ctx,rect.width,rect.height,experience.visual,values,time);if(running&&!reduce)frame=requestAnimationFrame(draw)};draw(performance.now());return()=>cancelAnimationFrame(frame)},[experience.visual,values,running]);
  useEffect(()=>{const sample=()=>setHistory(current=>[...current,{time:elapsedRef.current,value:liveValue(experience.visual,values,elapsedRef.current)}].slice(-72));sample();if(!running)return;const timer=window.setInterval(sample,250);return()=>window.clearInterval(timer)},[experience.visual,values,running]);
  const reset=()=>{setValues(Object.fromEntries(experience.controls.map((item)=>[item.key,item.value])));elapsedRef.current=0;setRunning(true);setHistory([]);setPrediction("");setPredictionLocked(false);setBaseline(null);setExplanation("");setNoteMessage("")};
  const commitPrediction=()=>{if(!prediction)return;setBaseline({...values});setPredictionLocked(true);setNoteMessage("Prediction committed. Change the variables and observe the model and graph.")};
  const expected=expectedDirection(experience,baseline??values);const conceptTrials=trials.filter(trial=>trial.conceptId===experience.id);const canRecord=predictionLocked&&explanation.trim().length>=12;
  const recordTrial=()=>{if(!prediction||!canRecord)return;const trial:LabTrial={id:`${experience.id}-${Date.now()}`,conceptId:experience.id,createdAt:new Date().toISOString(),values:{...values},metrics, prediction,expected,explanation:explanation.trim()};const next=[...trials,trial];setTrials(next);localStorage.setItem(notebookKey,JSON.stringify(next));setNoteMessage(`Trial ${conceptTrials.length+1} saved to this device.`)};
  const exportNotebook=()=>{const blob=new Blob([JSON.stringify(conceptTrials,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`${experience.id}-lab-notebook.json`;anchor.click();URL.revokeObjectURL(url)};
  return <section className={`concept-experience ${compact?"compact":""}`} aria-labelledby={`experience-${experience.id}`}>
    <header><div><span>LIVE CONCEPT · {experience.domain.toUpperCase()}</span><h2 id={`experience-${experience.id}`}>{experience.title}</h2><p>{experience.summary}</p></div><div className="concept-live"><i className={running?"running":""}/><b>{running?"LIVE MODEL":"MODEL PAUSED"}</b><small>SI training configuration</small></div></header>
    <div className="concept-experience-layout"><div className="concept-simulator"><div className="concept-canvas-head"><span>{experience.formula}</span><div><button onClick={()=>setRunning(!running)}><PhysicsIcon name={running?"step":"play"}/>{running?"Pause":"Run"}</button><button onClick={reset}>Reset</button></div></div><canvas ref={canvasRef} role="img" aria-label={`Animated ${experience.title} simulation. ${experience.principle}`}/><div className="concept-metrics">{metrics.map(([label,value])=><span key={label}><b>{label}</b><strong>{value}</strong></span>)}</div><RealtimeGraph points={history} label={metrics[0][0]} running={running}/></div>
      <aside className="concept-controls"><span>CHANGE THE MODEL</span>{experience.controls.map((control)=><label key={control.key}><b>{control.label}<em>{values[control.key].toFixed(control.step<.1?2:control.step<1?1:0)} {control.unit}</em></b><input type="range" min={control.min} max={control.max} step={control.step} value={values[control.key]} onChange={(event)=>setValues({...values,[control.key]:Number(event.target.value)})}/><small>{control.min} {control.unit}<i>{control.max} {control.unit}</i></small></label>)}<div className="concept-principle"><b>WHAT THE MODEL SHOWS</b><p>{experience.principle}</p></div>{!compact&&<ol>{experience.observe.map((item,index)=><li key={item}><span>0{index+1}</span>{item}</li>)}</ol>}</aside></div>
    {!compact&&<section className="concept-investigation" aria-labelledby={`investigation-${experience.id}`}><header><span>SCIENTIFIC METHOD</span><h3 id={`investigation-${experience.id}`}>Predict, observe, explain</h3><p>Purpose: turn the animation into a controlled investigation that produces evidence, not just motion.</p></header><div className="concept-method-steps"><span className={predictionLocked?"done":"active"}><b>01 PREDICT</b>State what the primary measurement will do.</span><span className={predictionLocked&&!explanation?"active":predictionLocked?"done":""}><b>02 OBSERVE</b>Change one variable and inspect the synchronized graph.</span><span className={explanation?"active":""}><b>03 EXPLAIN</b>Connect the evidence to the scientific principle.</span></div><div className="concept-prediction"><div><b>INVESTIGATION QUESTION</b><h4>When {experience.controls[0].label.toLowerCase()} increases, how will {metrics[0][0].toLowerCase()} change?</h4><p>Keep other variables controlled so the comparison is scientifically meaningful.</p></div><fieldset disabled={predictionLocked}><legend>Choose your prediction</legend>{(["increase","decrease","same"] as Direction[]).map(option=><label key={option}><input type="radio" name={`prediction-${experience.id}`} value={option} checked={prediction===option} onChange={()=>setPrediction(option)}/><span>{option==="same"?"No meaningful change":`${option[0].toUpperCase()}${option.slice(1)}`}</span></label>)}</fieldset><button className="concept-primary-action" disabled={!prediction||predictionLocked} onClick={commitPrediction}>{predictionLocked?"Prediction committed":"Commit prediction"}</button></div>{predictionLocked&&<div className="concept-explain"><label htmlFor={`explanation-${experience.id}`}>Explain the result using the graph and <strong>{experience.formula}</strong></label><textarea id={`explanation-${experience.id}`} value={explanation} onChange={event=>setExplanation(event.target.value)} placeholder={`Describe how changing ${experience.controls[0].label.toLowerCase()} affected ${metrics[0][0].toLowerCase()}, and why.`}/><div><span>{explanation.trim().length<12?"Add a short evidence-based explanation to record the trial.":prediction===expected?"Your prediction matches the model relationship.":`The model indicates ${expected}. Explain why your original prediction differed.`}</span><button className="concept-primary-action" disabled={!canRecord} onClick={recordTrial}>Record trial</button></div></div>}{noteMessage&&<p className="concept-note-message" role="status">{noteMessage}</p>}</section>}
    {!compact&&<ConceptMissionPanel experience={experience} values={values} setValues={setValues}/>} 
    {!compact&&<section className="concept-notebook" aria-labelledby={`notebook-${experience.id}`}><header><div><span>SCIENTIFIC NOTEBOOK</span><h3 id={`notebook-${experience.id}`}>Recorded evidence</h3><p>Purpose: preserve repeatable trials and compare how controlled variables changed the result.</p></div><button disabled={!conceptTrials.length} onClick={exportNotebook}>Export JSON</button></header>{conceptTrials.length===0?<div className="concept-empty-notebook">No trials recorded yet. Complete the scientific-method workflow above.</div>:<><div className="concept-trial-summary"><b>{conceptTrials.length}</b><span>TRIALS SAVED LOCALLY</span><strong>{conceptTrials.filter(trial=>trial.prediction===trial.expected).length}/{conceptTrials.length}</strong><span>PREDICTIONS SUPPORTED</span></div><div className="concept-trial-table" role="region" aria-label="Comparison of the two most recent trials"><table><thead><tr><th>Trial</th>{experience.controls.map(control=><th key={control.key}>{control.label}</th>)}<th>{metrics[0][0]}</th><th>Prediction</th><th>Evidence note</th></tr></thead><tbody>{conceptTrials.slice(-2).reverse().map((trial,index)=><tr key={trial.id}><td>#{conceptTrials.length-index}</td>{experience.controls.map(control=><td key={control.key}>{trial.values[control.key]} {control.unit}</td>)}<td>{trial.metrics[0][1]}</td><td>{trial.prediction===trial.expected?"Supported":"Revised"}</td><td>{trial.explanation}</td></tr>)}</tbody></table></div></>}</section>}
    {!compact&&<div className="concept-realworld"><section><header><PhysicsIcon name="eye"/><div><span>REAL-TIME EXAMPLES</span><h3>See it happening now</h3></div></header><div>{experience.examples.map((item)=><article key={item.title}><i/><b>{item.title}</b><p>{item.detail}</p></article>)}</div></section><section><header><PhysicsIcon name="spark"/><div><span>APPLICATIONS</span><h3>Where this physics works</h3></div></header><div>{experience.applications.map((item)=><article key={item.title}><i/><b>{item.title}</b><p>{item.detail}</p></article>)}</div></section></div>}
    {!compact&&<footer><span>Continue learning</span><Link to={experience.path}>Open curriculum topic →</Link><Link to={`/concepts?domain=${encodeURIComponent(experience.domain)}`}>Concept cards →</Link><Link to="/experiments">Related laboratories →</Link></footer>}
  </section>;
}

export function ConceptExperienceSelector({active,onSelect}:{active:string;onSelect:(id:string)=>void}){return <nav className="concept-experience-selector" aria-label="Interactive physics concepts">{conceptExperiences.map((item)=><button key={item.id} className={active===item.id?"active":""} onClick={()=>onSelect(item.id)}><PhysicsIcon name={item.icon}/><span>{item.shortTitle}</span></button>)}</nav>}

function calculate(type:ConceptVisual,v:Record<string,number>):[string,string][]{const g=9.81;switch(type){case"measure":return[["Reported",`${v.value.toFixed(1)} ± ${(v.resolution/2).toFixed(2)} mm`],["Relative uncertainty",`${(v.resolution/2/v.value*100).toFixed(2)}%`],["Resolution",`${v.resolution.toFixed(1)} mm`]];case"mechanics":case"newton":return[["Acceleration",`${(v.force/v.mass).toFixed(2)} m/s²`],["Net force",`${v.force.toFixed(0)} N`],["Mass",`${v.mass.toFixed(1)} kg`]];case"motion":{const a=v.angle*Math.PI/180;return[["Range",`${(v.speed*v.speed*Math.sin(2*a)/g).toFixed(1)} m`],["Flight time",`${(2*v.speed*Math.sin(a)/g).toFixed(2)} s`],["Max height",`${(v.speed*v.speed*Math.sin(a)**2/(2*g)).toFixed(1)} m`]]}case"energy":return[["Potential energy",`${(v.mass*g*v.height).toFixed(0)} J`],["Bottom speed",`${Math.sqrt(2*g*v.height).toFixed(1)} m/s`],["Energy","Conserved (ideal)"]];case"gravity":return[["Orbit period",`${(2*Math.PI*v.radius/(v.speed)).toFixed(0)} s`],["Centripetal a",`${(v.speed*v.speed*1000/v.radius).toFixed(2)} m/s²`],["Altitude",`${Math.max(0,v.radius-6371).toFixed(0)} km`]];case"oscillation":return[["Period",`${(1/v.frequency).toFixed(2)} s`],["Angular frequency",`${(2*Math.PI*v.frequency).toFixed(2)} rad/s`],["Damping",`${v.damping.toFixed(0)}%`]];case"wave":return[["Wavelength",`${(3.4/v.frequency).toFixed(2)} m`],["Wave speed","3.40 m/s"],["Frequency",`${v.frequency.toFixed(1)} Hz`]];case"optics":{const r=Math.asin(Math.sin(v.angle*Math.PI/180)/v.index)*180/Math.PI;return[["Refracted angle",`${r.toFixed(1)}°`],["Speed in medium",`${(299792458/v.index/1e6).toFixed(0)} Mm/s`],["Index",v.index.toFixed(2)]]}case"electricity":return[["Current",`${(v.voltage/v.resistance).toFixed(2)} A`],["Power",`${(v.voltage*v.voltage/v.resistance).toFixed(2)} W`],["Resistance",`${v.resistance.toFixed(0)} Ω`]];case"magnetism":return[["Relative field",`${(v.current*v.turns).toFixed(1)} A·turn`],["Polarity",v.current>=0?"North → right":"North → left"],["Turns",v.turns.toFixed(0)]];case"electronics":return[["Ideal output",`${(v.input*v.gain).toFixed(2)} V`],["Clipped output",`${Math.min(12,v.input*v.gain).toFixed(2)} V`],["Gain",`${v.gain.toFixed(1)}×`]];case"thermal":return[["Relative pressure",`${(v.temperature/v.volume).toFixed(1)} K/L`],["Particle energy",`${(1.5*1.38e-23*v.temperature*1e21).toFixed(2)} zJ`],["State","Ideal gas model"]];case"fluid":{const area=Math.PI*(v.narrowing/100)**2/4;return[["Outlet speed",`${(v.flow/1000/area).toFixed(2)} m/s`],["Flow rate",`${v.flow.toFixed(1)} L/s`],["Diameter",`${v.narrowing.toFixed(1)} cm`]]}case"modern":{const e=4.135667e-3*v.frequency;return[["Photon energy",`${e.toFixed(2)} eV`],["Max electron KE",`${Math.max(0,e-v.work).toFixed(2)} eV`],["Emission",e>v.work?"Electrons emitted":"Below threshold"]]}case"astronomy":return[["Recession speed",`${(70*v.distance).toFixed(0)} km/s`],["Look-back proxy",`${(v.distance*3.26).toFixed(0)} Mly`],["Lens mass",`${v.mass.toFixed(1)} ×10¹¹ M☉`]]}}

function drawExperience(ctx:CanvasRenderingContext2D,w:number,h:number,type:ConceptVisual,v:Record<string,number>,t:number){ctx.clearRect(0,0,w,h);const cyan="#52dcff",amber="#ffb052",white="#e8f7fb",muted="#567b8b",green="#65e39b";ctx.fillStyle="#06131b";ctx.fillRect(0,0,w,h);ctx.strokeStyle="#153543";ctx.lineWidth=1;for(let x=0;x<w;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.save();ctx.translate(w/2,h/2);const line=(x1:number,y1:number,x2:number,y2:number,color=cyan,width=2)=>{ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()};const dot=(x:number,y:number,r:number,color=cyan)=>{ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()};const text=(s:string,x:number,y:number,color=white,align:CanvasTextAlign="center")=>{ctx.fillStyle=color;ctx.font="700 11px ui-monospace";ctx.textAlign=align;ctx.fillText(s,x,y)};const path=(points:[number,number][],color=cyan)=>{ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke()};
  if(type==="measure"){line(-w*.38,50,w*.38,50,white,4);for(let i=0;i<=20;i++){const x=-w*.38+i*w*.76/20;line(x,50,x,50-(i%5===0?28:14),muted);if(i%5===0)text(String(i*5),x,75,muted)}const end=-w*.38+w*.76*(v.value/100);line(-w*.38,-10,end,-10,amber,12);line(end,-35,end,35,cyan);text(`${v.value.toFixed(1)} mm`,end,-45,cyan)}
  else if(type==="mechanics"||type==="newton"){const a=v.force/v.mass,x=Math.sin(t*.8)*Math.min(w*.24,Math.abs(a)*18);ctx.fillStyle="#163744";ctx.fillRect(x-55,5,110,70);line(x,5,x+Math.sign(v.force||1)*Math.min(150,Math.abs(v.force)*3),5,amber,5);text(`Fnet ${v.force.toFixed(0)} N`,x,-18,amber);line(-w*.4,76,w*.4,76,white,3);text(`a = ${a.toFixed(2)} m/s²`,0,110,cyan)}
  else if(type==="motion"){const a=v.angle*Math.PI/180,T=2*v.speed*Math.sin(a)/9.81,tt=t%Math.max(.5,T),scale=Math.min(w*.7/(v.speed*v.speed*Math.sin(2*a)/9.81+1),h*.55/(v.speed*v.speed*Math.sin(a)**2/19.62+1));const pts:[number,number][]=[];for(let q=0;q<=T;q+=T/50)pts.push([-w*.35+v.speed*Math.cos(a)*q*scale,h*.23-(v.speed*Math.sin(a)*q-4.905*q*q)*scale]);path(pts,muted);const x=-w*.35+v.speed*Math.cos(a)*tt*scale,y=h*.23-(v.speed*Math.sin(a)*tt-4.905*tt*tt)*scale;dot(x,y,9,amber);line(-w*.4,h*.24,w*.4,h*.24,white);text("projectile trajectory",0,-h*.32,cyan)}
  else if(type==="energy"){const phase=(Math.sin(t*.9)+1)/2,x=-w*.33+phase*w*.66,y=-h*.15+Math.cos(phase*Math.PI*2)*h*.13;path([[-w*.38,-h*.05],[-w*.2,h*.12],[0,-h*.1],[w*.2,h*.12],[w*.38,-h*.05]],muted);dot(x,y,12,amber);text("PE ↔ KE",0,-h*.32,cyan)}
  else if(type==="gravity"||type==="astronomy"){const r=Math.min(w,h)*.27,ang=t*(type==="gravity"?v.speed/7.7:.35);dot(0,0,type==="astronomy"?32:42,type==="astronomy"?amber:"#3d8bff");ctx.strokeStyle=muted;ctx.beginPath();ctx.ellipse(0,0,r,r*.56,0,0,Math.PI*2);ctx.stroke();dot(Math.cos(ang)*r,Math.sin(ang)*r*.56,9,cyan);if(type==="astronomy"){for(let i=0;i<5;i++){ctx.strokeStyle=`rgba(82,220,255,${.15+i*.08})`;ctx.beginPath();ctx.arc(0,0,50+i*13,-1.1,1.1);ctx.stroke()}text("gravity bends the light path",0,h*.34,white)}}
  else if(type==="oscillation"){const amp=Math.exp(-v.damping/100*t*.25)*90,x=Math.sin(t*v.frequency*Math.PI*2)*amp;line(0,-h*.35,0,-30,white,3);for(let i=0;i<12;i++){const y=-30+i*9;line(i%2?-12:12,y,i%2?12:-12,y+9,cyan)}dot(x,95,24,amber);line(0,78,x,95,white);text("equilibrium",0,135,muted)}
  else if(type==="wave"){const pts:[number,number][]=[];for(let x=-w*.45;x<w*.45;x+=4)pts.push([x,Math.sin(x*.035*v.frequency-t*4)*v.amplitude*24]);path(pts,cyan);for(let x=-w*.4;x<w*.41;x+=w*.08)dot(x,Math.sin(x*.035*v.frequency-t*4)*v.amplitude*24,4,amber);text("energy →",w*.35,-h*.3,white)}
  else if(type==="optics"){const ai=v.angle*Math.PI/180,ar=Math.asin(Math.sin(ai)/v.index);line(-w*.42,0,w*.42,0,white);line(0,-h*.4,0,h*.4,muted);line(-Math.sin(ai)*180,-Math.cos(ai)*180,0,0,amber,3);line(0,0,Math.sin(ar)*180,Math.cos(ar)*180,cyan,3);text("air",w*.35,-15,muted);text(`n = ${v.index.toFixed(2)}`,w*.35,22,cyan)}
  else if(type==="electricity"||type==="electronics"){const left=-w*.32,right=w*.32,top=-h*.23,bottom=h*.23;line(left,top,right,top,white);line(right,top,right,bottom,white);line(right,bottom,left,bottom,white);line(left,bottom,left,top,white);for(let i=0;i<12;i++){const q=(i/12+t*(type==="electricity"?v.voltage/v.resistance:.3))%1;let x,y;if(q<.25){x=left+(right-left)*q*4;y=top}else if(q<.5){x=right;y=top+(bottom-top)*(q-.25)*4}else if(q<.75){x=right-(right-left)*(q-.5)*4;y=bottom}else{x=left;y=bottom-(bottom-top)*(q-.75)*4}dot(x,y,4,cyan)}ctx.fillStyle="#172f39";ctx.fillRect(-42,-28,84,56);text(type==="electronics"?"AMPLIFIER":"RESISTOR",0,4,amber);text(type==="electronics"?`${Math.min(12,v.input*v.gain).toFixed(1)} V OUT`:`${(v.voltage/v.resistance).toFixed(2)} A`,0,80,cyan)}
  else if(type==="magnetism"){ctx.fillStyle="#d84f58";ctx.fillRect(-80,-28,80,56);ctx.fillStyle="#347bc1";ctx.fillRect(0,-28,80,56);text(v.current>=0?"S":"N",-40,5,white);text(v.current>=0?"N":"S",40,5,white);for(let i=-3;i<=3;i++){ctx.strokeStyle=cyan;ctx.beginPath();ctx.ellipse(0,0,120+Math.abs(i)*18,45+Math.abs(i)*10,0,0,Math.PI*2);ctx.stroke()}dot(Math.cos(t)*150,Math.sin(t)*58,7,amber)}
  else if(type==="thermal"){const count=28;const boxW=w*.65,boxH=h*.55;ctx.strokeStyle=white;ctx.strokeRect(-boxW/2,-boxH/2,boxW,boxH);for(let i=0;i<count;i++){const speed=Math.sqrt(v.temperature/300);const x=((Math.sin(i*91.7+t*speed*(i%3+1))*.5+.5)*boxW)-boxW/2,y=((Math.cos(i*47.3+t*speed*(i%4+1))*.5+.5)*boxH)-boxH/2;dot(x,y,3,i%4===0?amber:cyan)}text(`${v.temperature.toFixed(0)} K`,0,-boxH/2-18,amber)}
  else if(type==="fluid"){const inlet=h*.27,outlet=Math.max(18,v.narrowing*9),left=-w*.4,right=w*.4;ctx.fillStyle="rgba(82,220,255,.18)";ctx.beginPath();ctx.moveTo(left,-inlet/2);ctx.lineTo(0,-inlet/2);ctx.lineTo(right,-outlet/2);ctx.lineTo(right,outlet/2);ctx.lineTo(0,inlet/2);ctx.lineTo(left,inlet/2);ctx.closePath();ctx.fill();ctx.strokeStyle=cyan;ctx.stroke();for(let i=0;i<11;i++){const q=(i/11+t*v.flow*.03)%1,x=left+q*(right-left),half=x<0?inlet/2:(inlet/2+(outlet-inlet)/2*(x/(right)));dot(x,(i%3-1)*half*.55,4,amber)}text("slow / high pressure",left+70,-inlet/2-16,white);text("fast jet",right-45,-outlet/2-16,cyan)}
  else if(type==="modern"){dot(0,0,22,amber);for(let shell=1;shell<=3;shell++){ctx.strokeStyle=muted;ctx.beginPath();ctx.arc(0,0,shell*50,0,Math.PI*2);ctx.stroke();for(let e=0;e<shell*2;e++){const a=t*(.5+shell*.2)+e*Math.PI/shell;dot(Math.cos(a)*shell*50,Math.sin(a)*shell*50,5,cyan)}}const photonX=-w*.43+(t*80)%(w*.3);path([[photonX,-100],[photonX+12,-90],[photonX+24,-100],[photonX+36,-90]],green);text("photon E = hf",-w*.28,-125,green)}ctx.restore()}
