import { useId,useRef,useEffect,useState,type PointerEvent } from 'react';
import { solveFreeBody,type FreeBodyInput,type FreeBodyMotion } from '../lib/freeBody';
export interface FreeBodyDisplay { grid:boolean;components:boolean;values:boolean;net:boolean }
export function FreeBodyScene({input,motion,display,zoom,onForce}:{input:FreeBodyInput;motion:FreeBodyMotion;display:FreeBodyDisplay;zoom:number;onForce?:(force:number,angle:number)=>void}){
 const id=useId().replace(/:/g,''),svg=useRef<SVGSVGElement>(null),drag=useRef(false),f=solveFreeBody(input,motion),spatial=80,cameraX=Math.max(0,Math.abs(motion.x)*spatial-180)*Math.sign(motion.x),cameraY=Math.max(0,motion.y*spatial-80),cx=460+motion.x*spatial-cameraX,cy=350-motion.y*spatial+cameraY,ground=450+cameraY,forceScale=Math.min(2.4,230/Math.max(1,f.force,f.weight,f.normal,Math.abs(f.friction),Math.hypot(f.netX,f.netY))),gridN=[5,10,20,50,100].find(n=>n*forceScale>=24)??100,gridStep=gridN*forceScale;
 const [compact,setCompact]=useState(false);useEffect(()=>{const el=svg.current;if(!el)return;const observer=new ResizeObserver(()=>setCompact(el.clientWidth<650));observer.observe(el);return()=>observer.disconnect();},[]);
 const point=(x:number,y:number)=>({x:cx+x*forceScale,y:cy-y*forceScale}),end=point(f.fx,f.fy);
 const arrow=(x:number,y:number,color:string,label:string,offset=0)=>{if(Math.hypot(x,y)<1e-8)return null;const p=point(x,y);return <g><path d={`M${cx} ${cy}L${p.x} ${p.y}`} fill="none" stroke="#00111e" strokeWidth="6"/><path d={`M${cx} ${cy}L${p.x} ${p.y}`} stroke={color} strokeWidth="3.4" markerEnd={`url(#${id}${color.slice(1)})`}/>{display.values&&<text x={p.x+(x<0||p.x>760?-8:12)} y={p.y+(y>0?-10:18)+offset} textAnchor={x<0||p.x>760?'end':'start'} fill={color} fontSize={compact?30:15} paintOrder="stroke" stroke="#061726" strokeWidth="3">{compact?label.split(" = ")[0]:label}</text>}</g>;};
 const update=(e:PointerEvent<SVGSVGElement>)=>{if(!drag.current||!onForce||!svg.current)return;const matrix=svg.current.getScreenCTM();if(!matrix)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse()),dx=Math.max(0,(p.x-cx)/forceScale),dy=Math.max(0,(cy-p.y)/forceScale);onForce(Math.min(200,Math.hypot(dx,dy)),Math.atan2(dy,dx)*180/Math.PI);};
 return <svg ref={svg} className="fbd-scene-svg" viewBox={`${460-460/zoom} ${360-360/zoom} ${920/zoom} ${720/zoom}`} role="img" aria-label={`Free-body diagram: applied ${f.force.toFixed(1)} newtons, normal ${f.normal.toFixed(1)}, weight ${f.weight.toFixed(1)}, friction ${f.friction.toFixed(1)}; ${f.regime}`} onPointerMove={update} onPointerUp={()=>{drag.current=false;}} onPointerCancel={()=>{drag.current=false;}}><defs><pattern id={`${id}grid`} width={gridStep} height={gridStep} x={cx%gridStep} y={cy%gridStep} patternUnits="userSpaceOnUse"><path d={`M${gridStep} 0H0V${gridStep}`} fill="none" stroke="#10394e" strokeWidth=".7"/></pattern><filter id={`${id}stone`}><feTurbulence type="fractalNoise" baseFrequency=".055" numOctaves="4" seed="8" result="grain"/><feDiffuseLighting in="grain" lightingColor="#84909a" surfaceScale="6" diffuseConstant=".8"><feDistantLight azimuth="225" elevation="40"/></feDiffuseLighting><feComposite in2="SourceAlpha" operator="in"/></filter>{['#32b5ff','#45e78b','#f86766','#b16cff','#ffd46c'].map(color=><marker key={color} id={`${id}${color.slice(1)}`} markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5 0 7Z" fill={color}/></marker>)}</defs>
 {display.grid&&<rect width="920" height="720" fill={`url(#${id}grid)`}/>}
 <path d={`M0 ${cy}H908M${cx} 15V705`} stroke="#6087a8" strokeWidth="1"/><path d={`M908 ${cy}l-7-3v6ZM${cx} 15l-3 7h6Z`} fill="#83a9c6"/><text x="900" textAnchor="end" y={cy-10} fill="#8fbdda" fontSize={compact?28:14}>Fₓ (N)</text><text x={cx+11} y="26" fill="#8fbdda" fontSize={compact?28:14}>Fᵧ (N)</text>
 {ground<720&&<g><rect x="0" y={ground} width="920" height="100" fill="#233444"/><rect x="0" y={ground} width="920" height="100" filter={`url(#${id}stone)`}/><path d={`M0 ${ground}H920`} stroke="#bec8c7" strokeWidth="5"/>{Array.from({length:31},(_,i)=>{const x=i*40-(cameraX%40);return <path key={i} d={`M${x} ${ground+5}v${i%2?5:10}`} stroke="#bec8c7" opacity=".6"/>})}</g>}
 <image href="/assets/free-body/crate.png" x={cx-110} y={cy-110} width="220" height="220"/>
 {display.components&&<g><path d={`M${cx} ${cy}H${end.x}V${end.y}`} fill="none" stroke="#62baff" strokeWidth="1.5" strokeDasharray="7 5"/>{display.values&&<><text x={cx+(end.x-cx)/2} y={cy+23} textAnchor="middle" fill="#97d4ff" fontSize={compact?28:14} paintOrder="stroke" stroke="#082133" strokeWidth="3">{compact?"Fₓ":`Fₓ = ${f.fx.toFixed(1)} N`}</text><text x={end.x+(end.x>760?-12:12)} textAnchor={end.x>760?"end":"start"} y={cy+(end.y-cy)/2+(end.x>760?26:0)} fill="#97d4ff" fontSize={compact?28:14} paintOrder="stroke" stroke="#082133" strokeWidth="3">{compact?"Fᵧ":`Fᵧ = ${f.fy.toFixed(1)} N`}</text></>}</g>}
 {arrow(0,f.normal,'#45e78b',`N = ${f.normal.toFixed(1)} N`)}{arrow(0,-f.weight,'#f86766',`W = ${f.weight.toFixed(1)} N`)}{arrow(f.friction,0,'#b16cff',`f = ${Math.abs(f.friction).toFixed(1)} N`,12)}{arrow(f.fx,f.fy,'#32b5ff',`F = ${f.force.toFixed(1)} N`)}
 {display.net&&arrow(f.netX,f.netY,'#ffd46c',`ΣF = ${Math.hypot(f.netX,f.netY).toFixed(1)} N`,-12)}
 {onForce&&<circle cx={end.x} cy={end.y} r="15" fill="transparent" stroke="transparent" style={{cursor:'grab',touchAction:'none'}} onPointerDown={e=>{drag.current=true;e.currentTarget.ownerSVGElement?.setPointerCapture(e.pointerId);}}><title>Drag to change applied force and direction</title></circle>}
 <g fill="#adcee7" fontSize={compact?27:12}><path d="M28 678h80m-80-5v10m40-10v10m40-10v10" stroke="#b2d4ee"/><text x="28" y="667">0</text><text x="96" y="667">1 m</text>{!compact&&<text x="28" y="706">Spatial scale · camera follows motion</text>}<text x="900" y={compact?630:667} textAnchor="end">{f.contact?`${f.regime==='static'?'Static contact':'Sliding'} · μ = ${f.mu.toFixed(2)}`:motion.y<1e-8?'Lift-off · N = f = 0':'Airborne · N = f = 0'}</text><text x="900" y={compact?666:688} textAnchor="end">Force grid: {gridN} N per square</text><text x="900" y="708" textAnchor="end">x {motion.x.toFixed(2)} m · y {motion.y.toFixed(2)} m · t {motion.time.toFixed(2)} s</text></g>
 </svg>;
}
