import {useId,useRef,useEffect,useState,type PointerEvent} from 'react';import {solveIncline,INCLINE_LENGTH,type InclineInput,type InclineMotion} from '../lib/inclineStudio';
export type InclineView='Free-body diagram'|'Weight components'|'Apparatus only';
export function InclineScene({input,motion,view,zoom,onPosition}:{input:InclineInput;motion:InclineMotion;view:InclineView;zoom:number;onPosition:(s:number)=>void}){
 const id=useId().replace(/:/g,''),svg=useRef<SVGSVGElement>(null),drag=useRef(false),f=solveIncline(input,motion),theta=input.angle*Math.PI/180,c=Math.cos(theta),s=Math.sin(theta),px=865-Math.max(0,input.angle-35)*5,py=600,L=Math.min(900,(px-20)/c,480/Math.max(.01,s)),qx=px-L*c,qy=py-L*s,block=L*.45/3,h=block*.95,bx=motion.position/INCLINE_LENGTH*L;
 const [compact,setCompact]=useState(false);useEffect(()=>{const el=svg.current;if(!el)return;const o=new ResizeObserver(()=>setCompact(el.clientWidth<500));o.observe(el);return()=>o.disconnect()},[]);
 const cameraZoom=zoom*(1-.08*Math.max(0,Math.min(1,(motion.position-2.3)/.475)));
 const project=(x:number,y:number)=>({x:qx+x*c-y*s,y:qy+x*s+y*c}),center=project(bx,-30-h/2),forceScale=135/Math.max(f.weight,1),poly=(points:number[][])=>points.map(p=>p.join(',')).join(' ');
 const arrow=(fx:number,fy:number,color:string,label:string,dashed=false)=>{if(Math.hypot(fx,fy)<1e-8)return null;const x=center.x+fx*forceScale,y=center.y+fy*forceScale;return <g><path d={`M${center.x} ${center.y}L${x} ${y}`} stroke="#021320" strokeWidth="6"/><path d={`M${center.x} ${center.y}L${x} ${y}`} stroke={color} strokeDasharray={dashed?"7 4":undefined} strokeWidth="3.4" markerEnd={`url(#${id}${color.slice(1)})`}/><text className="ins-force-label" x={x+(fx<0||x>790?-8:10)} y={y-9-(label==='R'?36:0)} textAnchor={fx<0||x>790?'end':'start'} fill={color} fontSize="22" paintOrder="stroke" stroke="#052030" strokeWidth="3">{label}</text></g>};
 const move=(e:PointerEvent<SVGSVGElement>)=>{if(!drag.current||!svg.current)return;const m=svg.current.getScreenCTM();if(!m)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse());onPosition(Math.max(.225,Math.min(2.775,((p.x-qx)*c+(p.y-qy)*s)/L*3)));};
 return <svg ref={svg} className="ins-apparatus" viewBox={`${470-470/cameraZoom} ${372-372/cameraZoom} ${940/cameraZoom} ${744/cameraZoom}`} role="img" aria-label={`Inclined plane at ${input.angle} degrees; block at ${motion.position.toFixed(2)} metres, ${f.regime}`} onPointerMove={move} onPointerUp={()=>drag.current=false} onPointerCancel={()=>drag.current=false}><defs><linearGradient id={`${id}metal`} x2=".3" y2="1"><stop stopColor="#e0e7ea"/><stop offset=".08" stopColor="#738894"/><stop offset=".4" stopColor="#a2a9ac"/><stop offset=".7" stopColor="#455158"/><stop offset="1" stopColor="#14222a"/></linearGradient><linearGradient id={`${id}side`} x2="0" y2="1"><stop stopColor="#bbc6cd"/><stop offset=".08" stopColor="#404d54"/><stop offset=".9" stopColor="#72828c"/><stop offset="1" stopColor="#162833"/></linearGradient><filter id={`${id}rough`}><feTurbulence type="fractalNoise" baseFrequency=".5" numOctaves="3" seed="21"/><feDiffuseLighting lightingColor="#a4b0b7" surfaceScale="4" diffuseConstant=".85"><feDistantLight azimuth="230" elevation="40"/></feDiffuseLighting><feComposite in2="SourceAlpha" operator="in"/></filter><filter id={`${id}steelgrain`}><feTurbulence type="fractalNoise" baseFrequency=".075 .4" numOctaves="3" seed="7"/><feColorMatrix type="saturate" values="0"/><feComposite in2="SourceAlpha" operator="in"/></filter>{['#37d9f8','#b768eb','#9df35a','#ffb568','#ff757d'].map(color=><marker key={color} id={`${id}${color.slice(1)}`} markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3 0 6Z" fill={color}/></marker>)}</defs>
 <ellipse cx="495" cy="657" rx="417" ry="41" fill="#000" opacity=".6"/>
 <path d="M36 604L841 659 905 627 108 574Z" fill={`url(#${id}metal)`} stroke="#82939d" strokeWidth="2"/><path d="M36 604L841 659V691L36 635Z" fill={`url(#${id}side)`} stroke="#475f70"/><path d="M841 659L905 627V660L841 691Z" fill="#273944" stroke="#82939d"/>
 {[65,815].map(x=><g key={x}><ellipse cx={x} cy={x===65?657:710} rx="24" ry="9" fill="#000"/><path d={`M${x-15} ${x===65?634:683}v20h30v-20`} fill={`url(#${id}side)`}/></g>)}
 <path d={`M${qx-12} ${qy}V610h28V${qy}`} fill={`url(#${id}metal)`} stroke="#91a3af" strokeWidth="2"/><path d={`M${qx+40} ${qy-15}V604h17V${qy-15}`} fill={`url(#${id}side)`}/>
 <g transform={`translate(${qx+10} ${Math.min(qy+75,430)})`}><path d="M0 0H170A170 170 0 0 1 0 170Z" fill="#07141ce8" stroke="#708896"/><circle r="8" fill={`url(#${id}metal)`}/>{Array.from({length:91},(_,n)=>{const t=n*Math.PI/180,r=160;return <g key={n}><path d={`M${Math.cos(t)*r} ${Math.sin(t)*r}l${-Math.cos(t)*(n%10===0?14:6)} ${-Math.sin(t)*(n%10===0?14:6)}`} stroke="#cadce7"/>{(compact?n%30===0:n%10===0)&&<text x={Math.cos(t)*132} y={Math.sin(t)*132+5} fill="#dae9f0" fontSize={compact?25:13} textAnchor="middle">{n}°</text>}</g>})}<path d={`M0 0L${146*c} ${146*s}`} stroke="#7fe1ff" strokeWidth="2"/></g>
 <g transform={`translate(${qx} ${qy}) rotate(${input.angle})`}><path d={`M0 -30H${L}V4H0Z`} fill={`url(#${id}side)`} stroke="#c3d0d8" strokeWidth="2"/><polygon points={poly([[0,-30],[L,-30],[L+44,-55],[44,-55]])} fill="#24333b" stroke="#c3d0d8" strokeWidth="2"/><polygon points={poly([[3,-31],[L-3,-31],[L+40,-53],[47,-53]])} filter={`url(#${id}rough)`}/>{[12,L-12].map(x=><g key={x}><rect x={x-5} y="-68" width="10" height="40" rx="2" fill={`url(#${id}metal)`}/><circle cx={x} cy="-8" r="7" fill="#12202a" stroke="#9aaebc"/><path d={`M${x-4} -8h8`} stroke="#c8d6df"/></g>)}
 <g style={{cursor:'grab',touchAction:'none'}} onPointerDown={e=>{drag.current=true;e.currentTarget.ownerSVGElement?.setPointerCapture(e.pointerId);}}><title>Drag block to choose its starting position</title><rect x={bx-block/2} y={-30-h} width={block} height={h} rx="4" fill={`url(#${id}metal)`} stroke="#d7e8f2" strokeWidth="2"/><rect x={bx-block/2+2} y={-28-h} width={block-4} height={h-4} rx="3" filter={`url(#${id}steelgrain)`} opacity=".34"/><polygon points={poly([[bx-block/2,-30-h],[bx+block/2,-30-h],[bx+block/2+34,-52-h],[bx-block/2+34,-52-h]])} fill="#9eafb9" stroke="#dfedf6" strokeWidth="2"/><polygon points={poly([[bx+block/2,-30-h],[bx+block/2+34,-52-h],[bx+block/2+34,-52],[bx+block/2,-30]])} fill={`url(#${id}side)`} stroke="#95a9b6"/><path d={`M${bx-block/2+9} ${-38-h}h${block-18}`} stroke="#e6eef2" opacity=".65"/></g></g>
 {view!=='Apparatus only'&&<>{arrow(f.normal*s,-f.normal*c,'#37d9f8','N')}{arrow(f.friction*c,f.friction*s,'#b768eb',Math.abs(motion.velocity)<1e-10&&f.regime!=='sliding'?'fₛ':'fₖ')}{arrow(f.downhill*c,f.downhill*s,'#9df35a','mg sin θ',true)}{f.bumper!==0&&arrow(f.bumper*c,f.bumper*s,'#ffb568','R')}{arrow(0,f.weight,'#ff757d','mg')}{view==='Weight components'&&arrow(-f.normal*s,f.normal*c,'#37d9f8','mg cos θ',true)}</>}
 <path d={`M${px-220} ${py}H${px}M${px-120} ${py}A120 120 0 0 1 ${px-120*c} ${py-120*s}`} fill="none" stroke="#9cddff" strokeWidth="2" strokeDasharray="7 5"/><text x={px-190} y={py-24} fill="#e4f6ff" fontSize="23">θ = {input.angle.toFixed(1)}°</text><text x="24" y="720" fill="#b5d8f2" fontSize="15">3.00 m ramp · s = {motion.position.toFixed(2)} m · v = {motion.velocity.toFixed(2)} m/s</text>
 </svg>;
}
