import { useId } from 'react';
import { launcherGraph, launcherOpticalProfile, type LauncherEquipment, type LauncherParameters, type LauncherStudio } from '../lib/experimentLauncher';
export function LauncherGraph({studio,p,time,equipment}:{studio:LauncherStudio;p:LauncherParameters;time:number;equipment:LauncherEquipment}){
 const profiles=launcherOpticalProfile(p,equipment),opticalStatus=profiles.every(c=>c.tir)?'No direct beam: total internal reflection':profiles.every(c=>c.offset===null||Math.abs(c.offset)>20)?'Beam peak outside the plotted window':'';
 const id=useId().replace(/:/g,''),optics=studio==='optics',curves=optics?profiles.map(c=>({color:c.color,points:c.points})): [{color:'#43baff',points:launcherGraph(studio,p,time)}];
 const xMin=optics?-20:studio==='circuits'?-12:studio==='mechanics'?Math.max(0,time-8):0,xMax=optics?20:studio==='circuits'?12:studio==='thermal'?60:studio==='waves'?2:xMin+8;
 const marker=studio==='mechanics'?{x:time,y:p.amplitude*Math.cos(Math.sqrt(9.81/p.length)*time)}:studio==='thermal'?{x:Math.min(time,60),y:20+p.power*Math.min(time,60)/(p.mass*4184)}:studio==='circuits'?{x:p.voltage,y:p.voltage/p.resistance}:null;
 const yMin=studio==='mechanics'?-10:studio==='circuits'?-1.2:studio==='waves'?-2:0,yMax=studio==='thermal'?100:studio==='mechanics'?10:studio==='circuits'?1.2:studio==='waves'?2:1;
 const x=(v:number)=>35+(v-xMin)/(xMax-xMin)*235,y=(v:number)=>145-(v-yMin)/(yMax-yMin)*125;
 const title=optics?'Intensity vs Position':studio==='mechanics'?'Angle vs Time':studio==='circuits'?'Current vs Voltage':studio==='thermal'?'Temperature vs Time':'Pressure vs Position',xLabel=optics?'Position (mm)':studio==='circuits'?'Voltage (V)':studio==='waves'?'Position (m)':'Time (s)',unit=studio==='mechanics'?'°':studio==='circuits'?'A':studio==='thermal'?'°C':studio==='waves'?'Pa':'I / I₀';
 return <div className="el-graph"><h2>{title}</h2><svg viewBox="0 0 286 196" role="img" aria-label={`${title}, ${unit}`}><defs><pattern id={id+'grid'} width="12" height="12" patternUnits="userSpaceOnUse"><path d="M12 0H0V12" fill="none" stroke="#1b3c55" strokeWidth=".5"/></pattern><clipPath id={id+'clip'}><rect x="35" y="20" width="235" height="125"/></clipPath></defs><rect x="35" y="20" width="235" height="125" fill={`url(#${id}grid)`} stroke="#315a75" strokeWidth=".7"/>{[0,.5,1].map(t=><g key={t}><text x="26" y={148-t*125} textAnchor="end" fill="#aacbe6" fontSize="11">{(yMin+t*(yMax-yMin)).toFixed(yMax<=2?1:0)}</text><path d={`M35 ${145-t*125}H270`} stroke="#28516c" strokeWidth=".5"/></g>)}{[0,.25,.5,.75,1].map(t=><text key={t} x={35+t*235} y="166" textAnchor="middle" fill="#aacbe6" fontSize="11">{+(xMin+t*(xMax-xMin)).toFixed(1)}</text>)}<g clipPath={`url(#${id}clip)`}>{curves.map((c,i)=><path key={i} d={c.points.map((p,i)=>`${i?'L':'M'}${x(p.x).toFixed(2)} ${y(p.y).toFixed(2)}`).join(' ')} fill="none" stroke={c.color} strokeWidth="1.8"/>)}</g>{marker&&<circle data-current-reading="true" cx={x(marker.x)} cy={y(marker.y)} r="3.2" fill="#e0f8ff" stroke="#43baff" strokeWidth="1.5"/>}<text x="152" y="39" textAnchor="middle" fill="#c5e0f5" fontSize="10">{optics?opticalStatus:''}</text><text x="152" y="188" textAnchor="middle" fill="#c5e0f5" fontSize="12">{xLabel}</text><text x="37" y="13" fill="#8cb9da" fontSize="10">{unit}</text></svg></div>;
}
