import {useId,useRef,type PointerEvent} from 'react';import {LEVER_DROP,solveLever,type LeverInput,type LeverMotion} from '../lib/lever';
export function LeverScene({input,motion,zoom,labels,onChange}:{input:LeverInput;motion:LeverMotion;zoom:number;labels:boolean;onChange:(v:Partial<LeverInput>)=>void}){
 const id=useId().replace(/:/g,''),url=(n:string)=>`url(#${id+n})`,ref=useRef<SVGSVGElement>(null),drag=useRef<keyof LeverInput|null>(null),s=solveLever(input,motion),px=477+input.pivot*860,py=255,angle=-motion.angle*180/Math.PI;
 const point=(r:number,down=0)=>({x:px+860*(r*Math.cos(motion.angle)+down*Math.sin(motion.angle)),y:py+860*(-r*Math.sin(motion.angle)+down*Math.cos(motion.angle))});const a=point(s.rL,LEVER_DROP),b=point(s.rE),cx=477+input.load*860;
 const move=(e:PointerEvent<SVGElement>)=>{if(!drag.current||!ref.current)return;const matrix=ref.current.getScreenCTM();if(!matrix)return;const q=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());let x=q.x;if(drag.current!=='pivot')x=px+(q.x-px)*Math.cos(motion.angle)-(q.y-py)*Math.sin(motion.angle);onChange({[drag.current]:Math.max(-.5,Math.min(.5,(x-477)/860))})};
 const handle=(key:keyof LeverInput)=>({role:'slider',tabIndex:0,'aria-label':key==='load'?'Drag load':key==='pivot'?'Drag pivot':'Drag effort attachment','aria-valuemin':-.5,'aria-valuemax':.5,'aria-valuenow':input[key],onPointerDown:(e:PointerEvent<SVGGElement>)=>{drag.current=key;e.currentTarget.setPointerCapture(e.pointerId)},onPointerMove:move,onPointerUp:()=>{drag.current=null},onPointerCancel:()=>{drag.current=null},onKeyDown:(e:React.KeyboardEvent<SVGGElement>)=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();onChange({[key]:e.key==='Home'?-.5:e.key==='End'?.5:Math.max(-.5,Math.min(.5,input[key]+(e.key==='ArrowLeft'?-.01:.01)))})}}});
 const closeForces=Math.abs(a.x-b.x)<100;
 const auto=Math.max(1,(px+140-481)/459,(481-px+140)/459),view=962/zoom*auto,h=776/zoom*auto;
 return <svg ref={ref} className="tlv-apparatus" viewBox={`${481-view/2} ${388-h/2} ${view} ${h}`} role="img" aria-label="Interactive torque balance with draggable load, pivot and effort attachment"><defs><linearGradient id={id+'steel'}><stop stopColor="#202729"/><stop offset=".12" stopColor="#a5aca8"/><stop offset=".3" stopColor="#535b59"/><stop offset=".47" stopColor="#e3e2d8"/><stop offset=".59" stopColor="#737773"/><stop offset=".85" stopColor="#353e3f"/><stop offset="1" stopColor="#b9bcb3"/></linearGradient><linearGradient id={id+'beam'} x2="0" y2="1"><stop stopColor="#d0d0c6"/><stop offset=".35" stopColor="#888c87"/><stop offset=".65" stopColor="#a4a69d"/><stop offset="1" stopColor="#535a56"/></linearGradient><linearGradient id={id+'dark'} x2="0" y2="1"><stop stopColor="#414c4c"/><stop offset=".45" stopColor="#17201f"/><stop offset=".85" stopColor="#080d0e"/><stop offset="1" stopColor="#77827e"/></linearGradient><filter id={id+'grain'}><feTurbulence type="fractalNoise" baseFrequency=".62 .12" numOctaves="3" seed="21"/><feColorMatrix type="saturate" values="0"/><feComponentTransfer><feFuncA type="linear" slope=".13"/></feComponentTransfer><feComposite in2="SourceGraphic" operator="in"/><feBlend in="SourceGraphic" mode="soft-light"/></filter><marker id={id+'cyan'} viewBox="0 0 10 10" refX="5" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0 10 5 0 10z" fill="#37dffc"/></marker><marker id={id+'purple'} viewBox="0 0 10 10" refX="5" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0 10 5 0 10z" fill="#c681ff"/></marker></defs>
 <ellipse cx={px} cy="634" rx="144" ry="17" fill="#000" opacity=".55"/><path d={`M${px-124} 580h248l12 15v23h-272v-23z`} fill={url('dark')} stroke="#87918c"/><rect x={px-116} y="618" width="34" height="13" rx="3" fill={url('steel')}/><rect x={px+82} y="618" width="34" height="13" rx="3" fill={url('steel')}/><rect x={px-16} y="284" width="32" height="273" fill={url('steel')} stroke="#a8ada6"/><path d={`M${px-28} 497h56l18 90h-92z`} fill={url('dark')} stroke="#858c83" filter={url('grain')}/><circle cx={px} cy="568" r="10" fill={url('steel')} stroke="#8a8c7d"/><circle cx={px} cy="568" r="4" fill="#141b1b"/>
 <g transform={`rotate(${angle} ${px} ${py})`}><rect x="38" y="223" width="878" height="43" rx="1" fill={url('beam')} stroke="#c0c0b4" filter={url('grain')}/>{Array.from({length:101},(_,k)=>{const x=477+(k-50)*8.6;return <path key={k} d={`M${x} 240v${k%10===0?5:k%5===0?7:4}`} stroke="#27302e" strokeWidth={k%10===0?1.3:.7}/>})}{Array.from({length:11},(_,k)=>{const x=477+(k-5)*86;return <g key={k} className={k%2===0?"tlv-tick tlv-minor-label":"tlv-tick"}><circle cx={x} cy="250" r="5.5" fill="#11191b" stroke="#c5c8be"/><text x={x} y="237" textAnchor={k===0?"start":k===10?"end":"middle"} fill="#192523" fontSize="13">{((k-5)/10).toFixed(1)}</text></g>})}<text x="888" y="262" fill="#242e2d" fontSize="12">m</text>
 <g className="tlv-drag" {...handle('load')}><rect className="tlv-hit" x={cx-57} y="248" width="114" height="168" fill="transparent"/><path d={`M${cx} 250v${860*LEVER_DROP-18}`} stroke="#a8aca3" strokeWidth="7"/><circle cx={cx} cy="304" r="10" fill="none" stroke={url('steel')} strokeWidth="3"/>{Array.from({length:4},(_,k)=><g key={k}><rect x={cx-36} y={py+860*LEVER_DROP-35+k*18} width="72" height="16" fill={url('steel')} stroke="#d2d1bd"/><ellipse cx={cx} cy={py+860*LEVER_DROP-35+k*18} rx="36" ry="5" fill={url('beam')} stroke="#c4c5b8"/></g>)}</g>
 </g><g className="tlv-drag" {...handle('attachment')}><rect className="tlv-hit" x={b.x-57} y={b.y-10} width="114" height="114" fill="transparent"/><path opacity={closeForces?0:1} d={`M${b.x} ${b.y}v53`} stroke="#c3c5b6" strokeWidth="5"/><path opacity={closeForces?0:1} d={`M${b.x-9} ${b.y+54}q9-12 18 0l-3 31h-12z`} fill={url('steel')} stroke="#b0b7b0"/></g>
 <g className="tlv-drag" {...handle('pivot')}><circle className="tlv-pivot-hit" cx={px} cy={py} r="26" fill="transparent"/><path d={`M${px} 241l-36 74h72z`} fill={url('dark')} stroke="#a6aa9c" filter={url('grain')}/><circle cx={px} cy={py} r="13" fill="#236ca0" stroke="#b4b9b1"/><circle cx={px-25} cy="306" r="2.5" fill="#ddd9bf"/><circle cx={px+25} cy="306" r="2.5" fill="#ddd9bf"/></g>
 {labels&&<><text x={a.x} y={a.y+71} textAnchor="middle" fill="#eff5fa" fontSize="22">10.0 N</text><path d={`M${b.x} ${closeForces?b.y-100:b.y+94}v42`} stroke="#c681ff" strokeWidth="3.4" markerEnd={url('purple')}/><text x={b.x} y={closeForces?b.y-118:b.y+171} textAnchor="middle" fill="#e0b4ff" fontSize="23">{input.effort.toFixed(1)} N</text>{[[a.x,160,'cyan',Math.abs(s.armL)],[b.x,s.armL*s.armE<0?160:115,'purple',Math.abs(s.armE)]].map(([x,y,color,value])=><g key={String(color)} stroke={color==='cyan'?'#37dffc':'#c681ff'}><path d={`M${x} ${Number(y)+10}V${Number(y)+85}M${px} ${Number(y)+10}V${Number(y)+85}`} strokeDasharray="4 4" opacity=".7"/><path d={`M${x} ${y}H${px}`} markerStart={url(String(color))} markerEnd={url(String(color))}/><text x={(Number(x)+px)/2} y={Number(y)-15} fill={color==='cyan'?'#37dffc':'#c681ff'} stroke="none" textAnchor="middle" fontSize="20">{Number(value).toFixed(3)} m</text></g>)}</>}
 {motion.stopped&&<text x="481" y="54" textAnchor="middle" fill="#f0c681" fontSize="15">TRAVEL STOP • AXLE LATCHED</text>}
 </svg>
}
