import {useId,useLayoutEffect,useRef,useState,type PointerEvent} from 'react';
import {positionSamples,positionState,type PositionInput} from '../lib/positionTime';
export function PositionTimeGraph({input,time,baseTime,tangent,onTime,onBase}:{input:PositionInput;time:number;baseTime:number;tangent:boolean;onTime:(t:number)=>void;onBase:(t:number)=>void}){
 const host=useRef<HTMLElement>(null),svg=useRef<SVGSVGElement>(null),drag=useRef(false),[width,setWidth]=useState(665),id=useId().replace(/:/g,'');useLayoutEffect(()=>{const el=host.current;if(!el)return;const resize=()=>setWidth(el.clientWidth);resize();const r=new ResizeObserver(resize);r.observe(el);return()=>r.disconnect()},[]);
 const height=412,left=width<430?54:75,right=width-15,top=20,bottom=height-52,points=positionSamples(input),current=positionState(input,time),first=positionState(input,baseTime),min=Math.min(-.5,Math.floor(Math.min(...points.map(p=>p.x))*2)/2-.5),max=Math.max(3,Math.ceil(Math.max(...points.map(p=>p.x))*2)/2+.5),gx=(t:number)=>left+t/input.window*(right-left),gy=(x:number)=>bottom-(x-min)/(max-min)*(bottom-top),tipWidth=width<430?148:160,tipX=Math.min(right-tipWidth-5,Math.max(left+5,gx(time)+18)),rawTipY=Math.max(top+12,Math.min(bottom-115,gy(current.x)-105)),relationY=points.some(p=>gx(p.time)>right-178&&gy(p.x)>bottom-110)?top+12:bottom-100,tipY=tipX+tipWidth>right-178&&rawTipY+83>relationY&&rawTipY<relationY+89?(relationY===top+12?top+112:bottom-195):rawTipY,yStep=max-min>5?1:.5;
 const select=(e:PointerEvent<SVGSVGElement>)=>{const el=svg.current;if(!el)return;const point=el.createSVGPoint();point.x=e.clientX;point.y=e.clientY;const matrix=el.getScreenCTM();if(!matrix)return;const t=Math.max(0,Math.min(input.window,(point.matrixTransform(matrix.inverse()).x-left)/(right-left)*input.window));(e.shiftKey?onBase:onTime)(Math.round(t*100)/100)};
 return <section ref={host} className="ptm-graph ptm-panel"><header><h2>Position vs. Time</h2><div><span><i/>Position x(t)</span><span><b/>Tangent (slope = v)</span></div></header><svg ref={svg} viewBox={`0 0 ${width} ${height}`} style={{height}} role="slider" tabIndex={0} aria-label="Graph time; Shift selects first displacement point" aria-valuemin={0} aria-valuemax={input.window} aria-valuenow={time} aria-valuetext={`${time.toFixed(2)} seconds, position ${current.x.toFixed(2)} metres`} onPointerDown={e=>{drag.current=true;e.currentTarget.setPointerCapture(e.pointerId);select(e)}} onPointerMove={e=>{if(drag.current)select(e)}} onPointerUp={e=>{drag.current=false;e.currentTarget.releasePointerCapture(e.pointerId)}} onPointerCancel={()=>{drag.current=false}} onKeyDown={e=>{let t=e.shiftKey?baseTime:time;if(e.key==='Home')t=0;else if(e.key==='End')t=input.window;else if(e.key==='ArrowRight'||e.key==='ArrowUp')t+=.1;else if(e.key==='ArrowLeft'||e.key==='ArrowDown')t-=.1;else return;e.preventDefault();(e.shiftKey?onBase:onTime)(Math.max(0,Math.min(input.window,t)))}}>
 <defs><clipPath id={`${id}clip`}><rect x={left} y={top} width={right-left} height={bottom-top}/></clipPath></defs>
 {Array.from({length:Math.floor((max-min)/yStep)+1},(_,k)=>min+k*yStep).map(x=><g key={x}><path d={`M${left} ${gy(x)}H${right}`} stroke="#17364a"/><text x={left-11} y={gy(x)+4} textAnchor="end">{x.toFixed(1)}</text></g>)}{Array.from({length:Math.floor(input.window/(width<430?2:1))+1},(_,k)=>k*(width<430?2:1)).map(t=><g key={t}><path d={`M${gx(t)} ${top}V${bottom}`} stroke="#17364a"/><text x={gx(t)} y={bottom+25} textAnchor="middle">{t}</text></g>)}<path d={`M${left} ${top}V${bottom}H${right}`} fill="none" stroke="#9ab5cf"/>
 <g clipPath={`url(#${id}clip)`}><path d={points.map((p,k)=>`${k?'L':'M'}${gx(p.time)},${gy(p.x)}`).join(' ')} fill="none" stroke="#19b9f7" strokeWidth="2.7"/>{tangent&&<path d={`M${gx(Math.max(0,time-3))} ${gy(current.x+current.v*(Math.max(0,time-3)-time))}L${gx(Math.min(input.window,time+3))} ${gy(current.x+current.v*(Math.min(input.window,time+3)-time))}`} stroke="#8265ff" strokeWidth="2" strokeDasharray="8 5"/>}<path d={`M${gx(time)} ${top}V${bottom}`} stroke="#86b5e1" strokeDasharray="4 5" opacity=".8"/></g><circle cx={gx(baseTime)} cy={gy(first.x)} r="4" fill="#051626" stroke="#9bcafa"/><circle cx={gx(time)} cy={gy(current.x)} r="6" fill="#0ab5ff" stroke="#e5f6ff" strokeWidth="1.4"/>
 <g className="ptm-graph-tip" transform={`translate(${tipX},${tipY})`}><rect width={tipWidth} height="83" rx="5" fill="#031321" stroke="#285576"/><text x="12" y="22">t = {time.toFixed(2)} s</text><text x="12" y="45">x = {current.x.toFixed(2)} m</text><text x="12" y="68">slope (v) = {current.v.toFixed(2)} m/s</text></g>
 <g className="ptm-graph-relation" transform={`translate(${right-178},${relationY})`}><rect width="174" height="89" rx="5" fill="#031321" stroke="#285576"/><text x="87" y="31" textAnchor="middle">v = dx / dt</text><text x="87" y="68" textAnchor="middle">Δx = x(t₂) − x(t₁)</text></g><text x={(left+right)/2} y={height-6} textAnchor="middle">Time, t (s)</text><text transform={`translate(20 ${(top+bottom)/2}) rotate(-90)`} textAnchor="middle">Position, x (m)</text></svg></section>
}
