import {useEffect,useRef,useState} from 'react';
import {relativeMotionSolution,relativeMotionState,type RelativeMotionInput} from '../lib/relativeMotion';
export const relativeNumber=(n:number,d=1)=>Math.abs(n)>=10000?n.toExponential(1):Math.abs(n)<1e-9?(0).toFixed(d):n.toFixed(d);
function useWidth(initial:number){const ref=useRef<HTMLDivElement>(null),[width,setWidth]=useState(initial);useEffect(()=>{const o=new ResizeObserver(e=>setWidth(e[0].contentRect.width));if(ref.current)o.observe(ref.current);return()=>o.disconnect()},[]);return{ref,width}}
function Arrows({id}:{id:string}){return <defs>{[['b','#48ffa5'],['c','#1dbbff'],['g','#e068ff']].map(([key,color])=><marker key={key} id={id+key} markerWidth="9" markerHeight="9" refX="8" refY="4.5" orient="auto" markerUnits="userSpaceOnUse"><path d="M0 0L9 4.5L0 9Z" fill={color}/></marker>)}</defs>}
export function RelativeRiverScene({input,time,zoom,vectors,flow}:{input:RelativeMotionInput;time:number;zoom:number;vectors:boolean;flow:boolean}){
 const {ref,width}=useWidth(944),W=width*572/(ref.current?.clientHeight||572),H=572,s=relativeMotionSolution(input),p=relativeMotionState(input,time),duration=s.crossingTime??60,endX=s.groundX*duration;
 const low=Math.min(0,endX),high=Math.max(300,endX),sx=(W-180)/(high-low),sy=H*.72/300,x=(n:number)=>90+(n-low)*sx,y=(n:number)=>H*.86-n*sy,cx=x(p.x),cy=y(p.y);
 const scale=Math.max(0,Math.min(30,170/Math.max(1,input.boat,input.current,s.groundSpeed),(cy-28)/Math.max(1,s.boatY),(W-cx-25)/Math.max(1,s.groundX,s.boatX,input.current),(cx-25)/Math.max(1,-s.groundX,-s.boatX)));
 const endB=[cx+s.boatX*scale,cy-s.boatY*scale],endC=[cx+input.current*scale,cy],endG=[cx+s.groundX*scale,cy-s.groundY*scale];
 const camera=zoom===1?'':`translate(${W/2} ${H/2}) scale(${zoom}) translate(${-cx} ${-cy})`,barBase=10**Math.floor(Math.log10(210/sx)),bar=Math.floor(210/sx/barBase)*barBase,barStart=W-35-bar*sx,barUnit=bar>=1000?1000:1;
 return <div className="rvm-river" ref={ref} aria-label={`Boat at downstream ${relativeNumber(p.x)} metres, across ${relativeNumber(p.y)} metres`}><img src="/assets/relative-motion/river.png" alt=""/><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Top view of river crossing, boat and velocity vectors"><Arrows id="rvm-scene-"/><g transform={camera}><line x1="0" y1={y(300)} x2={W} y2={y(300)} stroke="#c9edf9" strokeDasharray="6 6"/><line x1="0" y1={y(0)} x2={W} y2={y(0)} stroke="#c9edf9" strokeDasharray="6 6"/><path d={`M${x(0)} ${y(0)}L${x(endX)} ${y(s.crossingTime===null?0:300)}`} fill="none" stroke="#e28dff" strokeWidth="1.5" strokeDasharray="4 8" opacity=".65"/>
 {flow&&input.current>0&&Array.from({length:16},(_,i)=>{const offset=(input.current*time*2)%80,px=60+(i%4)*90+offset,py=145+Math.floor(i/4)*95;return <path key={i} d={`M${px} ${py}h48m-6 -4l6 4l-6 4`} fill="none" stroke="#33caff" strokeWidth="1.5" opacity=".7"/>})}
 {vectors&&<>{input.boat>0&&<line x1={cx} y1={cy} x2={endB[0]} y2={endB[1]} stroke="#48ffa5" strokeWidth="3" markerEnd="url(#rvm-scene-b)"/>}{input.current>0&&<line x1={cx} y1={cy} x2={endC[0]} y2={endC[1]} stroke="#1dbbff" strokeWidth="3" markerEnd="url(#rvm-scene-c)"/>}{s.groundSpeed>1e-8&&<line x1={cx} y1={cy} x2={endG[0]} y2={endG[1]} stroke="#e068ff" strokeWidth="3" markerEnd="url(#rvm-scene-g)"/>}<path d={`M${endB[0]} ${endB[1]}L${endG[0]} ${endG[1]}L${endC[0]} ${endC[1]}`} fill="none" stroke="#d2beec" strokeDasharray="5 6"/><text x={Math.min(W-65,endB[0]-45)} y={Math.max(50,endB[1]-15)} fill="#58ffaf">vᵦ</text><text x={Math.min(W-55,endC[0]+4)} y={endC[1]+25} fill="#3dcaff">v꜀</text><text x={Math.min(W-50,endG[0]+5)} y={Math.max(45,endG[1]-9)} fill="#e88aff">vɢ</text></>}
 <g transform={`translate(${cx} ${cy}) rotate(${input.heading})`}><image href="/assets/relative-motion/boat.png" x="-36" y="-54" width="72" height="108"/></g><circle cx={cx} cy={cy} r="3" fill="white"/>
 </g><text x={W-100} y="57" fill="white">Far Shore</text><text x="80" y="540" fill="white">Near Shore</text><g transform="translate(26 474)" stroke="white" fill="white"><path d="M0 0v-48m-4 7l4-7l4 7M-5-5H42m-7-4l7 4l-7 4" fill="none"/><text x="-3" y="-55" stroke="none">N</text><text x="45" y="-2" stroke="none">E</text></g><line x1={barStart} y1="534" x2={W-35} y2="534" stroke="white"/>{[0,1,2,3,4].map(i=><g key={i}><line x1={barStart+i*bar*sx/4} y1="529" x2={barStart+i*bar*sx/4} y2="540" stroke="white"/><text x={barStart+i*bar*sx/4} y="554" textAnchor="middle" fill="white">{relativeNumber(bar*i/4/barUnit,Number.isInteger(bar*i/4/barUnit)?0:1)}</text></g>)}<text x={W-35} y="520" textAnchor="end" fill="white">{barUnit===1000?'km':'m'}</text></svg><span className="rvm-view-label">Top view · shore frame · not to scale</span><small>Boat enlarged · heading {input.heading}° from north{zoom>1?' · zoom follows boat':''}</small></div>
}
export function RelativeVectorDiagram({input}:{input:RelativeMotionInput}){const s=relativeMotionSolution(input),scale=Math.min(145/Math.max(1,input.boat,input.current,s.groundSpeed),180/Math.max(1,Math.max(0,s.boatX,s.groundX,input.current)-Math.min(0,s.boatX,s.groundX))),low=Math.min(0,s.boatX,s.groundX),ox=35-low*scale,oy=185,bx=ox+s.boatX*scale,by=oy-s.boatY*scale,gx=ox+s.groundX*scale;return <section className="rvm-panel rvm-vector"><h2>VECTOR DIAGRAM <small>(COMMON VECTOR SCALE)</small></h2><div><svg viewBox="0 0 250 225" role="img" aria-label={`Ground vector equals boat plus current, heading ${input.heading} degrees from north`}><Arrows id="rvm-diagram-"/><line x1={ox} y1={oy} x2={ox} y2="25" stroke="#8fb3c8" strokeDasharray="3 5"/><text x={ox-10} y="17" fill="#b1d4e9">N</text>{input.boat>0&&<line x1={ox} y1={oy} x2={bx} y2={by} stroke="#48ffa5" strokeWidth="3" markerEnd="url(#rvm-diagram-b)"/>}{input.current>0&&<line x1={ox} y1={oy} x2={ox+input.current*scale} y2={oy} stroke="#1dbbff" strokeWidth="3" markerEnd="url(#rvm-diagram-c)"/>}{s.groundSpeed>1e-8&&<line x1={ox} y1={oy} x2={gx} y2={by} stroke="#e068ff" strokeWidth="3" markerEnd="url(#rvm-diagram-g)"/>}<path d={`M${bx} ${by}H${gx}V${oy}`} fill="none" stroke="#8fc1d8" strokeDasharray="5 5"/><text x="30" y="215" fill="#bfd9f0">θ = {input.heading}° from N</text></svg><ul><li><b style={{color:'#48ffa5'}}>⟶</b><span>Boat: {input.boat.toFixed(1)} m/s<small>relative to water</small></span></li><li><b style={{color:'#1dbbff'}}>⟶</b><span>Current: {input.current.toFixed(1)} m/s<small>relative to shore</small></span></li><li><b style={{color:'#e068ff'}}>⟶</b><span>Ground: {s.groundSpeed.toFixed(2)} m/s<small>relative to shore</small></span></li></ul></div></section>}
export function RelativeCrossingGraph({input,time,onTime}:{input:RelativeMotionInput;time:number;onTime:(n:number)=>void}){
 const{ref,width}=useWidth(350),s=relativeMotionSolution(input),duration=s.crossingTime??60,p=relativeMotionState(input,time),endX=s.groundX*duration,lo=Math.min(0,endX)*1.15,hi=Math.max(20,endX)*1.15,left=57,right=Math.max(200,width)-20,top=32,bottom=174,x=(n:number)=>left+(n-lo)/(hi-lo)*(right-left),y=(n:number)=>bottom-n/300*(bottom-top);
 const choose=(clientX:number,clientY:number,el:SVGSVGElement)=>{const rect=el.getBoundingClientRect(),px=clientX-rect.left,py=clientY-rect.top,dx=x(endX)-x(0),dy=s.crossingTime===null?0:y(300)-y(0),fraction=(dx*dx+dy*dy)>0?((px-x(0))*dx+(py-y(0))*dy)/(dx*dx+dy*dy):0;onTime(Math.max(0,Math.min(duration,duration*fraction)))};
 return <section className="rvm-panel rvm-crossing" ref={ref}><h2>CROSSING PATH <small>(RELATIVE TO SHORE)</small></h2><svg width="100%" height="230" role="slider" tabIndex={0} aria-label="Crossing observation time" aria-valuemin={0} aria-valuemax={duration} aria-valuenow={time} onKeyDown={e=>{if(['Home','End','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();onTime(e.key==='Home'?0:e.key==='End'?duration:Math.max(0,Math.min(duration,time+(e.key==='ArrowRight'?1:-1)*duration/100)))}}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);choose(e.clientX,e.clientY,e.currentTarget)}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))choose(e.clientX,e.clientY,e.currentTarget)}}>
 {[0,150,300].map(v=><g key={v}><line x1={left} x2={right} y1={y(v)} y2={y(v)} stroke={v===300?'#87b5ca':'#173b50'} strokeDasharray={v===300?'5 4':undefined}/><text x={left-8} y={y(v)+4} textAnchor="end">{v}</text></g>)}{[0,1,2,3,4].map(i=>{const v=lo+(hi-lo)*i/4;return <g key={i}><line x1={x(v)} x2={x(v)} y1={top} y2={bottom+4} stroke="#16394c"/><text x={x(v)} y={bottom+19} textAnchor="middle">{relativeNumber(v,0)}</text></g>})}<line x1={left} x2={left} y1={top-8} y2={bottom} stroke="#b0cfe1"/><line x1={left} x2={right} y1={bottom} y2={bottom} stroke="#b0cfe1"/><path d={`M${x(0)} ${y(0)}L${x(endX)} ${y(s.crossingTime===null?0:300)}`} stroke="#e068ff" strokeWidth="2" fill="none"/><circle cx={x(p.x)} cy={y(p.y)} r="4" fill="#d1a0ff" stroke="#eff8ff"/><text x={right} y="21" textAnchor="end">Far Shore</text><text x={left+8} y="55">t = {relativeNumber(time)} s</text><text x={left+8} y="73">x = {relativeNumber(p.x)} m</text><text x={(left+right)/2} y="222" textAnchor="middle">Downstream (m)</text><text transform="translate(15 113) rotate(-90)" textAnchor="middle">Across river (m)</text></svg></section>
}
