import { useId } from 'react';
import { spherometerProfile, spherometerState, type SpherometerInput } from '../lib/spherometer';
export function SpherometerScene({ input, zoom=1, sample=false }: { input:SpherometerInput; zoom?:number; sample?:boolean }) {
  const s=spherometerState(input),id=useId().replace(/:/g,''),u=Math.min(8.5,260/s.r),cx=380,cy=425;
  const P=(x:number,y:number,z:number)=>({x:cx+x*u,y:cy+y*u*.32-z*u});
  const legs=[-90,30,150].map(degrees=>{const a=degrees*Math.PI/180;return{x:s.r*Math.cos(a),y:s.r*Math.sin(a)};});
  const axis=P(0,0,24),tip=P(0,0,s.signedHeight),knob=P(0,0,46+s.signedHeight),barrel=P(0,0,34),rx=s.r*u,ry=rx*.32;
  const leg=(index:number)=>{const l=legs[index],foot=P(l.x,l.y,0),top=P(l.x,l.y,24);return <g key={index}><ellipse cx={foot.x} cy={foot.y+6} rx="23" ry="8" fill="#052027" opacity=".45"/><path d={`M${top.x-12} ${top.y}h24v${foot.y-top.y-8}l-12 12-12-12z`} fill={`url(#${id}metal)`} stroke="#91a4a7"/><rect x={top.x-22} y={top.y-10} width="44" height={9*u} rx="9" fill={`url(#${id}metal)`}/><rect x={top.x-21} y={top.y-8} width="42" height={9*u-3} rx="8" fill={`url(#${id}steel)`} opacity=".25"/><ellipse cx={top.x} cy={top.y-10} rx="22" ry="7" fill={`url(#${id}steel)`}/>{Array.from({length:9},(_,n)=><path key={n} d={`M${top.x-13} ${top.y+9*u+n*(foot.y-top.y-9*u-8)/8}h26`} stroke="#25383c" strokeWidth="2"/>)}<rect x={top.x-16} y={top.y-34} width="32" height="22" rx="4" fill={`url(#${id}metal)`}/>{Array.from({length:9},(_,n)=><path key={n} d={`M${top.x-13+n*3} ${top.y-32}v18`} stroke="#273b41"/>)}<rect x={top.x-16} y={top.y-33} width="32" height="21" rx="3" fill={`url(#${id}knurl)`}/><ellipse cx={top.x} cy={top.y-34} rx="16" ry="5" fill={`url(#${id}steel)`}/></g>;};
  return <svg className="sph-apparatus" viewBox={sample?`${cx-rx-20} ${cy-ry-15} ${2*rx+40} ${2*ry+60}`:`${380-380/zoom} ${280-280/zoom} ${760/zoom} ${560/zoom}`} role="img" aria-label={`${input.surface} spherical surface, sagitta ${s.h.toFixed(3)} millimeters and three feet on radius ${s.r.toFixed(2)} millimeters`}>
    <defs><pattern id={`${id}steel`} width="350" height="220" patternUnits="userSpaceOnUse"><image href="/assets/vernier-caliper/brushed-steel.png" width="350" height="220" preserveAspectRatio="none"/></pattern><pattern id={`${id}knurl`} width="5" height="7" patternUnits="userSpaceOnUse"><path d="M-2 0L5 7M3 0L10 7M-2 7L5 0M3 7L10 0" stroke="#e1e6df" strokeWidth=".7" opacity=".38"/><path d="M-1 0L6 7M-1 7L6 0" stroke="#17262b" strokeWidth="1" opacity=".7"/></pattern><filter id={`${id}soft`} x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="2.5"/></filter><linearGradient id={`${id}metal`}><stop stopColor="#22343b"/><stop offset=".26" stopColor="#bccaca"/><stop offset=".44" stopColor="#e3e8e4"/><stop offset=".75" stopColor="#6a7c82"/><stop offset="1" stopColor="#233c45"/></linearGradient><linearGradient id={`${id}glass`} x2="0" y2="1"><stop stopColor="#d0f9ff" stopOpacity=".26"/><stop offset=".3" stopColor="#17484f" stopOpacity=".43"/><stop offset=".63" stopColor="#b9ffff" stopOpacity=".45"/><stop offset="1" stopColor="#06353c" stopOpacity=".85"/></linearGradient><pattern id={`${id}cast`} width="160" height="160" patternUnits="userSpaceOnUse"><image href="/assets/micrometer/hammered-enamel.png" width="160" height="160"/></pattern><linearGradient id={`${id}reflection`} x1="0" y1="0" x2="1" y2="1"><stop stopColor="#efffff" stopOpacity=".02"/><stop offset=".45" stopColor="#d7f3ff" stopOpacity=".2"/><stop offset=".6" stopColor="#96bbcf" stopOpacity=".03"/><stop offset="1" stopColor="#deffff" stopOpacity=".25"/></linearGradient><radialGradient id={`${id}top`}><stop stopColor="#91d2dc" stopOpacity=".2"/><stop offset=".7" stopColor="#2a5861" stopOpacity=".1"/><stop offset="1" stopColor="#b0f3f3" stopOpacity=".55"/></radialGradient></defs>
    <ellipse cx={cx} cy={cy+38} rx={rx+14} ry={ry+8} fill="#071c24" opacity=".6"/>
    <path d={`M${cx-rx} ${cy}a${rx} ${ry} 0 0 0 ${rx*2} 0v30a${rx} ${ry} 0 0 1 ${-rx*2} 0z`} fill={`url(#${id}glass)`} stroke="#84bfc1" strokeOpacity=".6"/>
    <ellipse cx={cx} cy={cy} rx={rx} ry={ry} fill={`url(#${id}top)`} stroke="#bfe9e8" strokeWidth="2"/>
    <ellipse cx={cx} cy={cy-s.signedHeight*u} rx={rx*.92} ry={ry*.92} fill={`url(#${id}reflection)`}/>
    {[[-.65,-.5,.12,.07],[.56,-.28,.17,.10],[.33,.49,.07,.045]].map(([x,y,w,h],i)=><ellipse key={i} cx={cx+x*rx} cy={cy+y*ry-spherometerProfile(input,s.r*Math.hypot(x,y))*u} rx={rx*w} ry={ry*h} fill="#e5ffff" opacity=".45" filter={`url(#${id}soft)`} transform={`rotate(-14 ${cx+x*rx} ${cy+y*ry})`}/>)}
    <ellipse cx={cx} cy={cy+14} rx={rx*.98} ry={ry*.98} fill="none" stroke="#e0f8f8" strokeOpacity=".27" strokeWidth="2"/>
    <path d={`M${cx-rx*.92} ${cy-ry*.22}a${rx*.94} ${ry*.92} 0 0 1 ${rx*1.62} ${-ry*.5}`} fill="none" stroke="#e5ffff" strokeWidth="5" opacity=".5"/>
    {!sample&&<>
      {leg(0)}
      {legs.map((l,i)=>{const p=P(l.x,l.y,24);return <g key={i}><path d={`M${axis.x} ${axis.y+10}L${p.x} ${p.y+10}`} stroke="#1a2b33" strokeWidth="53" strokeLinejoin="round"/><path d={`M${axis.x} ${axis.y}L${p.x} ${p.y}`} stroke={`url(#${id}steel)`} strokeWidth="37" strokeLinecap="round"/><path d={`M${axis.x} ${axis.y+4}L${p.x} ${p.y+4}`} stroke={`url(#${id}cast)`} strokeOpacity=".85" strokeWidth="32"/><path d={`M${axis.x} ${axis.y-18}L${p.x} ${p.y-18}`} stroke="#c5d1d1" strokeWidth="1"/></g>;})}
      <rect x={cx-11} y={axis.y+8} width="22" height={Math.max(3,tip.y-axis.y-12)} fill={`url(#${id}metal)`}/><path d={`M${cx-9} ${tip.y-9}l9 10 9-10`} fill="#b6cdd1" stroke="#314a52"/>
      {leg(1)}{leg(2)}
      <ellipse cx={cx} cy={axis.y-12} rx="37" ry="13" fill={`url(#${id}metal)`}/><rect x={cx-29} y={barrel.y} width="58" height={axis.y-barrel.y-10} fill={`url(#${id}steel)`} stroke="#bdccce"/><ellipse cx={cx} cy={barrel.y} rx="29" ry="9" fill={`url(#${id}metal)`}/>
      <g transform={`translate(0 ${barrel.y}) scale(1 ${u/8.5}) translate(0 ${-barrel.y})`}>{Array.from({length:100},(_,n)=>{const angle=(n/100-s.signedHeight)*2*Math.PI,depth=Math.cos(angle);if(depth<0)return null;const x=cx+27*Math.sin(angle);return <g key={n} opacity={.35+.65*depth}><path d={`M${x} ${barrel.y+34}v${n%10===0?20:n%5===0?13:7}`} stroke="#172a31" strokeWidth=".8"/>{n%10===0&&depth>.72&&<text x={x} y={barrel.y+27} textAnchor="middle" fontSize="9" fill="#172a31">{n}</text>}</g>;})}
      <path d={`M${cx} ${barrel.y+57}v15m-4-11l4-4 4 4`} stroke="#172a31" fill="none"/></g>
      <rect x={cx-9} y={knob.y+14} width="18" height={barrel.y-knob.y-11} fill={`url(#${id}metal)`}/>{Array.from({length:15},(_,n)=><path key={n} d={`M${cx-11} ${knob.y+20+n*5}l22-2`} stroke="#283b44" strokeWidth="2"/>)}
      <rect x={cx-36} y={knob.y-11} width="72" height="36" rx="7" fill={`url(#${id}metal)`}/>{Array.from({length:20},(_,n)=><path key={n} d={`M${cx-33+n*3.4} ${knob.y-8}l-4 30`} stroke="#2e4149"/>)}<rect x={cx-35} y={knob.y-10} width="70" height="34" rx="6" fill={`url(#${id}knurl)`}/><ellipse cx={cx} cy={knob.y-11} rx="36" ry="9" fill={`url(#${id}steel)`}/><path d={`M${cx-20} ${knob.y-15}l40 8m-40 0l40-8`} stroke="#41545f"/>
    </>}
  </svg>;
}

export function SpherometerGeometry({ input, top=false }: { input:SpherometerInput; top?:boolean }) {
  const s=spherometerState(input), id=useId().replace(/:/g,'');
  if(top)return <svg className="sph-geometry" viewBox="0 0 350 215" role="img" aria-label="Three feet equally spaced at 120 degrees"><defs><radialGradient id={`${id}dial`}><stop stopColor="#eef3ef"/><stop offset=".45" stopColor="#75858a"/><stop offset=".8" stopColor="#a8b6b7"/><stop offset="1" stopColor="#34434c"/></radialGradient><pattern id={`${id}arm`} width="80" height="80" patternUnits="userSpaceOnUse"><image href="/assets/micrometer/hammered-enamel.png" width="80" height="80"/></pattern></defs><circle cx="175" cy="110" r="86" fill="none" stroke="#5a7c91"/><circle cx="175" cy="110" r="72" fill="none" stroke="#a8cad9" strokeDasharray="4 5"/>{[-90,30,150].map(angle=>{const a=angle*Math.PI/180,x=175+72*Math.cos(a),y=110+72*Math.sin(a);return <g key={angle}><path d={`M175 110L${x} ${y}`} stroke={`url(#${id}arm)`} strokeWidth="20"/><path d={`M175 110L${x} ${y}`} stroke="#d1dadd" strokeWidth="1"/><circle cx={x} cy={y} r="10" fill={`url(#${id}dial)`} stroke="#d4e2e6"/></g>;})}<circle cx="175" cy="110" r="20" fill={`url(#${id}dial)`} stroke="#dcecf1"/><text x="68" y="70" fill="#accbdf" fontSize="12">120°</text><text x="250" y="70" fill="#accbdf" fontSize="12">120°</text><text x="160" y="207" fill="#accbdf" fontSize="12">120°</text></svg>;
  const baseline=125,u=180/s.r,magnification=Math.min(10,45/(Math.max(s.h,.001)*u)),points=Array.from({length:81},(_,i)=>{const x=-s.r+i*2*s.r/80;return `${250+x*u},${baseline-spherometerProfile(input,Math.abs(x))*u*magnification}`;}).join(' '),centre=baseline-s.signedHeight*u*magnification;
  return <svg className="sph-geometry" viewBox="0 0 500 215" role="img" aria-label={`Side geometry; vertical sagitta enlarged ${magnification.toFixed(1)} times; signed height ${s.signedHeight.toFixed(3)} millimeters`}><rect x="61" y="53" width="378" height="15" rx="3" fill="#193041" stroke="#c3ddea"/><path d="M70 68v57m360-57v57" stroke="#c3ddea" strokeWidth="3"/><rect x="62" y="95" width="16" height="21" fill="#183343" stroke="#c3ddea"/><rect x="422" y="95" width="16" height="21" fill="#183343" stroke="#c3ddea"/><rect x="243" y="22" width="14" height="47" rx="3" fill="#193041" stroke="#c3ddea"/><path d="M250 69V199" stroke="#89b1c8" strokeDasharray="3 4"/><path d={`M250 69V${centre}`} stroke="#c3ddea" strokeWidth="4"/><path d="M60 125H440" stroke="#6c8da3" strokeDasharray="4 4"/><polyline points={points} fill="none" stroke="#82d8fb" strokeWidth="2"/><path d={`M267 ${baseline}V${centre}`} stroke="#6ce0ff"/><text x="276" y={(baseline+centre)/2} fill="#c3e6f5" fontSize="15">h</text><path d="M70 163H250m-180-4v8m180-8v8" stroke="#a2bfcc"/><text x="155" y="180" fill="#cae3ef" fontSize="15">r</text><text x="16" y="207" fill="#9bbfd7" fontSize="13">Vertical ×{magnification.toFixed(1)}; R extends beyond this view</text></svg>;
}
