import {useLayoutEffect,useRef,useState,type PointerEvent} from 'react';
import {velocityAreas,velocityState,type VelocityInput} from '../lib/velocityTime';
export function VelocityTimeGraph({input,time,area,equation,onArea,onEquation,onTime}:{input:VelocityInput;time:number;area:boolean;equation:boolean;onArea:(v:boolean)=>void;onEquation:(v:boolean)=>void;onTime:(v:number)=>void}){
 const host=useRef<HTMLElement>(null),drag=useRef(false),[width,setWidth]=useState(820);useLayoutEffect(()=>{const el=host.current;if(!el)return;const resize=()=>setWidth(el.clientWidth);resize();const observer=new ResizeObserver(resize);observer.observe(el);return()=>observer.disconnect()},[]);
 const height=370,left=width<450?70:74,right=width-20,top=15,bottom=height-51,end=velocityState(input,input.duration),state=velocityState(input,time),lo=Math.min(-1,Math.floor(Math.min(input.v0,end.v)-.5)),hi=Math.max(5,Math.ceil(Math.max(input.v0,end.v)+.5)),span=hi-lo,step=span>20?5:span>10?2:1,horizon=Math.max(5,input.duration),x=(t:number)=>left+t/horizon*(right-left),y=(v:number)=>bottom-(v-lo)/span*(bottom-top);
 const select=(e:PointerEvent<SVGSVGElement>)=>{const p=e.currentTarget.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const matrix=e.currentTarget.getScreenCTM();if(matrix)onTime(Math.round(Math.max(0,Math.min(input.duration,(p.matrixTransform(matrix.inverse()).x-left)/(right-left)*horizon))*100)/100)};
 return <section ref={host} className="vtm-panel vtm-graph"><header><h2>Velocity–Time Graph</h2><div><label><input type="checkbox" checked={area} onChange={e=>onArea(e.target.checked)}/>Show area (displacement)</label><label><input type="checkbox" checked={equation} onChange={e=>onEquation(e.target.checked)}/>Show equation</label></div></header><svg viewBox={`0 0 ${width} ${height}`} style={{height}} role="slider" tabIndex={0} aria-label="Graph observation time" aria-valuemin={0} aria-valuemax={input.duration} aria-valuenow={time} onPointerDown={e=>{drag.current=true;e.currentTarget.setPointerCapture(e.pointerId);select(e)}} onPointerMove={e=>{if(drag.current)select(e)}} onPointerUp={e=>{drag.current=false;e.currentTarget.releasePointerCapture(e.pointerId)}} onPointerCancel={()=>drag.current=false} onKeyDown={e=>{let t=time;if(e.key==='Home')t=0;else if(e.key==='End')t=input.duration;else if(['ArrowRight','ArrowUp'].includes(e.key))t+=.1;else if(['ArrowLeft','ArrowDown'].includes(e.key))t-=.1;else return;e.preventDefault();onTime(Math.max(0,Math.min(input.duration,t)))}}>
 {Array.from({length:Math.floor(horizon/(width<450?1:.5))+1},(_,i)=>i*(width<450?1:.5)).map(t=><g key={t}><path d={`M${x(t)} ${top}V${bottom}`} stroke="#214158"/>{Number.isInteger(t)&&<text x={x(t)} y={bottom+26} textAnchor="middle">{t===0?'0':t.toFixed(1)}</text>}</g>)}
 {Array.from({length:Math.floor(hi/step)-Math.ceil(lo/step)+1},(_,i)=>(Math.ceil(lo/step)+i)*step).map(v=><g key={v}><path d={`M${left} ${y(v)}H${right}`} stroke={v===0?'#86a7c5':'#214158'}/><text x={left-12} y={y(v)+4} textAnchor="end">{v===0?'0':v.toFixed(1)}</text></g>)}
 {area&&velocityAreas(input,time).map((a,i)=><path key={i} data-area={a.area.toFixed(6)} d={`M${x(a.first.time)} ${y(0)}L${x(a.first.time)} ${y(a.first.v)}L${x(a.last.time)} ${y(a.last.v)}L${x(a.last.time)} ${y(0)}Z`} fill={a.area<0?'#e99a5c':'#63c9f7'} fillOpacity=".23"/>)}
 <path d={`M${left} ${top}V${bottom}H${right}`} fill="none" stroke="#9bbfdf"/><path d={`M${x(0)} ${y(input.v0)}L${x(time)} ${y(state.v)}`} stroke="#61cfff" strokeWidth="2.7" fill="none"/><path d={`M${x(time)} ${top}V${bottom}`} stroke="#d3e6fa" strokeDasharray="7 5"/><circle cx={x(time)} cy={y(state.v)} r="5.5" fill="#4abafa" stroke="#e5f3ff" strokeWidth="1.5"/>
 <text className="vtm-value-label" x={Math.max(left+8,Math.min(right-120,x(time)+15))} y={Math.max(top+20,Math.min(bottom-10,y(state.v)-17))}>v = {state.v.toFixed(2)} m/s</text>{equation&&<g><rect x={left+10} y={top+8} width={Math.min(275,right-left-20)} height="39" rx="5" fill="#07182a" stroke="#375c79"/><text x={left+20} y={top+33}>v(t) = {input.v0.toFixed(2)} {input.acceleration<0?'−':'+'} {Math.abs(input.acceleration).toFixed(2)}t</text></g>}
 <text x={(left+right)/2} y={height-7} textAnchor="middle">Time, t (s)</text><text transform={`translate(15 ${(top+bottom)/2}) rotate(-90)`} textAnchor="middle">Velocity, v (m/s)</text></svg><p className="vtm-graph-help">Drag the graph to inspect time. Blue area adds; amber area subtracts.</p></section>
}
