import fs from "node:fs";
import vm from "node:vm";
import ts from "typescript";

const experimentSource = fs.readFileSync("src/lib/experiments.ts", "utf8").replace(/^import\s+[^\n]+;\s*$/gm, "");
const experimentJs = ts.transpileModule(experimentSource, {
  compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 },
}).outputText;

const sandbox = {
  exports: {},
  module: { exports: {} },
  console,
  createObject: (...args) => ({ createObjectArgs: args }),
  withScientificTrust: (experiment) => experiment,
};
sandbox.exports = sandbox.module.exports;
vm.createContext(sandbox);
vm.runInContext(experimentJs, sandbox);

const experiments = sandbox.module.exports.experiments ?? [];
const registrySource = fs.readFileSync("src/lib/experimentVisualizationSpecs.ts", "utf8");
const specBlocks = [...registrySource.matchAll(/\{\s*experimentId:\s*"([^"]+)",([\s\S]*?)\n\s*\},/g)].map((match) => {
  const body = match[2];
  return {
    experimentId: match[1],
    domain: body.match(/domain:\s*"([^"]+)"/)?.[1] ?? "",
    twoD: body.match(/twoD:\s*pane\("([^"]+)"/)?.[1] ?? "",
    threeD: body.match(/threeD:\s*pane\("([^"]+)"/)?.[1] ?? "",
    phaseAssigned: Number(body.match(/phaseAssigned:\s*(\d+)/)?.[1] ?? 0),
    visualIdentity: body.match(/visualIdentity:\s*"([^"]+)"/)?.[1] ?? "",
  };
});

const experimentIds = new Set(experiments.map((experiment) => experiment.id));
const specIds = new Set(specBlocks.map((spec) => spec.experimentId));
const missingSpecs = [...experimentIds].filter((id) => !specIds.has(id));
const unknownSpecs = [...specIds].filter((id) => !experimentIds.has(id));
const duplicateSpecs = specBlocks.map((spec) => spec.experimentId).filter((id, index, ids) => ids.indexOf(id) !== index);
const incompleteSpecs = specBlocks.filter((spec) => !spec.twoD || !spec.threeD).map((spec) => spec.experimentId);
const unphasedPending = specBlocks
  .filter((spec) => (isPending(spec.twoD) || isPending(spec.threeD)) && !spec.phaseAssigned)
  .map((spec) => spec.experimentId);

const byId = new Map(specBlocks.map((spec) => [spec.experimentId, spec]));
const rows = experiments.map((experiment) => ({ ...experiment, spec: byId.get(experiment.id) }));
const alreadySpecific = rows.filter(({ spec }) => spec && !isPending(spec.twoD) && !isPending(spec.threeD));
const needs2DOnly = rows.filter(({ spec }) => spec && isPending(spec.twoD) && !isPending(spec.threeD));
const needs3DOnly = rows.filter(({ spec }) => spec && !isPending(spec.twoD) && isPending(spec.threeD));
const needsBoth = rows.filter(({ spec }) => spec && isPending(spec.twoD) && isPending(spec.threeD));

const report = [
  "# Experiment Visualization Status",
  "",
  "Generated by `npm run audit:visualizations`.",
  "",
  `Total experiments: ${experiments.length}`,
  `Already specific: ${alreadySpecific.length}`,
  `Needs 2D only: ${needs2DOnly.length}`,
  `Needs 3D only: ${needs3DOnly.length}`,
  `Needs both: ${needsBoth.length}`,
  "",
  section("Already Specific", alreadySpecific),
  section("Needs 2D Only", needs2DOnly),
  section("Needs 3D Only", needs3DOnly),
  section("Needs Both 2D And 3D", needsBoth),
  phaseSection(rows),
].join("\n");

fs.writeFileSync("EXPERIMENT_VISUALIZATION_STATUS.md", report);

const failures = { missingSpecs, unknownSpecs, duplicateSpecs, incompleteSpecs, unphasedPending };
const ok = Object.values(failures).every((items) => items.length === 0);
console.log(`Visualization audit: ${ok ? "PASS" : "FAIL"}`);
console.log(`Experiments: ${experiments.length}`);
console.log(`Already specific: ${alreadySpecific.length}`);
console.log(`Needs 2D only: ${needs2DOnly.length}`);
console.log(`Needs 3D only: ${needs3DOnly.length}`);
console.log(`Needs both: ${needsBoth.length}`);
console.log("Report: EXPERIMENT_VISUALIZATION_STATUS.md");

if (!ok) {
  console.error(JSON.stringify(failures, null, 2));
  process.exit(1);
}

function isPending(status) {
  return status === "generic-fallback" || status === "pending-custom";
}

function section(title, items) {
  const lines = [`## ${title}`, "", "| Experiment | Domain | 2D | 3D | Phase |", "|---|---|---|---|---:|"];
  for (const { id, title: experimentTitle, category, spec } of items) {
    lines.push(`| \`${id}\` ${experimentTitle} | ${category} | ${spec.twoD} | ${spec.threeD} | ${spec.phaseAssigned || ""} |`);
  }
  return lines.join("\n");
}

function phaseSection(items) {
  const lines = ["## Assigned Phase", "", "| Phase | Experiments |", "|---:|---|"];
  const phases = [...new Set(items.map(({ spec }) => spec?.phaseAssigned).filter(Boolean))].sort((a, b) => a - b);
  for (const phase of phases) {
    const names = items
      .filter(({ spec }) => spec?.phaseAssigned === phase)
      .map(({ id, title }) => `\`${id}\` ${title}`)
      .join("<br>");
    lines.push(`| ${phase} | ${names} |`);
  }
  return lines.join("\n");
}
