import fs from "node:fs/promises";
import path from "node:path";
import vm from "node:vm";

const projectRoot = process.cwd();
const auditDirectory = path.join(projectRoot, "outputs", "physics-syllabus-audit-20260910");
const gapSource = path.join(projectRoot, "outputs", "physics-syllabus-gaps-20260903", "gap_data.json");
const workbookBuilder = path.join(auditDirectory, "build_audit.mjs");
const outputFile = path.join(projectRoot, "src", "data", "upcomingPhysicsContent.generated.ts");

const gapData = JSON.parse(await fs.readFile(gapSource, "utf8"));
const theory = gapData.gaps
  .filter((item) => !["Foundational", "Preparatory"].includes(item.stage))
  .map((item) => ({
    id: `upcoming-theory-${item.lessonId}`,
    kind: "theory",
    title: item.title,
    stage: item.stage,
    level: item.level,
    domain: item.category,
    subdomain: item.subcategory,
    scope: item.concepts,
    plannedLab: item.lab,
    nearestContent: String(item.near ?? "None").replace(/^\d+:\s*/, ""),
    coverage: item.coverage,
    priority: item.priority,
    frameworks: item.stage === "Middle" || item.stage === "Secondary"
      ? "AP SCERT · CBSE/NCERT · representative state boards"
      : item.stage === "Senior Secondary"
        ? "AP Intermediate · CBSE Physics 042 · representative state boards"
        : item.stage === "Undergraduate"
          ? "UGC model curriculum · DU · IISc representative programmes"
          : item.stage === "Postgraduate"
            ? "DU · IISc · CSIR representative programmes"
            : "UGC PhD regulations · IISc · institutional research training",
    sourceNames: item.sourceNames,
    sourceUrls: item.sourceUrls,
    availability: "upcoming",
  }));

const builderSource = await fs.readFile(workbookBuilder, "utf8");
const practicalStart = builderSource.indexOf("const practicals = [");
const practicalEnd = builderSource.indexOf("\n];\n\nconst frameworks", practicalStart);
if (practicalStart < 0 || practicalEnd < 0) throw new Error("Could not locate the audited practical-gap register.");
const practicalLiteral = builderSource.slice(practicalStart + "const practicals = ".length, practicalEnd + 2);
const practicalRows = vm.runInNewContext(practicalLiteral, Object.create(null));
const stageForPracticalLevel = (level) => {
  if (String(level).includes("Grades 6")) return "Middle";
  if (String(level).includes("Grades 9")) return "Secondary";
  if (String(level).includes("Class XI") || String(level).includes("Class XII")) return "Senior Secondary";
  if (String(level).includes("PhD")) return "Doctoral / Research";
  if (String(level).includes("PG")) return "Postgraduate";
  return "Undergraduate";
};
const practical = practicalRows.map((row) => ({
  id: `upcoming-lab-${String(row[0]).toLowerCase()}`,
  kind: "lab",
  title: row[3],
  stage: stageForPracticalLevel(row[1]),
  level: row[1],
  domain: "Practical Physics",
  subdomain: row[2],
  scope: row[6],
  plannedLab: row[3],
  nearestContent: row[4],
  coverage: row[5],
  priority: row[7],
  frameworks: row[2],
  sourceNames: row[2],
  sourceUrls: "See the audited source register in the Physics syllabus gap workbook.",
  roadmap: row[8],
  availability: "upcoming",
}));

const fileBody = `// Generated by scripts/generateUpcomingPhysicsContent.mjs from the audited Grade 6–PhD gap registers.\n// Do not mark these entries interactive or covered until their theory/lab evidence is implemented and reviewed.\n\nexport type UpcomingPhysicsKind = "theory" | "lab";\nexport type UpcomingPhysicsAvailability = "upcoming";\n\nexport interface UpcomingPhysicsContent {\n  id: string;\n  kind: UpcomingPhysicsKind;\n  title: string;\n  stage: string;\n  level: string;\n  domain: string;\n  subdomain: string;\n  scope: string;\n  plannedLab: string;\n  nearestContent: string;\n  coverage: string;\n  priority: string;\n  frameworks: string;\n  sourceNames: string;\n  sourceUrls: string;\n  roadmap?: string;\n  availability: UpcomingPhysicsAvailability;\n}\n\nexport const upcomingTheoryContent: UpcomingPhysicsContent[] = ${JSON.stringify(theory, null, 2)};\n\nexport const upcomingLabContent: UpcomingPhysicsContent[] = ${JSON.stringify(practical, null, 2)};\n\nexport const upcomingPhysicsContent: UpcomingPhysicsContent[] = [...upcomingTheoryContent, ...upcomingLabContent];\n`;

await fs.mkdir(path.dirname(outputFile), { recursive: true });
await fs.writeFile(outputFile, fileBody, "utf8");
console.log(JSON.stringify({ outputFile, theory: theory.length, labs: practical.length, total: theory.length + practical.length }));
