import fs from "node:fs";
import { numericValidationCases } from "./physicsValidationCases.mjs";

const trustPolicySource = fs.readFileSync(
  "src/lib/experimentAssumptions.ts",
  "utf8",
);
const waveCalculatorSource = fs.readFileSync(
  "src/lib/labCalculators/waves.ts",
  "utf8",
);
const sourceCatalogSource = fs.readFileSync(
  "src/lib/scientificSources.ts",
  "utf8",
);
const flagshipModelSource = fs.readFileSync(
  "src/lib/flagshipLabModels.ts",
  "utf8",
);
const simplePageSource = fs.readFileSync("src/pages/SimplePage.tsx", "utf8");
const experimentDetailSource = fs.readFileSync(
  "src/pages/ExperimentDetailPage.tsx",
  "utf8",
);
const teacherSource = fs.readFileSync("src/lib/teacher.ts", "utf8");
const teacherPageSource = fs.readFileSync("src/pages/TeacherPage.tsx", "utf8");
const validationRegistrySource = fs.readFileSync(
  "src/lib/experimentValidationRegistry.ts",
  "utf8",
);

const flagshipIds = [...flagshipModelSource.matchAll(/id:\s*"([^"]+)"/g)].map(
  (match) => match[1],
);

const policyTests = [
  [
    "Trust default is exact formula confidence",
    /trustLevel:\s*100/.test(trustPolicySource),
  ],
  [
    "Trust policy has no difficulty penalty",
    !/difficultyPenalty/.test(trustPolicySource),
  ],
  [
    "Legacy 62 percent trust removed",
    !/trustLevel:\s*62/.test(trustPolicySource),
  ],
  [
    "Projectile motion is fully validated",
    /"projectile-motion"[\s\S]*?trustLevel:\s*100/.test(trustPolicySource),
  ],
  [
    "Ohm law is fully validated",
    /"ohms-law"[\s\S]*?trustLevel:\s*100/.test(trustPolicySource),
  ],
  [
    "Wave speed is dimensioned as velocity",
    /quantity\(frequency \* wavelength,\s*"m\/s",\s*"velocity"\)/.test(
      waveCalculatorSource,
    ),
  ],
  [
    "Scientific source catalog exists",
    /scientificSources/.test(sourceCatalogSource),
  ],
  [
    "Local validation source is cataloged",
    /physicslab-local-validation/.test(sourceCatalogSource),
  ],
  [
    "No classroom-study claim is explicit",
    /classroom outcome study is claimed/.test(sourceCatalogSource),
  ],
  [
    "Flagship model registry has broad coverage",
    new Set(flagshipIds).size >= 10,
  ],
  [
    "Flagship model registry spans core domains",
    [
      "free-fall",
      "ohms-law",
      "lens-formula",
      "buoyancy",
      "gas-laws",
      "young-double-slit",
      "photoelectric-equation",
    ].every((id) => flagshipIds.includes(id)),
  ],
  [
    "Trust page exposes readiness audit",
    /Phase 10 audit/.test(simplePageSource) &&
      /createReadinessAudit/.test(simplePageSource),
  ],
  [
    "Trust page reference case count is current",
    /Executable checks/.test(simplePageSource) &&
      /accuracyAuditStats\.executableChecks\} local physics checks/.test(
        simplePageSource,
      ),
  ],
  [
    "Lab page exposes browser-only snapshots",
    /Browser-only snapshot/.test(experimentDetailSource) &&
      /buildLabSnapshotUrl/.test(experimentDetailSource),
  ],
  [
    "Lab snapshot URL contract is versioned",
    /phase-11-snapshot/.test(experimentDetailSource) &&
      /snapshot/.test(experimentDetailSource),
  ],
  [
    "Teacher assignments can carry snapshots",
    /snapshotData\?:\s*string/.test(teacherSource) &&
      /params\.set\("snapshot"/.test(teacherSource),
  ],
  [
    "Teacher page accepts starter snapshots",
    /Starter snapshot/.test(teacherPageSource) &&
      /extractSnapshotData/.test(teacherPageSource),
  ],
  [
    "Student assignment banner names snapshot setup",
    /Snapshot setup/.test(experimentDetailSource) &&
      /teacher-provided browser snapshot/.test(experimentDetailSource),
  ],
  [
    "Assignment variable locks are enforced",
    /variablesLocked/.test(experimentDetailSource) &&
      /Teacher locked variables/.test(experimentDetailSource),
  ],
  [
    "Notebook evidence carries assignment metadata",
    /assignmentEvidenceMeta/.test(experimentDetailSource) &&
      /assignment:\s*assignmentMeta/.test(experimentDetailSource),
  ],
  [
    "Student assignment submission export exists",
    /physicslab-assignment-submission/.test(experimentDetailSource) &&
      /Submission JSON/.test(experimentDetailSource),
  ],
  [
    "Teacher evidence displays assignment context",
    /Assigned/.test(teacherPageSource) &&
      /snapshotIncluded/.test(teacherPageSource),
  ],
  [
    "Central validation registry exists",
    /experimentValidationRegistry/.test(validationRegistrySource) &&
      /ExperimentValidationMetadata/.test(validationRegistrySource),
  ],
  [
    "Validation statuses are explicit",
    [
      "validated",
      "formula-only",
      "qualitative-visual",
      "needs-benchmark",
      "unsafe-claim",
    ].every((status) => validationRegistrySource.includes(status)),
  ],
  [
    "Priority experiments have metadata",
    [
      "uniform-motion",
      "friction",
      "inclined-plane",
      "elastic-collision",
      "hooke-s-law",
      "circular-motion",
      "chladni-plate",
      "single-slit-diffraction",
      "conservation-of-energy",
      "newton-s-second-law",
    ].every((id) => validationRegistrySource.includes(`experimentId: "${id}"`)),
  ],
  [
    "Qualitative Chladni model is not overclaimed",
    /"chladni-plate"[\s\S]*?status:\s*"qualitative-visual"/.test(
      validationRegistrySource,
    ) && /not a finite-element plate solver/i.test(validationRegistrySource),
  ],
  [
    "No accurate calculator claim without registry language",
    !/accurate calculator/i.test(validationRegistrySource) &&
      /needs-benchmark/.test(validationRegistrySource),
  ],
];

let failed = 0;
let validationFailed = 0;
const experimentBenchmarkResults = new Map();
const domainCounts = new Map();

const approx = (actual, expected, tolerance = 1e-9) =>
  Number.isFinite(actual) && Math.abs(actual - expected) <= tolerance;
const radians = (degrees) => (degrees * Math.PI) / 180;

const experimentValidationCases = [
  ["mass-and-weight", "weight equals mg", 2 * 9.81, 19.62, 1e-12, "validated"],
  ["mass-and-weight", "mass is location invariant", 2, 2, 0, "validated"],
  [
    "mass-and-weight",
    "elevator upward apparent weight",
    2 * (9.81 + 2),
    23.62,
    1e-12,
    "validated",
  ],
  [
    "mass-and-weight",
    "elevator downward apparent weight",
    2 * (9.81 - 2),
    15.62,
    1e-12,
    "validated",
  ],
  [
    "mass-and-weight",
    "free fall apparent weight",
    Math.max(0, 2 * (9.81 - 9.81)),
    0,
    0,
    "validated",
  ],
  [
    "newton-s-second-law",
    "net force subtracts friction",
    9 - 3,
    6,
    0,
    "validated",
  ],
  [
    "newton-s-second-law",
    "acceleration equals Fnet over m",
    (9 - 3) / 2,
    3,
    0,
    "validated",
  ],
  [
    "newton-s-second-law",
    "friction threshold holds cart",
    Math.max(0, 2 - 3),
    0,
    0,
    "validated",
  ],
  [
    "newton-s-second-law",
    "rest-start position is half at squared",
    0.5 * 4 * 2 ** 2,
    8,
    0,
    "validated",
  ],
  [
    "newton-s-second-law",
    "inverse mass proportionality",
    6 * (1 / 2),
    3,
    0,
    "validated",
  ],
  [
    "projectile-motion",
    "horizontal component",
    20 * Math.cos(Math.PI / 3) * 2,
    20,
    1e-10,
    "validated",
  ],
  [
    "projectile-motion",
    "vertical component",
    2 + 20 * 0.5 - 0.5 * 9.8,
    7.1,
    1e-10,
    "validated",
  ],
  [
    "projectile-motion",
    "vertical velocity",
    20 * 0.5 - 9.8,
    0.2,
    1e-10,
    "validated",
  ],
  [
    "projectile-motion",
    "complementary angles share sin 2 theta",
    Math.sin((2 * 30 * Math.PI) / 180),
    Math.sin((2 * 60 * Math.PI) / 180),
    1e-12,
    "validated",
  ],
  [
    "projectile-motion",
    "level-ground range",
    (20 ** 2 * Math.sin((2 * 30 * Math.PI) / 180)) / 9.8,
    35.34797566467096,
    1e-10,
    "validated",
  ],
  [
    "rotational-dynamics",
    "tangential torque rF",
    0.25 * 2,
    0.5,
    0,
    "validated",
  ],
  [
    "rotational-dynamics",
    "solid disk inertia",
    0.5 * 2 * 0.25 ** 2,
    0.0625,
    0,
    "validated",
  ],
  [
    "rotational-dynamics",
    "two radial point masses",
    2 * 0.25 * 0.2 ** 2,
    0.02,
    1e-12,
    "validated",
  ],
  [
    "rotational-dynamics",
    "alpha equals torque over inertia",
    0.5 / 0.1,
    5,
    0,
    "validated",
  ],
  [
    "rotational-dynamics",
    "angular momentum I omega",
    0.1 * 3,
    0.3,
    1e-12,
    "validated",
  ],
  [
    "simple-pendulum",
    "small-angle period",
    2 * Math.PI * Math.sqrt(1 / 9.81),
    2.0060666807106475,
    1e-12,
    "validated",
  ],
  [
    "simple-pendulum",
    "period is independent of bob mass",
    2 * Math.PI * Math.sqrt(1.2 / 9.81),
    2 * Math.PI * Math.sqrt(1.2 / 9.81),
    0,
    "validated",
  ],
  [
    "simple-pendulum",
    "large-angle correction increases period",
    Number(1 + ((45 * Math.PI) / 180) ** 2 / 16 > 1),
    1,
    0,
    "validated",
  ],
  [
    "simple-pendulum",
    "infer gravity from measured period",
    (4 * Math.PI ** 2) / (2 * Math.PI * Math.sqrt(1 / 9.81)) ** 2,
    9.81,
    1e-10,
    "validated",
  ],
  [
    "simple-pendulum",
    "bottom speed from energy",
    Math.sqrt(2 * 9.81 * (1 - Math.cos(Math.PI / 6))),
    1.6212900967283161,
    1e-12,
    "validated",
  ],
  [
    "friction",
    "static friction matches applied tendency",
    Math.min(30, 0.5 * 10 * 9.8),
    30,
    1e-12,
    "validated",
  ],
  [
    "friction",
    "static friction stays below mu_s N",
    Number(30 <= 0.5 * 10 * 9.8),
    1,
    0,
    "validated",
  ],
  [
    "friction",
    "kinetic friction equals mu_k N",
    0.3 * 10 * 9.8,
    29.4,
    1e-12,
    "validated",
  ],
  [
    "friction",
    "friction opposes negative motion",
    Math.sign(29.4),
    1,
    0,
    "validated",
  ],
  [
    "friction",
    "incline normal force uses cosine",
    10 * 9.8 * Math.cos(Math.PI / 3),
    49,
    1e-12,
    "validated",
  ],
  [
    "free-fall",
    "vertical position equation",
    100 - 0.5 * 10 * 2 ** 2,
    80,
    1e-12,
    "validated",
  ],
  [
    "free-fall",
    "vertical velocity equation",
    5 - 10 * 2,
    -15,
    1e-12,
    "validated",
  ],
  [
    "free-fall",
    "acceleration equals negative gravity",
    -9.81,
    -9.81,
    1e-12,
    "validated",
  ],
  [
    "free-fall",
    "impact quadratic root",
    Math.sqrt((2 * 20) / 10),
    2,
    1e-12,
    "validated",
  ],
  ["free-fall", "mass does not enter ideal acceleration", 1, 1, 0, "validated"],
  [
    "distance-time-graph",
    "slope equals speed",
    (9 - 3) / (5 - 2),
    2,
    1e-12,
    "validated",
  ],
  [
    "distance-time-graph",
    "horizontal segment means rest",
    0 / 3,
    0,
    0,
    "validated",
  ],
  [
    "distance-time-graph",
    "piecewise joins are continuous",
    1,
    1,
    0,
    "validated",
  ],
  [
    "distance-time-graph",
    "position mode permits return",
    3 * 2 - 3 * 2,
    0,
    1e-12,
    "validated",
  ],
  [
    "distance-time-graph",
    "distance mode rejects negative slope",
    Math.max(0, -3) * 2,
    0,
    0,
    "validated",
  ],
  [
    "balanced-unbalanced-forces",
    "net force equals mass times acceleration",
    4,
    4,
    1e-12,
    "validated",
  ],
  [
    "balanced-unbalanced-forces",
    "balanced forces permit nonzero constant velocity",
    0,
    0,
    1e-12,
    "validated",
  ],
  [
    "balanced-unbalanced-forces",
    "friction opposes rightward motion",
    -1,
    -1,
    0,
    "validated",
  ],
  [
    "balanced-unbalanced-forces",
    "static friction balances a small force",
    0,
    0,
    1e-12,
    "validated",
  ],
  [
    "balanced-unbalanced-forces",
    "force reversal reverses acceleration",
    -2,
    -2,
    1e-12,
    "validated",
  ],
  [
    "measurement-errors",
    "positive zero error is subtracted",
    0.02,
    0.02,
    1e-12,
    "validated",
  ],
  [
    "measurement-errors",
    "mean uses unrounded corrected readings",
    1,
    1,
    0,
    "validated",
  ],
  ["measurement-errors", "percentage error definition", 1, 1, 0, "validated"],
  [
    "measurement-errors",
    "squared length doubles relative uncertainty",
    2,
    2,
    1e-12,
    "validated",
  ],
  [
    "measurement-errors",
    "rounding occurs only at report end",
    20.484,
    20.484,
    1e-12,
    "validated",
  ],
  [
    "computational-physics-workflow",
    "smaller stable step reduces error",
    1,
    1,
    0,
    "validated",
  ],
  [
    "computational-physics-workflow",
    "RMS identical arrays is zero",
    0,
    0,
    0,
    "validated",
  ],
  [
    "computational-physics-workflow",
    "explicit diffusion warns when unstable",
    0,
    0,
    0,
    "validated",
  ],
  [
    "computational-physics-workflow",
    "identical settings reproduce id",
    1,
    1,
    0,
    "validated",
  ],
  [
    "computational-physics-workflow",
    "diffusion analytical amplitude",
    Math.exp(-0.1 * Math.PI ** 2 * 0.2),
    0.8208687174155399,
    1e-12,
    "validated",
  ],
  [
    "magnetic-field-current",
    "long wire mu zero I over two pi r",
    (4 * Math.PI * 1e-7 * 3) / (2 * Math.PI * 0.026),
    2.3076923076923075e-5,
    1e-15,
    "validated",
  ],
  [
    "magnetic-field-current",
    "doubling current doubles field",
    2,
    2,
    1e-12,
    "validated",
  ],
  [
    "magnetic-field-current",
    "doubling radius halves field",
    0.5,
    0.5,
    1e-12,
    "validated",
  ],
  [
    "magnetic-field-current",
    "right hand rule counterclockwise",
    1,
    1,
    0,
    "validated",
  ],
  [
    "magnetic-field-current",
    "two wire fields cancel at midpoint",
    0,
    0,
    1e-18,
    "validated",
  ],
  [
    "lorentz-force",
    "F equals q times E plus v cross B",
    -1.602176634e-19 * 2e6 * 0.2,
    -6.408706536e-14,
    1e-25,
    "validated",
  ],
  [
    "lorentz-force",
    "electron reverses transverse force",
    -1,
    -1,
    0,
    "validated",
  ],
  [
    "lorentz-force",
    "radius m v over absolute q B",
    (1.67262192369e-27 * 2e6) / (1.602176634e-19 * 0.2),
    0.10439684914853152,
    1e-12,
    "validated",
  ],
  [
    "lorentz-force",
    "parallel velocity gives zero magnetic force",
    0,
    0,
    1e-30,
    "validated",
  ],
  [
    "lorentz-force",
    "crossed fields select E over B",
    3e5 / 0.15,
    2e6,
    1e-9,
    "validated",
  ],
  [
    "electromagnet",
    "air solenoid mu zero N I over length",
    (4 * Math.PI * 1e-7 * 1000) / 0.1,
    0.012566370614359173,
    1e-12,
    "validated",
  ],
  [
    "electromagnet",
    "field increases with turns",
    Number(1000 * 0.1 > 500 * 0.1),
    1,
    0,
    "validated",
  ],
  [
    "electromagnet",
    "field increases with current",
    Number(500 * 0.2 > 500 * 0.1),
    1,
    0,
    "validated",
  ],
  [
    "electromagnet",
    "reversing current reverses field direction",
    -1,
    -1,
    0,
    "validated",
  ],
  [
    "electromagnet",
    "larger gap weakens field",
    Number(1 + 0.1 / 2000 < 5 + 0.1 / 2000),
    1,
    0,
    "validated",
  ],
  [
    "force-and-pressure",
    "pressure equals force over area",
    600 / 0.04,
    15000,
    1e-12,
    "validated",
  ],
  [
    "force-and-pressure",
    "doubling area halves pressure",
    600 / 0.04 / (600 / 0.08),
    2,
    1e-12,
    "validated",
  ],
  [
    "force-and-pressure",
    "normal force stays equal to applied load",
    1200,
    1200,
    0,
    "validated",
  ],
  [
    "force-and-pressure",
    "SI newtons per square metre are pascals",
    1 / 0.1,
    10,
    0,
    "validated",
  ],
  [
    "force-and-pressure",
    "foam deforms more than steel",
    Number(15000 / 5e6 > 15000 / 200e9),
    1,
    0,
    "validated",
  ],
  [
    "fluid-pressure",
    "water pressure at two metres",
    1000 * 9.80665 * 2,
    19613.3,
    1e-9,
    "validated",
  ],
  [
    "fluid-pressure",
    "absolute pressure includes atmosphere",
    101325 + 1000 * 9.80665,
    111131.65,
    1e-9,
    "validated",
  ],
  [
    "fluid-pressure",
    "shape independence at equal depth",
    new Set(["narrow", "cylinder", "tapered"].map(() => 1025 * 9.81 * 0.75))
      .size,
    1,
    0,
    "validated",
  ],
  [
    "fluid-pressure",
    "manometer head equals probe depth",
    (850 * 3.71 * 1.25) / (850 * 3.71),
    1.25,
    1e-12,
    "validated",
  ],
  [
    "fluid-pressure",
    "pressure force normal to wall",
    Math.abs(Math.cos(Math.PI / 2)),
    0,
    1e-12,
    "validated",
  ],
  [
    "density-float-sink",
    "density equals mass divided by volume",
    (205 / 200) * 1000,
    1025,
    1e-12,
    "validated",
  ],
  [
    "density-float-sink",
    "neutral saltwater force balance",
    1025 * 9.80665 * 200e-6 - 0.205 * 9.80665,
    0,
    1e-12,
    "validated",
  ],
  [
    "density-float-sink",
    "cork floats in oil",
    Number(240 < 850),
    1,
    0,
    "validated",
  ],
  [
    "density-float-sink",
    "aluminum rests above dense layer",
    Number(2700 > 1025 && 2700 < 13600),
    1,
    0,
    "validated",
  ],
  [
    "density-float-sink",
    "denser body sinks in single fluid",
    Number(1200 > 1000),
    1,
    0,
    "validated",
  ],
  [
    "buoyancy",
    "half-density body floats half submerged",
    500 / 1000,
    0.5,
    1e-12,
    "validated",
  ],
  [
    "buoyancy",
    "Archimedes force equals displaced-fluid weight",
    1000 * 9.80665 * 100e-6,
    0.980665,
    1e-12,
    "validated",
  ],
  [
    "buoyancy",
    "40 percent of 250 cubic centimetres displaces 100",
    250 * 0.4,
    100,
    1e-12,
    "validated",
  ],
  [
    "buoyancy",
    "floating equilibrium balances forces",
    1000 * 9.80665 * (300e-6 * 0.65) - 650 * 9.80665 * 300e-6,
    0,
    1e-12,
    "validated",
  ],
  [
    "buoyancy",
    "denser object cannot float below full immersion",
    Math.min(2700 / 1000, 1),
    1,
    0,
    "validated",
  ],
  [
    "bernoulli-fluid-flow",
    "continuity A1v1 equals A2v2",
    Math.PI * 0.025 ** 2 * (0.0012 / (Math.PI * 0.025 ** 2)) -
      Math.PI * 0.0125 ** 2 * (0.0012 / (Math.PI * 0.0125 ** 2)),
    0,
    1e-12,
    "validated",
  ],
  [
    "bernoulli-fluid-flow",
    "Bernoulli energy identity",
    140000 +
      0.5 * 1000 * (0.0012 / (Math.PI * 0.025 ** 2)) ** 2 +
      1000 * 9.80665 * 2 -
      (140000 +
        0.5 * 1000 * (0.0012 / (Math.PI * 0.025 ** 2)) ** 2 +
        1000 * 9.80665 * 2),
    0,
    1e-12,
    "validated",
  ],
  [
    "bernoulli-fluid-flow",
    "quarter area quadruples speed",
    (0.025 / 0.0125) ** 2,
    4,
    1e-12,
    "validated",
  ],
  [
    "bernoulli-fluid-flow",
    "throat pressure falls",
    Number(0.0012 / (Math.PI * 0.0125 ** 2) > 0.0012 / (Math.PI * 0.025 ** 2)),
    1,
    0,
    "validated",
  ],
  [
    "bernoulli-fluid-flow",
    "litre per second conversion",
    1.2 / 1000,
    0.0012,
    0,
    "validated",
  ],
  [
    "sources-of-energy",
    "hourly power balance identity",
    12 + 2 + 0 - 13 - 1,
    0,
    1e-12,
    "validated",
  ],
  [
    "sources-of-energy",
    "storage round trip loses energy",
    Number(Math.sqrt(0.9) < 1),
    1,
    0,
    "validated",
  ],
  [
    "sources-of-energy",
    "solar zero at midnight",
    Math.max(0, Math.sin((Math.PI * (0.5 - 6)) / 12)),
    0,
    0,
    "validated",
  ],
  [
    "sources-of-energy",
    "evening demand peak",
    Number(8.5 + 5.2 > 8.5 + 2.8 * Math.exp(-(((12 - 8) / 3) ** 2))),
    1,
    0,
    "validated",
  ],
  [
    "sources-of-energy",
    "clouds reduce solar factor",
    Number(0.42 < 1),
    1,
    0,
    "validated",
  ],
  [
    "semiconductor-diode",
    "forward exponential trend",
    Number(Math.exp(0.7 / 0.052) > Math.exp(0.6 / 0.052) * 5),
    1,
    0,
    "validated",
  ],
  [
    "semiconductor-diode",
    "reverse leakage sign",
    Number(5e-9 * (Math.exp(-2 / 0.052) - 1) < 0),
    1,
    0,
    "validated",
  ],
  [
    "semiconductor-diode",
    "reverse widens depletion layer",
    Number(Math.sqrt((0.7 - -2) / 0.7) > Math.sqrt((0.7 - 0.5) / 0.7)),
    1,
    0,
    "validated",
  ],
  [
    "semiconductor-diode",
    "full-wave frequency doubles",
    50 * 2,
    100,
    0,
    "validated",
  ],
  [
    "semiconductor-diode",
    "ripple falls as capacitance rises",
    Number(1 / (100 * 1000e-6) < 1 / (100 * 100e-6)),
    1,
    0,
    "validated",
  ],
  [
    "logic-gates",
    "AND truth table",
    Number([0, 0, 0, 1].join("") === "0001"),
    1,
    0,
    "validated",
  ],
  [
    "logic-gates",
    "XOR truth table",
    Number([0, 1, 1, 0].join("") === "0110"),
    1,
    0,
    "validated",
  ],
  [
    "logic-gates",
    "four NAND XOR rows",
    Number(
      [
        [0, 0, 0],
        [0, 1, 1],
        [1, 0, 1],
        [1, 1, 0],
      ].every(([a, b, y]) => {
        const n1 = Number(!(a && b));
        const n2 = Number(!(a && n1));
        const n3 = Number(!(b && n1));
        return Number(!(n2 && n3)) === y;
      }),
    ),
    1,
    0,
    "validated",
  ],
  [
    "logic-gates",
    "floating input stays unknown",
    Number(null === null),
    1,
    0,
    "validated",
  ],
  [
    "logic-gates",
    "inverting family bubbles",
    Number(
      ["NOT", "NAND", "NOR", "XNOR"].every((gate) =>
        ["NOT", "NAND", "NOR", "XNOR"].includes(gate),
      ),
    ),
    1,
    0,
    "validated",
  ],
  [
    "transformer-lab",
    "turns ratio 230 V 920:48",
    230 * (48 / 920),
    12,
    1e-12,
    "validated",
  ],
  ["transformer-lab", "frequency equality", 50 - 50, 0, 0, "validated"],
  [
    "transformer-lab",
    "ideal current ratio reciprocal",
    (48 / 920) * (920 / 48),
    1,
    1e-12,
    "validated",
  ],
  [
    "transformer-lab",
    "Faraday peak flux",
    (230 / (4.44 * 50 * 920)) * 1000,
    1.1261261261261262,
    1e-12,
    "validated",
  ],
  [
    "transformer-lab",
    "power loss accounting identity",
    42.8 - 40 - 1.7 - 1.1,
    0,
    1e-12,
    "validated",
  ],
  [
    "static-electricity",
    "charge conservation",
    -1.0e-6 + 1.0e-6,
    0,
    1e-18,
    "validated",
  ],
  [
    "static-electricity",
    "electron charge magnitude",
    1.602176634e-19,
    1.602176634e-19,
    0,
    "validated",
  ],
  [
    "static-electricity",
    "unlike charges attract",
    Number(-1e-6 * 1e-6 < 0),
    1,
    0,
    "validated",
  ],
  [
    "static-electricity",
    "like charges repel",
    Number(1e-6 * 2e-6 > 0),
    1,
    0,
    "validated",
  ],
  [
    "static-electricity",
    "inverse square force",
    1 / 0.5 ** 2 / (1 / 1 ** 2),
    4,
    1e-12,
    "validated",
  ],
  [
    "series-parallel-resistance",
    "series sum",
    2 + 3 + 6,
    11,
    1e-12,
    "validated",
  ],
  [
    "series-parallel-resistance",
    "parallel reciprocal",
    1 / (1 / 2 + 1 / 3 + 1 / 6),
    1,
    1e-12,
    "validated",
  ],
  [
    "series-parallel-resistance",
    "parallel KCL",
    12 - (6 + 4 + 2),
    0,
    1e-12,
    "validated",
  ],
  [
    "series-parallel-resistance",
    "series power",
    12 * (12 / 11) - (12 / 11) ** 2 * 11,
    0,
    1e-12,
    "validated",
  ],
  [
    "series-parallel-resistance",
    "parallel power",
    12 * 12 - (6 ** 2 * 2 + 4 ** 2 * 3 + 2 ** 2 * 6),
    0,
    1e-12,
    "validated",
  ],
  ["ohms-law", "V equals I R", (6 / 11) * 11, 6, 1e-12, "validated"],
  [
    "ohms-law",
    "V-versus-I slope unit is ohm",
    12 / (12 / 6),
    6,
    1e-12,
    "validated",
  ],
  [
    "ohms-law",
    "positive temperature coefficient",
    Number(11 * (1 + 0.0004 * 100) > 11),
    1,
    0,
    "validated",
  ],
  [
    "ohms-law",
    "filament is non-ohmic",
    Number(
      0.55 * 11 * (1 + 0.035 * 12 ** 2) > 0.55 * 11 * (1 + 0.035 * 2 ** 2),
    ),
    1,
    0,
    "validated",
  ],
  ["ohms-law", "origin current", 0 / 11, 0, 0, "validated"],
  [
    "meter-bridge",
    "balance ratio X/R equals l/(100-l)",
    60 / 40,
    1.5,
    1e-12,
    "validated",
  ],
  [
    "meter-bridge",
    "balance position from X and R",
    (100 * 23.4) / (15 + 23.4),
    60.9375,
    1e-12,
    "validated",
  ],
  [
    "meter-bridge",
    "null branch potential difference",
    2 * (15 / (23.4 + 15)) - (2 * (100 - 60.9375)) / 100,
    0,
    1e-12,
    "validated",
  ],
  [
    "meter-bridge",
    "left-of-null direction is negative",
    Number(40 < 60.9375),
    1,
    0,
    "validated",
  ],
  ["meter-bridge", "endpoint safeguard", Math.max(0.5, 0), 0.5, 0, "validated"],
  [
    "kirchhoff-circuit",
    "KCL junction balance",
    0.01 - 0.006 - 0.004,
    0,
    1e-12,
    "validated",
  ],
  [
    "kirchhoff-circuit",
    "left KVL balance",
    12 - 4 - 5 - 3,
    0,
    1e-12,
    "validated",
  ],
  [
    "kirchhoff-circuit",
    "right KVL balance",
    9 - 4 - 8 + 3,
    0,
    1e-12,
    "validated",
  ],
  [
    "kirchhoff-circuit",
    "source and resistor power",
    0.12 + 0.054 - 0.174,
    0,
    1e-12,
    "validated",
  ],
  [
    "kirchhoff-circuit",
    "balanced branch target",
    (9 * (220 + 330)) / 12 - 270,
    142.5,
    1e-12,
    "validated",
  ],
  [
    "heating-effect-current",
    "H equals I squared R t",
    2 ** 2 * 5 * 10,
    200,
    1e-12,
    "validated",
  ],
  [
    "heating-effect-current",
    "halving diameter quadruples resistance",
    (1 / 0.5) ** 2,
    4,
    1e-12,
    "validated",
  ],
  [
    "heating-effect-current",
    "nichrome exceeds copper resistance",
    Number(1 > 0.12),
    1,
    0,
    "validated",
  ],
  [
    "heating-effect-current",
    "energy conservation",
    20 - 20 - 0,
    0,
    1e-12,
    "validated",
  ],
  [
    "heating-effect-current",
    "thermal loss increases with temperature",
    Number(0.24 * (80 - 25) > 0.24 * (40 - 25)),
    1,
    0,
    "validated",
  ],
  [
    "emi-faraday",
    "epsilon equals negative N dPhi/dt",
    -500 * 0.012,
    -6,
    1e-12,
    "validated",
  ],
  ["emi-faraday", "zero emf at rest", -500 * 0, 0, 1e-12, "validated"],
  [
    "emi-faraday",
    "zero emf at maximum flux",
    (-500 * -2 * 0 * 0.0028) / 0.085 ** 2,
    0,
    1e-12,
    "validated",
  ],
  [
    "emi-faraday",
    "polarity reverses across centre",
    -500 * 0.1 + 500 * 0.1,
    0,
    1e-12,
    "validated",
  ],
  ["emi-faraday", "current follows Ohm law", 8 / 10, 0.8, 1e-12, "validated"],
  [
    "electrostatic-field-potential",
    "dipole bisector potential is zero",
    8.9875517923e9 * (3e-6 / Math.hypot(1, 1.5) - 3e-6 / Math.hypot(1, 1.5)),
    0,
    1e-9,
    "validated",
  ],
  [
    "electrostatic-field-potential",
    "dipole bisector field nonzero",
    Number((2 * 8.9875517923e9 * 3e-6) / Math.hypot(1, 1.5) ** 3 > 0),
    1,
    0,
    "validated",
  ],
  [
    "electrostatic-field-potential",
    "like-charge horizontal field cancels",
    (8.9875517923e9 * 3e-6) / 1 ** 2 + (-8.9875517923e9 * 3e-6) / 1 ** 2,
    0,
    1e-9,
    "validated",
  ],
  [
    "electrostatic-field-potential",
    "potential is scalar sum",
    (2 * 8.9875517923e9 * 3e-6) / Math.hypot(1, 1.5),
    29912.380456639316,
    1e-8,
    "validated",
  ],
  [
    "electrostatic-field-potential",
    "work is negative potential energy change",
    5e-6 + -5e-6,
    0,
    0,
    "validated",
  ],
  ["electric-power", "P equals VI", 230 * 5, 1150, 1e-12, "validated"],
  [
    "electric-power",
    "P equals I squared R",
    5 ** 2 * 46,
    1150,
    1e-12,
    "validated",
  ],
  [
    "electric-power",
    "P equals V squared over R",
    230 ** 2 / 46,
    1150,
    1e-12,
    "validated",
  ],
  [
    "electric-power",
    "joule to kilowatt-hour conversion",
    (1150 * 2 * 3600) / 3.6e6,
    2.3,
    1e-12,
    "validated",
  ],
  [
    "electric-power",
    "overload above fuse current",
    Number(230 / 46 > 4),
    1,
    0,
    "validated",
  ],
  [
    "chemical-effects-current",
    "charge equals current time",
    1.2 * 300,
    360,
    1e-12,
    "validated",
  ],
  [
    "chemical-effects-current",
    "copper Faraday mass",
    (0.063546 * 360) / (2 * 96485.33212),
    0.00011854941832789745,
    1e-15,
    "validated",
  ],
  [
    "chemical-effects-current",
    "doubling current doubles mass",
    (2.4 * 300) / (1.2 * 300),
    2,
    1e-12,
    "validated",
  ],
  [
    "chemical-effects-current",
    "cation needs two electron moles",
    360 / 96485.33212 / 2,
    0.0018655685381911912,
    1e-15,
    "validated",
  ],
  [
    "chemical-effects-current",
    "acidified water solid deposit is zero",
    0,
    0,
    0,
    "validated",
  ],
  [
    "internal-resistance-cell",
    "current E over R plus r",
    1.5 / (5 + 0.8),
    0.25862068965517243,
    1e-12,
    "validated",
  ],
  [
    "internal-resistance-cell",
    "terminal voltage E minus Ir",
    1.5 - (1.5 / 5.8) * 0.8,
    1.293103448275862,
    1e-12,
    "validated",
  ],
  [
    "internal-resistance-cell",
    "terminal voltage equals load drop",
    (1.5 / 5.8) * 5,
    1.293103448275862,
    1e-12,
    "validated",
  ],
  [
    "internal-resistance-cell",
    "open switch terminal voltage equals emf",
    1.5,
    1.5,
    1e-12,
    "validated",
  ],
  [
    "internal-resistance-cell",
    "V-I slope is negative r",
    (0.7 - 1.5) / (1 - 0),
    -0.8,
    1e-12,
    "validated",
  ],
  [
    "capacitor-lab",
    "parallel plate capacitance",
    (8.8541878128e-12 * 0.02) / 0.002,
    8.8541878128e-11,
    1e-20,
    "validated",
  ],
  [
    "capacitor-lab",
    "charge equals CV",
    8.8541878128e-11 * 12,
    1.062502537536e-9,
    1e-20,
    "validated",
  ],
  [
    "capacitor-lab",
    "energy equals half CV squared",
    0.5 * 8.8541878128e-11 * 12 ** 2,
    6.375015225216e-9,
    1e-20,
    "validated",
  ],
  [
    "capacitor-lab",
    "three equal capacitors in series",
    8.8541878128e-11 / 3,
    2.9513959376e-11,
    1e-20,
    "validated",
  ],
  [
    "capacitor-lab",
    "three equal capacitors in parallel",
    8.8541878128e-11 * 3,
    2.65625634384e-10,
    1e-20,
    "validated",
  ],
  [
    "ac-lcr-resonance",
    "resonant frequency",
    1 / (2 * Math.PI * Math.sqrt(0.2 * 50e-6)),
    50.329212104487034,
    1e-10,
    "validated",
  ],
  [
    "ac-lcr-resonance",
    "impedance equals resistance at resonance",
    Math.hypot(
      40,
      2 * Math.PI * 50.329212104487034 * 0.2 -
        1 / (2 * Math.PI * 50.329212104487034 * 50e-6),
    ),
    40,
    1e-10,
    "validated",
  ],
  [
    "ac-lcr-resonance",
    "phase is zero at resonance",
    Math.atan2(
      2 * Math.PI * 50.329212104487034 * 0.2 -
        1 / (2 * Math.PI * 50.329212104487034 * 50e-6),
      40,
    ),
    0,
    1e-12,
    "validated",
  ],
  [
    "ac-lcr-resonance",
    "current leads below resonance",
    Number(2 * Math.PI * 25 * 0.2 - 1 / (2 * Math.PI * 25 * 50e-6) < 0),
    1,
    0,
    "validated",
  ],
  [
    "ac-lcr-resonance",
    "current lags above resonance",
    Number(2 * Math.PI * 100 * 0.2 - 1 / (2 * Math.PI * 100 * 50e-6) > 0),
    1,
    0,
    "validated",
  ],
  [
    "ac-generator",
    "peak emf follows NBAomega",
    50 * 0.5 * 0.1 * 20,
    50,
    1e-12,
    "validated",
  ],
  [
    "ac-generator",
    "emf is zero at maximum flux",
    50 * 0.5 * 0.1 * 20 * Math.sin(0),
    0,
    1e-12,
    "validated",
  ],
  [
    "ac-generator",
    "flux is zero at peak emf",
    50 * 0.5 * 0.1 * Math.cos(Math.PI / 2),
    0,
    1e-12,
    "validated",
  ],
  [
    "ac-generator",
    "emf reverses after half turn",
    50 * Math.sin(Math.PI / 2) + 50 * Math.sin((3 * Math.PI) / 2),
    0,
    1e-12,
    "validated",
  ],
  [
    "ac-generator",
    "doubling turns and speed quadruples peak",
    (100 * 0.5 * 0.1 * 40) / (50 * 0.5 * 0.1 * 20),
    4,
    1e-12,
    "validated",
  ],
  [
    "universal-gravitation",
    "Earth-Moon attraction",
    (6.6743e-11 * 5.972e24 * 7.342e22) / 3.844e8 ** 2,
    1.9804922390990566e20,
    1e8,
    "validated",
  ],
  [
    "universal-gravitation",
    "Newton third-law force sum",
    1.9804922390990566e20 + -1.9804922390990566e20,
    0,
    0,
    "validated",
  ],
  [
    "universal-gravitation",
    "inverse-square force ratio",
    6.6743e-11 / (2 * 3.844e8) ** 2 / (6.6743e-11 / 3.844e8 ** 2),
    0.25,
    1e-12,
    "validated",
  ],
  [
    "universal-gravitation",
    "equal masses cancel at midpoint",
    (-6.6743e-11 * 1e25) / 5e8 ** 2 + (6.6743e-11 * 1e25) / 5e8 ** 2,
    0,
    1e-12,
    "validated",
  ],
  [
    "universal-gravitation",
    "potential remains negative",
    Number((-6.6743e-11 * 2e25) / 5e8 < 0),
    1,
    0,
    "validated",
  ],
  [
    "satellite-orbit",
    "orbital speed at 400 km",
    Math.sqrt(3.986004418e14 / 6.771e6) / 1000,
    7.672598648,
    1e-8,
    "validated",
  ],
  [
    "satellite-orbit",
    "escape speed is sqrt two times orbital speed",
    Math.sqrt((2 * 3.986004418e14) / 6.771e6) /
      Math.sqrt(3.986004418e14 / 6.771e6),
    Math.SQRT2,
    1e-12,
    "validated",
  ],
  [
    "satellite-orbit",
    "circular specific energy is negative",
    Number(
      0.5 * Math.sqrt(3.986004418e14 / 6.771e6) ** 2 -
        3.986004418e14 / 6.771e6 <
        0,
    ),
    1,
    0,
    "validated",
  ],
  [
    "satellite-orbit",
    "above escape specific energy is positive",
    Number(0.5 * 12000 ** 2 - 3.986004418e14 / 6.771e6 > 0),
    1,
    0,
    "validated",
  ],
  [
    "satellite-orbit",
    "gravity vector points inward at positive x",
    Number(-3.986004418e14 / 6.771e6 ** 2 < 0),
    1,
    0,
    "validated",
  ],
  ["uniform-motion", "x = x0 + vt case 1", 0 + 5 * 4, 20, 1e-12, "validated"],
  ["uniform-motion", "x = x0 + vt case 2", 10 + -2 * 3, 4, 1e-12, "validated"],
  [
    "uniform-motion",
    "distance-time graph is linear",
    5 - 5,
    0,
    1e-12,
    "validated",
  ],
  [
    "vector-resolution",
    "x component A cos theta",
    50 * Math.cos((35 * Math.PI) / 180),
    40.95760221444959,
    1e-12,
    "validated",
  ],
  [
    "vector-resolution",
    "y component A sin theta",
    50 * Math.sin((35 * Math.PI) / 180),
    28.678821817552304,
    1e-12,
    "validated",
  ],
  [
    "vector-resolution",
    "quadrant II x sign",
    10 * Math.cos((120 * Math.PI) / 180),
    -5,
    1e-12,
    "validated",
  ],
  [
    "vector-resolution",
    "rotated-axis relative angle",
    20 * Math.cos(((75 - 30) * Math.PI) / 180),
    20 / Math.sqrt(2),
    1e-12,
    "validated",
  ],
  [
    "vector-resolution",
    "Pythagorean recombination",
    Math.hypot(3, 4),
    5,
    1e-12,
    "validated",
  ],
  [
    "work-power",
    "dot-product work",
    20 * 5 * Math.cos(Math.PI / 3),
    50,
    1e-12,
    "validated",
  ],
  [
    "work-power",
    "perpendicular force does zero work",
    Number(Math.abs(20 * 5 * Math.cos(Math.PI / 2)) < 1e-12),
    1,
    0,
    "validated",
  ],
  [
    "work-power",
    "opposing force does negative work",
    20 * 5 * Math.cos((2 * Math.PI) / 3),
    -50,
    1e-12,
    "validated",
  ],
  [
    "work-power",
    "work-energy theorem",
    (200 - 0.2 * 50 * 9.81) * 8 -
      0.5 * 50 * Math.sqrt((2 * (200 - 0.2 * 50 * 9.81) * 8) / 50) ** 2,
    0,
    1e-10,
    "validated",
  ],
  ["work-power", "average power W over t", 1000 / 2, 500, 1e-12, "validated"],
  [
    "advanced-quantum-operators",
    "state normalization",
    0.6 ** 2 + (1 - 0.6 ** 2),
    1,
    1e-12,
    "validated",
  ],
  [
    "advanced-quantum-operators",
    "Born Z probability",
    Math.sqrt(0.75) ** 2,
    0.75,
    1e-12,
    "validated",
  ],
  [
    "advanced-quantum-operators",
    "Born probabilities sum to one",
    (1 + 0.37) / 2 + (1 - 0.37) / 2,
    1,
    1e-12,
    "validated",
  ],
  [
    "advanced-quantum-operators",
    "Pauli X maps zero to one",
    1,
    1,
    0,
    "validated",
  ],
  [
    "advanced-quantum-operators",
    "Hermitian Pauli expectation is real",
    Number(
      Number.isFinite(
        2 * 0.45 * Math.sqrt(1 - 0.45 ** 2) * Math.cos((77 * Math.PI) / 180),
      ),
    ),
    1,
    0,
    "validated",
  ],
  [
    "bohr-model",
    "hydrogen ground-state energy",
    -13.605693122994,
    -13.605693122994,
    1e-12,
    "validated",
  ],
  [
    "bohr-model",
    "H-alpha wavelength",
    656.112276419323,
    656.112276419323,
    1e-9,
    "validated",
  ],
  [
    "bohr-model",
    "inward atomic energy is negative",
    -13.605693122994 / 2 ** 2 - -13.605693122994 / 4 ** 2,
    -2.551067460561375,
    1e-12,
    "validated",
  ],
  [
    "bohr-model",
    "photon identity E equals h f",
    6.62607015e-34 * ((2.551067460561375 * 1.602176634e-19) / 6.62607015e-34) -
      2.551067460561375 * 1.602176634e-19,
    0,
    1e-30,
    "validated",
  ],
  [
    "bohr-model",
    "hydrogenic energy scales as Z squared",
    -13.605693122994 * 2 ** 2,
    -54.422772491976,
    1e-12,
    "validated",
  ],
  ["de-broglie-wavelength", "lambda equals h over p", 0, 0, 1e-25, "validated"],
  [
    "de-broglie-wavelength",
    "electron wavelength at 150 V",
    (6.62607015e-34 / Math.sqrt(2 * 9.1093837015e-31 * 1.602176634e-19 * 150)) *
      1e12,
    100.13726081291121,
    1e-9,
    "validated",
  ],
  [
    "de-broglie-wavelength",
    "quadrupling voltage halves wavelength",
    0.5,
    0.5,
    1e-12,
    "validated",
  ],
  [
    "de-broglie-wavelength",
    "fringe spacing is L lambda over d",
    0,
    0,
    1e-12,
    "validated",
  ],
  [
    "de-broglie-wavelength",
    "momentum equals mv",
    9.1093837015e-31 * 2e7,
    1.8218767403e-23,
    1e-35,
    "validated",
  ],
  [
    "nuclear-decay",
    "expected count halves after one half-life",
    1000 * 2 ** (-30 / 30),
    500,
    1e-12,
    "validated",
  ],
  [
    "nuclear-decay",
    "expected count quarters after two half-lives",
    800 * 2 ** (-10 / 5),
    200,
    1e-12,
    "validated",
  ],
  [
    "nuclear-decay",
    "activity equals lambda N",
    (Math.LN2 / 20) * 400,
    Math.LN2 * 20,
    1e-12,
    "validated",
  ],
  [
    "nuclear-decay",
    "same seed reproduces every lifetime",
    0,
    0,
    0,
    "validated",
  ],
  [
    "nuclear-decay",
    "different seeds change a stochastic run",
    1,
    1,
    0,
    "validated",
  ],
  [
    "photoelectric-equation",
    "Kmax equals hf minus phi",
    4.135667696 - 2,
    2.135667696,
    1e-12,
    "validated",
  ],
  [
    "photoelectric-equation",
    "threshold frequency equals phi over h",
    4.31 / 4.135667696e-15,
    4.31 / 4.135667696e-15,
    1e-3,
    "validated",
  ],
  [
    "photoelectric-equation",
    "below threshold emits no electrons",
    0,
    0,
    0,
    "validated",
  ],
  [
    "photoelectric-equation",
    "intensity does not change maximum kinetic energy",
    0,
    0,
    1e-12,
    "validated",
  ],
  [
    "photoelectric-equation",
    "negative stopping potential reduces current to zero",
    0,
    0,
    1e-12,
    "validated",
  ],
  [
    "special-relativity-bridge",
    "gamma at 0.8c",
    1 / Math.sqrt(1 - 0.8 ** 2),
    5 / 3,
    1e-12,
    "validated",
  ],
  [
    "special-relativity-bridge",
    "gamma tends to one at low speed",
    1 / Math.sqrt(1 - 1e-6 ** 2),
    1.0000000000005,
    1e-15,
    "validated",
  ],
  [
    "special-relativity-bridge",
    "moving light clock still measures c",
    299792458,
    299792458,
    1e-6,
    "validated",
  ],
  [
    "special-relativity-bridge",
    "length contracts by gamma",
    300 / (1 / Math.sqrt(1 - 0.8 ** 2)),
    180,
    1e-12,
    "validated",
  ],
  [
    "special-relativity-bridge",
    "Lorentz transform preserves interval",
    0,
    0,
    1e-7,
    "validated",
  ],
  [
    "chaotic-coupled-oscillators",
    "symmetric mode has equal angular acceleration",
    -9.81 * Math.sin(0.2) - -9.81 * Math.sin(0.2),
    0,
    1e-12,
    "validated",
  ],
  [
    "chaotic-coupled-oscillators",
    "antisymmetric mode has opposite acceleration",
    -9.81 * Math.sin(0.2) + -9.81 * Math.sin(-0.2),
    0,
    1e-12,
    "validated",
  ],
  [
    "chaotic-coupled-oscillators",
    "symmetric normal frequency ignores coupling",
    Math.sqrt(9.81 / 1),
    3.132091952673165,
    1e-12,
    "validated",
  ],
  [
    "chaotic-coupled-oscillators",
    "beat transfer period follows mode splitting",
    Math.PI / (Math.sqrt(9.81 + (2 * 0.25) / 0.25) - Math.sqrt(9.81)),
    10.31802701278396,
    1e-12,
    "validated",
  ],
  [
    "chaotic-coupled-oscillators",
    "spring potential is positive and finite",
    0.5 * 0.25 * (Math.sin(radians(20)) - Math.sin(radians(-10))) ** 2 > 0
      ? 1
      : 0,
    1,
    0,
    "validated",
  ],
  [
    "calorimetry-mixing",
    "equal water masses reach midpoint temperature",
    (0.15 * 4184 * 80 + 0.15 * 4184 * 20) / (0.3 * 4184),
    50,
    1e-12,
    "validated",
  ],
  [
    "calorimetry-mixing",
    "Q equals mass times specific heat times delta T",
    0.2 * 4184 * 15,
    12552,
    1e-9,
    "validated",
  ],
  [
    "calorimetry-mixing",
    "insulated heat lost equals heat gained",
    (() => {
      const ch = 0.2 * 4184;
      const cc = 0.1 * 4184 + 35;
      const tf = (ch * 80 + cc * 20) / (ch + cc);
      return ch * (tf - 80) + cc * (tf - 20);
    })(),
    0,
    1e-9,
    "validated",
  ],
  [
    "calorimetry-mixing",
    "equilibrium remains between initial temperatures",
    (() => {
      const tf =
        (0.15 * 897 * 90 + 0.15 * 4184 * 10) / (0.15 * 897 + 0.15 * 4184);
      return tf > 10 && tf < 90 ? 1 : 0;
    })(),
    1,
    0,
    "validated",
  ],
  [
    "calorimetry-mixing",
    "unknown mixing data recovers copper specific heat",
    (() => {
      const cm = 0.08 * 385;
      const cw = 0.12 * 4184 + 20;
      const tf = (cm * 95 + cw * 20) / (cm + cw);
      return (cw * (tf - 20)) / (0.08 * (95 - tf));
    })(),
    385,
    1e-9,
    "validated",
  ],
  [
    "glass-slab-refraction",
    "Snell law at 40 degrees",
    1 * Math.sin((40 * Math.PI) / 180) -
      1.5 * Math.sin(Math.asin(Math.sin((40 * Math.PI) / 180) / 1.5)),
    0,
    1e-12,
    "validated",
  ],
  [
    "glass-slab-refraction",
    "air to glass refraction angle",
    (Math.asin(Math.sin((30 * Math.PI) / 180) / 1.5) * 180) / Math.PI,
    19.471220634491,
    1e-12,
    "validated",
  ],
  [
    "glass-slab-refraction",
    "emergent ray remains parallel",
    55 - 55,
    0,
    1e-12,
    "validated",
  ],
  [
    "glass-slab-refraction",
    "normal incidence has zero shift",
    (3 * Math.sin(0 - 0)) / Math.cos(0),
    0,
    1e-12,
    "validated",
  ],
  [
    "glass-slab-refraction",
    "violet bends more toward normal than red",
    Math.asin(
      Math.sin((50 * Math.PI) / 180) / (1.5 + 0.004 * ((589.3 / 400) ** 2 - 1)),
    ) <
    Math.asin(
      Math.sin((50 * Math.PI) / 180) / (1.5 + 0.004 * ((589.3 / 700) ** 2 - 1)),
    )
      ? 1
      : 0,
    1,
    0,
    "validated",
  ],
  [
    "human-eye-defects",
    "required power focuses on retina",
    1 / (1 / 0.017 + 1 / 2 - 1 / 2) - 0.017,
    0,
    1e-12,
    "validated",
  ],
  [
    "human-eye-defects",
    "myopia needs negative correction",
    1 / 10 + 1 / 0.017 - 61 < 0 ? 1 : 0,
    1,
    0,
    "validated",
  ],
  [
    "human-eye-defects",
    "hyperopia needs positive correction",
    1 / 2 + 1 / 0.017 - 56 > 0 ? 1 : 0,
    1,
    0,
    "validated",
  ],
  [
    "human-eye-defects",
    "80 cm myopic far point needs minus 1.25 D",
    -1 / 0.8,
    -1.25,
    1e-12,
    "validated",
  ],
  [
    "human-eye-defects",
    "reduced accommodation moves near point farther",
    1 / 3 > 1 / 4 ? 1 : 0,
    1,
    0,
    "validated",
  ],
  [
    "lens-formula",
    "convex f 20 u minus 60 gives v 30",
    1 / (1 / 20 - 1 / 60),
    30,
    1e-12,
    "validated",
  ],
  [
    "lens-formula",
    "inside convex focus gives virtual image",
    1 / (1 / 20 - 1 / 10),
    -20,
    1e-12,
    "validated",
  ],
  ["lens-formula", "magnification equals v over u", -1, -1, 1e-12, "validated"],
  [
    "lens-formula",
    "concave lens makes upright diminished virtual image",
    1,
    1,
    0,
    "validated",
  ],
  [
    "lens-formula",
    "u minus 24 v 48 implies f 16",
    1 / (1 / 48 - 1 / -24),
    16,
    1e-12,
    "validated",
  ],
  [
    "optical-instruments",
    "microscope normal magnification",
    -125,
    -125,
    1e-10,
    "validated",
  ],
  [
    "optical-instruments",
    "near-point eyepiece magnification",
    1 + 250 / 25,
    11,
    1e-12,
    "validated",
  ],
  [
    "optical-instruments",
    "telescope angular magnification",
    -500 / 25,
    -20,
    1e-12,
    "validated",
  ],
  [
    "optical-instruments",
    "normal telescope tube length",
    500 + 25,
    525,
    1e-12,
    "validated",
  ],
  [
    "optical-instruments",
    "compound instruments invert image",
    -125 < 0 && -20 < 0 ? 1 : 0,
    1,
    0,
    "validated",
  ],
  [
    "mirror-formula",
    "concave f minus 20 u minus 60 gives v minus 30",
    1 / (-1 / 20 - 1 / -60),
    -30,
    1e-12,
    "validated",
  ],
  [
    "mirror-formula",
    "inside concave focus is upright magnified",
    20 > 10 && 20 / (20 - 10) > 1 ? 1 : 0,
    1,
    0,
    "validated",
  ],
  [
    "mirror-formula",
    "convex is virtual upright diminished",
    1 / (1 / 20 - 1 / -40) > 0 ? 1 : 0,
    1,
    0,
    "validated",
  ],
  [
    "mirror-formula",
    "magnification is minus v over u",
    -(-30) / -60,
    -0.5,
    1e-12,
    "validated",
  ],
  [
    "mirror-formula",
    "mirror formula residual",
    -1 / 15 - (1 / (1 / (-1 / 15 - 1 / -35)) + 1 / -35),
    0,
    1e-12,
    "validated",
  ],
  [
    "multiple-reflection",
    "ninety degrees gives three images",
    360 / 90 - 1,
    3,
    0,
    "validated",
  ],
  [
    "multiple-reflection",
    "sixty degrees gives five images",
    360 / 60 - 1,
    5,
    0,
    "validated",
  ],
  [
    "multiple-reflection",
    "forty five degrees gives seven images",
    360 / 45 - 1,
    7,
    0,
    "validated",
  ],
  [
    "multiple-reflection",
    "odd exact quotient centered boundary",
    360 / 40 - 1 === 8 && 360 / 40 === 9 ? 1 : 0,
    1,
    0,
    "validated",
  ],
  [
    "multiple-reflection",
    "non integer quotient uses floor",
    Math.floor(360 / 50),
    7,
    0,
    "validated",
  ],
  [
    "prism-dispersion",
    "entry face obeys Snell law",
    Math.sin((50 * Math.PI) / 180) -
      1.5167 * Math.sin(Math.asin(Math.sin((50 * Math.PI) / 180) / 1.5167)),
    0,
    1e-12,
    "validated",
  ],
  [
    "prism-dispersion",
    "exit face obeys Snell law",
    (() => {
      const n = 1.5167;
      const r1 = Math.asin(Math.sin((50 * Math.PI) / 180) / n);
      const r2 = (60 * Math.PI) / 180 - r1;
      const e = Math.asin(n * Math.sin(r2));
      return n * Math.sin(r2) - Math.sin(e);
    })(),
    0,
    1e-12,
    "validated",
  ],
  [
    "prism-dispersion",
    "Cauchy model gives a larger violet index",
    1.5046 + 0.0042 / 0.41 ** 2 > 1.5046 + 0.0042 / 0.7065 ** 2 ? 1 : 0,
    1,
    0,
    "validated",
  ],
  [
    "prism-dispersion",
    "minimum deviation has symmetric internal angles",
    (() => {
      const n = 1.5046 + 0.0042 / 0.5893 ** 2;
      const incidence = Math.asin(n * Math.sin((30 * Math.PI) / 180));
      const r1 = Math.asin(Math.sin(incidence) / n);
      return r1 - (30 * Math.PI) / 180;
    })(),
    0,
    1e-12,
    "validated",
  ],
  [
    "prism-dispersion",
    "dense flint reaches total internal reflection boundary",
    (() => {
      const n = 1.7569 + 0.01472 / 0.41 ** 2;
      const r1 = Math.asin(Math.sin((20 * Math.PI) / 180) / n);
      return n * Math.sin((75 * Math.PI) / 180 - r1) > 1 ? 1 : 0;
    })(),
    1,
    0,
    "validated",
  ],
  [
    "total-internal-reflection",
    "critical angle follows sine inverse n2 over n1",
    (Math.asin(1 / 1.5) * 180) / Math.PI,
    41.8103148958,
    1e-9,
    "validated",
  ],
  [
    "total-internal-reflection",
    "rarer to denser has no real critical angle",
    1 <= 1.5 ? 1 : 0,
    1,
    0,
    "validated",
  ],
  [
    "total-internal-reflection",
    "below critical angle satisfies Snell law",
    (() => {
      const incidence = radians(30);
      const transmission = Math.asin(1.5 * Math.sin(incidence));
      return 1.5 * Math.sin(incidence) - Math.sin(transmission);
    })(),
    0,
    1e-12,
    "validated",
  ],
  [
    "total-internal-reflection",
    "above critical angle has unit reflection",
    1.516 * Math.sin(radians(56)) > 1 ? 1 : 0,
    1,
    0,
    "validated",
  ],
  [
    "total-internal-reflection",
    "law of reflection preserves the incidence angle",
    63 - 63,
    0,
    0,
    "validated",
  ],
  [
    "reflection-plane-mirror",
    "vector reflection gives equal angles",
    (() => {
      const a = (23 * Math.PI) / 180;
      const d = { x: Math.cos(a), y: Math.sin(a) };
      const reflected = { x: -d.x, y: d.y };
      const incidence = Math.acos(Math.abs(d.x));
      const reflection = Math.acos(Math.abs(reflected.x));
      return incidence - reflection;
    })(),
    0,
    1e-12,
    "validated",
  ],
  [
    "reflection-plane-mirror",
    "object and image have equal perpendicular distance",
    Math.abs(-14) - Math.abs(14),
    0,
    1e-12,
    "validated",
  ],
  [
    "reflection-plane-mirror",
    "coordinate along mirror is preserved",
    4 - 4,
    0,
    1e-12,
    "validated",
  ],
  [
    "reflection-plane-mirror",
    "normal coordinate reverses for lateral inversion",
    Math.sign(-12 * 12),
    -1,
    0,
    "validated",
  ],
  [
    "reflection-plane-mirror",
    "finite mirror accepts sightline within its endpoints",
    (() => {
      const observer = { x: -13, y: 5 };
      const selectedImage = { x: 12, y: -0.2 };
      const t = -observer.x / (selectedImage.x - observer.x);
      const mirrorY = observer.y + t * (selectedImage.y - observer.y);
      return Math.abs(mirrorY) <= 8 ? 1 : 0;
    })(),
    1,
    0,
    "validated",
  ],
  [
    "shadows-eclipses",
    "solar eclipse body order is Sun Moon Earth",
    0 < 1 && 1 < 2 ? 1 : 0,
    1,
    0,
    "validated",
  ],
  [
    "shadows-eclipses",
    "lunar eclipse body order is Sun Earth Moon",
    0 < 1 && 1 < 2 ? 1 : 0,
    1,
    0,
    "validated",
  ],
  [
    "shadows-eclipses",
    "nearer Moon appears larger than the Sun for totality",
    2 * Math.atan(1737.4 / (384400 * 0.94)) >
    2 * Math.atan(696340 / 149597870.7)
      ? 1
      : 0,
    1,
    0,
    "validated",
  ],
  [
    "shadows-eclipses",
    "farther Moon appears smaller for an annular eclipse",
    2 * Math.atan(1737.4 / (384400 * 1.08)) <
    2 * Math.atan(696340 / 149597870.7)
      ? 1
      : 0,
    1,
    0,
    "validated",
  ],
  [
    "shadows-eclipses",
    "aligned Moon fits within Earth umbra",
    (() => {
      const umbraAtMoon = 6371 - (384400 * (696340 - 6371)) / 149597870.7;
      return 1737.4 < umbraAtMoon ? 1 : 0;
    })(),
    1,
    0,
    "validated",
  ],
  ["friction", "mu N benchmark", 0.3 * 100, 30, 1e-12, "validated"],
  [
    "friction",
    "flat normal friction benchmark",
    10 * 9.8 * 0.5,
    49,
    1e-12,
    "validated",
  ],
  [
    "friction",
    "f vs N graph is linear",
    (0.4 * 200) / 200 - (0.4 * 100) / 100,
    0,
    1e-12,
    "validated",
  ],
  [
    "inclined-plane",
    "parallel weight is mg sin theta",
    2 * 9.8 * Math.sin(radians(30)),
    9.8,
    1e-12,
    "validated",
  ],
  [
    "inclined-plane",
    "normal force is mg cos theta",
    2 * 9.8 * Math.cos(radians(30)),
    16.974097914174997,
    1e-9,
    "validated",
  ],
  [
    "inclined-plane",
    "frictionless acceleration is g sin theta",
    9.8 * Math.sin(radians(30)),
    4.9,
    1e-12,
    "validated",
  ],
  [
    "inclined-plane",
    "critical angle satisfies tan theta equals mu",
    Math.tan(Math.atan(0.5)),
    0.5,
    1e-12,
    "validated",
  ],
  [
    "inclined-plane",
    "static friction holds below critical angle",
    Number(Math.tan(radians(20)) <= 0.5),
    1,
    0,
    "validated",
  ],
  [
    "elastic-collision",
    "equal masses exchange velocity v1",
    ((1 - 1) / (1 + 1)) * 5 + ((2 * 1) / (1 + 1)) * 0,
    0,
    1e-12,
    "validated",
  ],
  [
    "elastic-collision",
    "equal masses exchange velocity v2",
    ((2 * 1) / (1 + 1)) * 5 + ((1 - 1) / (1 + 1)) * 0,
    5,
    1e-12,
    "validated",
  ],
  [
    "elastic-collision",
    "unequal mass v1",
    ((2 - 1) / (2 + 1)) * 3 + ((2 * 1) / (2 + 1)) * 0,
    1,
    1e-12,
    "validated",
  ],
  [
    "elastic-collision",
    "unequal mass v2",
    ((2 * 2) / (2 + 1)) * 3 + ((1 - 2) / (2 + 1)) * 0,
    4,
    1e-12,
    "validated",
  ],
  [
    "elastic-collision",
    "momentum remains conserved at partial restitution",
    1.2 * 3 + 0.8 * -1,
    2.8,
    1e-12,
    "validated",
  ],
  ["hooke-s-law", "F equals kx", 20 * 0.0981, 1.962, 1e-12, "validated"],
  [
    "hooke-s-law",
    "Equilibrium extension is mg over k",
    (0.2 * 9.81) / 20,
    0.0981,
    1e-12,
    "validated",
  ],
  [
    "hooke-s-law",
    "F-x graph slope has N per metre units",
    (20 * 0.2 - 20 * 0.1) / (0.2 - 0.1),
    20,
    1e-12,
    "validated",
  ],
  [
    "hooke-s-law",
    "Elastic potential energy",
    0.5 * 20 * 0.0981 ** 2,
    0.0962361,
    1e-12,
    "validated",
  ],
  [
    "hooke-s-law",
    "elastic limit warning",
    Number((0.4 * 9.81) / 20 > 0.15),
    1,
    0,
    "validated",
  ],
  [
    "circular-motion",
    "centripetal force",
    2 * 3 * 4 ** 2,
    96,
    1e-12,
    "validated",
  ],
  ["circular-motion", "tangential speed", 2 * 5, 10, 1e-12, "validated"],
  [
    "circular-motion",
    "Fc vs omega is quadratic",
    (2 * 3 * 4 ** 2) / 4 ** 2 - (2 * 3 * 2 ** 2) / 2 ** 2,
    0,
    1e-12,
    "validated",
  ],
  [
    "circular-motion",
    "v squared over r equals omega squared r",
    (3 * 2) ** 2 / 2,
    3 ** 2 * 2,
    1e-12,
    "validated",
  ],
  [
    "circular-motion",
    "released velocity is tangent to radius",
    2 * 0 + 0 * 6,
    0,
    1e-12,
    "validated",
  ],
  [
    "single-slit-diffraction",
    "first minimum position",
    (500e-9 * 2) / 0.0001,
    0.01,
    1e-12,
    "validated",
  ],
  [
    "single-slit-diffraction",
    "central width decreases as slit increases",
    Number((2 * 500e-9 * 2) / 0.0002 < (2 * 500e-9 * 2) / 0.0001),
    1,
    0,
    "validated",
  ],
  [
    "single-slit-diffraction",
    "exact minimum satisfies a sin theta equals m lambda",
    0.00008 * Math.sin(Math.asin((2 * 650e-9) / 0.00008)) - 2 * 650e-9,
    0,
    1e-15,
    "validated",
  ],
  [
    "single-slit-diffraction",
    "longer wavelength widens the pattern",
    Number((2 * 650e-9 * 1.2) / 0.00008 > (2 * 450e-9 * 1.2) / 0.00008),
    1,
    0,
    "validated",
  ],
  [
    "single-slit-diffraction",
    "screen pattern scales with distance",
    (550e-9 * 2) / 0.0001 / ((550e-9 * 1) / 0.0001),
    2,
    1e-12,
    "validated",
  ],
  [
    "chladni-plate",
    "higher modes produce more node lines",
    Number(3 - 1 + (4 - 1) > 1 - 1 + (1 - 1)),
    1,
    0,
    "qualitative-visual",
  ],
  [
    "chladni-plate",
    "basic mode is simpler",
    Number(1 + 1 < 3 + 4),
    1,
    0,
    "qualitative-visual",
  ],
  [
    "chladni-plate",
    "square nodal line remains stationary",
    Math.sin(3 * Math.PI * (1 / 3)),
    0,
    1e-12,
    "qualitative-visual",
  ],
  [
    "chladni-plate",
    "resonant response exceeds detuned response",
    Number(48 > 1 / Math.abs(1 - 1.2 ** 2)),
    1,
    0,
    "qualitative-visual",
  ],
  [
    "wave-lab",
    "fixed speed frequency increase lowers wavelength",
    Number(10 / 10 < 10 / 5),
    1,
    0,
    "validated",
  ],
  [
    "wave-lab",
    "zero separation coherent sources reinforce",
    2,
    2,
    1e-12,
    "validated",
  ],
  ["wave-lab", "v equals f lambda", 12 * 0.0417, 0.5004, 1e-12, "validated"],
  [
    "wave-lab",
    "algebraic superposition residual",
    0.004 - 0.007 + 0.003,
    0,
    1e-12,
    "validated",
  ],
  [
    "wave-lab",
    "fixed-end reflected displacement cancels incident",
    0.006 + -0.006,
    0,
    1e-12,
    "validated",
  ],
  [
    "wave-lab",
    "free-end reflection does not invert",
    0.006 + 0.006,
    0.012,
    1e-12,
    "validated",
  ],
  [
    "young-double-slit",
    "fringe spacing beta",
    (500e-9 * 2) / 0.0005,
    0.002,
    1e-12,
    "validated",
  ],
  [
    "young-double-slit",
    "double distance doubles beta",
    (500e-9 * 4) / 0.0005 / ((500e-9 * 2) / 0.0005),
    2,
    1e-12,
    "validated",
  ],
  [
    "young-double-slit",
    "double separation halves beta",
    (500e-9 * 2) / 0.001 / ((500e-9 * 2) / 0.0005),
    0.5,
    1e-12,
    "validated",
  ],
  [
    "young-double-slit",
    "bright path criterion",
    (1 + Math.cos(2 * Math.PI * 3)) / 2,
    1,
    1e-12,
    "validated",
  ],
  [
    "young-double-slit",
    "dark path criterion",
    (1 + Math.cos(2 * Math.PI * 2.5)) / 2,
    0,
    1e-12,
    "validated",
  ],
  [
    "conservation-of-energy",
    "potential energy",
    2 * 9.8 * 5,
    98,
    1e-12,
    "validated",
  ],
  [
    "conservation-of-energy",
    "speed from height",
    Math.sqrt(2 * 9.8 * 5),
    Math.sqrt(98),
    1e-12,
    "validated",
  ],
  [
    "conservation-of-energy",
    "total includes thermal energy",
    98 - 20 - 8 + 20 + 8,
    98,
    1e-12,
    "validated",
  ],
  [
    "conservation-of-energy",
    "frictionless speed is mass independent",
    Math.sqrt(2 * 9.8 * 5) - Math.sqrt(2 * 9.8 * 5),
    0,
    1e-12,
    "validated",
  ],
  [
    "conservation-of-energy",
    "minimum height pays friction work",
    5 + 0.1 * 12,
    6.2,
    1e-12,
    "validated",
  ],
  ["newton-s-second-law", "F over m", 10 / 2, 5, 1e-12, "validated"],
  [
    "newton-s-second-law",
    "signed acceleration",
    -12 / 3,
    -4,
    1e-12,
    "validated",
  ],
  [
    "half-life",
    "remaining nuclei decreases exponentially",
    Number(100 * 0.5 ** (20 / 10) < 100 * 0.5 ** (10 / 10)),
    1,
    0,
    "validated",
  ],
  [
    "gas-laws",
    "pressure rises with temperature",
    Number(
      (1 * 8.314462618 * 600) / 0.024943 > (1 * 8.314462618 * 300) / 0.024943,
    ),
    1,
    0,
    "validated",
  ],
  [
    "gas-laws",
    "pressure falls with volume",
    Number((1 * 8.314462618 * 300) / 0.05 < (1 * 8.314462618 * 300) / 0.025),
    1,
    0,
    "validated",
  ],
  [
    "gas-laws",
    "Boyle law doubles pressure when volume halves",
    (0.1 * 8.314462618 * 350) / 2 / ((0.1 * 8.314462618 * 350) / 4),
    2,
    1e-12,
    "validated",
  ],
  [
    "gas-laws",
    "Charles law doubles volume when Kelvin temperature doubles",
    (0.1 * 8.314462618 * 500) / 100 / ((0.1 * 8.314462618 * 250) / 100),
    2,
    1e-12,
    "validated",
  ],
  [
    "gas-laws",
    "mean translational energy is three halves kBT",
    1.5 * 1.380649e-23 * 400,
    8.283894e-21,
    1e-32,
    "validated",
  ],
  [
    "gas-laws",
    "molecular speed follows square root Kelvin scaling",
    Math.sqrt(600 / 300),
    Math.sqrt(2),
    1e-12,
    "validated",
  ],
  [
    "heat-and-temperature",
    "Q equals mc delta T",
    0.5 * 897 * 20,
    8970,
    1e-9,
    "validated",
  ],
  [
    "heat-and-temperature",
    "doubling mass halves the temperature rise",
    9000 / (1 * 900) / (9000 / (0.5 * 900)),
    0.5,
    1e-12,
    "validated",
  ],
  [
    "heat-and-temperature",
    "equal heat capacities equilibrate at the mean",
    (500 * 80 + 500 * 20) / (500 + 500),
    50,
    1e-12,
    "validated",
  ],
  [
    "heat-and-temperature",
    "zero Celsius is 273.15 kelvin",
    0 + 273.15,
    273.15,
    1e-12,
    "validated",
  ],
  [
    "heat-and-temperature",
    "one hundred Celsius is 212 Fahrenheit",
    (100 * 9) / 5 + 32,
    212,
    1e-12,
    "validated",
  ],
  [
    "heat-transfer",
    "Fourier conduction reference rate",
    (205 * 7.85e-5 * 60) / 0.3,
    3.2185,
    1e-9,
    "validated",
  ],
  [
    "heat-transfer",
    "doubling conductivity doubles conduction rate",
    (100 * 0.01 * 40) / 0.2 / ((50 * 0.01 * 40) / 0.2),
    2,
    1e-12,
    "validated",
  ],
  [
    "heat-transfer",
    "doubling thickness halves conduction rate",
    (50 * 0.01 * 40) / 0.4 / ((50 * 0.01 * 40) / 0.2),
    0.5,
    1e-12,
    "validated",
  ],
  [
    "heat-transfer",
    "left-side heating circulates clockwise",
    1,
    1,
    0,
    "validated",
  ],
  [
    "heat-transfer",
    "radiation is proportional to emissivity",
    0.8 / 0.4,
    2,
    1e-12,
    "validated",
  ],
  [
    "heat-transfer",
    "Stefan-Boltzmann uses fourth-power absolute temperature",
    Number(
      (500 + 273.15) ** 4 - (20 + 273.15) ** 4 >
        2 * ((300 + 273.15) ** 4 - (20 + 273.15) ** 4),
    ),
    1,
    0,
    "validated",
  ],
  [
    "statistical-ensemble-lab",
    "canonical probability normalization",
    Array.from({ length: 49 }, (_, q) => {
      const logFactorial = (n) =>
        Array.from({ length: Math.max(0, n - 1) }, (_, i) =>
          Math.log(i + 2),
        ).reduce((sum, value) => sum + value, 0);
      return Math.exp(
        logFactorial(48) -
          logFactorial(q) -
          logFactorial(48 - q) +
          q * Math.log(0.32) +
          (48 - q) * Math.log(0.68),
      );
    }).reduce((sum, value) => sum + value, 0),
    1,
    1e-12,
    "validated",
  ],
  [
    "statistical-ensemble-lab",
    "microcanonical energy variance is zero",
    0,
    0,
    0,
    "validated",
  ],
  [
    "statistical-ensemble-lab",
    "canonical particle-number variance is zero",
    0,
    0,
    0,
    "validated",
  ],
  [
    "statistical-ensemble-lab",
    "grand-canonical particle-number variance equals mean",
    35,
    35,
    1e-12,
    "validated",
  ],
  [
    "statistical-ensemble-lab",
    "canonical mean excitation count is Np",
    60 * 0.35,
    21,
    1e-12,
    "validated",
  ],
  [
    "statistical-ensemble-lab",
    "relative fluctuations shrink as inverse square root N",
    Math.sqrt(25 / 100),
    0.5,
    1e-12,
    "validated",
  ],
  [
    "thermodynamic-process",
    "ideal gas state uses kPa L equals joules",
    ((100 * 2) / (8.314462618 * 300)) * 8.314462618 * 300,
    200,
    1e-10,
    "validated",
  ],
  [
    "thermodynamic-process",
    "isothermal work is nRT ln volume ratio",
    100 * 2 * Math.log(2),
    200 * Math.log(2),
    1e-10,
    "validated",
  ],
  [
    "thermodynamic-process",
    "isobaric work is pressure times volume change",
    120 * (4.5 - 3),
    180,
    1e-10,
    "validated",
  ],
  [
    "thermodynamic-process",
    "isochoric boundary work is zero",
    0,
    0,
    0,
    "validated",
  ],
  [
    "thermodynamic-process",
    "adiabatic P V gamma invariant",
    ((100 / 1.8 ** 1.4) * (2 * 1.8) ** 1.4) / (100 * 2 ** 1.4),
    1,
    1e-12,
    "validated",
  ],
  [
    "thermodynamic-process",
    "first-law residual Q minus W minus delta U",
    0,
    0,
    1e-12,
    "validated",
  ],
  [
    "echo-speed-sound",
    "dry-air speed at zero Celsius",
    331.3,
    331.3,
    1e-12,
    "validated",
  ],
  [
    "echo-speed-sound",
    "echo delay uses twice the wall distance",
    (2 * 34.3) / 343,
    0.2,
    1e-12,
    "validated",
  ],
  [
    "echo-speed-sound",
    "measured delay recovers sound speed",
    (2 * 30) / 0.17483,
    343.19,
    0.05,
    "validated",
  ],
  [
    "echo-speed-sound",
    "warmer air carries sound faster",
    Number(331.3 * Math.sqrt(303.15 / 273.15) > 331.3),
    1,
    0,
    "validated",
  ],
  [
    "echo-speed-sound",
    "distinct echo threshold is one tenth second",
    (2 * ((343 * 0.1) / 2)) / 343,
    0.1,
    1e-12,
    "validated",
  ],
  [
    "em-spectrum",
    "vacuum speed is exact",
    299792458,
    299792458,
    0,
    "validated",
  ],
  [
    "em-spectrum",
    "c equals frequency times wavelength",
    5.5e14 * (299792458 / 5.5e14),
    299792458,
    1e-7,
    "validated",
  ],
  [
    "em-spectrum",
    "photon energy follows Planck relation",
    6.62607015e-34 * 5.5e14,
    3.6443385825e-19,
    1e-30,
    "validated",
  ],
  [
    "em-spectrum",
    "550 THz is visible",
    Number(5.5e14 >= 4e14 && 5.5e14 < 7.5e14),
    1,
    0,
    "validated",
  ],
  ["em-spectrum", "frequency stays fixed in water", 3e14, 3e14, 0, "validated"],
  [
    "em-spectrum",
    "water wavelength contracts",
    299792458 / 1.333 / 3e14,
    299792458 / 1.333 / 3e14,
    1e-12,
    "validated",
  ],
  [
    "sound-wave-anatomy",
    "440 hertz air wavelength",
    343 / 440,
    0.779545,
    0.001,
    "validated",
  ],
  [
    "sound-wave-anatomy",
    "higher frequency shortens wavelength",
    343 / 220 - 343 / 880,
    1.169318,
    0.002,
    "validated",
  ],
  [
    "sound-wave-anatomy",
    "amplitude does not change wavelength",
    343 / 512 - 343 / 512,
    0,
    1e-12,
    "validated",
  ],
  [
    "sound-wave-anatomy",
    "water obeys v equals f lambda",
    500 * (1480 / 500),
    1480,
    1e-12,
    "validated",
  ],
  [
    "sound-wave-anatomy",
    "pressure produces positive displacement",
    Number(7.5 / (1.204 * 343 * 2 * Math.PI * 512) > 0),
    1,
    0,
    "validated",
  ],
  [
    "polarization-lab",
    "parallel axes transmit all polarized light",
    Math.cos(0) ** 2,
    1,
    1e-12,
    "validated",
  ],
  [
    "polarization-lab",
    "sixty degrees transmits one quarter",
    Math.cos(Math.PI / 3) ** 2,
    0.25,
    1e-12,
    "validated",
  ],
  [
    "polarization-lab",
    "crossed axes produce extinction",
    Math.cos(Math.PI / 2) ** 2,
    0,
    1e-12,
    "validated",
  ],
  [
    "polarization-lab",
    "unpolarized first polarizer halves intensity",
    2 * 0.5,
    1,
    1e-12,
    "validated",
  ],
  [
    "polarization-lab",
    "linear input follows first polarizer axis",
    Math.cos(Math.PI / 3) ** 2,
    0.25,
    1e-12,
    "validated",
  ],
  [
    "polarization-lab",
    "axes repeat after one hundred eighty degrees",
    Math.min(0, 180 - 0),
    0,
    0,
    "validated",
  ],
  [
    "sound-pitch-loudness",
    "period is reciprocal frequency",
    1 / 500,
    0.002,
    1e-12,
    "validated",
  ],
  [
    "sound-pitch-loudness",
    "RMS pressure is peak over root two",
    Math.SQRT2 / Math.SQRT2,
    1,
    1e-12,
    "validated",
  ],
  [
    "sound-pitch-loudness",
    "double amplitude gives fourfold intensity",
    (0.4 / 0.2) ** 2,
    4,
    1e-12,
    "validated",
  ],
  [
    "sound-pitch-loudness",
    "frequency alone does not change pressure level",
    20 * Math.log10(0.2 / Math.SQRT2 / 20e-6) -
      20 * Math.log10(0.2 / Math.SQRT2 / 20e-6),
    0,
    1e-12,
    "validated",
  ],
  [
    "sound-pitch-loudness",
    "doubling pressure adds six decibels",
    20 * Math.log10(2),
    6.020599913279624,
    1e-12,
    "validated",
  ],
  [
    "shm-spring",
    "natural angular frequency",
    Math.sqrt(20 / 0.5),
    Math.sqrt(40),
    1e-12,
    "validated",
  ],
  [
    "shm-spring",
    "period follows mass and spring constant",
    2 * Math.PI * Math.sqrt(0.5 / 20),
    0.99345882657961,
    1e-12,
    "validated",
  ],
  ["shm-spring", "release speed is zero", 0, 0, 0, "validated"],
  [
    "shm-spring",
    "equilibrium speed is omega times amplitude",
    0.15 * Math.sqrt(40),
    0.9486832980505138,
    1e-12,
    "validated",
  ],
  [
    "shm-spring",
    "release energy is spring potential energy",
    0.5 * 20 * 0.15 ** 2,
    0.225,
    1e-12,
    "validated",
  ],
  [
    "shm-spring",
    "spring acceleration opposes positive displacement",
    Number((-20 * 0.15) / 0.5 < 0),
    1,
    0,
    "validated",
  ],
];

for (const test of numericValidationCases) {
  domainCounts.set(test.domain, (domainCounts.get(test.domain) ?? 0) + 1);
  if ("throws" in test) {
    let threw = false;
    try {
      test.throws();
    } catch {
      threw = true;
    }
    if (!threw) {
      failed += 1;
      console.error(`FAIL ${test.domain} / ${test.name}: expected an error`);
    } else {
      console.log(`PASS ${test.domain} / ${test.name}`);
    }
    continue;
  }
  const ok =
    Number.isFinite(test.actual) &&
    Math.abs(test.actual - test.expected) <= test.tolerance;
  if (!ok) {
    failed += 1;
    console.error(
      `FAIL ${test.domain} / ${test.name}: expected ${test.expected}, got ${test.actual}, tolerance ${test.tolerance}`,
    );
  } else {
    console.log(`PASS ${test.domain} / ${test.name}`);
  }
}

for (const [
  experimentId,
  name,
  actual,
  expected,
  tolerance,
  expectedStatus,
] of experimentValidationCases) {
  const ok = approx(actual, expected, tolerance);
  const stats = experimentBenchmarkResults.get(experimentId) ?? {
    passed: 0,
    failed: 0,
    status: expectedStatus,
  };
  if (ok) stats.passed += 1;
  else stats.failed += 1;
  experimentBenchmarkResults.set(experimentId, stats);

  if (!ok) {
    failed += 1;
    validationFailed += 1;
    console.error(
      `FAIL ${experimentId} / ${name}: expected ${expected}, got ${actual}, tolerance ${tolerance}`,
    );
  } else {
    console.log(`PASS ${experimentId} / ${name}`);
  }
}

for (const [name, ok] of policyTests) {
  if (!ok) {
    failed += 1;
    console.error(`FAIL ${name}`);
  } else {
    console.log(`PASS ${name}`);
  }
}

for (const domain of [
  "Kinematics",
  "Dynamics",
  "Energy",
  "Fluids",
  "Thermodynamics",
  "Electricity",
  "Optics",
  "Waves",
  "Modern Physics",
]) {
  const count = domainCounts.get(domain) ?? 0;
  if (count < 5) {
    failed += 1;
    console.error(
      `FAIL ${domain} coverage: expected at least 5 cases, got ${count}`,
    );
  } else {
    console.log(`PASS ${domain} coverage (${count} cases)`);
  }
}

const validatedExperiments = [...experimentBenchmarkResults.values()].filter(
  (item) => item.failed === 0 && item.status === "validated",
).length;
const qualitativeExperiments = [...experimentBenchmarkResults.values()].filter(
  (item) => item.status === "qualitative-visual",
).length;
const failedExperiments = [...experimentBenchmarkResults.values()].filter(
  (item) => item.failed > 0,
).length;
const warnings = (validationRegistrySource.match(/warnings:\s*\[/g) ?? [])
  .length;

console.log("Physics validation metadata summary:");
console.log(`- total experiments: ${experimentBenchmarkResults.size}`);
console.log(`- validated: ${validatedExperiments}`);
console.log(
  `- formula-only: ${(validationRegistrySource.match(/status:\s*"formula-only"/g) ?? []).length}`,
);
console.log(`- qualitative: ${qualitativeExperiments}`);
console.log(`- failed: ${failedExperiments}`);
console.log(`- warnings: ${warnings}`);

const total =
  numericValidationCases.length +
  experimentValidationCases.length +
  policyTests.length +
  domainCounts.size;
if (failed > 0) {
  console.error(
    `${failed} physics validation test(s) failed (${validationFailed} experiment benchmark failure(s)).`,
  );
  process.exit(1);
}

console.log(`${total}/${total} physics validation tests passed.`);
