import fs from 'node:fs/promises';import ts from 'typescript';import assert from 'node:assert/strict';
const js=ts.transpileModule(await fs.readFile('src/lib/comparePhenomena.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;const m=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));const p=m.COMPARE_DEFAULTS,checks=[];const near=(a,b,e=1e-10)=>assert(Math.abs(a-b)<=e*Math.max(1,Math.abs(b)),`${a} != ${b}`);
near(m.compareModel('pendulum',p).period,2.0060666807,1e-9);near(m.compareModel('orbit',p).period/m.DAY,27.28462,1e-5);near(m.compareModel('wave',p).period,.5);near(m.compareModel('lc',p).period,.2*Math.PI);checks.push('Independent default periods and SI/day/mF conversions');
for(const kind of m.PHENOMENA.map(v=>v.id)){const base=m.compareModel(kind,p);near(base.period*base.frequency,1);near(base.angular*base.period,2*Math.PI);near(m.compareValue(kind,p,0),base.amplitude);near(m.compareValue(kind,p,base.period/4),0);near(m.compareValue(kind,p,base.period/2),-base.amplitude);near(m.compareValue(kind,p,base.period),base.amplitude);for(const key of m.COMPARE_KEYS[kind])for(const v of [m.COMPARE_CONTROLS[key].min,m.COMPARE_CONTROLS[key].max]){const param={...p,[key]:v},a=m.compareModel(kind,param);assert(a.period>0&&Number.isFinite(a.period));for(let i=0;i<8;i++)assert(Number.isFinite(m.compareValue(kind,param,i*a.period/4)));}}checks.push('All model reciprocal identities, phase quadrants and every control boundary');
near(m.compareModel('pendulum',{...p,length:4}).period/m.compareModel('pendulum',p).period,2);near(m.compareModel('orbit',{...p,radius:p.radius*2}).period/m.compareModel('orbit',p).period,Math.sqrt(8));near(m.compareModel('lc',{...p,inductance:2,capacitance:20}).period/m.compareModel('lc',p).period,2);checks.push('Pendulum, Kepler and LC scaling laws');
for(const [kind,key] of [['pendulum','angle'],['wave','amplitude'],['lc','voltage']])for(let t=0;t<5;t+=.1)near(m.compareValue(kind,{...p,[key]:0},t),0);near(m.compareValue('lc',{...p,voltage:-5},0),-5);checks.push('Zero-amplitude stationary states and reversed capacitor polarity');
const wave=m.compareModel('wave',p);near(wave.wavelength*wave.frequency,p.speed);for(const t of [0,.17,.32,2]){near(m.compareWave(p,0,t),m.compareValue('wave',p,t));near(m.compareWave(p,wave.wavelength,t),m.compareWave(p,0,t));near(m.compareWave(p,p.speed*t,t),p.amplitude);}checks.push('Travelling-wave speed, wavelength and graph point agree');
for(const v of [-10,0,10])for(const t of [0,.1,.2]){const w=m.compareModel('lc',{...p,voltage:v}).angular,C=p.capacitance/1000,V=v*Math.cos(w*t),I=C*v*w*Math.sin(w*t);near(.5*C*V*V+.5*p.inductance*I*I,.5*C*v*v);}checks.push('LC energy conserved across signed voltage and phase');
await fs.writeFile('artifacts/studio-rebuild/05-compare-phenomena/physics-results.json',JSON.stringify({checks,defaults:m.PHENOMENA.map(s=>({kind:s.id,...m.compareModel(s.id,p)}))},null,2));console.log(checks);
