import {chromium} from 'playwright-core';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const out='artifacts/studio-rebuild/06-mastery-challenge',checks=[],errors=[];
const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{const p=await b.newPage({viewport:{width:1536,height:1024}});p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5371/quiz');await p.locator('.mc-page').waitFor();
const pause=async()=>{if(await p.getByRole('button',{name:'Pause',exact:true}).count())await p.getByRole('button',{name:'Pause',exact:true}).click()};
const predict=async(answer,expected)=>{await p.locator('.mc-modes button').nth(1).click();const d=p.getByRole('dialog');await d.getByRole('button',{name:answer,exact:true}).click();await d.getByRole('button',{name:'Check prediction',exact:true}).click();assert((await d.locator('[role=status]').textContent()).includes(expected));await p.keyboard.press('Escape')};
await pause();await p.locator('.mc-stages button').nth(0).click();await p.getByLabel('Launch speed',{exact:true}).fill('0');await p.getByRole('button',{name:'Run this setup',exact:true}).click();await p.waitForTimeout(300);await pause();const values=await p.locator('.mc-values').textContent();assert(values.includes('20.0'));assert(values.includes('0.00 A'));await predict('Yes','Review the energy budget');checks.push('Zero input remains at ambient with zero current; wrong prediction receives corrective feedback');
await p.getByRole('button',{name:'Next Challenge',exact:true}).click();await pause();await predict('No','Correct');await p.locator('.mc-stages button').nth(2).click();await p.getByLabel('Lens focal length',{exact:true}).fill('0.1');await p.getByRole('button',{name:'Run this setup',exact:true}).click();await p.getByRole('button',{name:'Mastery settings',exact:true}).click();await p.getByLabel('Playback speed',{exact:true}).selectOption('1');await p.keyboard.press('Escape');await p.waitForFunction(()=>document.querySelector('.mc-goal strong').textContent.includes('Target achieved'),{},{timeout:30000});await pause();checks.push('Defocused mission predicts failure; refocusing reaches actual 70 degree target');
await p.getByRole('button',{name:'Next Challenge',exact:true}).click();await pause();await predict('No','Correct');await p.locator('.mc-stages button').nth(3).click();await p.getByLabel('Thermal conductance',{exact:true}).fill('0');await p.getByRole('button',{name:'Run this setup',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.mc-goal strong').textContent.includes('Target achieved'),{},{timeout:45000});await pause();await p.screenshot({path:`${out}/insulated-hold-success.png`});await p.getByRole('button',{name:'Progress',exact:true}).click();assert((await p.getByRole('dialog').textContent()).includes('Keep the sample warm · Advanced'));await p.keyboard.press('Escape');checks.push('Leaky hold mission predicts failure; insulation reaches 60 degrees at 12 seconds and records completion');
await p.getByRole('button',{name:'Reset',exact:true}).click();await pause();await p.locator('.mc-stages button').nth(3).click();assert.equal(await p.getByLabel('Thermal conductance',{exact:true}).inputValue(),'1');await p.keyboard.press('Escape');assert((await p.locator('.mc-clock').textContent()).includes('1×'));checks.push('Reset restores mission preset while retaining playback preference');
await p.getByRole('button',{name:'Play',exact:true}).click();const performance=await p.evaluate(()=>new Promise(resolve=>{const samples=[];let previous;function frame(t){if(previous!==undefined)samples.push(t-previous);previous=t;if(samples.length<120)requestAnimationFrame(frame);else{samples.sort((a,b)=>a-b);resolve({frames:samples.length,medianMs:samples[60],p95Ms:samples[114],maxMs:samples.at(-1)})}}requestAnimationFrame(frame)}));assert.deepEqual(errors,[]);await fs.writeFile(`${out}/boundary-browser-results.json`,JSON.stringify({checks,errors,performance},null,2));console.log({checks,performance});}finally{await b.close()}

