import {chromium} from 'playwright-core';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const out='artifacts/studio-rebuild/05-compare-phenomena',checks=[],errors=[],warnings=[],network=[];
let page;const record=s=>{checks.push(s);console.log(s)};
const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{const p=await b.newPage({viewport:{width:1536,height:1024}});page=p;p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='warning')warnings.push(m.text());if(m.type()==='error')errors.push(m.text());});p.on('requestfailed',r=>{if(!r.failure()?.errorText.includes('ERR_ABORTED'))network.push(r.url())});await p.goto('http://127.0.0.1:5371/comparison');await p.locator('.cp-page').waitFor();
assert.equal(await p.locator('.cp-card').count(),4);await p.getByRole('button',{name:'Pause',exact:true}).click();let time=await p.locator('.cp-time').first().textContent();await p.waitForTimeout(200);assert.equal(await p.locator('.cp-time').first().textContent(),time);await p.getByRole('button',{name:'Play',exact:true}).click();await p.waitForTimeout(150);assert.notEqual(await p.locator('.cp-time').first().textContent(),time);await p.getByRole('button',{name:'Pause',exact:true}).click();record('Four direct-load models and synchronized pause/play clocks');
const selectKinds=['pendulum','orbit','wave','lc'];for(let i=0;i<4;i++){for(const kind of selectKinds){await p.getByLabel(`System ${i+1}`,{exact:true}).selectOption(kind);assert.equal(await p.locator('.cp-card').nth(i).getAttribute('data-kind'),kind);}await p.getByLabel(`System ${i+1}`,{exact:true}).selectOption(selectKinds[i]);}await p.getByLabel('Phenomenon A',{exact:true}).selectOption('wave');assert.equal(await p.getByLabel('System 1',{exact:true}).inputValue(),'wave');await p.getByLabel('Phenomenon B',{exact:true}).selectOption('lc');assert.equal(await p.getByLabel('System 2',{exact:true}).inputValue(),'lc');await p.getByRole('button',{name:'Reset',exact:true}).click();record('All four header selectors and both comparison selectors');
for(const quantity of ['frequency','angular','period']){await p.getByLabel('Shared quantity',{exact:true}).selectOption(quantity);assert.equal(await p.locator('.cp-live dl>div').count(),4);assert((await p.locator('.cp-live').textContent()).includes(quantity==='angular'?'rad/':quantity==='frequency'?'Hz':'2.01 s'));}record('Shared quantity updates all live readings and relationship');
await p.getByRole('button',{name:'Experiment',exact:true}).click();let dialog=p.getByRole('dialog');for(let i=0;i<4;i++){await dialog.locator('.cp-system-tabs button').nth(i).click();const sliders=dialog.locator('.cp-parameters input');const count=await sliders.count();for(let j=0;j<count;j++){const slider=sliders.nth(j);const original=await slider.inputValue();for(const bound of ['min','max']){const v=await slider.getAttribute(bound);await slider.fill(v);assert.equal(Number(await slider.inputValue()),Number(v));assert(!(await dialog.textContent()).includes('NaN'));}await slider.fill(original);}}await p.getByRole('button',{name:'Observe changes',exact:true}).click();record('Every experiment parameter minimum/maximum and return to observation');
await p.getByRole('button',{name:'Explain',exact:true}).click();dialog=p.getByRole('dialog');assert((await dialog.textContent()).includes('86,400'));assert.equal(await dialog.locator('.cp-explanations section').count(),4);await p.keyboard.press('Escape');await p.getByRole('button',{name:'Observe',exact:true}).click();assert.equal(await p.getByRole('dialog').count(),0);record('Model assumptions, equations, SI comparison ratio and Observe mode');
await p.getByRole('button',{name:'Predict',exact:true}).click();dialog=p.getByRole('dialog');await dialog.locator('.cp-answers button').nth(1).click();await dialog.getByRole('button',{name:'Check prediction',exact:true}).click();assert((await dialog.getByRole('status').textContent()).includes('Try'));for(let i=0;i<5;i++){await dialog.getByRole('button',{name:'Another prediction',exact:true}).click();const correct=[0,1,2,1,0][i];await dialog.locator('.cp-answers button').nth(correct).click();await dialog.getByRole('button',{name:'Check prediction',exact:true}).click();assert((await dialog.getByRole('status').textContent()).includes('Correct.'));}await dialog.getByRole('button',{name:'Test in Experiment',exact:true}).click();assert.equal(await p.getByRole('dialog',{name:'Change one system'}).count(),1);await p.keyboard.press('Escape');await p.getByRole('button',{name:'Next Challenge',exact:true}).click();assert.equal(await p.getByRole('dialog',{name:'Predict the relationship'}).count(),1);await p.keyboard.press('Escape');record('Five challenge banks, wrong/correct feedback, score and next-challenge navigation');
await p.getByRole('button',{name:'Comparison settings',exact:true}).click();dialog=p.getByRole('dialog');for(const v of ['.25','.5','2','1']){await p.getByLabel('Playback speed',{exact:true}).selectOption(v);assert((await p.locator('.cp-time').nth(1).textContent()).includes(`${4*Number(v)} d/s`));}await p.getByLabel('Show pendulum amplitude guides',{exact:true}).uncheck();assert.equal(await p.getByLabel('Show pendulum amplitude guides',{exact:true}).isChecked(),false);await p.getByLabel('Show pendulum amplitude guides',{exact:true}).check();await p.keyboard.press('Escape');for(const zoom of ['0.75','1.25','1']){await p.getByLabel('Scene zoom',{exact:true}).fill(zoom);assert((await p.locator('[data-scene-zoom]').first().getAttribute('transform')).includes(`scale(${Number(zoom)})`));}record('Playback speeds, amplitude guides and scene zoom limits');
await p.getByRole('button',{name:'Notebook',exact:true}).click();await p.getByLabel('Comparison notes',{exact:true}).fill('Frequency doubles, period halves.');await p.getByRole('button',{name:'Save notes',exact:true}).click();assert((await p.getByRole('dialog').getByRole('status').textContent()).includes('saved'));await p.keyboard.press('Escape');await p.reload();await p.locator('.cp-page').waitFor();await p.getByRole('button',{name:'Notebook',exact:true}).click();assert.equal(await p.getByLabel('Comparison notes',{exact:true}).inputValue(),'Frequency doubles, period halves.');await p.evaluate(()=>{Storage.prototype.setItem=function(){throw Error('blocked')}});await p.getByRole('button',{name:'Save notes',exact:true}).click();assert((await p.getByRole('dialog').getByRole('status').textContent()).includes('unavailable'));await p.keyboard.press('Escape');await p.reload();await p.locator('.cp-page').waitFor();record('Notebook persistence, direct refresh, Escape and recoverable storage failure');
const sizes=[];for(const [width,height] of [[1536,1024],[1440,900],[1280,720],[1024,768],[768,1024],[390,844]]){await p.setViewportSize({width,height});await p.getByRole('button',{name:'Reset',exact:true}).click();await p.getByRole('button',{name:'Pause',exact:true}).click();await p.waitForTimeout(150);const data=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth-innerWidth,missing:[...document.images].filter(i=>!i.complete||!i.naturalWidth).length,clipped:[...document.querySelectorAll('.cp-summary>div,.cp-controls,.cp-intro')].filter(e=>e.scrollWidth>e.clientWidth+2).map(e=>e.className),graph:[...document.querySelectorAll('.cp-graph')].map(e=>e.getBoundingClientRect().height)}));assert.equal(data.overflow,0);assert.equal(data.missing,0);assert.deepEqual(data.clipped,[]);assert(data.graph.every(h=>h>=150));sizes.push({width,height,...data});await p.evaluate(()=>window.scrollTo(0,0));await p.waitForTimeout(150);await p.screenshot({path:`${out}/${width}x${height}.png`,fullPage:true});}
await p.getByRole('button',{name:'Explain',exact:true}).click();const bounds=await p.getByRole('dialog').evaluate(e=>{const r=e.getBoundingClientRect();return{top:r.top,bottom:r.bottom,color:getComputedStyle(e.querySelector('p')).color}});assert(bounds.top>=0&&bounds.bottom<=844);assert.equal(bounds.color,'rgb(205, 228, 247)');await p.screenshot({path:`${out}/mobile-explain.png`});await p.keyboard.press('Escape');record('Six responsive sizes without overflow or clipped controls, plus readable mobile dialog');
await p.goto('http://127.0.0.1:5371/comparison?view=benchmark');await p.getByRole('heading',{name:'Physics Tool Comparison',exact:true}).waitFor();assert.equal(await p.locator('.cp-page').count(),0);record('Original platform benchmark retained');const ownWarnings=warnings.filter(w=>!w.includes('React Router Future Flag'));assert.deepEqual(errors,[]);assert.deepEqual(ownWarnings,[]);assert.deepEqual(network,[]);await fs.writeFile(`${out}/interaction-results.json`,JSON.stringify({checks,sizes,errors,network,warnings},null,2));console.log({checks,sizes});
}catch(e){console.log({errors,warnings,network,url:page?.url()});await page?.screenshot({path:`${out}/failure.png`,fullPage:true}).catch(()=>{});throw e;}finally{await b.close()}
