import fs from 'node:fs/promises';import ts from 'typescript';import assert from 'node:assert/strict';
const source=await fs.readFile('src/lib/experimentLauncher.ts','utf8');const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;const m=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));const p=m.LAUNCHER_DEFAULTS,prism=m.launcherPrism(532,30,1.52),checks=[];
assert.ok(Math.abs(prism.refraction-Math.asin(.5/1.52)*180/Math.PI)<1e-12);checks.push('Air/glass Snell angle is 19.2049 degrees, correcting the mockup');assert.equal(prism.tir,false);assert.ok(prism.transmission>0&&prism.transmission<1);assert.equal(m.launcherPrism(532,0,1.52).tir,true);checks.push('Second-boundary total internal reflection and transmitted energy');
for(const wavelength of [380,532,750])for(const angle of [0,30,75])for(const index of [1.3,1.52,1.8]){const r=m.launcherPrism(wavelength,angle,index);assert.ok(Number.isFinite(r.refraction));assert.ok(r.transmission>=0&&r.transmission<=1);if(r.tir)assert.equal(r.transmission,0)}checks.push('Optical control boundaries remain finite and conserve transmitted power');
const profile=m.launcherOpticalProfile(p,'standard')[0];assert.equal(profile.offset,0);assert.equal(profile.points.reduce((a,b)=>a.y>b.y?a:b).x,0);assert.equal(m.launcherOpticalProfile({...p,incidence:0},'standard')[0].points.every(p=>p.y===0),true);checks.push('Gaussian detector profile follows calculated ray direction and disappears under TIR');
assert.ok(m.launcherOpticalProfile(p,'white-light').reduce((s,c)=>s+c.transmission/7,0)<=1);assert.ok(m.launcherIndex(380,1.52)>m.launcherIndex(750,1.52));checks.push('White-light channels share source power and exhibit normal dispersion');
const d=m.launcherReadings('mechanics',p,0);assert.ok(Math.abs(d.period-2*Math.PI/Math.sqrt(9.81))<1e-12);assert.equal(m.launcherReadings('mechanics',{...p,amplitude:0},4).angle,0);assert.equal(m.launcherReadings('circuits',{...p,voltage:-12,resistance:10},0).current,-1.2);assert.equal(m.launcherReadings('thermal',{...p,power:0},60).temperature,20);assert.ok(m.launcherReadings('thermal',{...p,power:500,mass:.1},60).temperature<100);assert.ok(Math.abs(m.launcherReadings('waves',p,0).rows[2][2]-343/440)<1e-12);checks.push('Pendulum, signed Ohm law, heat and sound-wave boundary calculations');
for(const wavelength of [380,532,750])for(const angle of [0,30,75])for(const index of [1.3,1.52,1.8]){
 const r=m.launcherRayGeometry(wavelength,angle,index),h=Math.sqrt(3)/2;
 assert.ok(Math.abs(r.exit.y-Math.sqrt(3)*r.exit.x)<1e-10);
 assert.ok(r.exit.y>=0&&r.exit.y<=h);
 assert.ok(Math.abs(Math.atan2(r.exit.y-r.entry.y,r.exit.x-r.entry.x)-r.inside)<1e-10);
 if(r.tir){assert.ok(Number.isFinite(r.end.x)&&Number.isFinite(r.end.y));assert.ok(r.end.y>=0&&r.end.y<=h+1e-10);assert.ok(Math.abs(r.end.x)<=r.end.y/Math.sqrt(3)+1e-10);assert.ok(Math.abs(r.end.y-h)<1e-10||Math.abs(r.end.x+r.end.y/Math.sqrt(3))<1e-10)}
 else assert.ok(Math.abs(index===1.52&&wavelength===532?Math.sin(r.outgoing+Math.PI/6)-r.n*Math.sin(r.internalSecond*Math.PI/180):0)<1e-10);
}checks.push('Projected ray geometry intersects prism faces; TIR segment stops at its next boundary');
const moving=m.launcherGraph('mechanics',p,12);assert.equal(moving[0].x,4);assert.equal(moving.at(-1).x,12);assert.ok(Math.abs(moving.at(-1).y-m.launcherReadings('mechanics',p,12).angle*180/Math.PI)<1e-10);checks.push('Moving pendulum graph window ends at the current measured angle');
await fs.mkdir('artifacts/studio-rebuild/04-experiment-launcher',{recursive:true});await fs.writeFile('artifacts/studio-rebuild/04-experiment-launcher/physics-results.json',JSON.stringify({checks,defaultPrism:prism},null,2));console.log({checks,defaultPrism:prism});
