import {chromium} from 'playwright-core';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const checks=[],sizes=[],errors=[],warnings=[],failed=[];
try{const p=await b.newPage({viewport:{width:1536,height:1024}});p.setDefaultTimeout(60000);p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(['warning','error'].includes(m.type()))warnings.push(m.text())});p.on('response',r=>{if(r.status()>=400)failed.push(r.url())});await p.goto('http://127.0.0.1:5371/measurement/spherometer');await p.locator('.sph-page').waitFor();const btn=name=>p.getByRole('button',{name,exact:true}),height=p.getByLabel('Screw height value',{exact:true}),radius=p.getByLabel('Leg radius value',{exact:true});
assert((await p.locator('.sph-readings').textContent()).includes('1071.6'));assert((await p.locator('.sph-readings').textContent()).includes('12.8'));checks.push('Correct default radius and propagated uncertainty');
for(const r of ['10','100'])for(const h of ['0','0.001','2']){await radius.fill(r);await height.fill(h);const reading=await p.locator('.sph-readings').textContent();assert(!reading.includes('NaN'));assert(reading.includes(h==='0'?'∞':(((+r)**2 + (+h)**2)/(2*+h)).toFixed(1)));for(const surface of ['concave','convex']){await p.getByLabel('Surface curvature',{exact:true}).selectOption(surface);assert((await p.locator('.sph-scene svg').getAttribute('aria-label')).startsWith(surface));}}
await p.getByRole('slider',{name:'Screw height',exact:true}).focus();await p.keyboard.press('Home');assert.equal(await height.inputValue(),'0');await p.keyboard.press('End');assert.equal(await height.inputValue(),'2');await p.getByRole('slider',{name:'Leg radius',exact:true}).focus();await p.keyboard.press('Home');assert.equal(await radius.inputValue(),'10');await p.keyboard.press('End');assert.equal(await radius.inputValue(),'100');await btn('Concave surface').click();await btn('Convex surface').click();checks.push('Both surfaces, all control limits, zero, near-flat, keyboard sliders');
await btn('Reset').click();await btn('Scan curvature').click();await p.waitForTimeout(350);await btn('Pause').click();const held=await height.inputValue();assert.notEqual(held,'0.42');await p.waitForTimeout(150);assert.equal(await height.inputValue(),held);await btn('Scan curvature').click();await p.waitForTimeout(150);await btn('Pause').click();assert.notEqual(await height.inputValue(),held);checks.push('Continuous scan, pause and resume');
for(const name of ['Zoom in','Zoom in','Zoom in'])await btn(name).click();assert.equal(await p.locator('.sph-actions output').textContent(),'150%');for(let i=0;i<4;i++)await btn('Zoom out').click();assert.equal(await p.locator('.sph-actions output').textContent(),'75%');await btn('Reset').click();assert.equal(await height.inputValue(),'0.42');assert.equal(await p.locator('.sph-actions output').textContent(),'100%');checks.push('Zoom clamps and default reset');
await btn('Predict').click();await btn('R increases').click();assert((await p.getByRole('dialog').getByRole('status').textContent()).includes('Compare'));await btn('R decreases').click();assert((await p.getByRole('dialog').getByRole('status').textContent()).includes('Correct'));await p.keyboard.press('Escape');await btn('Explain').click();assert((await p.getByRole('dialog').textContent()).includes('120°'));await p.keyboard.press('Escape');await btn('Notebook').click();await p.getByLabel('Spherometer notes').fill('R uses the leg-circle radius.');await p.keyboard.press('Escape');await btn('Notebook').click();assert.equal(await p.getByLabel('Spherometer notes').inputValue(),'R uses the leg-circle radius.');await p.keyboard.press('Escape');await btn('Settings').click();await p.getByRole('checkbox').uncheck();await p.keyboard.press('Escape');assert.equal(await p.locator('.sph-readings p').count(),0);await btn('Settings').click();await p.getByRole('checkbox').check();await p.keyboard.press('Escape');checks.push('Prediction feedback, explanation, retained notes and uncertainty setting');
await btn('Experiment').click();await btn('Set flat surface').click();assert.equal(await height.inputValue(),'0');await btn('Tools').click();assert((await p.getByRole('dialog').textContent()).includes('0.0000e+0'));await p.keyboard.press('Escape');await btn('Reset').click();for(const answer of ['261.0','infinity','1071.6']){await p.getByRole('button',{name:'Next Challenge',exact:false}).click();await p.getByLabel('Radius answer').fill(answer);await btn('Check radius').click();assert((await p.getByRole('dialog').getByRole('status').textContent()).includes('Correct'));await p.keyboard.press('Escape');}checks.push('Flat experiment, unit tools, all three numerical challenges');
await btn('Observe').click();await btn('Reset').click();for(const [width,height]of [[1536,1024],[1440,900],[1280,720],[1024,768],[768,1024],[390,844]]){await p.setViewportSize({width,height});await p.evaluate(()=>scrollTo(0,0));const geometry=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth-innerWidth,clipped:[...document.querySelectorAll('.sph-controls-side>section,.sph-views>section')].filter(e=>e.scrollWidth>e.clientWidth+3||e.scrollHeight>e.clientHeight+3).map(e=>e.className)}));sizes.push({width,height,...geometry});await p.screenshot({path:`artifacts/studio-rebuild/10-spherometer/${width}x${height}.png`,fullPage:true});}
await p.reload();await p.locator('.sph-page').waitFor();checks.push('Direct refresh');await fs.writeFile('artifacts/studio-rebuild/10-spherometer/interaction-prechecks.json',JSON.stringify({checks,sizes,errors,warnings,failed},null,2));console.log({checks,sizes,errors,warnings,failed});assert.equal(errors.length,0);assert.equal(failed.length,0);assert(sizes.every(s=>s.overflow<=0&&s.clipped.length===0));}finally{await b.close()}


