import {chromium} from 'playwright-core';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const out='artifacts/studio-rebuild/02-relationship-map';await fs.mkdir(out,{recursive:true});
const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const p=await b.newPage({viewport:{width:1536,height:1024}}),errors=[],checks=[],responsive=[];
p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
const button=name=>p.getByRole('button',{name,exact:true});const close=()=>button('Close panel').click();const select=id=>p.getByRole('combobox',{name:'Focus Concept'}).selectOption(id);const range=(name,value)=>p.getByRole('slider',{name,exact:true}).fill(String(value));const check=async(name,fn)=>{await fn();checks.push(name);console.log('PASS '+name)};
try{await p.goto('http://127.0.0.1:5371/graph',{waitUntil:'networkidle'});
await check('Default route, complete graph and correct readings',async()=>{assert.equal(await p.locator('h1').innerText(),'CONCEPT RELATIONSHIPS');assert.equal(await p.locator('.cr-graph-node').count(),20);assert.match(await p.locator('.cr-values').innerText(),/5.0 m\/s²/)});
await p.screenshot({path:`${out}/desktop-1536x1024.png`});
await check('Every focus concept updates selected node and details',async()=>{const options=await p.locator('select[aria-label="Focus Concept"] option').evaluateAll(es=>es.map(e=>({id:e.value,label:e.textContent})));for(const c of options){await select(c.id);assert.match(await p.locator('.cr-selected-title').innerText(),new RegExp(c.label));assert.equal(await button('Select '+c.label).getAttribute('aria-pressed'),'true');}});
await check('Pointer selection, drag, keyboard selection and movement',async()=>{await button('Reset').click();const node=button('Select Force'),before=await node.getAttribute('transform'),box=await node.boundingBox();await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+box.width/2+30,box.y+box.height/2+20);await p.mouse.up();assert.notEqual(await node.getAttribute('transform'),before);await button('Select Waves').focus();await p.keyboard.press('Enter');assert.equal(await p.getByRole('combobox',{name:'Focus Concept'}).inputValue(),'waves');const pos=await button('Select Waves').getAttribute('transform');await p.keyboard.press('ArrowLeft');assert.notEqual(await button('Select Waves').getAttribute('transform'),pos);});
await check('Prerequisite layers and visual strength respond',async()=>{await p.getByRole('combobox',{name:'Prerequisite Layer'}).selectOption('hide');assert.equal(await p.locator('.cr-graph-node').count(),15);await p.getByRole('combobox',{name:'Prerequisite Layer'}).selectOption('only');assert.equal(await p.locator('.cr-graph-node').count(),6);await p.getByRole('combobox',{name:'Prerequisite Layer'}).selectOption('all');await range('Link Strength',.1);const low=await p.locator('animateMotion').first().evaluate(e=>e.parentElement.parentElement.getAttribute('opacity'));await range('Link Strength',1);assert.notEqual(await p.locator('animateMotion').first().evaluate(e=>e.parentElement.parentElement.getAttribute('opacity')),low);});
await check('Pause, resume and bounded zoom',async()=>{await button('Pause').click();const t=await p.locator('.cr-graph-svg').evaluate(e=>e.getCurrentTime());await p.waitForTimeout(120);assert.equal(await p.locator('.cr-graph-svg').evaluate(e=>e.getCurrentTime()),t);await button('Play').click();await p.waitForTimeout(120);assert.ok(await p.locator('.cr-graph-svg').evaluate(e=>e.getCurrentTime())>t);for(let i=0;i<10;i++){if(await button('Zoom in').isEnabled())await button('Zoom in').click()}assert.equal(await button('Zoom in').isDisabled(),true);await button('Zoom').click();assert.equal(await p.locator('.cr-map-zoom output').innerText(),'100%');for(let i=0;i<10;i++){if(await button('Zoom out').isEnabled())await button('Zoom out').click()}assert.equal(await button('Zoom out').isDisabled(),true);await button('Fit').click();});
await check('Three challenge questions, feedback and experiment handoff',async()=>{await button('Reset').click();await button('Predict').click();await button('It doubles').click();await button('Check prediction').click();assert.match(await p.getByRole('dialog').getByRole('status').innerText(),/Try again/);await button('It halves').click();await button('Check prediction').click();assert.match(await p.getByRole('dialog').getByRole('status').innerText(),/Correct/);await close();await button('Next Challenge').click();assert.match(await p.getByRole('dialog').innerText(),/kinetic energy/);await button('It quadruples').click();await button('Check prediction').click();assert.match(await p.getByRole('dialog').getByRole('status').innerText(),/Correct/);await button('Test with the controls').click();assert.equal(await p.getByRole('slider',{name:'Speed'}).count(),1);await close();await button('Next Challenge').click();assert.match(await p.getByRole('dialog').innerText(),/period/);await close();});
const scenarios=[['force',{'Net force':-20,Mass:.1},'Acceleration: -200.000 m/s²'],['force',{'Net force':0,Mass:10},'Acceleration: 0.000 m/s²'],['work',{'Net force':-20,Displacement:5},'Net work: -100.000 J'],['kinetic',{Mass:10,Speed:20},'Kinetic energy: 2000.000 J'],['potential',{Mass:2,Height:-10},'Potential energy: -196.200 J'],['power',{'Net force':20,Displacement:5,'Elapsed time':.1},'Average power: 1000.000 W'],['oscillation',{Period:.1},'Frequency: 10.000 Hz'],['waves',{Frequency:10,Wavelength:3},'Wave speed: 30.000 m/s'],['waves',{Frequency:0},'Wave speed: 0.000 m/s'],['light',{'Light frequency':1000},'Wavelength: 299.792 nm'],['fields',{'Coil current':-5},'Magnetic field: -6.283 mT'],['fields',{'Coil current':0},'Magnetic field: 0.000 mT']];
await check('All nine physics families, signed values, zero and extrema',async()=>{for(const [id,values,expected] of scenarios){await select(id);await button('Experiment').click();await button('Reset values').click();for(const [label,value] of Object.entries(values))await range(label,value);assert.ok((await p.locator('.cr-lab-readings').innerText()).includes(expected),expected);assert.equal(await p.getByRole('dialog').locator('svg').count(),1);await close();}});
await check('Details, links, examples and explanations',async()=>{await button('Reset').click();await button('Details').click();assert.match(await p.locator('.cr-links').innerText(),/constant mass/);await button('Examples').click();assert.equal(await p.locator('.cr-links a').count(),2);await button('Connections').click();await p.locator('.cr-links').getByRole('button',{name:/Force → Mass/}).click();assert.equal(await p.getByRole('combobox',{name:'Focus Concept'}).inputValue(),'mass');await button('Explain').click();assert.match(await p.getByRole('dialog').innerText(),/vacuum/);await close();});
await check('Accessible sidebar, settings, help, notes persistence and modal focus',async()=>{await button('Settings').click();await p.getByRole('checkbox').uncheck();await p.keyboard.press('Escape');assert.equal(await button('Play').count(),1);await button('Help').click();await p.keyboard.press('Escape');assert.equal(await button('Help').evaluate(e=>e===document.activeElement),true);await button('Notebook').click();await p.locator('textarea').fill('F/m sets acceleration; a signed net force sets its direction.');await button('Save notes').click();await p.reload({waitUntil:'networkidle'});await button('Notebook').click();assert.match(await p.locator('textarea').inputValue(),/signed/);await close();});
await check('Full reset restores parameters, layout, zoom, filters and playback',async()=>{await button('Reset').click();assert.equal(await p.getByRole('combobox',{name:'Focus Concept'}).inputValue(),'force');assert.equal(await p.getByRole('slider',{name:'Link Strength'}).inputValue(),'0.7');assert.equal(await button('Select Force').getAttribute('transform'),'translate(382 115)');assert.equal(await button('Pause').count(),1);assert.match(await p.locator('.cr-values').innerText(),/5.0 m\/s²/);});
for(const [width,height] of [[1536,1024],[1440,900],[1280,720],[1024,768],[768,1024],[390,844]]){await p.setViewportSize({width,height});await p.waitForTimeout(70);const layout=await p.evaluate(()=>{const r=s=>document.querySelector(s).getBoundingClientRect();return{width:innerWidth,height:innerHeight,overflow:document.documentElement.scrollWidth-innerWidth,documentHeight:document.documentElement.scrollHeight,overlap:r('.cr-inspector').bottom-r('.cr-summary').top,clipped:[...document.querySelectorAll('.cr-panel,.cr-summary>div')].filter(e=>e.scrollHeight>e.clientHeight+3||e.scrollWidth>e.clientWidth+3).map(e=>e.className)}});assert.equal(layout.overflow,0);assert.ok(layout.overlap<=0,JSON.stringify(layout));assert.deepEqual(layout.clipped,[]);for(const name of ['Notebook','Settings','Help'])assert.equal(await button(name).count(),1);await p.screenshot({path:`${out}/${width}x${height}.png`,fullPage:true});responsive.push(layout)}checks.push('Six responsive sizes without overlap, clipping or horizontal overflow');
await p.setViewportSize({width:1536,height:1024});await p.getByRole('link',{name:'Simulations',exact:true}).click();assert.match(p.url(),/view=experiments/);assert.equal(await p.locator('canvas').count(),1);checks.push('Original experiment graph remains accessible');
assert.deepEqual(errors,[]);await fs.writeFile(`${out}/results.json`,JSON.stringify({checks,responsive,errors},null,2));console.log('ALL PASS');
}catch(e){await p.screenshot({path:`${out}/failure.png`,fullPage:true});throw e}finally{await b.close()}

